package.json
*Description of changes:* Fixing a typo with the `vue-example` workspace name in our `package.json`.
=> Fix vue-example workspace name in package.json

packages/e2e/cypress/integration/common/index.tsx, packages/e2e/cypress/integration/ui/components/authenticator/reset-password.feature, packages/e2e/cypress/integration/ui/components/authenticator/reset-password/reset-password.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-force-new-password/sign-in-force-new-password.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-with-email/sign-in-with-email.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-with-phone/sign-in-with-phone.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-with-username/sign-in-with-username.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up-with-email.feature, packages/e2e/cypress/integration/ui/components/authenticator/sign-up-with-email/sign-up-with-email.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up-with-phone/sign-up-with-phone.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up/sign-up.steps.ts
*Description of changes:* With the introduction of I18N strings in authenticator ([PR 189](https://github.com/aws-amplify/amplify-ui/pull/189)), we need the common "Click button" Cypress action to be case insensitive to function correctly with the new strings.
Furthermore, I'm skipping the "Sign up with valid email & password" test in `sign-up-with-email.feature`. We continuously get a failure due to `Exceeded daily email limit for the operation or the account. If a higher limit is required, please configure your user pool to use your own Amazon SES configuration for sending email.` This will be addressed as part of my audit of skipped e2e tests ([Asana](https://app.asana.com/0/1200781756632584/1200751914824795)), but it makes the most sense right now to skip …
=> Use common button click step and make it case insensitive

packages/core/tsup.config.cjs, packages/react/tsup.config.cjs
Fixes <img width="974" alt="Screen Shot 2021-08-20 at 5 24 01 PM" src="https://user-images.githubusercontent.com/15182/130464680-e3620b92-15f3-4743-9397-6076ee628b2e.png">
=> Explicitly exclude aws-amplify modules

.github/workflows/tests.yml, examples/angular/package.json, yarn.lock
*Description of changes:* This uses `serve` npm package to serve the built `next-example/dist`, so that `yarn build` does not build the same package twice.
Looked into using this in Vue/React as well, but their `yarn start` command were already using the `dist` directory as intended.
=> chore(angular): use serve to serve built package

.husky/pre-commit
*Description of changes:*  This additional shell commands prevent committing to main by mistake. If you need to bypass this hook for whatever reason, then you can do so via git commit --no-verify.
=> chore: prevent commit to main

docs/src/pages/ui/primitives/visuallyHidden/index.page.mdx, docs/src/pages/ui/primitives/visuallyHidden/react.mdx, packages/react/__tests__/exports.ts, packages/react/src/primitives/Pagination/PaginationItem.tsx, packages/react/src/primitives/Pagination/__tests__/Pagination.test.tsx, packages/react/src/primitives/Rating/Rating.tsx, packages/react/src/primitives/VisuallyHidden/VisuallyHidden.tsx, packages/react/src/primitives/VisuallyHidden/__tests__/VisuallyHidden.test.tsx, packages/react/src/primitives/VisuallyHidden/index.ts, packages/react/src/primitives/index.tsx, packages/react/src/primitives/shared/constants.ts, packages/react/src/primitives/types/visuallyHidden.ts, packages/ui/src/theme/css/component/pagination.scss, packages/ui/src/theme/css/component/visuallyHidden.scss, packages/ui/src/theme/css/styles.scss
This PR adds a `VisuallyHidden` and removes `.sr-only` css class usage in favor of it
=> VisuallyHidden Primitive

docs/src/pages/_app.page.tsx
This PR fixes app page import by removing the import of the theme style file. This file isn't needed because it's already exported via `@aws-amplify/ui-react/styles.css`
Error message when running `yarn docs dev`:
```
error - ./src/pages/_app.page.tsx:2:0
Module not found: Package path ./dist/style.css is not exported from package /Volumes/workplace/amplify-ui/node_modules/@aws-amplify/ui (see exports field in /Volumes/workplace/amplify-ui/node_modules/@aws-amplify/ui/package.json)
1 | import Head from 'next/head';
> 2 | import '@aws-amplify/ui/dist/style.css';
3 | import '../styles/styles.css';
4 | import '@aws-amplify/ui-react/styles.css';
5 | import '../styles/primitivesStyles.css';
```
Tested running `yarn docs dev` after making this change and they build. Manually tested the docs …
=> Fix docs by removing missing/unneeded theme styles CSS

packages/angular/projects/ui-angular/src/lib/components/amplify-sign-in/amplify-sign-in.component.html, packages/e2e/cypress/integration/common/index.tsx, packages/e2e/cypress/integration/ui/components/authenticator/reset-password/reset-password.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-with-email/sign-in-with-email.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-with-multi-alias/sign-in-with-multi-alias.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-with-phone/sign-in-with-phone.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-with-username/sign-in-with-username.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up-with-email/sign-up-with-email.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up-with-phone/sign-up-with-phone.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up/sign-up.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/verify-user/verify-user.steps.ts, packages/vue/src/components/sign-in-password-control.vue, packages/vue/src/components/sign-in.vue, packages/vue/src/defaults/DefaultTexts.ts
*Description of changes:* With [PR 336](https://github.com/aws-amplify/amplify-ui/pull/336) we updated the reset password text at the sign in component to be `Forgot your password?`. This PR makes some changes to fix CI and bring Angular and Vue implementations in-line with the new e2e test format:
1. Change Angular reset password text to `Forgot your password?`
2. Change Vue reset password text to `Forgot your password?`
3. Add placeholder text to password field in Vue for Cypress query selector
4. Escape strings used to form regex in Cypress steps so the `?` in `Forgot your password?` isn't treated as a special character
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> CI: Change reset password button text and escape regex

packages/e2e/cypress/integration/ui/components/authenticator/sign-up-with-email/sign-up-with-email.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up-with-phone/sign-up-with-phone.steps.ts, packages/e2e/cypress/integration/ui/components/authenticator/sign-up/sign-up.steps.ts, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/shared/ErrorText.tsx
n/a
Initial styling for the `SignUp` page. The "Sign In" button will be removed once the `Tabs` component is ready.
Old sign up page - 
New sign up page -
=> initial styling for SignUp

packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/react/src/components/Authenticator/shared/ConfirmationCodeInput.tsx, packages/ui/src/machines/actors/auth/signIn.ts, packages/ui/src/machines/actors/auth/signUp.ts
https://app.asana.com/0/1200881947262804/1200935010977983/f
Initial styling for the `ConfirmSignUp` screen. Also made some tweaks to the `signIn` and `signUp` machines in order to make the UX a bit better and remove the extra username input from the `ConfirmSignUp` screen.
=> initial styling for ConfirmSignUp

packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/react/src/components/Authenticator/shared/ErrorText.tsx, packages/react/src/components/Authenticator/shared/TwoButtonSubmitFooter.tsx
https://app.asana.com/0/1200881947262804/1200935010977981/f
Initial styling pass through for the reset password flow. This flow is actually not in the mocks for some reason, so I'm just following the example of other screens.
!!! Fixed the title string in the screenshots below so both should be the same now (`Reset your password`). Don't feel like taking a new screenshot though.
=> initial styling for ResetPassword flow

packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/shared/ConfirmSignInFooter.tsx
https://app.asana.com/0/1200881947262804/1200952565427110/f
https://app.asana.com/0/1200881947262804/1200952565427109/f
Adding initial styling for `SetupTOTP` and `ConfirmSignIn` (mfa) screens.
=> initial styling for totp setup and mfa code screens

packages/e2e/cypress/integration/ui/components/authenticator/sign-in-force-new-password/sign-in-force-new-password.steps.ts, packages/e2e/features/ui/components/authenticator/sign-in-force-new-password.feature, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/ui/src/machines/actors/auth/signIn.ts
https://app.asana.com/0/1200881947262804/1200952565427106/f
Initial styling for the `ForceNewPassword` screen. This adds a new `confirm_password` field to the screen. As a result, I also modified the state machine to handle validating that the passwords match each other, identical to the `SignUp` screen (literally copy/pasted most of it).
This PR *might* break functionality in Vue and Angular on the `ForceNewPassword` screen due to changes in the state machine.
=> initial styling for ForceNewPassword

examples/angular/src/pages/ui/components/authenticator/sign-up/sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-authenticator/amplify-authenticator.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-authenticator/amplify-authenticator.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-confirm-sign-in/amplify-confirm-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-confirm-sign-in/amplify-confirm-sign-in.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-confirm-sign-up/amplify-confirm-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-confirm-sign-up/amplify-confirm-sign-up.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-force-new-password/amplify-force-new-password.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-force-new-password/amplify-force-new-password.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-reset-password/amplify-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-reset-password/amplify-reset-password.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-setup-totp/amplify-setup-totp.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-setup-totp/amplify-setup-totp.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-sign-in/amplify-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-sign-in/amplify-sign-in.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-sign-up/amplify-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-sign-up/amplify-sign-up.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-verify-user/amplify-verify-user.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-verify-user/amplify-verify-user.component.ts, packages/angular/projects/ui-angular/src/lib/components/confirm-reset-password/amplify-confirm-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/confirm-reset-password/amplify-confirm-reset-password.component.ts, packages/angular/projects/ui-angular/src/lib/components/confirm-verify-user/amplify-confirm-verify-user.component.html, packages/angular/projects/ui-angular/src/lib/components/confirm-verify-user/amplify-confirm-verify-user.component.ts
*Description of changes:* This adds context to every template outlet that customers can use to get `helper` functions or relevant context like `user`.
This enables in-template use cases like 
```tsx
<amplify-authenticator>
<ng-template amplifyOverride="authenticated" let-user="user">
<h1>Welcome, {{ user.username }}</h1>
</ng-template>
</amplify-authenticator>
```
where `let-user="user"` is coming from template outlet context.
=> feat(Angular): expose relevant context from each template outlet

packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/VerifyUser/ConfirmVerifyUser.tsx, packages/react/src/components/Authenticator/VerifyUser/VerifyUser.tsx, packages/react/src/components/Authenticator/shared/RemoteErrorMessage.tsx, packages/react/src/components/Authenticator/shared/index.ts, packages/react/src/components/Authenticator/styles.css
https://app.asana.com/0/1200881947262804/1200960625209728/f
Adding `Alert` primitives for `RemoteError` messages. These are distinct from `ValidationError` messages. Remote errors come from Cognito, validation errors are operations we perform (password matching, for instance).
EDIT: screenshot showing new width of authenticator to better match the mocks --
=> Error message styling

CONTRIBUTING.md, docs/src/pages/ui/components/authenticator/index.page.mdx
*Description of changes:* As part of [PR 340](https://github.com/aws-amplify/amplify-ui/pull/340), the `sign-up` examples and e2e tests were updated to be the more specific `sign-up-with-username`. This PR updates docs in this repository to reflect that change.
=> Update docs to reference sign-up-with-username

packages/react/package.json, packages/ui/package.json, packages/vue/package.json
- https://app.asana.com/0/0/1200982218231966/f
- https://app.asana.com/0/0/1200982218231967/f
`exports` isn't supported by CRA, but `browser` appears to based on @ErikCH .
Tested the `legacy` usage with:
```diff
diff --git a/package.json b/package.json
index 8b58ec5..5d311fd 100644
--- a/package.json
+++ b/package.json
@@ -3,9 +3,11 @@
"version": "0.1.0",
"private": true,
"dependencies": {
+    "@aws-amplify/ui-react": "^2.0.1-next.1",
"@testing-library/jest-dom": "^5.11.4",
"@testing-library/react": "^11.1.0",
"@testing-library/user-event": "^12.1.10",
+    "aws-amplify": "^4.2.9",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-scripts": "4.0.3",
diff --git a/src/App.js b/src/App.js
index 3784575..5bb0923 100644
--- a/src/App.js
+++ …
```
=> Use `browser` for .css paths instead of `exports`

packages/ui/src/machines/actors/auth/signUp.ts
*Description of changes:* We need to add default value to `login_mechanisms` on `signUp` service, or else we'd get 
>login_mechanisms is not iterable
error... or even worse, 
> l is not iterable 
on production if `login_mechanisms` is not provided 😈 
=> fix(ui): Add missing default to login_mechanisms on sign up

examples/angular/src/pages/ui/components/authenticator/sign-in-federated/sign-in-federated.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-sign-up/amplify-sign-up.component.html, yarn.lock
*Description of changes:* 
https://user-images.githubusercontent.com/43682783/133345375-5fcee603-9665-4034-9543-4a992b586bd4.mp4
=> fix(angular): Fix typo in federated example + add federated sign up

docs/src/pages/ui/primitives/icon/react.mdx, packages/ui/src/theme/css/component/rating.scss
Custom icon styles for `Rating` will affect Icon's base styles.
1. Scoping down the custom icon styles to Rating specific.
2. Also fixed an alignment issue in Icon docs.
=> fix: scoping down rating icon style

packages/react/package.json
*Issue #, if available:* https://app.asana.com/0/0/1200984303035950/f
Fixes this warning:
```
$ yarn install @aws-amplify/ui-react@next
> warning nohoist config is ignored in "@aws-amplify/ui-react" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
```
=> Remove nohoist from React package

docs/src/pages/ui/components/authenticator/index.page.mdx, examples/angular/src/pages/ui/components/authenticator/auth-with-translations/auth-with-translations.component.ts, examples/next/pages/ui/components/authenticator/i18n/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-federated/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-sms-mfa/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-totp-mfa/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-totp-sms-mfa/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-with-email/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-with-phone/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-with-username/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-up-with-email/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-up-with-phone/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-up-with-username/index.page.tsx, examples/next/pages/ui/components/authenticator/withAuthenticator/index.page.tsx, packages/angular/projects/ui-angular/src/lib/components/amplify-authenticator/amplify-authenticator.component.ts, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/cypress/integration/common/sign-up.ts, packages/e2e/features/ui/components/authenticator/i18n.feature, packages/e2e/features/ui/components/authenticator/sign-up-with-email.feature, packages/e2e/features/ui/components/authenticator/sign-up-with-phone.feature, packages/e2e/features/ui/components/authenticator/sign-up-with-username.feature, packages/react/__tests__/exports.ts, packages/react/src/components/Authenticator/index.tsx, packages/react/src/components/Authenticator/shared/UserNameAlias.tsx, packages/react/src/index.tsx
*Issue #, if available:* https://app.asana.com/0/0/1200973733971731/f
Can't do this yet without a PR to send `Hub` events in Amplify JS
Not doing this explicitly because this would be a change in behavior where _by simply adding the new `Authenticator`_ could potentially change the entire page's language. (If the customer is using `I18n` anywhere else)
> ![Screen Shot 2021-09-21 at 4 52 48 PM](https://user-images.githubusercontent.com/15182/134252940-6628dbed-1d4f-4cd1-b7d9-149da5313085.png)
=> Default I18n Support

packages/react/src/primitives/types/style.ts
- Adds a `textAlign` property (similar to CSS text-align)
=> Add Primitives textAlign property

packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx
https://app.asana.com/0/0/1200981579819726/f
adding `RemoteErrorMessage` component to the `SetupTOTP` screen.
=> adding error message component to setupTotp screen

packages/ui/src/validators/index.ts
https://app.asana.com/0/1201058552570744/1200974176066591/f
Update the `passwordMatches` validator to only run if both the `password` and `confirm_password` fields have values entered. If one of the fields is blank, it will not show the error message.
=> update the password validator

packages/angular/projects/ui-angular/src/lib/components/amplify-authenticator/amplify-authenticator.component.html
*Description of changes:* The user content when `state.matches('authenticated')` should not be under `amplify-authenticated` so that it's free of authenticator styles.
Before:
After:
=> fix(angular): Render authenticated content outside amplify-authenticator

docs/src/pages/ui/components/authenticator/headless.angular.mdx, docs/src/pages/ui/components/authenticator/sign-up-with-email.angular.mdx, docs/src/pages/ui/components/authenticator/sign-up-with-phone.angular.mdx
*Description of changes:* Adds `sign-up-with-{email,phone}.angular.mdx` that were missing. Also updates headless docs to use template variable instead of `StateMachineService`, which needs more research.
=> docs: add missing angular docs

packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/VerifyUser/ConfirmVerifyUser.tsx
https://app.asana.com/0/1201058552570744/1201090845906805/f
Fixing styles that got messed up by removing Tailwind. Really, the only thing that needed changing was replacing `FieldGroup` with `Flex`. `FieldGroup` doesn't respect the `justify-content: space-between` style prop.
I watched as I ran each of the tests, and all the screens looked back to normal.
Screenshot showing fixed on one of the screens.
=> fixing styles by replacing FieldGroup with Flex

packages/react/src/components/Authenticator/index.tsx
> ![Screen Shot 2021-09-29 at 11 10 12 AM](https://user-images.githubusercontent.com/15182/135317880-30f8481e-a059-405d-aa31-4aada890b599.png)
---
=> withAuthenticator supports AuthenticatorProps

packages/react/src/primitives/Collection/Collection.tsx, packages/react/src/primitives/Collection/__tests__/Collection.test.tsx
#439 
This PR fixes a bug on the `<Collection>` component, which wasn't validating the type of `items` property (it should be an array)
=> Fix Collection items property validation

examples/next/next.config.js, examples/next/package.json, examples/next/pages/_app.page.tsx, examples/next/pages/examples/listings/index.page.tsx, examples/next/pages/ui/components/authenticator/auth-with-multi-alias/index.page.tsx, examples/next/pages/ui/components/authenticator/i18n/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-federated/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-sms-mfa/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-totp-mfa/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-totp-sms-mfa/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-with-email/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-with-phone/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-with-username/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-up-with-attributes/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-up-with-email/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-up-with-phone/index.page.tsx, examples/next/pages/ui/components/authenticator/withAuthenticator/index.page.tsx, yarn.lock
The styles for `examples/listings` were affecting the Authenticator pages (namely the `body` background color), making it look different than how it would appear for customers out of the box.
> <img width="681" alt="Screen Shot 2021-10-01 at 1 08 09 PM" src="https://user-images.githubusercontent.com/15182/135668676-b68f82b6-633c-4904-863b-10c9115eac37.png">
> <img width="1272" alt="Screen Shot 2021-10-01 at 1 08 44 PM" src="https://user-images.githubusercontent.com/15182/135668719-2315ddf3-8bf6-4d69-9167-38d8dbe2b387.png">
=> Move CSS imports to individual example pages

package.json, yarn.lock
Fixes security issue in `docs` where `trim` should be at least `0.0.3`.
[CVE-2020-7753](https://github.com/advisories/GHSA-w5p7-h5w8-2hfq)
```
high severity
Vulnerable versions: < 0.0.3
Patched version: 0.0.3
All versions of package trim lower than 0.0.3 are vulnerable to Regular Expression Denial of Service (ReDoS) via trim().
````
=> fix: pin trim to ^0.0.3

package.json, yarn.lock
This PR fixes a security issue with prismjs by bumping from 1.23.0 to 1.25.0.
[CVE-2021-3801](https://github.com/advisories/GHSA-hqhp-5p83-hx96)
> 
> Vulnerable versions: < 1.25.0
> Patched version: 1.25.0
> 
> The prismjs package is vulnerable to ReDoS (regular expression denial of service). An attacker that is able to provide a crafted HTML comment as input may cause an application to consume an excessive amount of CPU.
*Alternatives to pinning the version*
```bash
yarn why v1.22.11
=> Found "prismjs@1.25.0"
- "_project_#docs#mdx-prism#refractor" depends on it
- Hoisted from "_project_#docs#mdx-prism#refractor#prismjs"
```
I attempted to see if we could upgrade `mdx-prism` to get the latest version of `prismjs`, but `mdx-prism` …
=> Pin prismjs to ^1.25.0

package.json, yarn.lock
*Description of changes:* I was able to narrow down the recent vue failures to upstream dependency `vscode-vue-languageservice`. `vue-tsc` depends on `vscode-vue-languageservice@^0.27.0`, which got bumped as its semver is denoted by carets. Pinning this version to 0.27.26 to resolve CI. Will check their repo for related issues.
=> chore: Pin vscode-vue-languageservice to 0.27.26

packages/e2e/cypress/integration/common/shared.ts, packages/e2e/features/ui/components/authenticator/sign-in-with-username.feature, packages/ui/src/machines/authenticator/index.ts
*Issue #, if available:* Closes #470
`initialState` was being used for `initial`, which bypassed the `idle` checks.
https://user-images.githubusercontent.com/15182/136095045-51c22719-0101-4ff2-9ec3-befd8fdb8f49.mp4
=> Fix Authenticate on reload

docs/src/components/ScrollViewPropControls.tsx, docs/src/components/useScrollViewProps.tsx, docs/src/pages/ui/primitives/scrollview/demo.tsx, docs/src/pages/ui/primitives/scrollview/index.page.mdx, docs/src/pages/ui/primitives/scrollview/react.mdx, docs/src/styles/index.css, docs/src/styles/scrollView.css, packages/react/__tests__/exports.ts, packages/react/src/primitives/ScrollView/ScrollView.tsx, packages/react/src/primitives/ScrollView/__tests__/ScrollView.test.tsx, packages/react/src/primitives/ScrollView/index.ts, packages/react/src/primitives/index.tsx, packages/react/src/primitives/shared/constants.ts, packages/react/src/primitives/types/index.ts, packages/react/src/primitives/types/scrollView.ts, packages/ui/src/theme/css/component/scrollView.scss, packages/ui/src/theme/css/styles.scss
This PR will be adding `ScrollView` primitive. A `ScrollView` is essentially a `View` that allows scrolling of its inner contents.
Note: The `horizontal` and `vertical` scrolling orientation look no difference and behave the same as the default(`overflow: scroll`) because setting one axis to `visible` (the initial) while setting the other to a different value results in `visible` behaving as `auto`. See [overflow - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow)
=> ScrollView Primitive

docs/src/components/Example.tsx, docs/src/styles/styles.css, packages/angular/projects/ui-angular/src/lib/components/amplify-authenticator/amplify-authenticator.component.html, packages/angular/projects/ui-angular/styles/component.css, packages/react/src/components/Authenticator/index.tsx, packages/ui/src/theme/css/component/authenticator.scss, packages/vue/src/components/authenticator.vue
> <img width="1172" alt="Screen Shot 2021-10-06 at 1 02 01 PM" src="https://user-images.githubusercontent.com/15182/136258367-5c50a2dd-7e78-45e3-b43e-57c9cfd199df.png">
> https://ui.docs.amplify.aws/ui/components/authenticator#sign-up
> <img width="807" alt="Screen Shot 2021-10-06 at 1 03 56 PM" src="https://user-images.githubusercontent.com/15182/136258712-8adf9ef5-b910-443e-b4a5-73fa23b47105.png">
For example, I could use this style to make it more like an "overlay":
```css
[data-amplify-authenticator] { backdrop-filter: blur(2px) lightness(0.5); }
[data-amplify-modal] { opacity: 0.5; }
```
=> Make Authenticator modal adjacent to the form

.github/workflows/publish-latest.yml, package.json, yarn.lock
=> ci: changeset/actions minor fixes

.changeset/cold-yaks-laugh.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/authenticator.module.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/amplify-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/amplify-sign-up.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/sign-up-form-fields/sign-up-form-fields.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/sign-up-form-fields/sign-up-form-fields.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/index.ts
*Description of changes:* This adds `sign-up-form-fields` slot and component. 
`useAuthenticator` changes in angular will be in a later PR! (that'll be the last one for sign-up customization).
=> feat(angular): add sign-up-form-fields component

.changeset/shaggy-ladybugs-crash.md, packages/ui/src/theme/css/styles.scss
Applies styling rule `box-sizing: border-box` to all children of Amplify theme element.
=> Apply `box-sizing: border-box` to all Amplify theme children

packages/vue/src/components/confirm-reset-password.vue
On the Confirm reset password page, the error message that was displayed if the password and confirm password did not match was appearing at the bottom of the page. It should appear above the button.
=> Vue: Bug Fixed error messages on page

.changeset/stale-zoos-rescue.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-authenticator/amplify-authenticator.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-authenticator/amplify-authenticator.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-confirm-sign-in/amplify-confirm-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-confirm-sign-in/amplify-confirm-sign-in.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-confirm-sign-up/amplify-confirm-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-confirm-sign-up/amplify-confirm-sign-up.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-force-new-password/amplify-force-new-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-force-new-password/amplify-force-new-password.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-reset-password/amplify-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-reset-password/amplify-reset-password.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-setup-totp/amplify-setup-totp.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-setup-totp/amplify-setup-totp.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-in/amplify-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-in/amplify-sign-in.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/amplify-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/amplify-sign-up.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-verify-user/amplify-verify-user.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-verify-user/amplify-verify-user.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-verify-user/amplify-confirm-verify-user.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-verify-user/amplify-confirm-verify-user.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/amplify-form-field/amplify-form-field.component.ts, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/ui/src/helpers/auth.ts, packages/vue/src/components/authenticator.vue
Now, each auth subcomponents looks like how customers would implement their own components ✨ 
=> feat(angular): Implement public `AuthenticatorService` 

examples/angular/src/pages/ui/components/authenticator/custom-sign-up-fields/custom-sign-up-fields.component.html, examples/next/pages/ui/components/authenticator/custom-sign-up-fields/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/custom-sign-up-fields/index.vue, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/cypress/support/commands.d.ts, packages/e2e/features/ui/components/authenticator/custom-sign-up-fields.feature
*Issue #, if available:* Fixes #590
*Description of changes:* Marks "Preferred Username" custom input as required. Also adds a cypress util for testing if an input is invalid based on native html validations using `inputHTMLElement.checkValidity()`.
=> chore: Mark "Preferred Username" custom input as required

.changeset/tricky-worms-act.md, packages/react/src/primitives/shared/__tests__/utils.test.tsx, packages/react/src/primitives/shared/utils.ts
`getOverrideProps` was only returning the first `2` overrides.
This is a PR for @hsspain's fix to return all overrides.
=> Fix getOverrideProps to return all, not just 2

package.json
*Description of changes:* Prepends commit hash so that the versions look like 
```
next-[commit_sha]-timestamp
```
which will increase the specificity of each versions in case customers are interested in pinning to one of them.
=> build: prepend commit hash before date to @next versions

.github/CODEOWNERS
*Issue #, if available:* SecOps
*Description of changes:* As `legacy` is a protected branch of the repository, we should add a `CODEOWNERS` file which requires approval of pull requests to `legacy` by a member of the amplify-ui team.
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-branch-protection.
=> CODEOWNERS for legacy

.github/CODEOWNERS
*Issue #, if available:* SecOps
*Description of changes:* As `main` is a protected branch of the repository, we should add a `CODEOWNERS` file which requires approval of pull requests to `main` by a member of the amplify-ui team.
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-branch-protection.
=> CODEOWNERS for main

packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-authenticator/amplify-authenticator.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-confirm-sign-in/amplify-confirm-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-confirm-sign-up/amplify-confirm-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-force-new-password/amplify-force-new-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-reset-password/amplify-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-setup-totp/amplify-setup-totp.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-in/amplify-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/amplify-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-verify-user/amplify-verify-user.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-verify-user/amplify-confirm-verify-user.component.html, packages/ui/src/theme/css/component/authenticator.scss, packages/vue/src/components/authenticator.vue
*Description of changes:* Applying #647 changes to Angular as well.
Only meaningful html change is organizing authenticator content into header, body, and footer:
```diff
<div amplify-authenticator>
...
<div amplify-container>
+   <div data-amplify-header> ... </div>
+   <div data-amplify-body> ... </div>
+   <div data-amplify-footer> ... </div>
</div>
</div>
```
=> feat(angular,vue): header and footer slot + style

docs/src/components/Layout/SecondaryNav.tsx, docs/src/data/links.ts, docs/src/pages/components/ComponentsGrid.tsx
This PR updates the secondary navigation and components grid logic. It alphabetizes all the links and adds some missing components.
=> Docs - update secondary nav & grid logic

.changeset/cold-yaks-laugh.md, .changeset/stale-zoos-rescue.md, .changeset/wet-candles-warn.md, .changeset/wicked-cups-tie.md, .changeset/wise-bananas-protect.md, examples/angular/package.json, examples/next/package.json, examples/vue/package.json, packages/angular/projects/ui-angular/package.json, packages/e2e/package.json, packages/react/package.json, packages/ui/package.json, packages/vue/package.json, yarn.lock
*Description of changes:* Puts `ui` and `ui-[framework]` versions to current latest NPM version. This helps us to be more flexible about the version bump types we put on changesets.
Before/On GA, We can follow this up with adding changesets that makes "major" version bumps. This will bump everything to `2.0.0` (and `3.0.0` for `ui`). Maybe we can add one for the authenticator and one for primtives!
=> build: version clean up

examples/angular/src/app/app-routing.module.ts, examples/angular/src/app/app.module.ts, examples/angular/src/pages/ui/components/authenticator/sign-up-with-attributes/sign-up-with-attributes.component.html, examples/angular/src/pages/ui/components/authenticator/sign-up-with-attributes/sign-up-with-attributes.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-authenticator/amplify-authenticator.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/sign-up-form-fields/sign-up-form-fields.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/amplify-sign-up/sign-up-form-fields/sign-up-form-fields.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/amplify-form-field/amplify-form-field.component.html, packages/angular/projects/ui-angular/src/lib/primitives/amplify-form-field/amplify-form-field.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/amplify-password-field/amplify-password-field.component.html, packages/angular/projects/ui-angular/src/lib/primitives/amplify-password-field/amplify-password-field.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/amplify-text-field/amplify-text-field.component.html, packages/angular/projects/ui-angular/src/lib/primitives/amplify-text-field/amplify-text-field.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/phone-number-field/phone-number-field.component.html, packages/angular/projects/ui-angular/src/lib/primitives/phone-number-field/phone-number-field.component.ts, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/e2e/features/ui/components/authenticator/sign-up-with-attributes.feature, packages/e2e/features/ui/components/authenticator/sign-up-with-phone.feature, packages/e2e/features/ui/components/authenticator/sign-up-with-username.feature, packages/ui/src/helpers/auth.ts, packages/ui/src/types/authMachine.ts
*Issue #, if available:* #623, extending #650
=> Render required attributes by default in Angular

packages/react/src/components/Authenticator/FederatedSignIn/FederatedSignInButtons/FederatedSignInButton.tsx
Fixing text does not center in federated signin buttons
=> fix: center text in federated signin buttons

docs/src/pages/getting-started/installation/dependencies.react.mdx
*Issue*
Closes https://github.com/aws-amplify/amplify-ui/issues/667
This PR fixes an omission on the getting started page where the required `aws-amplify` dependency was missing from the yarn instructions.
=> Update yarn installation instructions

docs/src/styles/docs/code.scss, docs/src/styles/docs/header.scss, docs/src/styles/docs/sidebar.scss, docs/src/styles/docs/toc.scss, docs/src/theme.ts
*Description of changes:* 
* Fixing selection background color in dark mode
* Fixing light/dark transition bug in ToC
* Updating syntax highlighting colors to add more contrast for a11y
https://user-images.githubusercontent.com/321279/141269896-3c33b03f-7e88-45af-b55f-417247abbe8e.mp4
=> Updating docs colors to meet contrast standards

packages/ui/src/helpers/auth.ts, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/ui/src/machines/authenticator/signUp.ts
#599
I noticed the imports of lodash in the `@aws-amplify/ui` package was inconsistent. I updated it so all the lodash imports looked the same. This also helped reduce the bundle size in the Vue packages by 50kb.
=> Reduced bundle size by changing imports of lodash

.github/scripts/track-todos.sh, .github/workflows/tests.yml, .github/workflows/track-todos.yml
*Description of changes:* Currently, we have `@todo` items fail on `main` to track `@todo` tags. But failing `e2e` tests is not necessary because `@todo` tests are _expected_ to fail and are not breaking functionality. Instead, we really care about _tracking_ those @todos.
This adds a separate workflow for tracking @todo- features. e2e tests will no longer fail on them and continuous deployment will not be blocked by it.
See https://github.com/aws-amplify/amplify-ui/runs/4172243825?check_suite_focus=true for an example output:
---
=> ci: Add a workflow for tracking `@todo-`s

packages/react/src/components/AmplifyProvider/AmplifyContext.tsx, packages/react/src/hooks/useAmplify.ts, packages/react/src/primitives/shared/styleUtils.ts, packages/react/src/primitives/types/style.ts
1. Adding flex and margin style props
2. Making all props required in `ComponentPropToStyleProp` so that any missing style props in `ComponentPropsToStylePropsMap` will be caught.
3. Adding interface to type `useAmplify` hook explicitly
=> chore: adding flex and margin style props

examples/angular/src/pages/ui/components/authenticator/custom-sign-up-fields/custom-sign-up-fields.component.html, examples/angular/src/pages/ui/components/authenticator/custom-sign-up-fields/custom-sign-up-fields.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/amplify-form-field/amplify-form-field.component.ts
=> fix(angular): fix typos on `form-fields` and `custom-sign-up-fields` example

.changeset/dirty-keys-eat.md, packages/react/src/primitives/Button/Button.tsx, packages/react/src/primitives/Button/__tests__/Button.test.tsx, packages/react/src/primitives/View/View.tsx, packages/react/src/primitives/View/__tests__/View.test.tsx, packages/react/src/primitives/types/view.ts
This PR adds React.forwardRef support to the Button and View primitives to start. I'm not including all the primitive components in this PR for ease of review. When approved, I will cut follow up PRs for the other primitives.
*Why this PR*
React offers the `ref` API as a way to access the underlying DOM element for a component. This PR forwards a ref attached on one of the Amplify UI primitives down to the underlying element. This allows customers to have an escape hatch to manage focus, animations, check if an element is in viewport, etc.
Example:
```tsx
const CustomerComponent = () =>{
const ref = React.useRef<HTMLButtonElement>(null);
// In response to some other app action, force focus on button:
// ref.current.focus();
return(
<Button ref={ref>Hello</Button> …
```
=> Add forwardRef support to Button & View

.changeset/moody-clocks-rest.md, docs/src/pages/ui/hooks/storage/index.page.mdx, docs/src/pages/ui/hooks/storage/react.mdx, packages/react/__tests__/exports.ts, packages/react/src/hooks/__tests__/useStorageURL.test.ts, packages/react/src/hooks/index.tsx, packages/react/src/hooks/useStorageURL.ts
This PR introduces a new `useStorageURL` React hook to easily get a signed URL for an Amplify Storage object
=> useStorageURL React hook

.changeset/bump-versions.md, docs/src/components/CheckboxFieldPropControls.tsx, docs/src/components/ExpanderPropControls.tsx, docs/src/components/SliderFieldPropControls.tsx, docs/src/components/StepperFieldPropControls.tsx, docs/src/components/ToggleButtonPropControls.tsx, docs/src/components/useCheckboxFieldProps.tsx, docs/src/pages/components/authenticator/index.page.mdx, docs/src/pages/components/checkboxfield/demo.tsx, docs/src/pages/components/checkboxfield/examples/controlledExample.tsx, docs/src/pages/components/checkboxfield/examples/valueExample.tsx, docs/src/pages/components/checkboxfield/react.mdx, examples/next/pages/ui/components/authenticator/custom-sign-up-fields/index.page.tsx, packages/react/src/primitives/Checkbox/Checkbox.tsx, packages/react/src/primitives/Checkbox/__tests__/Checkbox.test.tsx, packages/react/src/primitives/CheckboxField/CheckboxField.tsx, packages/react/src/primitives/CheckboxField/__tests__/CheckboxField.test.tsx, packages/react/src/primitives/types/checkbox.ts, packages/react/src/primitives/types/checkboxField.ts
The `CheckboxField` is accepting `children` as label which is inconsistent with other field primitives
Removing labelled by `children` support in favor of passing a `label` prop
=> refactor: removing labelled by children in favor of label prop

.changeset/sharp-cherries-knock.md, docs/src/pages/_app.page.tsx, examples/next/pages/examples/listings/App.tsx, packages/react/src/components/AmplifyProvider/AmplifyContext.tsx, packages/react/src/components/AmplifyProvider/__tests__/AmplifyProvider.test.tsx, packages/react/src/components/AmplifyProvider/index.tsx, packages/react/src/hooks/useAmplify.ts
This PR removes the `AmplifyProvider` custom components feature. The original intention of this feature was to allow customers to completely override any primitive used below the `AmplifyProvider`. However, it doesn't work correctly as currently implemented as we import primitives used in other composed primitives directly from relative paths. Additionally, there is little evidence of a customer need for this feature that cannot be met primarily by overriding the provided CSS variables. This PR removes the feature for GA launch, but we may return to revisit this feature in the future depending on customer feedback.
Further background:
https://github.com/aws-amplify/amplify-ui/pull/582
(original git blame commits were overwritten)
By submitting this pull request, …
=> Remove AmplifyProvider custom components feature

.changeset/strong-spies-rush.md, packages/react/src/primitives/Divider/Divider.tsx, packages/react/src/primitives/Divider/__tests__/Divider.test.tsx, packages/react/src/primitives/Heading/Heading.tsx, packages/react/src/primitives/Heading/__tests__/Heading.test.tsx, packages/react/src/primitives/Icon/Icon.tsx, packages/react/src/primitives/Icon/__tests__/Icon.test.tsx, packages/react/src/primitives/Image/Image.tsx, packages/react/src/primitives/Image/__tests__/Image.test.tsx, packages/react/src/primitives/Text/Text.tsx, packages/react/src/primitives/Text/__test__/Text.test.tsx, packages/react/src/primitives/View/View.tsx
This PR adds forward ref support for base primitives: `Divider`, `Heading`, `Icon`, `Image`,  `Text` by wrapping them in `React.forwardRef`. I'm limiting the number of primitives changed per PR to make them easier to review.
```jsx
// do something with ref, like measure where it is on screen:
// ref.current.getBoundingClientRect()
return (
<Image ref={ref} />
);
};
```
=> ForwardRef support - base primitives

.changeset/heavy-bulldogs-sit.md, packages/react/src/primitives/Flex/Flex.tsx, packages/react/src/primitives/Flex/__tests__/Flex.test.tsx, packages/react/src/primitives/Grid/Grid.tsx, packages/react/src/primitives/Grid/__tests__/Grid.test.tsx, packages/react/src/primitives/View/View.tsx
*Issue:*
Closes https://github.com/aws-amplify/amplify-ui/issues/710
This PR adds forward ref support for `Flex` and `Grid` primitives by wrapping them in `React.forwardRef`. I'm limiting the number of primitives changed per PR to make them easier to review.
```jsx
// do something with ref, like measure where it is on screen:
// ref.current.getBoundingClientRect()
return (
<Flex ref={ref} />
);
};
```
=> ForwardRef support - Flex and Grid

.changeset/rich-experts-allow.md, packages/react/src/primitives/FieldGroupIcon/FieldGroupIcon.tsx, packages/react/src/primitives/FieldGroupIcon/__tests__/FieldGroupIcon.test.tsx, packages/react/src/primitives/Input/Input.tsx, packages/react/src/primitives/Input/__tests__/Input.test.tsx, packages/react/src/primitives/Label/Label.tsx, packages/react/src/primitives/Label/__tests__/Label.test.tsx, packages/react/src/primitives/Select/Select.tsx, packages/react/src/primitives/Select/__tests__/Select.test.tsx, packages/react/src/primitives/View/View.tsx
This PR adds forward ref support for the simple input related primitives (ones that directly render View) by wrapping them in `React.forwardRef`. I'm limiting the number of primitives changed per PR to make them easier to review.
```jsx
// do something with ref, like measure where it is on screen:
// ref.current.focus()
return (
<Input ref={ref} />
);
};
```
=> ForwardRef support - Simple Inputs

packages/react/src/helpers/index.ts, packages/react/src/helpers/utils.ts, packages/react/src/hooks/__tests__/useControllable.test.tsx, packages/react/src/hooks/index.tsx, packages/react/src/hooks/useControllable.ts, packages/react/src/hooks/useThemeBreakpoint.ts
1. Add `useControllable` internal hook to implement primitives (or other components) in an optionally controlled fashion. Currently we are already using this behavior in some of our components (eg. `Checkbox`) without appropriately warning the users about the improper usage. With this hook the duplication of the pattern would be avoided with better DX.
2. Add `useThemeBreakpoint` hook to get the current breakpoint value of the configured theme without writing down all the boilerplate for the same.
=> Add useControllable and useThemeBreakpoint hooks

docs/src/pages/components/image/demo.tsx, packages/react/src/primitives/Alert/__tests__/Alert.test.tsx, packages/react/src/primitives/Collection/__tests__/Collection.test.tsx, packages/react/src/primitives/Flex/__tests__/Flex.test.tsx, packages/react/src/primitives/Grid/__tests__/Grid.test.tsx, packages/react/src/primitives/Heading/__tests__/Heading.test.tsx, packages/react/src/primitives/Image/__tests__/Image.test.tsx, packages/react/src/primitives/Link/__tests__/Link.test.tsx, packages/react/src/primitives/Rating/RatingIcon.tsx, packages/react/src/primitives/Rating/__test__/Rating.test.tsx, packages/react/src/primitives/SwitchField/__tests__/SwitchField.test.tsx, packages/react/src/primitives/Tabs/Tabs.tsx, packages/react/src/primitives/Tabs/__tests__/Tabs.test.tsx, packages/react/src/primitives/Text/__test__/Text.test.tsx, packages/react/src/primitives/View/View.tsx, packages/react/src/primitives/View/__tests__/View.test.tsx, packages/react/src/primitives/types/input.ts, packages/react/src/primitives/types/link.ts, packages/react/src/primitives/types/tabs.ts
Tiny PR to update lodash imports in tests, and update React imports in primitive type files.
Related: https://github.com/aws-amplify/amplify-ui/pull/682
=> Update lodash / react imports

packages/react/src/primitives/Loader/Loader.tsx, packages/react/src/primitives/Loader/__tests__/Loader.test.tsx, packages/react/src/primitives/Placeholder/Placeholder.tsx, packages/react/src/primitives/Placeholder/__tests__/Placeholder.test.tsx, packages/react/src/primitives/VisuallyHidden/VisuallyHidden.tsx, packages/react/src/primitives/VisuallyHidden/__tests__/VisuallyHidden.test.tsx
This PR adds forward ref support for Util and simpler Feedback primitives (ones that directly render View) by wrapping them in `React.forwardRef`. I'm limiting the number of primitives changed per PR to make them easier to review.
```jsx
// do something with ref
// console.log(ref.current.nodeName); // logs "svg"
return (
<Loader ref={ref} />
);
};
```
=> ForwardRef support Utils and simple Feedback

docs/src/components/Layout/FrameworkChooser.tsx, docs/src/pages/components/authenticator/signUpAttributes.all.angular.mdx, docs/src/pages/components/authenticator/signUpAttributes.all.vue.mdx, docs/src/pages/components/authenticator/signUpAttributes.default.angular.mdx, docs/src/pages/components/authenticator/signUpAttributes.default.vue.mdx, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/vue/src/components/authenticator.vue
=> Angular / Vue , socialProviders, signUpAttributes documentation fix

docs/src/pages/components/togglebutton/examples.tsx, docs/src/pages/index.page.tsx, packages/react/package.json
* No longer running build:icons as part of react build since it will override prettier's changes
* Fixing broken icons in docs, should unblock #732
=> Fixing icon issues with docs build and react build

.changeset/polite-bags-wonder.md, packages/react/src/primitives/Checkbox/Checkbox.tsx, packages/react/src/primitives/Checkbox/__tests__/Checkbox.test.tsx, packages/react/src/primitives/CheckboxField/CheckboxField.tsx, packages/react/src/primitives/CheckboxField/__tests__/CheckboxField.test.tsx, packages/react/src/primitives/Radio/Radio.tsx, packages/react/src/primitives/Radio/__tests__/Radio.test.tsx, packages/react/src/primitives/RadioGroupField/RadioGroupField.tsx, packages/react/src/primitives/RadioGroupField/__tests__/RadioGroupField.test.tsx, packages/react/src/primitives/TextArea/TextArea.tsx, packages/react/src/primitives/TextArea/__tests__/TextArea.test.tsx
This PR adds forward ref support for the `TextArea`, `Checkbox`, `CheckboxField`, `Radio` and `RadioGroupField` primitives (ones that directly render View) by wrapping them in `React.forwardRef`. I'm limiting the number of primitives changed per PR to make them easier to review.
```jsx
// Below returns INPUT because the ref is forwarded down to DOM element
// (CheckboxField => Checkbox => View => <input>)
// ref.current.nodeName 
return (
<CheckboxField ref={ref} />
);
};
```
=> ForwardRef support - textarea, checkbox, radio

.github/workflows/tests.yml, docs/src/pages/components/authenticator/index.page.mdx, environments/README.md
*Issue #, if available:* Closes #646
=> Remove @beta references to @aws-amplify/cli

packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/badge.scss, packages/ui/src/theme/tokens/components/badge.js
* Added font color tokens for badges
* Used a reference to radii token for badge border radius so it is theme-able at a broader level
=> adding text color and border radius to badges

.changeset/angry-suns-divide.md, packages/react/src/primitives/PhoneNumberField/CountryCodeSelect.tsx, packages/react/src/primitives/PhoneNumberField/__tests__/CountryCodeSelect.test.tsx, packages/react/src/primitives/SelectField/SelectField.tsx, packages/react/src/primitives/SelectField/__tests__/SelectField.test.tsx, packages/react/src/primitives/SliderField/SliderField.tsx, packages/react/src/primitives/SliderField/__tests__/SliderField.test.tsx, packages/react/src/primitives/types/view.ts
This PR adds forward ref support for the `CountryCodeSelect`, `SelectField`, and `SliderField` primitives by wrapping them in `React.forwardRef`.
```jsx
// Below returns SPAN because the ref is forwarded down to DOM element (SliderField => Root => <span>)
// ref.current.nodeName 
return (
<SliderField ref={ref} />
);
};
```
=> ForwardRef support - CountryCode and SliderField

examples/angular/src/pages/ui/components/authenticator/custom-slots/custom-slots.component.ts
*Description of changes:* Currently, `private authenticator: AuthenticatorService` is marked as `private` in `custom-slots` example. This should be marked as public because they are being used in the templates. Technically the samples still worked because transpiled JS doesn't actually have private variables (yet), but it's a good practice.
=> chore(angular): make authenticator service variable public

.changeset/young-cheetahs-perform.md, packages/react/__tests__/exports.ts, packages/react/src/primitives/components.ts
This PR removes the `FieldGroup` internal component from the external API surface area. It wasn't intended to be exposed.
=> Remove internal FieldGroup from public export

docs/src/components/TablePropControls.tsx
*Description of changes:* Table docs page is fixed now:
=> Fixing table page

packages/angular/projects/ui-angular/src/lib/components/authenticator/components/reset-password/reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/reset-password/reset-password.component.ts, packages/e2e/features/ui/components/authenticator/reset-password.feature, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/ui/src/i18n/dictionaries/en.ts, packages/vue/src/components/reset-password.vue, packages/vue/src/composables/useAuth.ts
#714 
Updated placeholder label so it shows the correct `email/phone number/username` label on the reset password page. 
=> Fix forgot password placeholder

packages/react/__tests__/exports.ts, packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/VerifyUser/ConfirmVerifyUser.tsx, packages/react/src/components/Authenticator/VerifyUser/VerifyUser.tsx, packages/react/src/helpers/utils.ts, packages/react/src/primitives/index.tsx
Removes the `Form` primitive and replaces it with `form` in all the places it was used in Authenticator.
TODO:
=> Remove POC Form primitive

docs/src/components/Layout/Header.tsx, docs/src/components/Layout/SecondaryNav.tsx, docs/src/pages/components/ComponentsGrid.tsx
When navigating the docs site if you change to `Vue` or `Angular` the site forgets these selections when moving around the site.
My fix will always pass the current platform query params to every `NavLink`.
https://user-images.githubusercontent.com/65630/142316030-66397f57-4441-44b1-996e-16f594686ba8.mp4
=> Docs: Update navigation so query params are passed over

docs/src/components/useGridContainerProps.tsx
https://ui.docs.amplify.aws/components/grid fails with an error because `useState` is not defined.
=> Add missing useState import

docs/src/components/Layout/FrameworkChooser.tsx
https://user-images.githubusercontent.com/15182/142470568-e9821622-0906-4e43-b530-98a95f8ec23c.mp4
=> Persist & scroll to anchor when changing frameworks

.changeset/four-melons-double.md
*Description of changes:* Adds changeset for primitives + theming release. Added a placeholder for now.
=> Add changeset for Primitives + Theming Release

packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.html, packages/react/src/components/Authenticator/Router/index.tsx, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/ui/src/theme/css/component/authenticator.scss, packages/vue/src/components/authenticator.vue, packages/vue/src/components/primitives/base-footer.vue, packages/vue/src/components/sign-in.vue
*Description of changes:* Adding default padding-bottom to `sign-in-footer`.
Also adjusted `data-amplify-*` structure slightly. Now the routed screen is labeled `data-amplify-router`. Each screen has `data-amplify-header` and `data-amplify-footer` that has default styles. 
Overriding those headers will also remove those styles.
=> Add bottom-padding to sign-in and sign-up footer

docs/src/pages/components/pagination/react.mdx
Remove `usePagination` usage on docs but keep it exported for now per discussion today. Need more discussion on whether we should make it available externally.
=> docs: removing usePagination usage

docs/src/components/Layout/Footer.tsx, docs/src/components/Layout/SecondaryNav.tsx, docs/src/pages/_app.page.tsx
CopyToClipboard behavior relies on this to get element.innerText,
so this was the easiest implementation to stop warnings *for valid code*
=> Fix doc warnings

docs/src/pages/components/authenticator/LabelsAndTextDemo.tsx, docs/src/pages/components/authenticator/index.page.mdx, docs/src/pages/components/authenticator/initialState.resetPassword.react.mdx, docs/src/pages/components/authenticator/initialState.signIn.react.mdx, docs/src/pages/components/authenticator/initialState.signUp.react.mdx, docs/src/pages/components/authenticator/loginMechanisms.email.react.mdx, docs/src/pages/components/authenticator/loginMechanisms.phone_number.react.mdx, docs/src/pages/components/authenticator/loginMechanisms.username.react.mdx, docs/src/pages/components/authenticator/sign-up-fields.react.mdx, docs/src/pages/components/authenticator/signUpAttributes.all.react.mdx, docs/src/pages/components/authenticator/signUpAttributes.default.react.mdx, docs/src/pages/components/authenticator/socialProviders.react.mdx, examples/next/pages/ui/components/authenticator/custom-sign-up-fields/index.page.tsx, examples/next/pages/ui/components/authenticator/reset-password/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-in-with-username/index.page.tsx, examples/next/pages/ui/components/authenticator/sign-up-with-username/index.page.tsx
*Issue #, if available:* Closes #640
> Using the past <AmplifyAuthenticator/> is more component composition friendly compared to the new HOC withAuthenticator. I guess the new UI is not backward compatible as I have tried to simply replace <AmplifyAuthenticator/> with the new <Authenticator/>, but it doesn't work.
This will also make way for use cases like https://codesandbox.io/s/change-your-layout-rh4z9?file=/src/App.js with `useAuthenticator`.
=> React documentation prefers Authenticator over withAuthenticator

packages/react/src/components/AmplifyProvider/index.tsx
*Description of changes:* Instead of using `dangerouslySetInnerHTML`, using a string child node for the theme CSS injection. 
=> Removing dangerouslySetInnerHTML

packages/ui/src/theme/css/component/placeholder.scss
Height and width styles are ignored because the component has a default `inline` behavior. This PR add a `display: block` CSS property to the Placeholder primitive styles.
=> Change display policy for Placeholder component

.changeset/itchy-cougars-hug.md, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/cypress/integration/ui/components/authenticator/confirm-sign-up/confirm-sign-up.steps.ts, packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature, packages/ui/src/machines/authenticator/actions.ts
*Issue #, if available:* Fixes #818
*Description of changes:* Transition from `signIn` to `confirmSignUp` wasn't working correctly because `setCredentials` assumes `formValues[primaryAlias]` contains the username. This is not true for `signIn` because `signIn` always has its `primaryAlias` input `name` set to `username`. 
This PR handles `signIn` case and adds a test for it.
=> Fix redirect from signIn to confirmSignUp

docs/src/pages/components/chatbot/index.page.mdx, docs/src/pages/components/chatbot/usage.vue.mdx, docs/src/pages/components/chatbot/warning.angular.mdx, docs/src/pages/components/chatbot/warning.react.mdx, docs/src/pages/components/chatbot/warning.vue.mdx, docs/src/pages/components/storage/index.page.mdx, docs/src/pages/components/storage/warning.angular.mdx, docs/src/pages/components/storage/warning.react.mdx, docs/src/pages/components/storage/warning.vue.mdx, docs/src/pages/getting-started/installation/dependencies.vue.mdx
#815 
Vue Banner
Angular/React Banner
=> Vue: Fix docs for vue

.changeset/new-pumpkins-dress.md, packages/react/src/primitives/FieldGroup/FieldGroup.tsx, packages/react/src/primitives/FieldGroup/__tests__/FieldGroup.test.tsx, packages/react/src/primitives/FieldGroupIcon/FieldGroupIconButton.tsx, packages/react/src/primitives/FieldGroupIcon/__tests__/FieldGroupIconButton.test.tsx, packages/react/src/primitives/PasswordField/PasswordField.tsx, packages/react/src/primitives/PasswordField/__tests__/PasswordField.test.tsx
This PR adds forward ref support for the `PasswordField`, `FieldGroup`, & `FieldGroupIconButton` primitives by wrapping them in `React.forwardRef`. 
```jsx
// Below returns INPUT because the ref is forwarded down to DOM element (PasswordField => TextField => Input => <input>)
// ref.current.nodeName
return (
<PasswordField label="name" ref={ref} />
);
};
```
=> ForwardRef support for PasswordField, FieldGroup, & FieldGroupIconButton

.changeset/tall-cups-obey.md, packages/react/src/primitives/Field/FieldClearButton.tsx, packages/react/src/primitives/Field/__tests__/FieldClearButton.test.tsx, packages/react/src/primitives/FieldGroupIcon/FieldGroupIconButton.tsx, packages/react/src/primitives/FieldGroupIcon/__tests__/FieldGroupIcon.test.tsx, packages/react/src/primitives/FieldGroupIcon/__tests__/FieldGroupIconButton.test.tsx
Adding forward ref support for `FieldClearButton` & `FieldGroupIconButton`.  
@reesscot finished most all of the work here. Credits to him
=> ForwardRef support for FieldClearButton & FieldGroupIconButton

.changeset/olive-glasses-bake.md, examples/next/pages/ui/components/authenticator/withAuthenticator/index.page.tsx, packages/e2e/features/ui/components/authenticator/withAuthenticator.feature, packages/react/src/components/Authenticator/withAuthenticator.tsx
*Issue #, if available:* Closes #837
`withAuthenticator` didn't pass along props, but this PR passes it & validates it with a new `.feature` test.
=> Pass props from withAuthenticator to Component

.changeset/violet-bees-draw.md, docs/src/pages/components/phonenumberfield/examples/refs.tsx, docs/src/pages/components/phonenumberfield/react.mdx, packages/react/src/primitives/PhoneNumberField/PhoneNumberField.tsx, packages/react/src/primitives/PhoneNumberField/__tests__/PhoneNumberField.test.tsx, packages/react/src/primitives/types/phoneNumberField.ts
This PR adds forward ref support for the `PhoneNumberField` primitive by wrapping it in `React.forwardRef`. In this case we're supporting both the standard `ref` for access to the `input` field, and `countryCodeRef` for access to the `select` field.
```jsx
const countryCodeRef = React.useRef(null);
// Below returns INPUT because the ref is forwarded down to DOM element (PhoneNumberField => TextField => Input => <input>)
// ref.current.nodeName
// Below returns SELECT because the ref is forwarded down to DOM element (PhoneNumberField => SelectField => Input => <input>)
// ref.current.nodeName
return (
<PhoneNumberField label="name" ref={ref} countryCodeRef={countryCodeRef}/>
);
};
```
By submitting …
=> ForwardRef for PhoneNumberField

.changeset/swift-moons-kneel.md, docs/src/pages/components/passwordfield/examples/refs.tsx, docs/src/pages/components/passwordfield/react.mdx, packages/react/src/primitives/PasswordField/PasswordField.tsx, packages/react/src/primitives/PasswordField/ShowPasswordButton.tsx, packages/react/src/primitives/PasswordField/__tests__/PasswordField.test.tsx, packages/react/src/primitives/PasswordField/__tests__/ShowPasswordButton.test.tsx, packages/react/src/primitives/types/passwordField.ts
This PR adds forward ref support for the `ShowPasswordButton` in the `PasswordField` primitive by offering a `showPasswordRef` prop.
```jsx
export const RefExample = () => {
const inputRef = React.useRef(null);
const showPasswordRef = React.useRef(null);
const onShowPasswordClick = React.useCallback(() => {
inputRef.current.focus();
}, []);
React.useEffect(() => {
if (showPasswordRef && showPasswordRef.current) {
console.count('useeffect');
showPasswordRef.current.addEventListener(
'click',
onShowPasswordClick,
false
);
return () => {
showPasswordRef.current.removeEventListener(
'click',
onShowPasswordClick,
false
);
};
}
}, [onShowPasswordClick]);
return (
<PasswordField
ref={inputRef}
showPasswordRef={showPasswordRef}
label="Password"
/>
);
};
```
By submitting …
=> Update PasswordField to support showPasswordButton ref

.changeset/tidy-buckets-build.md, docs/src/pages/components/passwordfield/examples/refs.tsx, docs/src/pages/components/passwordfield/react.mdx, docs/src/pages/components/phonenumberfield/react.mdx, docs/src/pages/components/searchfield/examples/refs.tsx, docs/src/pages/components/searchfield/react.mdx, docs/src/pages/components/shared/forwardRefAlert.mdx, packages/react/src/primitives/SearchField/SearchField.tsx, packages/react/src/primitives/SearchField/SearchFieldButton.tsx, packages/react/src/primitives/SearchField/__tests__/SearchField.test.tsx, packages/react/src/primitives/SearchField/__tests__/SearchFieldButton.test.tsx, packages/react/src/primitives/types/searchField.ts
This PR adds forward ref support for the `SearchField` primitive by wrapping it in `React.forwardRef`. In this case we're supporting both the standard `ref` for access to the `input` field, and `searchButtonRef` for access to the `button` elements.
```jsx
const inputRef = React.useRef(null);
const searchButtonRef = React.useRef(null);
return (
<SearchField label="search" 
ref={inputRef}
searchButtonRef={searchButtonRef}
/>
);
};
```
=> ForwardRef support for SearchField

.changeset/clever-turtles-live.md, packages/react/src/primitives/Rating/Rating.tsx, packages/react/src/primitives/Rating/__test__/Rating.test.tsx
This PR adds forward ref support for the `Rating` primitive by wrapping it in `React.forwardRef`.
```jsx
const ref = React.useRef(null); // ref.current.nodeName will be `DIV`
return (
<Rating ref={ref}  />
);
};
```
=> ForwardRef support - Rating

.changeset/forward-ref-stepperfield.md, packages/react/src/primitives/StepperField/StepperField.tsx, packages/react/src/primitives/StepperField/__tests__/StepperField.test.tsx
This PR adds forward ref support for the `StepperField` primitive by wrapping it in `React.forwardRef`.
```jsx
const ref = React.useRef(null); // ref.current.nodeName will be `INPUT`
return (
<StepperField ref={ref}  />
);
};
```
=> ForwardRef for StepperField

.changeset/six-tigers-wink.md, packages/react/src/primitives/Alert/Alert.tsx, packages/react/src/primitives/Alert/__tests__/Alert.test.tsx, packages/react/src/primitives/ButtonGroup/ButtonGroup.tsx, packages/react/src/primitives/ButtonGroup/__tests__/ButtonGroup.test.tsx, packages/react/src/primitives/Expander/Expander.tsx, packages/react/src/primitives/Expander/ExpanderItem.tsx, packages/react/src/primitives/Expander/__tests__/Expander.test.tsx, packages/react/src/primitives/Expander/__tests__/ExpanderItem.test.tsx, packages/react/src/primitives/types/alert.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/alert.scss, packages/ui/src/theme/tokens/components/alert.js
Adding forward ref support for `Alert`, `ButtonGroup`, `Expander` & `ExpanderItem`.
=> ForwardRef support for Alert, ButtonGroup, Expander & ExpanderItem

.changeset/nice-cougars-reflect.md, package.json, yarn.lock
Vulnerable versions of `json-schema`: < 0.4.0
Upgrade to `^0.4.0`
=> fix: upgrading json-schema to 0.4.0 or later

.changeset/rotten-glasses-explode.md, packages/react/src/hooks/__tests__/useDataStore.test.ts, packages/react/src/hooks/useDataStore.tsx, packages/react/src/primitives/types/datastore.ts
Add `DataStore.observeQuery` support for `useDataStoreCollection` hook
=> Add DataStore.observeQuery support

.changeset/slimy-walls-marry.md, packages/react/src/primitives/Table/Table.tsx, packages/react/src/primitives/Table/TableBody.tsx, packages/react/src/primitives/Table/TableCell.tsx, packages/react/src/primitives/Table/TableFoot.tsx, packages/react/src/primitives/Table/TableHead.tsx, packages/react/src/primitives/Table/__tests__/Table.test.tsx, packages/react/src/primitives/Table/__tests__/TableBody.test.tsx, packages/react/src/primitives/Table/__tests__/TableCell.test.tsx, packages/react/src/primitives/Table/__tests__/TableFoot.test.tsx, packages/react/src/primitives/Table/__tests__/TableHead.test.tsx
This PR adds ForwardRef support for `Table/TableBody/TableHeader/TableFoot/TableCell` primitives.
```jsx
const ref = React.useRef(null); // ref.current.nodeName will be `TABLE`
return (
<Table ref={ref}  />
);
};
```
=> ForwardRef support for Table/TableBody/TableHeader/TableFoot/TableCell

.changeset/perfect-scissors-melt.md, packages/react/src/primitives/SwitchField/SwitchField.tsx, packages/react/src/primitives/SwitchField/__tests__/SwitchField.test.tsx
This PR adds forward ref support for the `SwitchField` primitive by wrapping it in `React.forwardRef`.
```jsx
const ref = React.useRef(null); // ref.current.nodeName will be `DIV`
return (
<SwitchField ref={ref}  />
);
};
```
=> ForwardRef support - SwitchField

.github/workflows/tests.yml
*Issue #, if available:* Closes #845
This enables **maintainers** to run tests on forks and PRs created by `github-actions` like #838. Tests on forks couldn't run because environment secrets aren't passed for security reasons.
To enable tests on these cases, `tests.yml` trigger is updated to `pull_request_target`. It is granted a read/write repository token and can access secrets even when it is triggered from a fork, so we need to be very careful about the tokens/secrets we expose.
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ has practical advices. This PR uses label-based approach -- maintainer first checks that code changes do not tamper secrets/tokens, then they can add `run-tests` to trigger the tests. Tests will run only when the label was *added* …
=> ci: Enable tests to run on forks and action-created PR

.changeset/tricky-camels-tie.md, packages/react/src/primitives/Menu/Menu.tsx, packages/react/src/primitives/Menu/__tests_/menu.test.tsx, packages/react/src/primitives/Pagination/Pagination.tsx, packages/react/src/primitives/Pagination/__tests__/Pagination.test.tsx
This PR adds forward ref support for the `Menu` and `Pagination` primitives by wrapping them in `React.forwardRef`.
```jsx
const ref = React.useRef(null); // ref.current.nodeName will be `NAV`
return (
<Pagination ref={ref}  />
);
};
```
=> ForwardRef support - Menu & Pagination primitives

.changeset/happy-shirts-doubt.md, packages/react/src/components/AmplifyProvider/index.tsx
*Issue #, if available:* #876
*Description of changes:* This adds back in dangerouslySetInnerHTML for the theme injection because without it there are hydration issues in NextJS because on the server the quotes are turned into html entities like `&quot;` and on the client they are not. 
https://user-images.githubusercontent.com/321279/143313100-a46e92b1-49e1-4c3c-a4e7-b14b7babe1c9.mp4
=> Add back in dangerouslySetInnerHTML for theme

.changeset/silver-comics-know.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/password-field/password-field.component.html, packages/angular/projects/ui-angular/src/lib/primitives/password-field/password-field.component.ts, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/e2e/cypress/integration/common/sign-in.ts, packages/e2e/cypress/integration/common/sign-up.ts, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/SignUp/FormFields.tsx, packages/ui/src/helpers/auth.ts, packages/ui/src/machines/authenticator/actions.ts, packages/ui/src/machines/authenticator/actors/resetPassword.ts, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/ui/src/machines/authenticator/defaultServices.ts, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/machines/authenticator/signUp.ts, packages/ui/src/types/authMachine.ts, packages/ui/src/types/validator.ts, packages/ui/src/validators/index.ts, packages/vue/src/components/authenticator-sign-up-form-fields.vue, packages/vue/src/components/authenticator.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/force-new-password.vue, packages/vue/src/components/password-control.vue, packages/vue/src/composables/useUtils.ts
#767 
Improved UX for confirm. Now it shows the error on blur, or when the value is over 6 characters
Validation occurs on blur (Less then six characters)
https://user-images.githubusercontent.com/65630/143136838-ce186970-354d-425d-97ef-5572343ee2ad.mp4
Validation occurs after six or more characters are type
https://user-images.githubusercontent.com/65630/143136867-92ed44e0-af20-40f8-ba6f-d9c2d6d2c841.mp4
=> Improve Confirm Password Error Validation

.changeset/JrPribs-885.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/authenticator.module.ts
This import is causing angular to attempt to import the BrowserModule twice
=> Removes BrowserModule as Angular packages shouldn't import it

packages/react/src/primitives/Badge/Badge.tsx, packages/react/src/primitives/Button/Button.tsx, packages/react/src/primitives/Card/Card.tsx, packages/react/src/primitives/Checkbox/Checkbox.tsx, packages/react/src/primitives/CheckboxField/CheckboxField.tsx, packages/react/src/primitives/Divider/Divider.tsx, packages/react/src/primitives/FieldGroupIcon/FieldGroupIcon.tsx, packages/react/src/primitives/Flex/Flex.tsx, packages/react/src/primitives/Grid/Grid.tsx, packages/react/src/primitives/Heading/Heading.tsx, packages/react/src/primitives/Icon/Icon.tsx, packages/react/src/primitives/Image/Image.tsx, packages/react/src/primitives/Input/Input.tsx, packages/react/src/primitives/Label/Label.tsx, packages/react/src/primitives/Link/Link.tsx, packages/react/src/primitives/Loader/Loader.tsx, packages/react/src/primitives/Placeholder/Placeholder.tsx, packages/react/src/primitives/Radio/Radio.tsx, packages/react/src/primitives/RadioGroupField/RadioGroupField.tsx, packages/react/src/primitives/ScrollView/ScrollView.tsx, packages/react/src/primitives/Select/Select.tsx, packages/react/src/primitives/Text/Text.tsx, packages/react/src/primitives/TextArea/TextArea.tsx, packages/react/src/primitives/View/View.tsx, packages/react/src/primitives/VisuallyHidden/VisuallyHidden.tsx
Standardize primitive function names to use a `*Primitive` suffix (instead of `*Inner`)
=> Rename *Inner primitive names

amplify.yml
Set console Amplify UI build to use Node 14, instead of 16, so build will deploy correctly in console. 
=> Update Node Version for Amplify UI Docs Console Build

amplify.yml
To fix error in console add in `nvm use 14`
2021-11-26T23:11:49.680Z [INFO]: Found '/codebuild/output/src626742148/src/amplify-ui/.nvmrc' with version <lts/*>
2021-11-26T23:11:49.763Z [WARNING]: N/A: version "lts/* -> N/A" is not yet installed.
2021-11-26T23:11:49.764Z [WARNING]: You need to run "nvm install lts/*" to install it before using it.
2021-11-26T23:11:49.764Z [ERROR]: !!! Build failed
=> Fix build console

.changeset/nine-comics-work.md, packages/react/src/primitives/Table/TableRow.tsx, packages/react/src/primitives/Table/__tests__/Table.test.tsx, packages/react/src/primitives/Table/__tests__/TableRow.test.tsx, packages/react/src/primitives/Tabs/Tabs.tsx, packages/react/src/primitives/Tabs/__tests__/Tabs.test.tsx, packages/react/src/primitives/ToggleButton/ToggleButton.tsx, packages/react/src/primitives/ToggleButton/__tests__/ToggleButton.test.tsx, packages/react/src/primitives/ToggleButtonGroup/ToggleButtonGroup.tsx, packages/react/src/primitives/ToggleButtonGroup/__tests__/ToggleButtonGroup.test.tsx, packages/react/src/primitives/View/View.tsx, packages/react/src/primitives/View/__tests__/View.test.tsx, packages/react/src/primitives/shared/constants.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/tabs.scss, packages/ui/src/theme/tokens/components/tabs.js
This PR will be adding Forward ref support for `TableRow`, `Tabs`, `ToggleButton` & `ToggleButtonGroup`
=> Forward ref support for TableRow, Tabs, ToggleButton & ToggleButtonGroup

packages/react/scripts/generatePrimitivesCatalog.ts
*Description of changes:* The primitives.json catalog generates a lot of noise. The `Alert` primitive for example has around 150 props, most of which are not useful in 99% of cases. As an **interim** quick and dirty solution, I am adding a `priority` attribute in the primitives.json file to signify if that a certain prop is actually one a user would use. There is a wider discussion we will probably need to have about how we should be managing our types and props for components across frameworks and how that makes it into documentation. For example, the primitive docs pages have an editorialized set of props in the demo, like the [Alert](https://ui.docs.amplify.aws/components/alert) demo shows 5 props and that demo code is hand-written. So this is a temporary …
=> Adding a priority field to the generated primitives.json

docs/src/pages/getting-started/installation/dependencies.react.mdx, docs/src/pages/getting-started/installation/index.page.mdx
Building some sample apps I've found myself forgetting to add the CSS file via `import '@aws-amplify/ui-react/styles.css'`. This is my attempt to make the getting started instructions a bit clearer.
Changes:
1. _Add the CSS import in the main code block, so customers can copy paste a single code block to get started_
```
import { AmplifyProvider } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css'; // <--- added CSS import here
export default = () => (
<AmplifyProvider>
<App />
</AmplifyProvider>
);
```
2. Add Packages and Styles as Level 3 headings to put them under Dependencies.
=> Update getting started to include CSS import

amplify.yml, docs/.eslintrc.json, docs/next.config.js, docs/package.json, docs/src/components/Demo.tsx, docs/src/components/Feature.tsx, docs/src/pages/ThemeButton.tsx, docs/src/pages/_app.page.tsx, docs/src/pages/_document.page.tsx, docs/src/pages/components/ComponentsGrid.tsx, docs/src/pages/components/card/demo.tsx, docs/src/pages/components/card/examples/CardAsExample.tsx, docs/src/pages/components/icon/AllIcons.tsx, docs/src/pages/components/tabs/demo.tsx, docs/src/pages/components/view/demo.tsx, docs/src/pages/theming/default-theme/colors.tsx, docs/src/pages/theming/default-theme/themeStructure.tsx, docs/tsconfig.json, examples/next/package.json, package.json, yarn.lock
rm -rf docs/.next && time yarn docs build
✨  Done in 61.51s.
yarn docs build  218.09s user 36.18s system 412% cpu 1:01.65 total
✨  Done in 48.16s.
yarn docs build  141.65s user 44.45s system 385% cpu 48.301 total
We couldn't do this before because we had to share the same version of Next.js as https://github.com/aws-amplify/docs
=> Convert docs from SSR to SSG

docs/src/pages/getting-started/installation/troubleshooting.react.mdx
This PR adds more troubleshooting docs for using ui-react with Vite. In particular it solves the following errors:
1. `process is not defined`
This error message is caused because, unlike Webpack, Vite doesn't shim the NodeJS `process`. The solution is to add a shim for it as detailed [here](https://docs.amplify.aws/start/getting-started/setup/q/integration/angular/#angular-6-support).
*REMOVED: as this solution only worked for `yarn` and not `npm`*
2. `[vite] Internal server error: Failed to find '@aws-amplify/ui/styles.css'`-
This is caused by our peer dependency on `aws-amplify`, which has a dependency on `@aws-amplify/ui@v2`. The older version of  `@aws-amplify/ui` doesn't have the browser aliases which redirect `'@aws-amplify/ui/styles.css'` => …
=> Add Vite troubleshooting docs for missing node var

docs/src/pages/index.page.tsx
This PR fixes an issue where Firefox locks up on homepage when running the demo (sandpack). The fix is to disable `autorun` so that it only runs when clicking `run`. This is a stopgap measure, as clicking `run` in Firefox will still lock up the browser, so a follow up fix is needed for a complete solution. However, this will make the homepage useable in Firefox.
_Before in Firefox (Initial page load):_
_After in Firefox (Initial page load):_
=> Docs: update sandpack to not autorun on homepage

docs/src/pages/index.page.tsx, docs/src/styles/docs/base.scss, docs/src/styles/docs/header.scss
Closes #923 
This PR constrains the width of the homepage content to prevent it from getting too wide on large screens.
*Also fixed:*
* Horizontal scrollbar bug caused by vertical scrollbar (`100vw` => `100%`)
* Made "Looking for other Amplify Products?" list collapse to single column on smaller screens
https://user-images.githubusercontent.com/6165315/144944106-e983f74d-7d76-4b97-be66-b7dbe873d9c6.mp4
https://user-images.githubusercontent.com/6165315/144944118-0673121c-bb31-4daa-8ad5-6d7620f33d00.mp4
https://user-images.githubusercontent.com/6165315/144944094-512d5f7a-5838-47e9-9a2f-a0ae6d0b039f.mp4
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> Docs: constrain homepage content width on larger screens

.changeset/quiet-carpets-swim.md, examples/angular/src/pages/ui/components/authenticator/i18n/aws-exports.js, examples/angular/src/pages/ui/components/authenticator/i18n/i18n.component.ts, examples/next/pages/ui/components/authenticator/i18n/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/i18n/index.vue, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.ts, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/e2e/cypress/integration/ui/components/authenticator/i18n/i18n.steps.ts, packages/e2e/features/ui/components/authenticator/i18n.feature, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/SignUp/FormFields.tsx, packages/react/src/components/Authenticator/shared/RemoteErrorMessage.tsx, packages/vue/src/components/authenticator-sign-up-form-fields.vue, packages/vue/src/components/authenticator.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/confirm-sign-in.vue, packages/vue/src/components/confirm-sign-up.vue, packages/vue/src/components/confirm-verify-user.vue, packages/vue/src/components/force-new-password.vue, packages/vue/src/components/reset-password.vue, packages/vue/src/components/setup-totp.vue, packages/vue/src/components/sign-in.vue, packages/vue/src/components/sign-up.vue, packages/vue/src/components/verify-user.vue
#255 
This fix will allow users to overwrite any error or validation error message in the application. For example a user can overwrite the error message when a user does not exist when logging in.
```
I18n.putVocabularies(translations);
I18n.setLanguage('ja');
I18n.putVocabulariesForLanguage('ja', {
'Sign In': 'Sign In Custom',
'User does not exist.': 'Error with your user',
});
```
You can see an example of this in our `i18n` feature test. 
=> Add custom translatable error messages from Cognito

packages/react/package.json
Adding a missing entry for `primitives.json` file in package.json `exports` section
=> Add primitives.json to package exports

.changeset/spicy-needles-shave.md, packages/react/src/hooks/__tests__/useComposeRefsCallback.test.tsx, packages/react/src/hooks/useComposeRefsCallback.tsx, packages/react/src/primitives/SearchField/SearchField.tsx, packages/react/src/primitives/SearchField/__tests__/SearchField.test.tsx, packages/react/src/primitives/SearchField/useSearchField.tsx, packages/react/src/primitives/types/searchField.ts
Closes #848 
This PR adds behavior of refocusing the search input field when a user clicks the clear button so that a user can reenter their search query.
=> Refocus `SearchField` input field on clear button click

docs/src/pages/components/authenticator/index.page.mdx
https://ui.docs.amplify.aws/components/authenticator#styling incorrectly links `theme` to https://ui.docs.amplify.aws/ui/theme/ instead of `/theming`.
=> Fix path to /theming

.github/workflows/publish-latest.yml, .github/workflows/publish-next.yml, .github/workflows/tests.yml, .husky/post-merge, CONTRIBUTING.md, package.json
*Issue #, if available:* Fixes #927
*Description of changes:* This uses [`actions/cache`](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows) to shorten the CI runtime to reuse artifacts and dependencies.
Cache is identified by a unique key. With `hashFiles` and other identifiers, we can construct keys to explicitly define the criteria for cache hit. For example, I use 
```
key: ${{ runner.os }}-cypress-${{ hashFiles('yarn.lock') }}
``` 
to cache cypress runner. This ensures that we reuse the same cypress file between workflows as long as they have the same `yarn.lock` file. If `yarn.lock` changes, which means cypress runner have possible changes, we rebuild and cache the new cypress runner.
This PR also separates `build` from `install` to allow …
=> ci: cache artifacts and remove repeated steps

.github/workflows/tests.yml
*Description of changes:* tests/setup was checking out the wrong `ref` because `${{ steps.get-ref.outputs.ref }}` were undefined at that step. Reordering steps to correct it.
=> CI: Get ref before checkout

.changeset/late-snails-cover.md, examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.html, examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.ts, examples/next/pages/ui/components/authenticator/sign-up-with-email/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-email/index.vue, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/features/ui/components/authenticator/sign-up-with-email.feature, packages/ui/src/machines/authenticator/actors/resetPassword.ts, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/ui/src/machines/authenticator/defaultServices.ts, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/machines/authenticator/signUp.ts, packages/ui/src/types/authMachine.ts, packages/ui/src/types/validator.ts
#836
Added additional ways to override common submissions for the following:
handleSignUp: SignUp
handleSignIn: Sign In
handleConfirmSignIn: Confirm Sign In
handleConfirmSignUp: Confirm Sign Up
handleForgotPasswordSubmit: Forgot Password Submit
handleForgotPassword: Forgot Password
I'll add docs for this feature in #974
=> Validate/modify formData on SignUp 

amplify.yml, docs/package.json
This fixes an issue where the Amplify Hosting build is failing when using Webpack 5 because the docs/package.json doesn't explicitly declare the `@aws-amplify/ui-react` dependency.
=> Docs fix: add missing dep @aws-amplify/ui-react required by Webpack 5

docs/public/amplify-logo.svg, docs/src/pages/components/authenticator/index.page.mdx, docs/src/pages/components/image/demo.tsx, docs/src/pages/components/scrollview/demo.tsx, docs/src/pages/components/scrollview/react.mdx
*Problem*
The new UI Docs site CSP rules block external images, so the ScrollView amplify logo loaded from [docs.amplify.aws](https://docs.amplify.aws/assets/logo-dark.svg) is not loading.
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://docs.amplify.aws/assets/logo-dark.svg (“default-src”).
```
*Solution*
This PR fixes this issue by moving the amplify logo file into UI repo so that we don't need any additional CSP rules, and don't have cross doc site dependencies.
_Before_
_After_
=> docs fix: img src csp blocking external demo images

.changeset/modern-ligers-attack.md, packages/e2e/cypress/fixtures/force-change-password-mfa-setup.json, packages/e2e/features/ui/components/authenticator/sign-in-totp-mfa.feature, packages/ui/src/machines/authenticator/actors/signIn.ts
#995 
Updated code so it also checks for SETUP TOTP after force change password, not just SMS MFA
=> Force Change Password should also check for SETUP TOTP

.changeset/rude-bobcats-grin.md, packages/ui/src/i18n/dictionaries/authenticator/de.ts
Add the missing Confirm Password to the german translation
=> Add missing translation

docs/src/pages/index.page.tsx
This PR changes the `@aws-amplify/ui-react` dependency version used by the demo on the homepage  from `next` to `latest`. This will protect the homepage demo from breaking from changes on `next`.
=> docs fix: pin homepage demo ui-react dep to latest

docs/src/pages/_document.page.tsx
N/A
Seeing the following error message in console on [docs site](https://ui.docs.amplify.aws):
Note: I only see this error when refreshing the page, so it appears to be occurring on page unload.
Update the CSP rule for `connect-src` with required URL.
=> docs fix: CSP error for analytics domain

.changeset/green-onions-cheer.md, packages/ui/src/machines/authenticator/signUp.ts
Closes https://github.com/aws-amplify/amplify-ui/issues/1008
This fixes an issue where phone number validation fails for country code `+1` when there are other form validation errors such as a short password. This causes the `phone_number` value to be mutated, and `N` number of `+1`'s to be appended (where N is number of times the form has been submitted):
```
UserAttributes: { phone_number: "+1+1+12223334444"}
Username: "+1+1+12223334444
```
The fix ensures that `formValues.phone_number` is not mutated on each `signUp` call.
=> Authenticator: fix issue where phone_number validation fails

.changeset/hungry-forks-play.md, packages/react/src/styles.css, packages/react/src/styles.ts, packages/react/tsup.config.js
Fixes: https://github.com/aws-amplify/amplify-ui/issues/1020 and https://github.com/aws-amplify/amplify-ui/issues/1005
Customers are experiencing an issue with the [parcel bundler](https://parceljs.org/recipes/react/) where the CSS statement `@import '@aws-amplify/ui/styles.css';` pointing to `ui` package cannot be resolved via `node_modules`. This PR fixes this by building the styles from `ui` into `ui-react` using `tsup`.
Testing TODO:
=> Build `ui` styles into `ui-react` package

docs/src/pages/404.page.tsx
*Description of changes:* Fixing an issue with loading a cat photo on the 404 page. Now we are grabbing a random cat photo on the client side only so there isn't a flash of content and making sure we have a cat before rendering the image. 
=> Fix cats on 404

docs/src/styles/docs/code.scss
Fixes: https://github.com/aws-amplify/amplify-ui/issues/1030
Fix color of equals sign so that it's visible in dark mode.
=> Fix equals sign color in dark mode

docs/src/pages/getting-started/installation/index.page.mdx
Closes https://github.com/aws-amplify/amplify-ui/issues/1029
Fix link to theme docs page.
=> fix docs theme link

docs/src/pages/theming/getting-started.react.mdx, docs/src/pages/theming/index.page.mdx
There are multiple unnecessary references to `createTheme` in the [Theme docs ](https://ui.docs.amplify.aws/theming). The `AmplifyProvider` already runs `createTheme` to extend custom themes from the default theme, so it's redundant for customers to do this as well.
=> Theming docs cleanup - remove `createtheme` references

docs/src/components/Demo.tsx
*Description of changes:* Made the layout for the demo area of primitive pages responsive. 
https://user-images.githubusercontent.com/321279/146978510-c73518d5-a55e-48cc-a4de-26d158544706.mp4
=> Better mobile layout for demo on primitive pages

.gitignore, examples/vue/package.json, package.json, yarn.lock
This primarily improves the `yarn build` experience, particularly _post-merge_
https://turborepo.org/docs/features/pipelines#defining-a-pipeline
**There shouldn't be much need to `rm -rf node_modules` since #1051
Nope, because `yarn ui build` is ran instead of `yarn build`.
This PR primarily improves local DX.  For CI improvements, we'd want to use [remote caching](https://turborepo.org/docs/features/remote-caching).
=> Replace `ultra build` with `turbo run build`

packages/ui/src/theme/css/component/text.scss
#1048 
Add a `pre-wrap` word-wrap behavior for `<Text>` components. Note: this only applies when the component is rendered as a HTML `p` tag.
=> Add white-space (pre-wrap) behavior for Text components

.changeset/gorgeous-ways-jam.md, packages/vue/package.json, packages/vue/src/composables/useAuth.ts, yarn.lock
#1050 
Added wrapper to handle memory better when reusing the `useAuthenticator` composable in multiple vue instances. 
=> Vue: Fix memory allocation for useAuthenticator composable

docs/src/pages/getting-started/installation/troubleshooting.react.mdx
Fixes: https://github.com/aws-amplify/amplify-ui/issues/930
This PR adds instructions on how to polyfill the Node.js globals needed by `aws-amplify` when using Webpack 5.
=> Add Webpack 5 troubleshooting

.changeset/dull-turkeys-juggle.md, packages/react/src/primitives/shared/responsive/__tests__/getMediaQueries.test.ts, packages/react/src/primitives/shared/responsive/getMediaQueries.ts
Closes https://github.com/aws-amplify/amplify-ui/issues/1059
Because `em`'s are calculated based on the base font size, there was a 14px gap below breakpoints where the default breakpoint of `base` is returned. This fixes the issue using `calc()` to calculate the max-width as the upper breakpoint minus `1px`. This allows us to continue using `em` breakpoints while returning the correct breakpoint styling for 1-14px below a given breakpoint.
**Before fix**
At 767px (1px below medium 768px), background color rendering **incorrectly** as `base: "red"`.
**After fix**
At 767px (1px below medium 768px), background color rendering **correctly** as `small: "orange"`
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> Update media query logic to return correct breakpoint

.changeset/dull-turkeys-juggle.md, packages/react/src/primitives/shared/responsive/__tests__/getMediaQueries.test.ts, packages/react/src/primitives/shared/responsive/getMediaQueries.ts
This reverts commit 10af6031e8beb22e79c8ecb5a3ea57f7e2d0bb3c.
While [calc is supported in media queries](https://caniuse.com/mdn-css_at-rules_media_calc) Chrome doesn't like multi-unit calc functions. Reverting while I figure out an alternative fix for the media query issue.
=> Revert "Update media query logic to return correct breakpoint (#1060)"

.changeset/fuzzy-gifts-punch.md, packages/ui/src/theme/css/styles.scss
Fixes https://github.com/aws-amplify/amplify-ui/issues/1062
This fixes an issue where defining a fonts token in custom theme didn't override the default Inter font. This was occurring because the `font-family: var(--amplify-fonts-default-static)` was only defined at the root. The `AmplifyProvider` converts custom theme tokens to CSS variables at the [data-amplify-theme] node and below. Since the rule was at the root node level, `--amplify-fonts-default-static` still had the original value of `Inter`, so the custom font token (defined at the [data-amplify-theme] node) wouldn't be read.
Solution:
Moving it to the [data-amplify-theme] ensures that the custom font token CSS variable is picked up correctly.
*Testing*
Manually tested using my …
=> Move font-family rule to [data-amplify-theme]

docs/src/pages/theming/getting-started.react.mdx
Adds TypeScript and JavaScript tabs to getting started theming screen
Adds a component variation example to the "use the theme" step
Makes small formatting adjustments
Addresses comments from https://github.com/aws-amplify/amplify-ui/pull/960. 
=> Adds TypeScript and JavaScript tabs to getting started theming screen

.changeset/orange-toys-remain.md, packages/angular/projects/ui-angular/theme.css, packages/vue/src/components/primitives/styles.css
After we moved the fonts to `[data-amplify-theme]` in #1065 this caused the fonts in Vue and Angular to default back to Times New Roman.
To fix this, I added back these fonts only for Vue and Angular. When Vue and Angular implement their own theming/ component system, this can be deleted. 
Before:
After:
=> Angular + Vue: Fix Fonts

.changeset/config.json
*Description of changes:* This ignores `@aws-amplify/ui-angular` , `@aws-amplify/ui-vue`, and `@aws-amplify/ui-react` so that only `@aws-amplify/ui-svelte` is published to `@next` on `ui-svelte/main` branch. This prevents conflicts to `@next` tag from the two branches.
=> ci(@aws-amplify/ui-svelte): only enable publish from `packages/svelte`

docs/src/theme.ts
#983 
Removing color and background color overrides in doc site theme
Light mode:
Unpressed
Pressed
--------------------------------
Dark mode:
Unpressed
Pressed
=> fix: fixing the color and background color in pressed state

.changeset/big-emus-brake.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-totp/setup-totp.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-totp/setup-totp.component.ts, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/ui/src/theme/css/component/authenticator.scss, packages/vue/src/components/setup-totp.vue
#881 
Updated QR code page so users can copy the secret key, instead of using QR code.
https://user-images.githubusercontent.com/65630/148132938-3be26b59-df36-4996-af81-4fa9135ae769.mp4
=> Updated to QR code page

.github/workflows/publish-next.yml
*Description of changes:* With `ui-svelte/main` branch set up, this workflow now needs to checkout the head branch that triggered the workflow, instead of assuming it to be `main`.
=> Checkout the head_branch when publish `@next`

.changeset/good-toes-change.md, .github/workflows/tests.yml, docs/src/pages/theming/responsive/index.page.mdx, docs/src/pages/theming/responsive/react.mdx, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/cypress/integration/ui/theme/responsive/responsive.steps.ts, packages/e2e/features/ui/theme/responsive.feature, packages/e2e/features/ui/theme/theme.features, packages/e2e/package.json, packages/react/src/hooks/useThemeBreakpoint.ts, packages/react/src/primitives/shared/responsive/__tests__/getMediaQueries.test.ts, packages/react/src/primitives/shared/responsive/__tests__/useBreakpoint.test.ts, packages/react/src/primitives/shared/responsive/getMediaQueries.ts, packages/react/src/primitives/shared/responsive/useBreakpoint.ts, packages/react/src/primitives/shared/styleUtils.ts, packages/react/src/primitives/types/responsive.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/breakpoints.ts, packages/ui/src/theme/createTheme.ts
Closes https://github.com/aws-amplify/amplify-ui/issues/1059
This PR updates the responsive breakpoint logic to use `px` instead of `em`. Previous fix for https://github.com/aws-amplify/amplify-ui/issues/1059 attempted to use `calc` to subtract `1px` from the `em` value of the next breakpoint. This didn't work correctly in Chrome, which doesn't support mixing units while using calc in media queries, so I [did more experiments](https://codepen.io/reescott/pen/RwLQbVg).
**Background**: 
I originally built the responsive support using `em`s because `em`s are based on the [user's font size choice](https://css-tricks.com/weekly-platform-news-focus-rings-donut-scope-ditching-em-units-and-global-privacy-control/#the-case-for-em-based-media-querie …
=> Update responsive breakpoints to use `px`

.changeset/many-pigs-chew.md, docs/src/pages/components/authenticator/LabelsAndTextDemo.tsx, docs/src/pages/components/authenticator/index.page.mdx, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.ts, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/ui/src/i18n/dictionaries/authenticator/de.ts, packages/ui/src/i18n/dictionaries/authenticator/defaultTexts.ts, packages/ui/src/i18n/dictionaries/authenticator/en.ts, packages/ui/src/i18n/dictionaries/authenticator/fr.ts, packages/ui/src/i18n/dictionaries/authenticator/it.ts, packages/ui/src/i18n/dictionaries/authenticator/ja.ts, packages/ui/src/i18n/dictionaries/authenticator/kr.ts, packages/ui/src/i18n/dictionaries/authenticator/nl.ts, packages/ui/src/i18n/dictionaries/authenticator/pl.ts, packages/ui/src/i18n/dictionaries/authenticator/pt.ts, packages/ui/src/i18n/translations.ts, packages/vue/src/components/sign-in.vue
*Issue #, if available:* Fixes #900.
*Description of changes:* Removes trailing space on "Forgot your password? ". This extra space was used in legacy authenticator to put spacing between "Forgot your password" and "Reset your password":
This is no longer needed or desired.
=> Remove trailing space on "Forgot your password? "

.changeset/dull-years-judge.md, packages/angular/projects/ui-angular/package.json, yarn.lock
*Issue #, if available:* Fixes #1091
*Description of changes:* This PR pins `@stencil/core` to `@2.8.0`. `@2.10.0` has known exports conflict with web components library built with previous versions: [[related](https://github.com/vime-js/vime/issues/261), [2](https://forum.ionicframework.com/t/stencil-v2-10-removed-attachshadow-from-bundle/217064)].
We could go the other direction and bump `@aws-amplify/ui-components`' stencil dependency to `2.10.0`, but it currently depends on previous major version `1.15.0`. Handling this from framework side to reduce any risk from breaking change.
On 2.10.0:
On 2.8.0:
=> deps(angular): Pin @stencil/core to 2.8.0

packages/ui/src/machines/authenticator/actors/resetPassword.ts, tough-numbers-notice.md
I noticed the reset passwords actor has an unused import of Auth from aws-amplify, thought it should be removed.
Removed import 👾
=> Removed unused Amplify auth import in reset password actor

.github/workflows/tests.yml
We added new steps to tests github action to [run e2e tests on the docs site](https://github.com/aws-amplify/amplify-ui/blob/main/.github/workflows/tests.yml#L338-L342). I couldn't get the new steps to run on a separate branch, so it was merged to main without full testing. I'm seeing that the ["Start docs site" step is stuck](https://github.com/aws-amplify/amplify-ui/runs/4721645361?check_suite_focus=true). Based on the [other steps](https://github.com/aws-amplify/amplify-ui/blob/main/.github/workflows/tests.yml#L265), it looks like `yarn docs start` command is not exiting and should be put in the background using `&` to allow for the `npx wait-on` command to run.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Put yarn docs start into background process

.github/workflows/tests.yml
Fix docs build by restoring the cypress runner cache.
*Error message*:
```
$ TZ=UTC cypress run --spec features/ui/theme/*.features
The cypress npm package is installed, but the Cypress binary is missing.
We expected the binary to be installed here: /home/runner/.cache/Cypress/8.7.0/Cypress/Cypress
Reasons it may be missing:
- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress
Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.
Alternatively, you can run 'cypress install' to download the binary again.
https://on.cypress.io/not-installed-ci-error
``` …
=> Fix docs tests

.changeset/good-pandas-press.md, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/countryCodeSelect.scss, packages/ui/src/theme/css/component/select.scss, packages/ui/src/theme/css/styles.scss, packages/ui/src/theme/tokens/components/countryCodeSelect.js, packages/ui/src/theme/tokens/components/index.js, packages/ui/src/theme/tokens/components/select.js
#1095 
Fixing `PhoneNumberField` styling to get the height of `CountryCodeSelect` and `TextField` matching
=> fix: fixing unaligned border outlines

.changeset/strange-ducks-search.md, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/select.scss, packages/ui/src/theme/tokens/components/select.js
#1104
Firefox default background color on `option`  is not friendly in dark mode. This can be resolved by adding a more readable custom background color, targeting Firefox only.
Testing on Firefox 95.0
=> fix: fixing option background color in darkmode for Firefox

docs/src/data/links.ts
#1112 
The description for `View` on components page is wrongly placed with the one for `Alert`.
This PR will be updating the description for `View` to use the correct one.
=> fix: fixing View description on component page

.changeset/lucky-numbers-lay.md, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/react/src/components/Authenticator/Provider/index.tsx, packages/react/src/components/Authenticator/Router/index.tsx, packages/ui/src/helpers/auth.ts, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/types/authMachine.ts, packages/vue/src/components/authenticator.vue
*Description of changes:* This PR refactors `authMachine` to have an explicit `INIT` step that takes in all `authenticatorMachineProps` and applies it to its `context`. 
Previously, machine props need to be passed in *before* the machine was created:
https://github.com/aws-amplify/amplify-ui/blob/933d08dd9fccd1e313d4377e2f72969c4a0e025f/packages/react/src/components/Authenticator/Provider/index.tsx#L28-L32
This behavior is susceptible to timing issues -- machine can be only created after `authenticator` is mounted with proper props (and Provider on React). For example, if customer tries to use `useAuthenticator` React hook outside `<Authenticator/ >`, their `useAuthenticator` runs before `Authenticator` is mounted before `machineProps` are passed in. This results …
=> Add explicit state for initializing authMachine

.changeset/lucky-numbers-lay.md, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/react/src/components/Authenticator/Provider/index.tsx, packages/react/src/components/Authenticator/Router/index.tsx, packages/ui/src/helpers/auth.ts, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/types/authMachine.ts, packages/vue/src/components/authenticator.vue
This reverts commit c3fccb7feb16a54c2bce739b08edabfd0d783126.
*Description of changes:* This was causing "App Error" when someone clicks on any of the tabs in this section of docs (Default values, Sign in, etc. ) https://ui.docs.amplify.aws/components/authenticator#labels--text 
=> Revert "Add explicit state for initializing authMachine (#1142)"

packages/react/src/primitives/Tabs/Tabs.tsx, packages/react/src/primitives/Tabs/__tests__/Tabs.test.tsx
*Issue #1033
Add null check to tabs primitive to handle null children correctly
=> handle null children in tabs

.changeset/lucky-numbers-lay.md, docs/src/pages/components/authenticator/LabelsAndTextDemo.tsx, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/react/src/components/Authenticator/Provider/index.tsx, packages/react/src/components/Authenticator/Router/index.tsx, packages/ui/src/helpers/auth.ts, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/types/authMachine.ts, packages/vue/src/components/authenticator.vue
Descriptions: We previously had to revert #1142 because it was causing docs failure to https://ui.docs.amplify.aws/components/authenticator#labels--text. 
This PR adds a fix for that failure by making sure machine is fully initialized before the component renders: 2669bf6.
For additional context, see the original PR #1142.
=> Attempt #2: Add explicit state for initializing authMachine (#1142)

.changeset/five-moons-stare.md, packages/react/package.json
*Issue #, if available:* Part of CoE
In order to prevent new dependency versions from breaking our library, we need to pin all our dependencies to specific versions. 
This PR pins all `package.json` 3rd-party dependencies to specific versions. 
=> Pin all @aws-amplify/ui-react dependencies

amplify.yml, docs/next.config.js, docs/package.json, docs/src/pages/theming/index.page.mdx
#1111 
Some links on docs site that require redirects do not work as expect because we are deploying our docs site with SSG.
Moving docs site back to SSR
=> build: moving docs back to hybrid site to support redirects

.changeset/wet-plums-type.md, packages/angular/projects/ui-angular/README.md
n/a
Fix a typo in the Angular package readme - `angular` was misspelled as `anuglar`
=> Fix Angular README 'anuglar' typo

.github/workflows/tests.yml
small change so that github action tests will ignore the yarn lockfile and test will run with newly resolved dependencies similar to what users will experience.
=> No lock tests

docs/src/pages/components/authenticator/LabelsAndTextDemo.tsx
*Description of changes:* This fixes https://ui.docs.amplify.aws/components/authenticator#labels--text that I broke again with #1168. Not a runtime error this time, but screens weren't rendering because its state machine was not initiated.
This PR ensures that `LabelsAndTextDemo` starts the state machine by explicitly sending INIT event.
https://user-images.githubusercontent.com/43682783/151238207-0f12533a-bf64-4105-b5e0-32a3e5d8ccb9.mp4
=> Fix I18n demo screen bugs

docs/src/pages/components/authenticator/index.page.mdx
*Description of changes:* Fixes a typo on https://ui.docs.amplify.aws/components/authenticator#internationalization-i18n
=> Fix language typo

.changeset/many-bags-explode.md, examples/angular/src/pages/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.component.ts, examples/next/pages/ui/components/authenticator/sign-in-sms-mfa/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue, packages/e2e/features/ui/components/authenticator/sign-in-sms-mfa.feature, packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx
#1200 
Added additional translations of error text for React.
=> Added additional error translation text for SMS MFA

.changeset/gold-beers-tell.md, packages/angular/projects/ui-angular/package.json, packages/e2e/cypress/plugins/index.js, packages/ui/package.json, packages/vue/package.json, yarn.lock
*Description of changes:* This pins all `xstate` version to last known working version in `yarn.lock`. This fixes Typescript error found in https://github.com/aws-amplify/amplify-ui/issues/1223, which actually happened to React/Vue as well as Angular. 
Not sure why this wasn't caught in `no-lock` test we have, we shoudl look into it.
=> Pin xstate versions

.changeset/purple-apples-crash.md, packages/angular/projects/ui-angular/package.json, packages/ui/package.json, yarn.lock
*Description of changes:* Resolves #1226.
Bumping xstate to `4.28.0`, which is the last version before `xstate` brought major TypeScript updates. We should look into updating to `4.29.0` eventually, but we should unblock customers first.
=> Pin xstate to `4.28.0`

packages/react/src/hooks/actions/__tests__/useNavigateAction.test.ts, packages/react/src/hooks/actions/useNavigateAction.ts
Moving `useNavigateAction` test file to the correct folder under `hooks/actions/__tests__`
=> chore: moving useNavigateAction test to action test folder

.changeset/gorgeous-queens-kick.md, docs/src/styles/docs/base.scss, packages/ui/src/theme/css/styles.scss
Closes https://github.com/aws-amplify/amplify-ui/issues/1092
This PR fixes an issue where a customer was using a library which injected its CSS too early to override ours. Our `box-sizing` CSS rule had a specificity of `0 1 0`. We primarily need this level of specificity for the `amplify*` classes, but can reduce the specificity to`0 0 0` for other elements. This means any element used in an Amplify UI app will have a default `box-sizing` of `border-box`, but can easily override it with any level of specificity. This should allow other library UI components to be used inside of Amplify UI components such as `Flex` without changing their `box-sizing` styling. 
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> fix: change box-sizing to have less specificity

package.json, packages/e2e/package.json, packages/e2e/process, yarn.lock
Instead of bumping the version to `3.48.0`, this PR removes the resolution entirely to see if the tests still pass. 
=> Remove @aws-sdk/client-location resolution

docs/package.json, package.json
Adding `prism-react-renderer` to `resolutions` because it is currently breaking the build ([see issue](https://github.com/FormidableLabs/prism-react-renderer/issues/142)), and it also has transitive dependencies. 
=> Pin prism-react-renderer to 1.2.1

.changeset/stupid-rice-nail.md, docs/src/pages/components/icon/examples/CustomIconWithPathsExample.tsx, docs/src/pages/components/icon/examples/index.tsx, docs/src/pages/components/icon/react.mdx, packages/react/src/primitives/Icon/Icon.tsx, packages/react/src/primitives/Icon/__tests__/Icon.test.tsx, packages/react/src/primitives/types/icon.ts
*Description of changes:* Adding `paths` prop to Icon primitive that accepts an array of path-like objects.
```jsx
<Icon
ariaLabel="tag"
viewBox={{ width: 23, height: 15 }}
paths={[
{
d: 'M1 0.5C0.723858 0.5 0.5 0.723858 0.5 1V14C0.5 14.2761 0.723858 14.5 1 14.5H14C14.1148 14.5 14.2262 14.4605 14.3153 14.3881L22.3153 7.88806C22.4322 7.79311 22.5 7.65056 22.5 7.5C22.5 7.34944 22.4322 7.20689 22.3153 7.11194L14.3153 0.611943C14.2262 0.539529 14.1148 0.5 14 0.5H1Z',
strokeLinejoin: 'bevel',
strokeLinecap: 'round',
strokeDasharray: '4 4',
fill: 'transparent',
stroke: 'currentColor',
},
]}
/>
```
=> Adding paths prop to Icon

.changeset/hip-numbers-lay.md, packages/react/package.json, packages/react/src/primitives/Link/Link.tsx, packages/react/src/primitives/Link/__tests__/Link.test.tsx, packages/react/src/primitives/types/link.ts
https://github.com/aws-amplify/amplify-ui/issues/705
Adds the `to` prop to the `<Link />` primitive to remediate a TypeScript error. 
=> Add 'to' prop to Link primitive

.changeset/fifty-keys-move.md, .changeset/three-dryers-swim.md, docs/src/pages/components/switchfield/examples/SwitchFieldIsCheckedExample.tsx, docs/src/pages/components/switchfield/react.mdx, packages/react/src/primitives/SwitchField/__tests__/SwitchField.test.tsx, packages/react/src/primitives/SwitchField/useSwitch.ts
Update `SwitchField` logic to allow modifications of the checked state through the `onChange` handler.  Also updated the documentation to reflect this change and display an example of the change.
Additional tests were added to capture the changed behavior and manually validated the behavior through the documentation site.
=> update SwitchField to allow updates on controlled component

canary/angular/angularcli/package.json, canary/react/cra-ts/package.json, canary/react/cra/package.json, canary/react/next/package.json, canary/vue/vite/package.json, canary/vue/vuecli/package.json, examples/angular/package.json, examples/vue/package.json, yarn.lock
This PR fixes an issue where we were pulling in two separate versions of the `aws-amplify` dependencies, 4.3.14 and 4.3.8. Now we will only have the latest version of `aws-amplify` in the node_modules folder.
Note: I found this bug when making an examples app of DataStore hooks. Having multiple versions of `@aws-amplify/datastore` in `node_modules` causes DataStore not to fully initialize, leaving the `DataStore.save` call to throw the following cryptic error message:
```
Cannot read properties of undefined (reading 'version')
```
=> Dedupe `aws-amplify` versions

docs/src/pages/_app.page.tsx, docs/src/theme.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/tokens/components/card.js, packages/ui/src/theme/tokens/components/sliderField.js, packages/ui/src/theme/tokens/components/switchField.js, packages/ui/src/theme/tokens/components/toggleButton.js
* Removed default theme overrides in the docs site so the primitives match exactly what we show in the docs. 
* Fixed a few tokens in the default theme
* Fixed the theme switcher on the docs homepage
| before | after |
| ----- | ----- |
| ![CleanShot 2022-02-14 at 22 50 52](https://user-images.githubusercontent.com/321279/154009432-73deaf44-35c1-46bd-8e4c-d7191d984f47.gif) | ![CleanShot 2022-02-14 at 22 50 19](https://user-images.githubusercontent.com/321279/154009452-563b2846-70a2-4ca7-b295-e9b35baab9c0.gif) |
=> Removing base docs theme overrides and fixing theme switcher on docs site

.github/workflows/run-builds.yml
* Increase the canary run rate to  run every 7minutes only during working hours
* Change emitted value to 0 for success and 1 for build failure
=> Increase canary run rate to every 7min

.github/workflows/run-builds.yml
Update Canaries to run 24 hrs / day
=> Update Canaries to run 24 hrs / day

.github/workflows/run-builds.yml
We temporarily turned off the building of Vue CLI. This was a downstream issue with babel and is now fixed. https://github.com/vuejs/vue-cli/issues/6994
Ran manually
=> Turn on Building for VueCLI

.prettierignore, .prettierrc, packages/react/src/primitives/PhoneNumberField/CountryCodeSelect.tsx, packages/ui/src/i18n/dictionaries/authenticator/de.ts, packages/ui/src/i18n/dictionaries/authenticator/en.ts, packages/ui/src/i18n/dictionaries/authenticator/it.ts, packages/vue/src/types/index.ts
This PR adds all the available prettier config keys with their default values. This is to attempt to ensure that we always run prettier with the same settings.
This following the recommendation here: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#configuration
>  It is recommended that you always include a prettier configuration file in your project specifying all settings for your project
After that I ran prettier on all files and it only had a few changes, which I've added to this PR.
=> Set default prettier configs

.changeset/famous-tigers-visit.md, packages/react/src/primitives/Tabs/Tabs.tsx, packages/react/src/primitives/Tabs/__tests__/Tabs.test.tsx
This PR allows the `<TabItem />` primitive to not have `children`, giving customers more flexibility. 
https://github.com/aws-amplify/amplify-ui/issues/1282
Created a sample `<Tabs />` example with no `children` in the `<TabItems />`, then confirmed that there were no `console.warning`'s getting thrown. 
Also caught a tiny bug with newline characters causing the `console.warning`: `'Amplify UI: <Tabs> component only accepts <TabItem> as children.'` This is because React considers newline characters (`\n`) to be children. I added a conditional to ignore whitespace characters as children.  
=> Allow Content-less TabItem

.changeset/silent-queens-guess.md, .github/workflows/run-builds.yml, docs/src/pages/components/selectfield/examples/SelectFieldOptionsExample.tsx, docs/src/pages/components/selectfield/examples/index.ts, docs/src/pages/components/selectfield/react.mdx, packages/react/src/primitives/SelectField/SelectField.tsx, packages/react/src/primitives/SelectField/__tests__/SelectField.test.tsx, packages/react/src/primitives/types/selectField.ts
The added `options` prop accepts an array of strings which maps to the value, label and children of each `<option>` in a SelectField. 
If there are children and an `options` prop is set, then the children will win but there will be a warning in the console. 
This requirement will help Amplify Studio's Codegen team create a SelectField easier, plus it has a nice DX if the customer just wants a simple SelectField. 
Added a test and confirmed that a new `options` example in the docs works correctly. 
=> Add `options` prop to <SelectField>

docs/src/pages/components/authenticator/quick-start.angular.mdx, docs/src/pages/components/authenticator/quick-start.react.mdx
Adds docs link from current React and Angular Authenticator docs to the v1 docs.
React:
Angular:
https://github.com/aws-amplify/amplify-ui/issues/1128
Ran docs site and clicked links
=> docs: add links to legacy v1 version

examples/next/pages/ui/components/authenticator/default-region-code/aws-exports.js, examples/next/pages/ui/components/authenticator/default-region-code/index.page.tsx, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/features/ui/components/authenticator/default-region-code.feature
This adds a React test for setting default region code through slots. For now, I used Slots to mock default region code manually. Eventually, we should look to introduce explicit API for setting default region code without having to region code.
I only added test for React as Vue/Angular do not have primitives to mock `PhoneNumberField` through slots. Since we'll be adding an explicit API for setting default form values, let's update the examples after then. This will at least verify the fix for #1324.
#1324, accompanies #1366.
New e2e test!
=> React test for setting default region code

packages/react/src/hooks/useDataStore.tsx
Removing dependencies in `useEffect` enforced by rules of Hook to fix the infinite loop issue in `useDataStore` hook. Not sure exactly why follow the rules will break things there. Removing them to unblock studio side 
https://github.com/aws-amplify/amplify-ui/issues/1396
Manual tested local with a simple app looks like the following:
```jsx
import Amplify from 'aws-amplify';
import awsexports from './aws-exports';
import { Todo } from './models';
import {
useDataStoreBinding,
createDataStorePredicate,
} from '@aws-amplify/ui-react/internal';
Amplify.configure(awsexports);
export default function App() {
const todo = useDataStoreBinding({
type: 'collection',
model: Todo,
criteria: createDataStorePredicate({
field: 'name',
operand: 'Working on E2E Tests',
operator: 'eq',
}),
}).items[0]; …
```
=> fix: fixing infinite useEffect call in useDataStore hook

.github/changeset-presets/bump-react.md, .github/workflows/publish-geo.yml
This workflow will publish the Map components to the `@geo` npm tag. It triggers on merges to the `ui-geo/main` branch, which includes e2e tests which must pass prior publishing.
N/A
Publishing workflow is based upon the `.github/workflows/publish-next.yml` workflow.
=> Add workflow for publishing to geo tag

canary/react/next/package.json, package.json
Removing resolution for `eslint-plugin-react` since it got fixed upstream now
https://github.com/yannickcr/eslint-plugin-react/issues/3215
=> chore: removing resolution since upstream has fixed the issue

.changeset/slow-radios-try.md
This PR is to upgrade our package version bumps to `minor` releases due to the new [form field props](https://github.com/aws-amplify/amplify-ui/pull/1389) being considered a new, backwards-compatible feature. This release will occur on 3/1/2022.
N/A
=> Update form-field-props changset to minor releases

.changeset/clean-icons-guess.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-in/confirm-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-verify-user/amplify-confirm-verify-user.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/force-new-password/force-new-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/reset-password/reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-totp/setup-totp.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/verify-user/verify-user.component.html
This fixes Angular Authenticator screens being too narrow. This was due to an unneeded `data-amplify-container` underneath. 
I removed the parent `div` for these screens, because they are unneeded and react/vue do not have one.
#1454
Tested manually.
Before: 
After: 
Also confirmed other screens take the full with as exected by running through cypress mocks.
=> fix(angular): remove unneeded parent div 

.changeset/gentle-turkeys-think.md, packages/react/src/primitives/Pagination/Pagination.tsx, packages/react/src/primitives/Pagination/PaginationItem.tsx, packages/react/src/primitives/Pagination/__tests__/Pagination.test.tsx
Set the default currentPage value of the Pagination component to 1
Updated the Pagination component to set the currentPage default value to 1.  This fixes an error that was showing NaN if no currentPage was given.
reproducible with `<Pagination totalPages={20} onNext={()=>{}} onPrevious={()=>{}} onChange={()=>{}} />`
=> set pagination current page default to 1

.github/workflows/run-and-test-builds.yml
This caches the environment we use for canary runtime tests. Not significant time improvement, but this will help as we build on our canary tests.
To be add on to #1450
https://github.com/aws-amplify/amplify-ui/runs/5415010995?check_suite_focus=true!
=> Cache canary environments

.changeset/sixty-teachers-ring.md, packages/react/src/primitives/TextAreaField/TextAreaField.tsx, packages/react/src/primitives/TextField/TextField.tsx
This PR moves the `width` and `height` style props to the parent container to be consistent with the `SelectField` styling. This fixes an issue where the TextField `height` prop is applied to the input field, whereas the `SelectField` `height` prop is applied to the parent Flex container.
* Ran unit tests
* Manually tested setting height and width on SelectField and TextField on same line:
=> TextField/TextAreafield - width and height style props

.github/workflows/tests.yml
Makes concurrency group unique for all commits to `main`, so that a new commit does not cancel previous one. 
This does not affect concurrency on pull requests, in which we will still cancel previous old workflows for the sake of efficiency.
Same logic from https://github.com/aws-amplify/amplify-ui/blob/b8675d1b007e5a3bb4cfd8b0ad675e876ee1e836/.github/workflows/tests.yml#L51.
=> Make e2e concurrency group unique in `main`

.changeset/nine-camels-cover.md, packages/react/src/components/Authenticator/Authenticator.tsx
This PR fixes an issue where the `InitMachine` component is defined on each render. This caused the `useEffect` inside `InitMachine` to also run on each render, which finally caused the `children` of `InitMachine` to be unmounted and remounted. I also found that on initial render, the `useEffect` hook inside `InitMachine` was called many times. This PR fixes all of this by moving `InitMachine` outside of the `Authenticator` function. 
Fixes: https://github.com/aws-amplify/amplify-ui/issues/1451
Using the app from https://github.com/aws-amplify/amplify-ui/issues/1451 I validated the following:
* useEffect was only called a single time on initial render
* useEffect is not called when typing in the input field, and focus is not lost
By submitting this pull request, I confirm that my …
=> fix: Authenticator issue where InitMachine useEffect runs every render

.github/workflows/publish-next.yml
The goal of this PR is to test a GitHub action that will release the Amplify UI Docs site after successfully publishing to npm. 
I confirmed that manually merging `main` into `docs-release` and pushing my changes triggers a redeployment of the docs site (or rather, a test version of the docs site). The next step is to automate that process whenever we release our library. 
Instead of creating a separate workflow to test this action, I'm appending it to the end of the `publish-next` workflow for two reasons. 
1. We need access to the `published` output from the [changeset release action](https://github.com/changesets/action#outputs). 
2. This workflow runs more frequently than `publish-latest`, so we'll be able to test it and make sure it works. 
Once we confirm that the GitHub action …
=> Test GitHub action to release docs

package.json, yarn.lock
This will fix a security issue with `ansi-html` found by dependabot. This will make sure we are using the earliest fixed version.
Dependabot
=> Fix Dependabot ANSI-HTML version

docs/package.json
Removes the compatibility flag from the `@aws-amplify/ui-react` version in _docs/package.json_. Usage of this flag leads to false warnings for `@aws-amplify/ui-react` imports and allows for VS Code IntelliSense to work correctly with those imports
NA
Warnings cleared uo in editor
=> fix(docs): remove ^ flag from @aws-amplify/ui-react version

packages/react/src/primitives/types/textField.ts
Add default TS generic value to `TextFieldProps` to prevent TS warnings when used without a generic
NA
Manually tested in docs
=> fix(react): add default TS generic value to TextFieldProps

.changeset/witty-owls-applaud.md, packages/ui/src/helpers/authenticator/formFields/defaults.ts
This fixes a regression I introduced in #1484, in which phone number field would show up as `Enter your phone_number` instead of `Enter your phone number`. This aligns with previous behaviors.
Before fix:
After fix:
=> Fix phone number label in reset-password

.github/workflows/publish-next.yml
Reverting #1493. This was for POC purposes only and should no longer be in our workflows.
=> Revert "Test GitHub action to release docs"

.changeset/thick-pumas-guess.md, packages/react/src/primitives/Radio/Radio.tsx, packages/react/src/primitives/SliderField/SliderField.tsx, packages/react/src/primitives/StepperField/StepperField.tsx, packages/react/src/primitives/TextAreaField/TextAreaField.tsx, packages/react/src/primitives/TextField/TextField.tsx
Figma to Studio integration will absolutely position components when autolayout is not enabled in Figma. This causes an issue for field components that were passing `position`, `top`, and `left`, and `padding` down to the input element, causing the layout not to match Figma. This is fixed by moving the absolute position props and `padding` up to the container Flex element.
* Manually published packaged to local Verdaccio and installed in in sample app
* Checked that sample app using code generated from Amplify Studio matches Figma
=> fix: update complex field components to allow absolute positioning

.changeset/unlucky-ducks-melt.md, packages/react/src/hooks/__tests__/useDeprecationWarning.test.tsx, packages/react/src/hooks/useDeprecationWarning.ts
This fixes an issue where when isMultiline is undefined (which is usually true), shouldWarn will default to true and trigger the warning. This causes the TextField component to always complain about the use of isMultiline for fields where it's not set to `true`. Now setting `isMultiline` to any falsy value should not trigger the deprecation warning. I added a unit test to ensure passing `undefined` to `shouldWarn` doesn't trigger a console warning.
* Ran docs site and verified that Multline deprecation message is no longer shown
=> fix: make shouldWarn required prop on useDeprecationWarning

docs/src/pages/components/checkboxfield/CheckboxFieldPropControls.tsx, docs/src/pages/components/checkboxfield/demo.tsx, docs/src/pages/components/checkboxfield/useCheckboxFieldProps.tsx, docs/src/pages/components/switchfield/SwitchPropControls.tsx, docs/src/pages/components/switchfield/demo.tsx, docs/src/pages/components/switchfield/useSwitchProps.tsx
It does not make any sense to have label hidden on `CheckBoxField` and `SwitchField`
(https://app.asana.com/0/1201840995372760/1201908824917654)
No more `isLabelHidden` on demo for these two
=> docs: remove isLabelHidden in demo for CheckboxField and SwitchField

docs/src/pages/getting-started/installation/dependencies.react.mdx
Trying to wrap your application in <AmplifyProvider/> on `Next.js` with the code snippet on https://ui.docs.amplify.aws/getting-started/installation#packages will fail, with the error described in #1345.
This is because the `default export` on `Next.js` requires `{ Component, pageProps }` as props, while that of CRA does not take any props.
This PR adds a tab for `Next.js` to resolve this. Also changed arrow function to named constant here, to satisfy `react/display-name` eslint rule: [link](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md#rule-details).
Resolves #1345, resolves #1367.
https://user-images.githubusercontent.com/43682783/159073863-07ce2110-20a6-48a5-8f8d-ce6c1bd64bde.mp4
Also checked with a new `create-next-app` …
=> Add how to default export with `AmplifyProvider` on Next.js

examples/angular/src/app/app-routing.module.ts, examples/angular/src/app/app.module.ts, examples/angular/src/pages/ui/components/authenticator/useAuthenticator/home/useAuthenticatorHome.component.html, examples/angular/src/pages/ui/components/authenticator/useAuthenticator/home/useAuthenticatorHome.component.ts, examples/angular/src/pages/ui/components/authenticator/useAuthenticator/useAuthenticator.component.html, examples/angular/src/pages/ui/components/authenticator/useAuthenticator/useAuthenticator.component.ts, examples/next/pages/_app.page.tsx, examples/next/pages/ui/components/authenticator/useAuthenticator/home/index.page.tsx, examples/next/pages/ui/components/authenticator/useAuthenticator/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/useAuthenticator/home/index.vue, examples/vue/src/pages/ui/components/authenticator/useAuthenticator/index.vue, packages/e2e/cypress/integration/ui/components/authenticator/useAuthenticator/useAuthenticator.ts, packages/e2e/features/ui/components/authenticator/useAuthenticator.feature
This updates the `useAuthenticator` examples and their e2e test to match #1580.
**Details**
Our current `useAuthenticator` examples are really SPA and do not sufficiently test router use cases.
There are many `useAuthenticator` bugs, especially with refresh, so we plan to update examples and tests incrementally as we add more `router` support. For now, this PR adds additional route `useAuthenticator/home`. 
This PR adds:
1. Test starts at `/useAuthenticater` route. This has the authenticator for user to sign in.
1. User signs in with Authenticator.
2. Once user signs in, they'll see a "Navigate to Home" button. (This can be something like "Manage your account" irl)
3. Clicking that button redirects user to /useAuthenticator/home`. This will have basic greetings with a sign out button.
4. …
=> fix(examples,e2e): Add examples and tests for #1580

.changeset/healthy-zoos-ring.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts, packages/vue/src/components/authenticator.vue
We were attempting to call `unsubscribe` before it was initialized, leading to issues on lifecycle methods dealing with Authenticator.
Now Authenticator stores a local copy of `unsubscribe`, and unsubscribes it when the component is destroyed. This should be more resilient than we trying to guess when the correct timing is.
Locally validated angular.
=> Fix unscription timing issues in Vue/Angular

yarn.lock
When I upgraded the `resolution` for `node-forge`, I forgot to run `yarn install` to update `yarn.lock`. This PR fixes that mistake by simply running `yarn install`. 
This is also part of an effort to address the GitHub security patching tickets from t.corp for this repo and [amplify-ui-staging](https://github.com/aws-amplify/amplify-ui-staging), which pulls upstream from this repo.
=> Upgrade node-forge in yarn.lock

.changeset/wet-ads-yawn.md, packages/react/rollup.config.js, packages/ui/rollup.config.js
In my sample apps using CRA I'm seeing a lot of errors due to our sourcemaps linking to ts files that we don't ship in the package:
This PR disables sourcemaps in the rollup config (both prod and dev builds at the moment). I'd like to follow up with a dev version of the rollup config in a separate PR.
=> Remove sourcemaps from rollup build

.changeset/kind-badgers-marry.md, docs/src/styles/primitives/passwordFieldStyles.css, packages/ui/src/theme/css/component/fieldGroup.scss
This PR addresses the issue of a double border appearing on the Authenticator component password field, and the underlying primitive. It updates the appearance of the outer controls on the [TextField](https://ui.docs.amplify.aws/components/textfield#outer-components) component when using outerStartComponent and outerEndComponent props
**Note**: This currently shows with a single border on the Authenticator in the docs site because there is some docs specific css added to fix it. This PR also removes that CSS since it will no longer be needed.
**Before**
**After**
https://github.com/aws-amplify/amplify-ui/issues/1468
Tested changes in docs instance as well as the Next example instance.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> fix: remove double border on TextField outer components

.changeset/proud-trainers-collect.md, packages/react/src/components/Authenticator/hooks/useAuthenticator/index.tsx
`useAuthenticator` did not optimize re-renders as expected when it selects an actor context. For example,
```tsx
const { error } = useAuthenticator((context) => [context.error])
```
would always re-render, even if `error` hasn't changed. This was because `prevState` and `nextState` we use in comparators holds a *reference* to actor contexts, which could easily change between each compare calls. 
This PR resolves it by explicitly holding onto actor snapshot values that wouldn't change between compares. More details on code comments.
Related to #1602
E2e test, + some manual validation on `examples/next`.
=> fix(react): Keep a local copy of previous facade value 

package.json, yarn.lock
This updates the `glob-parent` dependency used by the angular example to minimum version 6.0.2.
See dependabot alerts
=> fix: update glob-parent used by angular build

package.json, yarn.lock
Updates nth-check to 2.0.1 to fix a security vulnerability raised by dependabot.
See dependabot
```
$ yarn why nth-check
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "nth-check"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^6.0.1"
warning Resolution field "node-forge@1.3.0" is incompatible with requested version "node-forge@^0.10.0"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
warning Resolution field "ansi-regex@5.0.1" is …
```
=> fix: update nth-check dependency

docs/src/pages/components/geo/react.mdx
PR fixes an issue where the geo title showed twice after the page content was moved to a react specific page (introduced in https://github.com/aws-amplify/amplify-ui/pull/1636).
Before (present on dev.ui.docs.amplify.aws, but not prod docs site)
After:
Ran docs site, validated changes above.
=> fix: remove extra title and description from geo page

.changeset/five-shrimps-attend.md, packages/ui/sd.config.ts
Transforming the shadow tokens in style dictionary for the default CSS Amplify UI generates. 
Before:
After:
=> fix shadow tokens

.changeset/wild-comics-carry.md, packages/react/src/components/AmplifyProvider/index.tsx
This PR exposes the capability to add a [nonce](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce) to the`<style>` tag rendered by the `AmplifyProvider`:
Example:
`<AmplifyProvider nonce="randomString"/> => <style nonce="randomString">`
This will allow customers to use strict CSP rules while also using a custom theme. See the [example below](https://content-security-policy.com/examples/allow-inline-style/):
I spent quite a bit of time testing this out on the UI Docs site and NextJS example app, as well as in different browsers. I can confirm that:
- If there is a nonce in headers and it matches the nonce passed to the `<style>` tag, then those styles will get applied to the page. 
- If there is a nonce in headers but it does not match the nonce passed to the …
=> Add `nonce` prop to AmplifyProvider

.changeset/fresh-eagles-accept.md, packages/react/src/components/Authenticator/hooks/useAuthenticator/index.tsx
Whenever customer are trying to use `useAuthenticator` without wrapping their App with `Authenticator.Provider`, they'll get the cryptic error message 
```
TypeError: Cannot read properties of undefined (reading 'send')
```
This PR adds a check for that and adds a more dev-friendly message.
#1651: dev confusion with errors when no provider is added/
No runtime behavior changes unless the app is already on faulty configuration. I might have missed edge cases like `Authenticator.Provider` not being ready by the time `useAuthenticator` first runs, but e2e test should catch that.
=> chore: Add error message for no provider found

docs/src/components/ComponentClassTable.tsx, docs/src/components/ComponentVariableTable.tsx
No visual changes, just addresses the validateDomNesting warnings for the styling tables in docs. Adds `<tbody />` and `<thead />` where applicable.
**Console warning**
**Before DOM**
**After DOM**
N/A
Tested docs instance locally.
=> docs/fix: valid table DOM nesting for docs css styling tables

docs/src/pages/components/geo/react.mdx
Since we've decided to treat `maplibre-gl` and `react-map-gl` as hard dependencies rather than peer dependencies, we can remove the block of documentation explaining to install those dependencies separately for the Geo components.
N/A
=> fix(docs): remove block regarding geo peer dependencies

.changeset/tender-parents-sniff.md, packages/e2e/features/ui/components/authenticator/sign-in-with-username.feature, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/types/authenticator/stateMachine/context.ts
This resolves issues when users try to sign in or sign up after they refresh in signed in state.
This happened because `setup` state was skipped when user has refreshed, and hence Authenticator would not send `INIT` event. This PR resolves it by ensuring setup has run after refresh + signing out.
Resolves #1623, Resolves #1676, Resolves #1659
Added new tests. Note how they fail on my first two commits but pass later after I add the fix.
=> fix(authenticator): Ensure setup has ran after refresh

.github/workflows/publish-latest.yml
We recently defaulted all `GITHUB_TOKEN` access to read. `release-@latest` in particular though needs write token to create and commit to "Version Packages" PR, so adding those permissions in with some comments.
Tested on my POC repo https://github.com/wlee221/changeset-poc/blob/main/.github/workflows/release-main.yml
=> Update required permissions for publish-latest

docs/src/pages/components/authenticator/AuthStyle.tsx, docs/src/pages/components/authenticator/customization.styling.react.mdx, docs/src/pages/components/authenticator/customization.styling.web.mdx
Updated docs so the Authenticator style example works correctly. Also added example of using `AmplifyProvider` with a `theme` object.
#1694
=> fix(docs Authenticator): Update style authenticator

.github/workflows/tests.yml, package.json
Having docs site build respect `yarn.lock` since this is not a canary build and it doesn't have to be acting like a new customer.
Minor release of `micromark-util-events-to-acorn` from `1.0.4` to `1.0.5` this morning is breaking our docs build.
=> chore: updating docs build to respect yarn.lock

docs/src/pages/theming/dark-mode/darkMode.tsx
Fixing dark mode example on docs site. `flipPalette` is an internal util function which confuses one of our customers. Any examples on docs site should be instructive and not reference any local files.
#1717 
=> docs: fixing dark mode example

docs/src/components/Layout/index.tsx
This PR ensures docs to scroll to the anchor tag on load. 
This doesn't work on our live docs. For example, click on https://ui.docs.amplify.aws/components/authenticator?platform=react#headers--footers and you'll see you're not scrolled to the content.
Validated manually: 
https://user-images.githubusercontent.com/43682783/163648868-87885c26-d19d-4c65-bb8c-4c3767220257.mp4
=> fix(docs): Fix anchor tags between pages

.changeset/spicy-weeks-smoke.md, packages/react/package.json, yarn.lock
This pull request updates the dependency `maplibre-gl-js-amplify` to the latest version, v1.5.0. This version of the dependency fixes source map warnings received when using the library in a Create React App v5 application (see [Issue #147](https://github.com/aws-amplify/maplibre-gl-js-amplify/issues/147)). These warnings are reported by users of the Amplify UI library (see [this comment](https://github.com/aws-amplify/amplify-ui/issues/1647#issuecomment-1100232282)).
#1647 
Building the canary CRA package can verify whether these source map warnings appear after updating the `maplibre-gl-js-amplify` package.
=> chore: Bump maplibre-gl-js-amplify dependency version

docs/src/components/Demo.tsx
This PR temporary removes the Theme tab from the Docs demos until we figure out a way to let customers dynamically edit a theme object in the demos.
=> docs(fix): remove Theme tab from demos

.github/workflows/publish-geo.yml, .github/workflows/publish-next.yml, .github/workflows/test-main.yml, .github/workflows/test-prs.yml
Fixing workflow stop publishing to next
Workflow stops publishing to next after splitting
=> chore: fixing workflow not publishing to next tag

packages/react/scripts/generatePrimitivesCatalog.ts
In our generatePrimitivesCatalog script union types of numbers were being ignored.
=> fix: issue where number unions ignored

packages/react/scripts/generatePrimitivesCatalog.ts
Fixes an issue where in our `generatePrimitivesCatalog` script  where union types of numbers were being ignored. This made it so that the `Header` primitive's `level` prop was not included in the `primitives.json` or `primitivesCatalog` ESM export. In Studio UI, it get's filtered out for not being a valid prop from the definition.
I also fixed a few other warnings in the script because `Radio` doesn't have a `label` prop, and `TextField` `isMultiline` prop has been deprecated and is no longer used in Studio.
Diff of the JSON files before and after these changes:
```diff
"variation": {
"type": "string"
},
+                   "level": {
+                     "type": "number",
+                     "priority": true
+                   },
"isTruncated": {
"type": "boolean"
```
</body></html> …
=> fix: issue where number unions ignored in primitivesCatalog

.changeset/tame-seas-grin.md, packages/ui/src/theme/css/component/authenticator.scss
add overflow so that long authenticator modals will cause page scroll instead of just being cut off.
=> add overflow styling to authenticator modal

canary/script/changeCanaryPackageVersion.mjs
This makes glob more specific in the canary script we have. This will prevent errors in which it'll try to modify `package.json` in child `node_modules` and end up in errors like
```
✅ Updated undefined to "next" for file:///Users/willeea/Documents/spark/amplify-ui/canary/apps/vue/vuecli/node_modules/postcss-selector-parser/package.json
```
=> chore: Make glob more specific in canary script

.changeset/cuddly-buses-walk.md, packages/react/src/components/Geo/Geocoder/index.tsx
The `position` property for the `Geocoder` component needs to be passed as the second argument to the `useControl` hook when `Geocoder` is used as a map control.
N/A
Passing a `position` property to the `Geocoder` component in the `map-with-geocoder` example is reflected in the map.
```jsx
import { MapView, Geocoder } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';
import awsExports from './aws-exports';
Amplify.configure(awsExports);
export default function MapWithGeocoder() {
return (
<MapView>
<Geocoder position="top-left" />
</MapView>
);
}
```
=> fix(geo): Add position option to GeocoderControl

.changeset/chatty-scissors-change.md, packages/ui/src/theme/css/component/select.scss
This is essentially setting the text color of our `<option />` elements to the browser default to fix the following issue:  
The SelectField options are not legible in Chrome on Windows in dark mode. While the text color from dark mode cascades down (a very light gray), we do not update the background color.
Alternatively, we could consider theming of the option dropdown for browsers that allow it; Windows on Chrome allows you to style the background color of the options dropdown. That will require some further consideration for creating tokens for the font color as well. The fix in this PR works with our current theming options so seems the better fit for now.
**Before**
**After**
Fixes: https://github.com/aws-amplify/amplify-ui/issues/1738
Checked in a number of other browsers with the …
=> fix: Resets select option text color to fix windows darkmode bug

.github/actions/has-changesets/action.yml, .github/workflows/publish-latest.yml
This PR adds a reusable action to check whether there are changesets in `.changeset` directory. This will be used to later split `publish-latest` to `version-packages` and `publish-latest`. 
This composite action has been tested in a POC -- https://github.com/aws-amplify/amplify-ui/pull/1770:
- `has-changesets` is true when `.changeset` folder is empty: [workflow run](https://github.com/aws-amplify/amplify-ui/runs/6162647393?check_suite_focus=true), [commit](https://github.com/aws-amplify/amplify-ui/pull/1770/commits/fed90313491a26cfb4b386109395bce4ec16f96d)
- `has-changesets` is false when `.changeset` folder is not empty: [workflow run](https://github.com/aws-amplify/amplify-ui/runs/6162670185?check_suite_focus=true), [797c50c](https://github.com/aws-amplify/amplify-ui/pull/1770/commits/ …
=> ci: Add action that checks whether there are changesets in `.changeset`

.changeset/silver-months-talk.md, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SetupTOTP/__tests__/SetupTOTP.test.tsx
Prevent destructuring of `undefined` values from `formFields` lookup in `SetupTOTP` component:
- default to an empty object when `formFields` lookup resolves to falsy
- add unit tests
- add `getTotpCode` util
https://github.com/aws-amplify/amplify-ui/issues/1785
- recreated issue in example app by passing an empty object as `formFields` argument
- manually tested failing use case with changes in this PR
- added some unit testing
=> fix(ui-react): add graceful handling of falsy form field values in SetupTOTP component

.changeset/silver-foxes-clap.md, packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/VerifyUser/ConfirmVerifyUser.tsx, packages/react/src/components/Authenticator/VerifyUser/VerifyUser.tsx, packages/ui/src/theme/css/component/authenticator.scss
This pull request is to remove all inline styling from the react authenticator so that it can comply with strict csp rules
=> remove inline styling from react authenticator

.changeset/shiny-bags-doubt.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.ts
The text for the submit button on the `ConfirmResetPassword` screen incorrectly showed `Send Code` even when the code was already sent during the `ResetPassword` state. This PR updates the text to `Submit` to match the experience in the React and Vue implementations.
Before:
After:
#1784 
Manual visual validation.
=> fix(authenticator): Update ConfirmResetPassword submit text for Angular

yarn.lock
This is totally on me, I forgot to update `yarn.lock` after I pinned `@xstate/react` version in https://github.com/aws-amplify/amplify-ui/pull/1798/commits/9a5ea7e82db22872dd7a1fcab9ab78a57e9d334b of #1793. 
=> chore: update `yarn.lock`

docs/src/pages/components/radiogroupfield/examples/BasicExample.tsx, docs/src/pages/components/radiogroupfield/examples/LabelPositionExample.tsx, docs/src/pages/components/radiogroupfield/examples/ThemeExample.tsx
This updates examples for RadioGroupField to use a unique `name` prop per example.
RadioGroupFields that have the same name can cause issues with tabbing; one group might be skipped completely from the tab order. You can see this happening now by attempting to tab to the Demo example on https://ui.docs.amplify.aws/components/radiogroupfield
**Before**
**After**
Tested in local docs instance in Chrome and Safari
=> docs/fix: radio groups missing unique names causes focus/styling issues

.changeset/spicy-queens-happen.md, docs/src/pages/components/authenticator/advanced/current-route.angular.mdx, docs/src/pages/components/authenticator/advanced/current-route.react.mdx, docs/src/pages/components/authenticator/advanced/current-route.vue.mdx, examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.html, examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.ts, examples/next/pages/ui/components/authenticator/sign-up-with-email/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-up-with-email/index.vue, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/e2e/cypress/integration/ui/components/geo/map-with-geocoder/map-with-geocoder.steps.ts, packages/e2e/features/ui/components/authenticator/sign-up-with-email.feature, packages/ui/src/helpers/authenticator/facade.ts, packages/vue/src/composables/useUtils.ts
To make it simple for people to access our `authenticated` state, we've added in another facade called `authStatus`. This will return if the user is `authenticated`, `unauthenticated` or `configuring`.
#1497 
Added test
=> feat: Added Auth Status 

.changeset/good-gifts-camp.md, packages/react/.eslintrc.js, packages/react/package.json, yarn.lock
Remove `eslint-config-airbnb` and `eslint--config-airbnb-typescript` plugins and other `eslint` updates:
- remove aforementioned configs as:
- the configs are very opinionated and come with a ton of predefined rules, creating more maintenance overhead in both resolving linting errors and determining which preconfigured rules need to be overridden
- allows for easier refinement of applied `eslint` rules to match better serve the `ui-react` codebase, and ensures they are easily visible in the local _.eslintrc.js_ config
- remove `import` overrides related to the aforementioned configs
- add back some rules from the aforementioned configs
- improve file structure/commenting
- add `eslint:recommended` rule set
- add additional `react` rules
- replace `plugin:prettier/recommended` with just …
=> chore(ui-react): update eslint config

.github/workflows/test-deploy-main.yml, .github/workflows/test-prs.yml, canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, canary/apps/react/next/package.json, canary/apps/react/vite/package.json, packages/react/package.json, yarn.lock
This PR set up bundle size checks for both ui-react lib and canary Apps with [size-limit](https://github.com/ai/size-limit). Size limit is based on current sizes plus 10%~20%. 
- For ui-react, size checks will be a follow-up action after build in  unit tests when a PR request is created or pushing to main.  
- For canary Apps, size checks will be executed through postbuild script.
Tested out the changes on my [fork](https://github.com/zchenwei/amplify-ui/actions)
=> build: setup size limit configs

.changeset/soft-panthers-hug.md, packages/react/src/components/Authenticator/Router/types.ts
Remove `?` flag from `props` of render prop children of `RouterProps`
https://github.com/aws-amplify/amplify-ui/issues/1845
Manually tested in sample app
=> fix(ui-react): remove optional flag from render prop child in RouterProps

.changeset/tasty-tables-walk.md, examples/angular/src/pages/ui/components/authenticator/sign-in-with-phone/sign-in-with-phone.component.ts, examples/next/pages/ui/components/authenticator/sign-in-with-phone/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-in-with-phone/index.vue, packages/e2e/cypress/fixtures/force-change-password-phone-failure.json, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/cypress/integration/common/sign-up.ts, packages/e2e/features/ui/components/authenticator/sign-in-force-new-password.feature, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx
Added missing translation for force new password page for React
#1789 
Added cypress test
=> fix: Add missing translation for force new password page

packages/ui/src/machines/authenticator/index.ts
While #1809 resolves happy cases, refresh token could still cause an infinite loop when it expires (default 30 days). 
This is because we have
https://github.com/aws-amplify/amplify-ui/blob/04c49c44999d62287a6e932f7d0188c84a90ede6/packages/ui/src/machines/authenticator/index.ts#L208
which forwards any `SIGN_OUT` event to the actor. 
But when refresh token is expired and the app is refreshed, it calls `SIGN_OUT` event before state machine has any actor. This confuses the `forwardTo` action. Specifically, `forwardTo` action uses `send` under the hood, and it sends the event to itself if [the target is undefined](https://xstate.js.org/docs/guides/actions.html#send-action). So when `SIGN_OUT` is called when actor doesn't exist yet, it sends that event over and over to itself.
This PR fixes it …
=> fix(authenticator): fix infinite loop on refresh after refresh token expires

.changeset/orange-sheep-learn.md, packages/react/src/primitives/FieldGroup/FieldGroup.tsx, packages/react/src/primitives/FieldGroup/__tests__/FieldGroup.test.tsx, packages/react/src/primitives/TextField/TextField.tsx, packages/react/src/primitives/types/fieldGroup.ts, packages/ui/src/theme/css/component/fieldGroup.scss
1. Update corresponding border colors to fix `PasswordField` and `SearchField` quiet variation styling. Make the colors `transparent` to avoid border pixel shift when switching between focus and non-focus state
2. Update unit tests to cover new cases.
Fixes #1794, fixes #1634
=> fix(style): fix PasswordField and SearchField quiet styling

.changeset/rude-wasps-hammer.md, packages/react/src/primitives/View/View.tsx
Removing non-existant prop `isDisabled` on DOM element on View primitive.
Was causing this warning
Ran manually
=> Remove is disabled

docs/src/components/Layout/SecondaryNav.tsx, docs/src/pages/guides/auth-protected/index.page.mdx
The guides for Angular and Vue show under protected routes `How to create a React application with protected routes using the Authenticator component`
This should be hidden instead, and only show for React.
fixes #1874 
Manual
=> fix: Fix Guide title for Vue and Angular

.github/workflows/publish-latest.yml
This adds "canary" build tests before `publish-latest` workflow publishes to `@latest`. One less manual step we need to worry about!
Test run here: https://github.com/aws-amplify/amplify-ui/actions/runs/2310172534
=> feat(ci): Run build test before publishing to latest

.changeset/five-experts-hunt.md, packages/react/src/primitives/Button/Button.tsx, packages/react/src/primitives/Button/__tests__/Button.test.tsx, packages/react/src/primitives/FieldGroupIcon/__tests__/FieldGroupIconButton.test.tsx
This PR is to add the disabled class to Button primitives when the disabled attribute is present
Validated on docs site with the pagination primitive which uses an `as={Button}` that strips out the `isDisabled` property
=> Button disabled

docs/src/pages/components/switchfield/examples/SwitchFieldThumbColorExample.tsx, docs/src/theme.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/tokens/colors.ts, packages/ui/src/theme/tokens/components/sliderField.ts, packages/ui/src/theme/tokens/components/switchField.ts, packages/ui/src/theme/tokens/types/scales.ts
1. Bump up neutral-60 to 3:1 ratio compared with white
2. Update track background color of switch and slider to use neutral-60
Fixes #1820 
| Light   | Dark |
| ----------- | ----------- |
| ![Screen Shot 2022-05-11 at 2 49 55 PM](https://user-images.githubusercontent.com/40295569/167958556-d4b98988-2d2a-47d9-9bfc-243a37518cb5.png) | ![Screen Shot 2022-05-11 at 2 51 40 PM](https://user-images.githubusercontent.com/40295569/167958566-5fbbfdde-e1f7-4bf7-9907-23fab667e847.png)  |
| ![Screen Shot 2022-05-11 at 3 02 07 PM](https://user-images.githubusercontent.com/40295569/167958630-ae07c656-f008-4a63-a01e-a60e818efa8b.png) | ![Screen Shot 2022-05-11 at 3 28 09 PM](https://user-images.githubusercontent.com/40295569/167958644-ac1cdaeb-6f94-43a2-8958-93a4b470cf48.png) |
By submitting this pull …
=> fix(style): adjust switch track color to comply with 3:1 contrast ratio

docs/src/components/Demo.tsx, docs/src/pages/components/view/ViewPropControls.tsx, docs/src/pages/components/view/demo.tsx, docs/src/pages/components/view/useViewProps.tsx
Add maxWidth Value to View Demo, Update Demo to scroll if the demo is larger than avaialbe space on the screen, remove maxWidth from demo `propsToCode` for mobile view.
=> update scrollability and width values for view docs on mobile

.changeset/fast-chefs-rest.md, packages/react/src/components/Geo/Geocoder/index.tsx, packages/react/src/components/Geo/MapView/index.tsx
Some users have reported issues with ES 2020 features that are used by our `react-map-gl` dependency and certain build tools that they're using (e.g. Create React App v4). This PR updates our use of `react-map-gl` to point to the ES5-compatible bundle provided by the library which will mitigate issues related to ES 2020 features.
#1656 
Manually validated this change by sym-linking it to a CRA4 sample application using the `<MapView>` component and verified that there were no build issues and the [workaround suggested in #1656](https://github.com/aws-amplify/amplify-ui/issues/1656#issuecomment-1095389881) is not needed.
=> fix(geo): Point to react-map-gl es5 bundle

docs/src/pages/components/stepperfield/examples/ControlledStepperFieldExample.tsx, docs/src/pages/components/stepperfield/react.mdx
This PR updates the documentation about using the `onStepChange` handler in the StepperField component. 
=> docs(update): StepperField onStepChange handler

.changeset/serious-geckos-act.md, packages/react/src/primitives/PhoneNumberField/CountryCodeSelect.tsx, packages/react/src/primitives/PhoneNumberField/PhoneNumberField.tsx, packages/react/src/primitives/PhoneNumberField/__tests__/PhoneNumberField.test.tsx, packages/react/src/primitives/types/phoneNumberField.ts
This PR address [this issue](https://github.com/aws-amplify/amplify-ui/issues/1795): "PhoneNumberField dial code dropdown doesn't honor readonly prop"
As a result of these changes, if the `isReadOnly` prop is passed to the `PhoneNumberField`:
- The `CountryCodeSelect` primitive is marked with the `aria-disabled=“true”` attribute. The reason we’re not marking it with `aria-readonly=“true”` is because that does not cause screen readers to announce anything to customers. @hbuchel 
- All the options in the `CountryCodeSelect` are marked with the `disabled` attribute because the select field should still be readable and focusable, but disallow changing the readonly selection. 
- Form data is still submitted if the `isReadOnly` prop is passed. 
Fixes …
=> bug(fix): PhoneNumberField does not honor readonly prop

.changeset/tasty-pans-rhyme.md, packages/react/src/primitives/Menu/MenuButton.tsx, packages/react/src/primitives/Menu/__tests_/menu.test.tsx
While updating the Menu docs, I noticed that there was no visual change for a disabled `MenuItem`, even though the `isDisabled` prop is getting passed through and works with screen readers. 
To fix this, I replaced the HTML `<button>` element used in `MenuButton` to our own `Button` component. This allows disabled styling to get applied to MenuItems via the `amplify-button--disabled` class (`MenuItem` renders a `MenuButton`). 
Before:
After:
=> bug(fix): MenuItem disabled styling not applied

.changeset/cyan-tips-pull.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts, packages/react/src/components/Authenticator/hooks/useAuthenticator/index.tsx, packages/ui/src/helpers/authenticator/utils.ts, packages/ui/src/types/authenticator/stateMachine/authMachine.ts, packages/vue/src/components/authenticator.vue
Instead of blindly accepting hub events and passing them to state machine, this PR adds a state check to ensure that the authenticator is in the correct state. 
This will prevent sending hub events (e.g. `tokenRefresh`) over and over when Authenticator is already handling it.
`listenToAuthHub` now needs access to current state, so I refactored the signature to accept `authService`, which is a static context that provides access to `state` and `send`. I also abstracted out the default hub handler, and enabled other libraries to pass custom hub handler. This helps Angular because it has been using extra handling for change detection (see #1809).
Related to #1683.
=> fix(authenticator): Only pass hub event when authenticator is in correct state

.changeset/wild-vans-pay.md, packages/ui/src/theme/css/component/menu.scss
While updating the Menu docs, I stumbled across this small bug mapping `minHeight` to the min-width CSS variable. I can confirm that this change fixes the problem. 
=> bug(fix): MenuItem minHeight mapped incorrectly

.changeset/chilled-houses-impress.md, packages/ui/src/theme/css/component/scrollView.scss
Fixes a regression which always shows scrollbars on the ScrollView component even when they are unneeded. This was introduced when #1236 was merged after https://github.com/aws-amplify/amplify-ui/pull/1835.
`yarn docs dev`
=> fix: regression in scrollview that shows scrollbars when unneeded

.changeset/tough-sheep-cry.md, packages/react/src/components/Geo/Geocoder/index.tsx, packages/react/src/components/Geo/MapView/index.tsx
Reverts aws-amplify/amplify-ui#1887
Pointing `react-map-gl` to the es5 bundle causes an error when an application uses the package with >=es6 module resolution. This represents a breaking change to customer applications.
=> Revert "fix(geo): Point to react-map-gl es5 bundle"

packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/sliderField.scss, packages/ui/src/theme/tokens/components/sliderField.ts
1. Bump up slider thumb border width
2. Add focus border color and adjust box shadow
3. Update test snapshots
=> fix(style): adjust slider thumb border width, focus color and box shadow

.changeset/gentle-ears-hunt.md, examples/angular/src/pages/ui/components/authenticator/reset-password/reset-password.component.ts, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.ts, packages/e2e/features/ui/components/authenticator/reset-password-angular.feature, packages/e2e/features/ui/components/authenticator/sign-in-with-username.feature
This fix changes the `Send Code` text in the Confirm Reset Password page to show `Submit` instead (for Angular, already fixed in Vue and React). Unless, the customer already has a translation for `Send Code`, in that case it will show the translated message. This is for added backwards compatibility.
#1784 
Added a couple test, only for Angular
=> fix: Submit Code Text Translation Fix

docs/src/pages/[platform]/index.page.tsx, docs/src/pages/_app.page.tsx, docs/src/pages/index.page.tsx, docs/src/theme.ts
Add override amplify provide to home page of docs to scope the theme override examples from the home page to just the home page.
Manual inspection of the docs site.
=> Doc home scope

docs/src/pages/[platform]/components/alert/index.page.mdx, docs/src/pages/[platform]/components/button/index.page.mdx, docs/src/pages/[platform]/components/checkboxfield/index.page.mdx, docs/src/pages/[platform]/components/expander/index.page.mdx, docs/src/pages/[platform]/components/grid/index.page.mdx, docs/src/pages/[platform]/components/link/index.page.mdx, docs/src/pages/[platform]/components/menu/index.page.mdx, docs/src/pages/[platform]/components/radiogroupfield/index.page.mdx, docs/src/pages/[platform]/components/selectfield/index.page.mdx, docs/src/pages/[platform]/components/sliderfield/index.page.mdx, docs/src/pages/[platform]/components/stepperfield/index.page.mdx, docs/src/pages/[platform]/components/switchfield/index.page.mdx, docs/src/pages/[platform]/components/table/index.page.mdx, docs/src/pages/[platform]/components/tabs/index.page.mdx, docs/src/pages/[platform]/components/tabs/react.mdx, docs/src/pages/[platform]/components/togglebutton/index.page.mdx
The [WAI Aria Practices](https://www.w3.org/TR/wai-aria-practices/#abstract) site we were using to link to our component's aria patterns has been deprecated in favor of the new [Aria Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/). This PR updates all of our links, example:
```
ariaPattern: https://www.w3.org/WAI/ARIA/apg/patterns/button
```
Tested in docs instance locally and verified each new link works.
=> docs/fix: update aria pattern links to point to new W3 APG site

docs/scripts/generate-sitemap-robotstxt.ts
**Issue**: hard-coded prod url for sitemap
**fix**: dynamically use `SITE_URL` from the environment to generate sitemap
tested at local
=> fix(sitemap): dynamically generate urls

docs/src/components/Layout/SecondaryNav.tsx, docs/src/pages/[platform]/getting-started/installation/dependencies.vue.mdx, docs/src/pages/[platform]/getting-started/installation/index.page.mdx, docs/src/pages/[platform]/getting-started/troubleshooting/index.page.mdx, docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.angular.mdx, docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx, docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.vue.mdx
This PR moves the Troubleshooting section off from `/{platform}/getting-started/installation` to its own page at `/{platform}/getting-started/troubleshooting` to align with our new IA.
Part of our "Docs: Getting Started - Installation refactor" task.
Tested changes in local docs install.
=> docs: move troubleshooting to new page

docs/package.json, examples/angular/package.json, examples/vue/package.json, packages/angular/projects/ui-angular/package.json, packages/react-core/package.json, packages/react/package.json, packages/ui/package.json, packages/vue/package.json, yarn.lock
Temporarily set all `aws-amplify` deps to point at the "in-app-messaging" tagged release. These updates will need to be reverted prior to local "in-app-messaging" feature merge.
> Note: There are currently some issues with the `aws-amplify` "in-app-messaging" tagged release and NextJS, which will prevent the integ tests from running correctly for the local "in-app-messaging" feature branch once this is merged. These issues are being actively worked through.
NA
`yarn`
=> chore(in-app-messaging): point all aws-amplify deps to in-app-messaging tagged release

.changeset/calm-hornets-care.md, packages/react/src/components/ThemeProvider/__tests__/ThemeProvider.test.tsx, packages/react/src/components/ThemeProvider/index.tsx
**Issue**: when changing page, `data-amplify-theme` and `data-amplify-color-mode` sometimes are `null`, which caused issue for the search modal https://github.com/aws-amplify/amplify-ui/pull/1775/. If the system mode is changed dark, the modal doesn't change accordingly. It might cause similar issue to the customers.
https://user-images.githubusercontent.com/11983489/170784598-a4c92b2e-3fd6-4def-98bf-64b2ab99d7fe.mov
https://user-images.githubusercontent.com/11983489/170784640-6a8c59df-1f3a-42f4-a5f9-76fee272cffc.mov
**Fix**: set default value if query value from the empty `html` tag
locally tested
https://fix-amplifyprovider.dnxy4amiz00i4.amplifyapp.com/
=> fix(amplifyprovider): prevent original values from being null

docs/src/components/Layout/FrameworkChooser.tsx, docs/src/pages/_app.page.tsx
**Issue**: we show all the available frameworks on all pages even though some pages don't support that framework, but the crawler crawl those links
**Fix**: dynamically only show the supported framework options on the switcher
| Before  | After  |
|---|---|
| ![image](https://user-images.githubusercontent.com/11983489/171292715-571e8d07-3500-4c99-95b6-d87e94dae744.png)  |  ![Pasted_Image_5_31_22__15_57](https://user-images.githubusercontent.com/11983489/171297340-d6c6eaf3-037a-4930-b05c-20e7f60dd0bf.png) |
| ![image](https://user-images.githubusercontent.com/11983489/171292847-7d8309cd-bb61-48fc-89c4-439e1af18104.png)  |  ![Pasted_Image_5_31_22__15_55](https://user-images.githubusercontent.com/11983489/171297220-9ad493b5-653f-4a9b-8dea-bae63db9a7d4.png)| …
=> fix(docs): dynamically show supported frameworks on each page

docs/src/pages/_document.page.tsx
I noticed on our [dev docs site](https://dev.ui.docs.amplify.aws/react/getting-started/create-react-app) that the Unsplash images for the CRA tutorial weren't displaying, but they displayed in my dev environment. 
I added the image-src CSP rule to our prod env as well, which should hopefully fix this. 
=> docs(fix): Add CSP rule for prod env

docs/src/components/Layout/Sidebar.tsx
Making the `isCurrent` conditional in the `NavLink` use the `pathname` which doesn't include anchors (hashes) at the end of the URL. 
Tested it locally and it works like a charm. 
=> Fixing nav item selected with a hash

.changeset/mean-eyes-remain.md, docs/src/pages/[platform]/components/expander/examples/CustomTitleComponent.tsx, docs/src/pages/[platform]/components/expander/examples/index.ts, docs/src/pages/[platform]/components/expander/react.mdx, packages/react/src/primitives/Expander/__tests__/ExpanderItem.test.tsx
We recently updated the ExpanderItem component to accept any ReactNode as a title. 
```
title?: React.ReactNode;
```
This adds a unit test for passing a custom component to the title prop. It also updates our docs to show an example of using a custom component as the title (screenshot below).
Ran tests locally and verify they pass. Ran docs instance locally to verify new example.
=> chore(react): update unit test for Expander for custom title component

canary/apps/vue/vuecli/package.json
Fix Vue CLI from this [bug](https://github.com/stacktracejs/error-stack-parser/issues/80).
Can remove when bug is fixed if needed.
Fixes #2038 
=> Fix Vue-CLI canary from failing to build

packages/react/package.json, packages/ui/package.json
Fixes an issue where `npm pack` or `npm publish` in npm version 8.8+ no longer includes the `dist/esm/node_modules/tslib` folder. This folder includes a file `tslib.es6.js` which polyfills a few ES6 features. The fix is to tell npm to always include this folder by adding it to `files`. 
Runtime error seen when `dist/esm/node_modules/tslib` folder is missing
```bash
ERROR in ./node_modules/@aws-amplify/ui-react/dist/esm/primitives/VisuallyHidden/VisuallyHidden.js 1:0-68
Module not found: Error: Can't resolve '../../node_modules/tslib/tslib.es6.js'
```
=> fix: issue where npm v8.8+ doesn't include tslib

packages/angular/projects/ui-angular/tsconfig.lib.prod.json
Sets `angularCompilerOptions` to use partial compilation mode, as suggested in https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility.
This has been blocking publish to `@next`.
Confirmed NPM publish works with verdaccio:
=> fix(angular): Use partial ivy compilation mode

docs/src/styles/docs/base.scss
Small fix for alignment of `<h4>` tags. The  anchor link icon was pushing it inward, and the icon wasn't visible.
Before (hovering on "Resizable"):
After (hovering on "Resizable")
=> fix(docs): align h4 and make anchor visible on hover

.changeset/dull-pillows-cover.md, packages/react/src/hooks/useBreakpointValue.ts, packages/react/src/primitives/Alert/__tests__/Alert.test.tsx, packages/react/src/primitives/shared/__tests__/utils.test.tsx, packages/react/src/primitives/shared/responsive/__tests__/utils.test.ts, packages/react/src/primitives/shared/responsive/utils.ts, packages/react/src/primitives/shared/styleUtils.ts, packages/react/src/primitives/shared/utils.ts, packages/react/src/primitives/types/style.ts, packages/react/src/primitives/types/theme.ts, packages/ui/src/theme/index.ts
This PR will be adding colors theme key support in style props. Styling with theme key right away and it will be converted into CSS variable reference under the hood. Responsive value support as well. No need to call `useTheme` hook to get the tokens first anymore!
**Example Code**
```jsx
import { View } from '@aws-amplify/ui-react';
export const Demo = () => {
return <View backgroundColor="pink.10" color="red.40"/>
}
```
For more colors, please reference [here](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/theme/tokens/colors.ts#L100-L283).
=> feat: adding colors theme key support in style props

.changeset/wet-pets-remain.md, packages/react/src/hooks/useBreakpointValue.ts, packages/react/src/primitives/shared/responsive/utils.ts, packages/react/src/primitives/shared/utils.ts
The docs on dev endpoint is broken. The error is coming from `HomePage` component.
```jsx
const showEditor = useBreakpointValue({
base: false,
medium: true,
});
```
The value used in `useBreakpointValue` can be `any`
[](https://dev.ui.docs.amplify.aws/)
Tested it out locally
=> fix(docs): fix type error

.changeset/healthy-actors-relate.md, packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts, packages/ui/src/machines/authenticator/defaultServices.ts
Previously in our password validation util, we were matching special characters with `\W`, which matches all non-word character **except underscore**. 
https://github.com/aws-amplify/amplify-ui/blob/5b713ad3f5ddaf24583f7589138c1545a26f6c3a/packages/ui/src/machines/authenticator/defaultServices.ts#L109
This was not sufficient because underscore is a valid special character. Instead, this PR makes password rules more explicit by directly matching [special characters allowed by Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html). 
Fixes #2052
New unit test
=> fix(authenticator): explicitly filter special characters allowed by Cognito

docs/src/components/CardLink.tsx, docs/src/pages/[platform]/getting-started/accessibility/accessibility.react.mdx
Switch CardLink to use our Link component. It was using next/Link but that breaks smooth scrolling to anchor tags.
Tested in local docs instance. Click  any CardLink on /react/getting-started/accessibility  and it will now smoothly scroll down to the section from the hash.
=> fix(docs): use our Link, not Next Link for CardLink

.changeset/rare-horses-check.md, docs/src/components/CopyButton.tsx, docs/src/components/Demo.tsx, docs/src/components/Example.tsx, docs/src/pages/[platform]/index.page.tsx, docs/src/styles/docs/example.scss
Updates to the copy buttons used in the demo and example code blocks:
- consolidate copy related buttons in to `CopyButton`
- update styling to fix issues called out in https://github.com/aws-amplify/amplify-ui/pull/1905#issuecomment-1130258047
**Screenshots**
Extra space below horizontal scroll bar. overlap of copy button on horizontal scroll bar:
Before:
After:
Example text visible through copy button:
Copy button spacing when vertical scroll bar visible:
Before:
After:
https://github.com/aws-amplify/amplify-ui/pull/1905#issuecomment-1130258047
Manual testing
=> chore(docs): update example and demo copy buttons

docs/src/components/Layout/index.tsx
Using `&&` for conditional rendering in React should be avoided because you might get weird cases like this where the ToC will show `0` because `headings.length` is 0. 
=> fix: docs table of contents with no headings

.changeset/mighty-impalas-fail.md, docs/src/pages/[platform]/components/textfield/examples/TextFieldThemeExample.tsx, docs/src/pages/[platform]/components/textfield/examples/index.ts, docs/src/pages/[platform]/components/textfield/react.mdx, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/textField.scss, packages/ui/src/theme/tokens/components/index.ts, packages/ui/src/theme/tokens/components/textField.ts
Add Design Tokens and Theme section to textfield
validated on docs site
=> add textfield design tokens

.changeset/modern-cups-help.md, packages/react/src/components/ThemeProvider/__tests__/ThemeProvider.test.tsx, packages/react/src/components/ThemeProvider/index.tsx, packages/react/src/primitives/Menu/Menu.tsx, packages/ui/src/theme/css/component/menu.scss
* Menu primitive uses `portalled={false}` now so it no longer renders in a React portal outside the DOM node of the ThemeProvider, meaning it now properly accepts the theme of the nearest ThemeProvider. 
* Removing all the junk in the ThemeProvider to get around that Portal issue. 
Potential alternative: we could make our own Portal (using the ThemeProvider's DOM node) potentially and render the menu content in that. Seems a bit more difficult. 
* Navigated around the docs site, things work fine. Examples with ThemeProvider work.
=> fix: nested theme providers by removing menu's portal

.github/workflows/publish-latest-v2.yml, .github/workflows/test-deploy-v2.yml, .github/workflows/test-prs.yml, .github/workflows/version-packages-v2.yml
Changing `v2/react` to `ui-react@v2` as discussed. I thought @ is not allowed in branch name, but it is 😋 
=> ci: change v2 branch name to `ui-react@v2`

packages/react/src/hooks/__tests__/useAuth.test.ts, packages/react/src/hooks/__tests__/useStorageURL.test.ts
Updates imports of `act` from `react-dom/test-utils` to `@testing-library/react-hooks` to prevent transitive unit test warning:
```
Warning: It looks like you're using the wrong act() around your test interactions.
Be sure to use the matching version of act() corresponding to your renderer:
// for react-dom:
import {act} from 'react-dom/test-utils';
// ...
act(() => ...);
// for react-test-renderer:
import TestRenderer from react-test-renderer';
const {act} = TestRenderer;
// ...
act(() => ...);
at TestComponent (amplify-ui/node_modules/@testing-library/react-hooks/lib/helpers/createTestHarness.js:22:5)
at Suspense
at ErrorBoundary (amplify-ui/node_modules/@testing-library/react-hooks/node_modules/react-error-boundary/dist/react-error-boundary.cjs.js:59:35)
```
NA
`yarn react test`
By …
=> chore(ui-react): align act imports

.changeset/eighty-birds-develop.md, packages/react/__tests__/exports.ts, packages/react/src/primitives/shared/constants.ts, packages/react/src/primitives/shared/index.ts
This PR will remove `SharedText` export as part of 3.0 `BREAKING CHANGE`.
We want to clean up unintentional exports in 3.0.
=> BREAKING CHANGE: remove ShareText export

docs/src/components/SocialProviderDemo.tsx, docs/src/pages/[platform]/components/authenticator/configuration/socialProviders.web.mdx, docs/src/pages/[platform]/components/authenticator/customization/LabelsAndTextDemo.tsx, docs/src/pages/[platform]/components/authenticator/customization/customization.headers-and-footers.web.mdx, docs/src/pages/[platform]/components/authenticator/customization/customization.labels-and-text.web.mdx
Fix docs error messages when people click buttons in the authenticator in the docs.
Also fixed broken translation accordion.
Before:
After:
Fixes #2066  
=> fix: Fix docs error messages for Authenticator demo

docs/src/components/Layout/FrameworkChooser.tsx
Removes some redundant alt text for framework chooser buttons which was causing SR to announce "React React"; we have a text label for them already so we can use an empty alt attribute for the icons.
**Before**
**After**
n/a
Local docs instance
=> fix (docs): Remove redundant alt text

.github/actions/install-with-retries/action.yml, .github/actions/install-with-retries/install-with-retries.sh, .github/workflows/run-and-test-builds.yml
This PR adds new `install-with-retries` action that will try `yarn install` up to 3 times. This can be reused in other PRs, but I scoped it to just canary workflow because that's where `yarn install` failed the most. 
This fixed a bug where `yarn install` failed silently after it failed all three retries. See "Install Cypress" step in this [workflow](https://github.com/aws-amplify/amplify-ui/runs/6914109019?check_suite_focus=true) for example.
`install-with-retries` optionally accepts `skip-cypress-binary` argument. If this is set to true, it'll skip cypress binary installation step, which has [been really flimsy](https://github.com/aws-amplify/amplify-ui/runs/6914109019?check_suite_focus=true) recently.
Instead of installing cypress binary every time, canaries will cache cypress binary …
=> ci(canary): new `install-with-retries` action

.github/actions/install-with-retries/install-with-retries.sh
This PR increases `--network-timeout` on `yarn install` on canary. This is the timeout for network request for each package.
The default is pretty aggressive at [30 seconds](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/constants.js#L40), and `yarn install` occasionally failed due to this (issue https://github.com/yarnpkg/yarn/issues/4890#issuecomment-348479446, [workflow run](https://github.com/aws-amplify/amplify-ui/runs/6930774348?check_suite_focus=true)).
This increases the network request to 1 minute. I didn't set it too high, to prevent workflows from waiting >1 minute for already failing network connection. We can revisit this later.
=> ci: increase network timeout

docs/src/styles/docs/home.scss
Adds focus styles for framework links
=> fix framework focus styles

docs/src/components/ThemeExample.mdx
Removes some of the extra margins/spacing around elements in the ThemeExample
**Before**
**After**
=> remove extra spacing around theme example elements

docs/src/pages/[platform]/components/image/ImagePropControls.tsx, docs/src/pages/[platform]/components/image/demo.tsx, docs/src/pages/[platform]/components/image/useImageProps.tsx
This PR reduces the number of props in the Image's main demo from 20 to 9, only including props that have a noticeable visual effect on the demo. 
Current demo: https://ui.docs.amplify.aws/react/components/image
Updated demo:
=> docs(chore): Image docs update

docs/src/components/InstallScripts.tsx, docs/src/pages/[platform]/getting-started/installation/dependencies.angular.mdx, docs/src/pages/[platform]/getting-started/installation/dependencies.react.mdx, docs/src/pages/[platform]/getting-started/installation/dependencies.vue.mdx, docs/src/pages/[platform]/getting-started/usage/create-react-app/react.mdx, docs/src/pages/[platform]/getting-started/usage/nextjs/react.mdx, docs/src/pages/[platform]/getting-started/usage/usage.react.mdx, docs/src/styles/docs/home.scss
This PR creates a reusable `<InstallScripts />` component, which reduces some redundant code across the Getting Started section. It also includes a "Copy" button for improved UX. 
Current:
Updated:
Ran the docs locally.
=> docs(chore): Add copy button to installation fragment

docs/src/components/Layout/PageTabLayout.tsx, docs/src/styles/docs/main.scss
=> add owl selector back to tabs page  content

docs/src/components/InstallScripts.tsx, docs/src/pages/[platform]/getting-started/usage/create-react-app/examples/AdvancedExampleCode.tsx, docs/src/pages/[platform]/getting-started/usage/create-react-app/react.mdx, docs/src/pages/[platform]/getting-started/usage/nextjs/examples/AdvancedExampleCode.tsx, docs/src/pages/[platform]/getting-started/usage/nextjs/react.mdx, docs/src/pages/[platform]/getting-started/usage/shared/AdvancedShoppingCard.tsx, docs/src/pages/[platform]/index.page.tsx
This PR adds a copy button to terminal commands, and applies a few small tweaks to the Getting Started pages. 
Current:
Updated:
=> docs(fix): Add copy button to terminal commands

.changeset/pretty-parents-add.md, packages/react/src/primitives/types/view.ts
To help with [MJ's props table PR](https://github.com/aws-amplify/amplify-ui/pull/2090), this PR adds a few prop descriptions which are missing from each primitive page:
- `isDisabled`
- `style`
- `as` 
=> docs(fix): Add missing prop descriptions

.github/workflows/publish-latest.yml, .github/workflows/test-deploy-main.yml, .github/workflows/test-deploy-studio.yml
Cypress binary doesn't need to be installed for publish scripts, so this PR skips them.
Checked the reusable action works against the root `package.json` here: https://github.com/aws-amplify/amplify-ui/runs/6975009310?check_suite_focus=true
I didn't POC publish part, but I'll make any updates promptly if needed.
=> ci(publish): Skip cypress binary installation in publish scripts

docs/src/data/links.ts
This PR simply moves the Pagination component from the Feedback section to the Layout section. I think this more accurately categorizes the function of Pagination in laying out data for the customer, but I am open to other ideas. 
Current:
Updated:
=> docs(fix): Move Pagination to Layout section

docs/src/pages/[platform]/components/ComponentsGrid.tsx
Hides the tertiary pages on the /components page. We don't currently link to this in the menu, but the new home page will.
**Before**
**After**
Local docs instance
=> docs(fix): hide tertiary pages on /components page

package.json, yarn.lock
Aliases the `shell-quote` dependency to `v1.7.3` to fix [this dependabot alert](https://github.com/aws-amplify/amplify-ui/security/dependabot/44).
N/A
Ran all unit tests and the Next e2e tests (`shell-quote` is a nested dependency of Next.js). Run `yarn list shell-quote` to verify that 1.7.3 is the only version listed.
=> chore: Fix for dependabot alert

.changeset/few-rockets-tell.md, packages/react/src/primitives/shared/constants.ts
While updating the RadioGroupField docs, I was wondering why the Target Classes did not include `amplify-radio__button`. It turns out it was because of a typo in the ComponentClassObject. 
Current:
Updated:
=> docs(fix): Fixed typo in ComponentClassObject

docs/src/pages/[platform]/theming/default-theme/cssTokenUsage.mdx, docs/src/pages/[platform]/theming/default-theme/tokenUsage.angular.mdx, docs/src/pages/[platform]/theming/default-theme/tokenUsage.react.mdx, docs/src/pages/[platform]/theming/default-theme/tokenUsage.vue.mdx, docs/src/pages/[platform]/theming/default-theme/web.mdx
This PR re-orders some content on the /theming/default-theme page and removes React specific code that was showing up for Angular/Vue.
N/A
Local docs instance
=> docs(fix): remove react specific code from angular/vue theme page

amplify.yml
Adds an `rm -rf node_modules` to amplify.yml build settings and removes node_modules cache setting. We can revert this after the next docs release; we just need to get the proper version of Canvas to build.
Docs builds are failing because of Canvas module. We updated this to a new version in the props-table feature, as well as a new Node version, however it keeps  trying to build the old version (which doesn't build against the newest version of Node we specified). Hosting team suggested an `rm -rf node_modules` and removing the cache setting for node_modules.
=> chore(docs): amplify.yml temp update to fix build

docs/src/pages/_document.page.tsx
We lost unsplash from our CSP rules in a recent update, this adds them back in. Our getting started guides for Next and CRA use unsplash to demo the Image component.
**Before (screenshot from https://dev.ui.docs.amplify.aws/react/getting-started/usage/create-react-app)**
**After (local instance with fix added)**
N/A
Local docs instance
=> fix(docs): add unsplash back to csp rules

amplify.yml
This reverts commit a495cfa9d381d93b4cf75e906e8b3ec2aae78264.
To fix the build, we had to remove the cache in https://github.com/aws-amplify/amplify-ui/pull/2194 temporarily, so https://github.com/aws-amplify/amplify-ui/pull/2197 was added to add it back. 
Then we found the cache doesn't decrease the build time, 
Without cache https://tiny.amazon.com/33aqtqqv/IsenLink
> Build duration
> 16 minutes 33 seconds
With cache https://tiny.amazon.com/qvwqxecw/IsenLink
> Build duration
> 17 minutes 23 seconds
So make the change in https://github.com/aws-amplify/amplify-ui/pull/2194 permanently in this PR. 
=> Revert "Revert "chore(docs): amplify.yml temp update to fix build (#2194)" (#2197)"

docs/src/styles/docs/code.scss
Fixes code examples (those not using Example or custom component) that are not getting owl selector margins.
**Before**
**After**
No change to home page code examples or Example code:
=> fix(docs): fix margins on stand alone code examples

docs/src/pages/_app.page.tsx
_Issue (from dev docs bug bash):_
- Dark mode: extra white on bottom, and when you go to landscape mode there are borders to the right and left
[Danny's recent PR](https://github.com/aws-amplify/amplify-ui/pull/2212) that added back the `document.documentElement` logic pretty much fixed this issue. 
The only additional change here is slightly adjusting the useEffect logic to ensure that the `data-amplify-color-mode` attribute is set on initial render even if `colorModePreference` is not set in localStorage. 
=> docs(fix): Dark mode background color

canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, docs/package.json, guides/react/protected-routes/package.json, package.json
This fixes a build error where @types/eslint version 8.4.4 is returning a 404 in the docs build and canaries.
=> fix: pin `@types/eslint` version

.changeset/slow-dragons-deny.md, packages/react/src/components/Authenticator/Authenticator.tsx, packages/react/src/components/Authenticator/Router/Router.tsx, packages/react/src/components/Authenticator/Router/types.ts
In `Authenticator`, directly return user defined `children` argument when user is authenticated. Currently, `children` is rendered from within the `Router` component, which may be remounted due to `Authenticator` life cycle events.
Potentially fixes https://github.com/aws-amplify/amplify-ui/issues/2191
Manual testing, ran integ tests
NA
=> fix(ui-react): directly return children from Authenticator

docs/src/pages/[platform]/components/scrollview/examples/AccessibleScrollViewExample.tsx, docs/src/pages/[platform]/components/scrollview/examples/ScrollViewStylePropsExample.tsx, docs/src/pages/[platform]/components/scrollview/examples/index.ts, docs/src/pages/[platform]/components/scrollview/react.mdx, docs/src/styles/primitives/scrollView.css
Adds section about Accessible scroll views to ScrollView docs.
Additionally, updated some styling/styleProps examples to have more contrast-ey backgrounds:
**Before**
**After**
=> docs: Add Accessibility example to ScrollView

packages/ui/src/theme/css/component/toggleButtonGroup.scss
* Changed from having a transparent border on one side to overlapping the button borders. This fixes an issue where you see little cut-outs in the top right & left of the border
* Added a z-index on focus so the focused button's border/box-shadow always appears on top
| - | - |
| <img width="434" alt="CleanShot 2022-07-05 at 09 35 22@2x" src="https://user-images.githubusercontent.com/321279/177376108-e2a9a934-0329-492e-a2ff-e8ace02bd5ac.png"> | <img width="430" alt="CleanShot 2022-07-05 at 09 46 21@2x" src="https://user-images.githubusercontent.com/321279/177377045-6adad795-06d3-4728-a646-9d61b39300e6.png"> |
| ![CleanShot 2022-07-05 at 09 36 45](https://user-images.githubusercontent.com/321279/177376115-f4a64ad5-ce48-4618-95ce-be7809af001d.gif) | ![CleanShot 2022-07-05 …
=> fix(ui): toggle button group borders

canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, docs/package.json, guides/react/protected-routes/package.json, package.json
This reverts commit f4560d39b3ab4a2666cc9d3feb5c839904e13e6d introduced in https://github.com/aws-amplify/amplify-ui/pull/2232. This change was no longer needed now that npm repo issues publishing tarballs has been fixed.
=> Revert "fix: pin `@types/eslint` version (#2232)"

docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.web.mdx
Fixes [some translation text](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#confirm-sign-up-page-translations) that was causing a horizontal scroll on the Authenticator docs on smaller viewports.
Note: There is also a table causing a larger horizontal scroll on this page but that should be fixed with [this PR](https://github.com/aws-amplify/amplify-ui/pull/2243) where the markdown table is converted to a ResponsiveTable
**Before**
**After**
=> fix(docs): translations causing scroll on auth docs

packages/react/.gitignore, packages/react/__tests__/exports.ts, packages/react/package.json, packages/react/scripts/generatePrimitiveCatalog.ts, packages/react/src/internal.tsx, packages/react/src/types/catalog.ts, packages/react/tsconfig.json, yarn.lock
This PR fixes an issue where our ESM export of the PrimitivesCatalog doesn't work correctly and throws a "Cannot find module" error due to the path `/internal/primtives-catalog`. This PR moves the catalog to be built into the source folder and exported alongside the other `internal` exports.
Import error message before this PR:
After this PR:
1. yarn react build
1. cd packages/react && npm pack
1. Opened my studio test app and installed the tarball
1. Observed that the import doesn't throw an error
=> Fix primitive catalog export

.changeset/nasty-tips-eat.md, packages/react/src/primitives/shared/utils.ts
Currently, overrides can only be type `string`. But other types such as `number`, `boolean`, and `React.ReactNode` have their uses. To let customers override any property on any component, we're setting the type to `unknown`.
=> chore: update internal type EscapeHatchProps

canary/apps/.gitignore, canary/package.json
This updates one of our canary apps to be installed with `npm install` in order to catch differences between `npm install` and `yarn install`. This is inspired by a problem where `npm install` went into an infinite loop on our package but it wasn't caught by canary apps because they only use `yarn install`.
**Tested `yarn react:install` triggers `npm install` for the CRA app:**
=> chore: update cra canary app to use npm install

.changeset/nervous-clocks-reply.md, packages/e2e/cypress/fixtures/sign-up-with-email-with-lambda-trigger.json, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/features/ui/components/authenticator/sign-up-with-email-with-lambda-trigger.feature, packages/ui/src/machines/authenticator/signUp.ts
When using auto confirmed lambda an error will show that the `username is not defined`
This PR sets the correct credentials, so the sign in can occur correctly. This was caused by a regression that no longer
set the credentials when you skip the confirmed page.
#2235 
Created new test to check values being sent to SignIn
=> fix: username undefined with autoconfirmed lambda

.changeset/young-dancers-hang.md, packages/react/package.json, yarn.lock
- Updated maplibre-gl-js-amplify to 2.0.2 which uses maplibre-gl-draw 0.1.1
- this removes the old dependency on mapbox-gl-draw which fixes the having multiple versions of mapbox-gl-draw, fixes npm empty package
=> fix: bump maplibre-gl-js-amplify to fix dependabot and other security related issues

examples/vue/package.json, examples/vue/src/router/index.ts, yarn.lock
The plugin for the Vue examples was using an older version of vite-plugin-pages. This was misconfigured and was using an incorrect `virtual:generated-pages-react` import.
This fix adds the latest version of the plugin with the correct import in the router.
closes #2246 
Passed Tests
=> fix: Update Vite Plugin Pages for Vue Examples

.github/workflows/run-and-test-builds.yml, .github/workflows/test-deploy-main.yml
https://app.asana.com/0/1201736086077862/1201914591116096/f
This PR add metrics for success and failures of the after merge next tag publishing events in Prod account.
TODO:
- manually create an alarm to trigger Sev3 tickets
- Ideally, we need to migrate the metrics and alarms to CDK and deploy them to the canary accounts
=> feat: add alert for publishing @next version

.github/workflows/publish-latest.yml
Since `PublishNext` in `test-deploy-main` workflow also publish to NPM, a.k.a, both `next` and `latest` are tags published to NPM, it's more accurate to name the metric `PublishLatest`.
=> chore(github): rename PublishNPMFailure to PublishLatestFailure

packages/react/.eslintrc.js, packages/react/src/primitives/Checkbox/Checkbox.tsx, packages/react/src/primitives/Checkbox/__tests__/Checkbox.test.tsx, packages/react/src/primitives/CheckboxField/CheckboxField.tsx, packages/react/src/primitives/utils/testUtils.ts, packages/react/src/primitives/utils/useLayoutEffect.ts, packages/react/src/primitives/utils/useStableId.ts
Update _primitives/utils_ to pass linting rules
- remove extraneous memoization in `useTestId` and rename to `getTestId` as it no longer requires usage of a React hook internally
=> chore(ui-react): lint primitives/utils

.github/workflows/publish-latest.yml, .github/workflows/publish-next.yml, .github/workflows/publish-studio.yml, .github/workflows/reusable-e2e.yml, .github/workflows/run-and-test-builds.yml, .github/workflows/test-prs.yml, .github/workflows/version-packages.yml
This PR updates workflow names to be more specific to what they actually do. Also adds (hopefully) helpful headers to each of the workflow, explaining what it does and when it's triggered.
- Publish workflows
- `publish-latest.yml`
- `publish-next.yml`
- `publish-studio.yml`
- `version-packages.yml`
- Test workflows
- `test-prs.yml`
- `reusable-e2e.yml`
- `run-and-test-builds.yml` (ie. canary)
No actual code changes.
=> chore(ci): Update workflow names + add comments

.changeset/late-ducks-divide.md, packages/angular/projects/ui-angular/src/lib/primitives/error/error.component.html, packages/angular/projects/ui-angular/src/lib/primitives/error/error.component.ts, packages/vue/src/components/primitives/__tests__/base-alert.spec.ts, packages/vue/src/components/primitives/base-alert.vue
The alert dismiss button is missing the accessible label for Vue and React Authenticator. This fix will add this text, and also make it translatable, so it can be updated in the future.
#2284
Validated by manual testing, and Vue test.
=> fix(Angular + Vue): Add accessible label to Alert dismiss button Authenticator

.changeset/tall-waves-worry.md, packages/react/src/primitives/StepperField/StepperField.tsx, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/stepperField.scss, packages/ui/src/theme/tokens/components/stepperField.ts
This changes fixes an issue where the StepperField disabled buttons are hard to see (Fixes: #2215).
| Before  | After |
| ------------- | ------------- |
|<img width="467" alt="Screen Shot 2022-07-22 at 9 16 48 AM" src="https://user-images.githubusercontent.com/68251134/180482694-661eee07-3827-48bc-bcad-8a0c819c671b.png">|<img width="565" alt="Screen Shot 2022-07-21 at 8 38 56 PM" src="https://user-images.githubusercontent.com/68251134/180482800-5158f511-ba1c-4886-9e64-b7374e7aedfb.png">  |
| <img width="663" alt="Screen Shot 2022-07-22 at 9 17 27 AM" src="https://user-images.githubusercontent.com/68251134/180483044-817e7e23-f561-4b39-b551-ed30e0a98964.png">  | <img width="605" alt="Screen Shot 2022-07-21 at 8 39 35 PM" src="https://user-images.githubusercontent.com/68251134/180483108-0f70 …
=> chore: Update StepperField disabled buttons style

packages/react-native/src/InAppMessaging/hooks/useMessageImage/useMessageImage.ts, packages/react/src/components/InAppMessaging/hooks/index.ts, packages/react/src/components/InAppMessaging/hooks/useMessageImage/__tests__/useMessageImage.spec.ts, packages/react/src/components/InAppMessaging/hooks/useMessageImage/index.ts, packages/react/src/components/InAppMessaging/hooks/useMessageImage/types.ts, packages/react/src/components/InAppMessaging/hooks/useMessageImage/useMessageImage.ts
Add React Web `useMessageImage` hook for prefetching message images
- remove an unused enum value in the React Native version
- align the docs between the React Native and React Web versions
NA
Manually tested in sample app
=> feat(in-app-messaging): add React web useMessageImage

.changeset/eighty-snails-push.md, docs/src/pages/[platform]/components/pagination/react.mdx, packages/react/src/primitives/Pagination/PaginationItem.tsx, packages/react/src/primitives/Pagination/__tests__/Pagination.test.tsx, packages/react/src/primitives/shared/constants.ts
Fixes: https://github.com/aws-amplify/amplify-ui/issues/1982
To improve the accessibility of the Pagination component:
- current item button is focusable
- screenreader announces if the item is current or not
https://user-images.githubusercontent.com/48109584/180571531-8cb72f58-70c6-4fbf-bb77-2ab775f5a9d0.mov
https://github.com/aws-amplify/amplify-ui/issues/1982
Ran the docs locally and used a screen reader. 
=> fix(ui-react): Pagination current item a11y

packages/react-native/package.json, yarn.lock
Downgrade `@types/react-test-renderer` in _@aws-amplify/ui-react-native_. The previous version was pulling `@types/react@18.x` which was causing linting issues with `xstate`
NA
`yarn react lint && yarn react test`
=> fix(in-app-messaging): downgrade @types/react-test-renderer in ui-react-native

packages/react/src/components/InAppMessaging/CloseIconButton/CloseIconButton.tsx, packages/react/src/components/InAppMessaging/CloseIconButton/__tests__/CloseIconButton.spec.tsx, packages/react/src/components/InAppMessaging/CloseIconButton/index.ts, packages/react/src/components/InAppMessaging/CloseIconButton/types.ts, packages/react/src/primitives/Icon/icons/IconClose.tsx
This PR adds a CloseIconButton component to be used by the In-App Messaging feature.
Tested with a local app and yarn test
=> feat(react): add close button component for In-App Messaging

.github/workflows/reusable-e2e.yml
Previously in #1174, we added `--no-lockfile` to `yarn install` commands to test against latest dependency. 
But this has been problematic because:
- this creates discrepancy between local dev environment and the ci/cd environment, 
- ci/cd has been breaking to different hoisting structures ([example](https://github.com/aws-amplify/amplify-ui/runs/7548985338?check_suite_focus=true))
Also updates `reusable-e2e` test to use `install-with-retries` action that I created previously.
=> ci: remove `--no-lockfile` flag in e2e test

docs/src/components/home/HomeEditor.tsx
There is an issue in the "Take it for a test drive" example on the [UI Docs homepage](https://ui.docs.amplify.aws/) where the live code editor wasn't working. 
To fix:
- Removed the `onChange` event handler and put the click tracking logic inside of `onKeyDown`
Ran the docs locally
=> fix(docs): Fix UI docs homepage editor interactivity

.changeset/gorgeous-pumas-cheat.md, packages/ui/src/theme/css/component/textArea.scss
Fixes: #2173 
This change fixes an issue where TextAreaField does not show line breaks properly in Firefox.
#2173 
Ran docs locally and validated in Firefox.
=> fix(ui-react): Textarea new line in Firefox

packages/react/src/components/Authenticator/hooks/useAuthenticator/index.tsx
Disable linting for the `_state` return value of `useAuthenticator` due to 1) it's deprecated and will be removed 2) fixing the typing is currently out of scope (and `_state` will be removed eventually)
NA
=> fix(in-app-messaging): turn off linting for useAuthenticator._state

.changeset/popular-bats-glow.md, packages/react/src/primitives/Alert/Alert.tsx, packages/react/src/primitives/Alert/AlertIcon.tsx, packages/react/src/primitives/Alert/__tests__/Alert.test.tsx
This change hides decorative alert icons such that redundant text is not announced by screen readers.
N/A
Deployed docs locally and added unit test.
=> fix(ui-react): Hide decorative alert icons from screen readers

canary/apps/react/vite3/package.json, canary/apps/react/vite3/waitOnConfig.json, canary/apps/vue/vite3/waitOnConfig.json
After the recent changes to the canary, we need a new waitOnConfig file to be in the directory for it to run correctly.
=> fix: Fix Canary Build

.changeset/wise-terms-travel.md, packages/react/src/primitives/Heading/Heading.tsx, packages/react/src/primitives/Heading/__tests__/Heading.test.tsx, packages/ui/src/theme/css/component/heading.scss
This PR fixes an issue where the `isTruncated` prop of the `<Heading />` component was not properly applying a truncation.
Tested locally in a sample app and `yarn test`
=> fix: allow heading truncation

examples/angular/package.json, examples/vue/package.json, yarn.lock
Point Vue example App `aws-amplify` version to `in-app-messaging`
NA
Ran e2e tests locally
=> fix(in-app-messaging): point vue example at in-app amplify tagged version

docs/package.json, docs/src/components/InstallScripts.tsx, docs/src/components/home/sections/CompatibleSection.tsx, yarn.lock
This PR enables linting in `docs`, which I assume we were unintentionally skipping. Also fixes linting errors that were found after so.
For quite some time, `yarn docs lint` hasn't been running. This was because `docs` was looking at incompatible version of `eslint` that was in the monorepo root, and `next` silently skipped lint.
This PR explicitly defines `eslint` as devDependency on `docs` so that we do not implicitly depend on which version of `eslint` is at the monorepo root.
e2e test now runs `yarn lint`. 
=> chore: enable lint on docs

packages/react/__tests__/exports.ts, packages/react/scripts/generatePrimitiveCatalog.ts
This removes the internally used primitives.json output which represents the Primitive properties for Studio. This file is no longer being used by the UI Builder team; they have migrated over to the ES Module internal export.
N/A
```
// Build a tarball
cd packages/react
npm pack
// navigate to Studio app and tests the import
npm install [tarball path]
npm start
```
=> chore: remove unneeded internal primitives.json output

packages/e2e/features/ui/components/authenticator/sign-in-totp-mfa.feature
This intercepts and mocks `Auth.signUp` call in totp-mfa test. 
=> fix(e2e): mock Auth.signUp call in totp test

packages/react-core/src/InAppMessaging/types.ts, packages/react/src/components/InAppMessaging/BannerMessage/BannerMessage.tsx
This PR fixes react linting issues on `BannerMeessage.tsx` file.
`yarn react lint` was failing ([workflow](https://github.com/aws-amplify/amplify-ui/runs/7661680933?check_suite_focus=true)) on `in-app-messaging/main` because 
1. `BannerMessage` was not explicitly typed and could not infer which fields are optional (see [workflow](https://github.com/aws-amplify/amplify-ui/runs/7661680933?check_suite_focus=true)),
2. `BannerMessageCommonProps` was missing `alignment` type, and
3. `BannerMessage` was missing `import React from 'react';`
=> fix(in-app-messaging): Strictly type BannerMessage

docs/package.json, examples/next/package.json, yarn.lock
This pins `@types/react` to `17.0.47` in next.js apps, because next.js@11 is incompatible with latest `@types/react@17.0.48`.
See minimal repro: 
- `@types/react@17.0.48` — [fails](https://codesandbox.io/s/next11-with-types-react-17-0-48-vq5fhr?file=/README.md)
- `@types/react@17.0.47` — [works](https://codesandbox.io/s/next11-with-types-react-17-0-47-dgrzuv?file=/README.md)
This has happened a few times before in https://github.com/vercel/next.js/issues/36085 and https://github.com/vercel/next.js/issues/36106, but the fix has been onto `next.js@12` and not 11. We can merge this until we upgrade to better supported version.
=> deps: pin @types/react to 17.0.47 in next apps

packages/react/package.json, packages/react/tsconfig.json, packages/ui/package.json, yarn.lock
Add `tslib` as hard dependency in both react and ui package so that it will not be included in the bundle but instead it will get pulled down from npm when users install the react/ui package.
This will fix the weird CI issue where `tslib` is unable to be resolved correctly
=> fix: add tslib as hard dependency in react and ui package

docs/src/pages/[platform]/connected-components/geo/fragments/margin-reset.react.mdx, docs/src/pages/[platform]/connected-components/geo/react.mdx
When using the `<MapView>` component, the map will sometimes not take up the entire viewport of the browser and the attribution footer will be cut off. To address this, users will need to reset the default `body` CSS margins. This pull request adds an info callout to reset css `body` margins.
N/A
=> docs: Add callout for MapView margin reset

docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx
The link in the configuration sign up attributes points to the configuration section. This should point to the customization section, otherwise the link does not work after clicking it.
Manually
=> fix(docs): Update sign up fields link

.changeset/weak-pillows-dream.md, packages/angular/projects/ui-angular/src/lib/primitives/error/error.component.html, packages/vue/src/components/primitives/__tests__/base-alert.spec.ts, packages/vue/src/components/primitives/base-alert.vue
This change hides decorative alert icons such that redundant text is not announced by screen readers.
N/A
=> fix(ui-angular + ui-vue): Hide decorative alert icons from screen readers

packages/react/src/components/Authenticator/hooks/useAuthenticator/index.tsx
Disable linting for the `_state` return value of `useAuthenticator` due to 1) it's deprecated and will be removed 2) fixing the typing is currently out of scope (and `_state` will be removed eventually)
NA
=> fix(ui-react-native): turn off linting for useAuthenticator._state

packages/react-core/src/InAppMessaging/types.ts, packages/react/src/components/InAppMessaging/BannerMessage/BannerMessage.tsx, packages/react/src/components/InAppMessaging/BannerMessage/index.ts, packages/react/src/components/InAppMessaging/BannerMessage/types.ts, packages/react/src/components/InAppMessaging/FullScreenMessage/index.ts, packages/react/src/components/InAppMessaging/InAppMessageDisplay/types.ts
Updates the typing of the React web `BannerMessage` to follow patterns used by other In-App Messaging components, in addition move `alignment` prop to React web only (does not exist in React Native component)
NA
`yarn react lint && yarn build`
=> chore(in-app-messaging): update React web BannerMessage typing

examples/next/pages/ui/components/in-app-messaging/demo/aws-exports.js, examples/next/pages/ui/components/in-app-messaging/demo/index.page.tsx, examples/next/pages/ui/components/in-app-messaging/demo/utils.ts
Add base NextJS In-App demo app for local testing and (non-documentation example) e2e testing
NA
=> feat(in-app-messaging): add NextJS demo app

.changeset/fast-mirrors-talk.md, docs/src/pages/[platform]/components/searchfield/examples/SearchFieldThemeExample.tsx, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/searchField.scss, packages/ui/src/theme/tokens/components/searchField.ts
Adding design token for  SearchField button so that it can be customized. Docs example is updated to showcase usage:
Fixes #2412 
=> fix(ui-react): Add base bg color for the SearchField component button

.changeset/early-beans-build.md, docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx, packages/angular/projects/ui-angular/package.json, packages/ui/package.json, yarn.lock
Bumping xstate to 4.33.0, which contains https://github.com/statelyai/xstate/pull/3126 that fixes https://github.com/aws-amplify/amplify-ui/issues/764.
#764
Build and e2e tests passing. This is not really a change in customer's end, because we pointed to latest `xstate` anyway.
=> chore(ui): Bump xstate to ^4.33.0

.github/workflows/test-in-app-messaging.yml
This adjusts `test-in-app-messaging.yml` to reference the reusable e2e file with absolute path. This is generally considered safer when combined with `pull_request_target`. 
(To be precise, it doens't change the threat model in this case because `in-app-messaging/main` is protected and only maintainers can push onto it, but it's a good practice).
This only changes the path so I'm comfortable with manually verifying after merge.
=> ci(in-app-messaging): use absolute path to reference reusable workflow

docs/src/data/links.tsx, docs/src/pages/[platform]/connected-components/authenticator/headless/headless-usage.flutter.mdx
Remove "Headless Usage" Page from Flutter, since it doesn't exist.
|  Before  | After  |
|---|---|
| ![image](https://user-images.githubusercontent.com/11983489/183782373-156a217e-eebc-4c0e-a3c1-a24a9ed15a6d.png) | ![image](https://user-images.githubusercontent.com/11983489/183782398-9159f6b9-759f-4f4a-b364-b75438fcefb0.png)  |
- Verified in local. See the screenshot above
- Manually checked sitemap which is not affact
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202729371496839
=> fix: remove headless usage page from flutter

.github/workflows/test-in-app-messaging-prs.yml
Sets up `in-app-messaging` PR CI tests to run the workflow on `@in-app-messaging/main`, instead of one in `main`.
This **only** affects workflows related to in-app-messaging.
`in-app-messaging/main` has updated version of CI tests because it tests for `react-native` and `react-core` in addition to preexisting packages.
Now that its CI has diverged, we want to ensure the tests against `in-app-messaging` branches uses the new one.
=> ci: Handle `in-app-messaging` PR tests separately

docs/src/components/Demo.tsx
Remove props tab in demo control panel to reduce unneeded noise for SR users and keyboard users. We can add it back in once we have a theme section
=> docs: remove tab in props control panel

package.json, packages/react-native/src/InAppMessaging/components/CarouselMessage/__tests__/CarouselMessageItem.spec.tsx, packages/react-native/src/InAppMessaging/components/MessageWrapper/__tests__/MessageWrapper.spec.tsx, packages/react-native/src/__mocks__/react-native-safe-area-context.ts, packages/react-native/src/primitives/Carousel/__tests__/CarouselPageIndicator.spec.tsx, packages/react/__tests__/__snapshots__/exports.ts.snap
- add `react-native-safe-area-context` mock, remove individual mocks
- add `yarn react-core test` and `yarn react-native test` to `yarn test`
- update the exports snapshot in _@aws-amplify/ui-react_
NA
`yarn test`
=> fix(in-app-messaging): resolve issues blocking CI

docs/src/components/Fragment.tsx
=> fix(docs): type error on fragment

.changeset/clean-suns-fix.md, packages/ui/src/machines/authenticator/actors/resetPassword.ts, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/ui/src/machines/authenticator/actors/signOut.ts, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/machines/authenticator/signUp.ts
This was **not** meant to be merged. Reverting, apologies for the inconvenience.
=> Revert "chore(ui): Set `predictableActionArguments` to true"

examples/next/pages/ui/components/in-app-messaging/override-styling/aws-exports.js, examples/next/pages/ui/components/in-app-messaging/override-styling/index.page.tsx, examples/react-native/App.tsx, packages/react-core/src/InAppMessaging/hooks/useMessage/__tests__/useMessage.spec.ts, packages/react-core/src/InAppMessaging/hooks/useMessage/types.ts, packages/react-core/src/InAppMessaging/hooks/useMessage/useMessage.ts, packages/react-native/src/InAppMessaging/components/InAppMessageDisplay/InAppMessageDisplay.tsx, packages/react-native/src/InAppMessaging/components/InAppMessageDisplay/index.ts, packages/react-native/src/InAppMessaging/components/InAppMessageDisplay/types.ts, packages/react-native/src/InAppMessaging/components/index.ts, packages/react-native/src/InAppMessaging/components/withInAppMessaging/withInAppMessaging.tsx, packages/react-native/src/InAppMessaging/index.ts, packages/react-native/src/__tests__/__snapshots__/index.spec.ts.snap, packages/react-native/src/__tests__/index.spec.ts, packages/react-native/src/index.ts, packages/react/__tests__/exports.ts, packages/react/src/components/InAppMessaging/InAppMessageDisplay/InAppMessageDisplay.tsx, packages/react/src/components/InAppMessaging/InAppMessageDisplay/index.ts, packages/react/src/components/InAppMessaging/InAppMessageDisplay/types.ts, packages/react/src/components/InAppMessaging/index.ts, packages/react/src/components/InAppMessaging/withInAppMessaging/withInAppMessaging.tsx
- remove `styles` prop from `InAppMessageDisplay` components and related types
- add InApp components as properties of `inAppMessageDisplay` components
- add "exports" snapshot test for `@aws-amplify/ui-react-native`
- add NextJS example app for custom styling of InApp UI components
NA
=> feat(in-app-messaging): remove styles prop from InAppMessageDisplay

amplify.yml
Cypress binary installation is unnecessary for docs hosting. Skipping it with `CYPRESS_INSTALL_BINARY=0`.
https://docs.cypress.io/guides/references/advanced-installation#Environment-variables
Built docs locally after running that command. 
=> chore(hosting): Skip cypress binary installation

.changeset/gold-tips-punch.md, packages/react/src/components/Authenticator/shared/FormField.tsx
Update the react authenticator component to use the dialCode props instead of the countryCode versions.
This is part of the effort being made to deprecate all of the countryCode props and migrate over to dialCode instead.  The dialCode props were added in this [PR](https://github.com/aws-amplify/amplify-ui/pull/2459) alongside the countryCode props.  Currently either prop can be used and if both are provided the dialCode versions will be preferred.
=> update authenticator to use the new dial code props

.github/workflows/publish-next.yml, .github/workflows/reusable-e2e.yml
Instead of running `yarn environments pull` to pull all environments altogether, this PR splits them off to just pull the environments they need (`auth`, `datastore`,  or `geo`).
#2517 is running e2e + guide test. I disabled cache this time 😅 
- e2e: [workflow](https://github.com/aws-amplify/amplify-ui/runs/8022933916)
- guides: [workflow](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-test-guide.yml)
=> chore(ci): split `yarn environment pull` call in workflows 

.changeset/brave-emus-ring.md, packages/react/src/primitives/PhoneNumberField/PhoneNumberField.tsx
Removing the deprecation console warning from the countryCode props usage.  The countryCode props are being deprecated but because these props are used in the UI Builder phoneNumberField the deprecation message is being removed to give UI Builder a chance to migrate over to the dialCode props.
=> remove deprecation console warning from countryCodeSelect usage

docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.react.mdx
Fixes a broken link on the React Authenticator [Headless Usage](https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#authenticator-provider) page in the 'Authenticator Provider' section.
Fixes: https://github.com/aws-amplify/amplify-ui/issues/2531
https://github.com/aws-amplify/amplify-ui/issues/2531
=> fix(docs): Broken Authenticator link

.changeset/gentle-ads-hang.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-in/confirm-sign-in.component.ts, packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/ui/src/machines/authenticator/defaultServices.ts, packages/ui/src/types/authenticator/stateMachine/context.ts, packages/ui/src/types/authenticator/user.ts, packages/ui/src/types/authenticator/validator.ts, packages/vue/src/components/confirm-sign-in.vue
Replace `AuthChallengeNames` enum with `AuthChallengeName` string union (set to the value of Cognito supplied `ChallengeName`) to prevent type conflicts between `CognitoUserAmplify['challengeName']` and usage of `AuthChallengeName` in utils
Additionally, added some typed `challengeName` utils in _packages/ui/src/machines/authenticator/actors/signIn.ts_
NA
=> chore(rwa): convert AuthChallengeNames enum to string union

examples/vue/package.json, examples/vue/src/pages/ui/components/authenticator/custom-sign-up-fields/index.vue, examples/vue/src/pages/ui/components/authenticator/custom-slots/index.vue, examples/vue/src/pages/ui/components/authenticator/modal/index.vue, examples/vue/src/pages/ui/components/authenticator/reset-password/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-federated/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-totp-mfa/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-username/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-attributes/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-email-lambda/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-phone/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-username/index.vue, examples/vue/src/pages/ui/components/authenticator/useAuthenticator/index.vue, examples/vue/tsconfig.json, package.json, packages/vue/package.json, packages/vue/vite.config.ts, yarn.lock
After upgrading two issues were found:
1. `rollup` versions were incompatible between root package and version required by vue build. ViteJS requires the following version of rollup:
```
rollup “>=2.59.0 <2.78.0"
```
The root `rollup` version was upgraded to `2.79.0`
Here's the build error I'm getting:
```
@aws-amplify/ui-vue:build: vite.config.ts(21,5): error TS2322: Type 'Plugin' is not assignable to type 'PluginOption'.
@aws-amplify/ui-vue:build:   Type 'import("/Users/reesscot/amplify-ui/node_modules/rollup/dist/rollup").Plugin' is not assignable to type 'import("/Users/reesscot/amplify-ui/node_modules/vite/dist/node/index").Plugin'.
@aws-amplify/ui-vue:build:     Types of property 'resolveId' are incompatible.
@aws-amplify/ui-vue:build:       Type 'ObjectHook<(this: PluginContext, …
```
=> chore: update yarn.lock file

.github/workflows/publish-latest.yml, .github/workflows/version-packages.yml
We have two environments for GitHub Actions workflow: `CI`, and `deployment`. 
- `CI` holds secrets that are required to run e2e tests, and 
- `deployments` holds secrets related to publishing.
This PR cleans up the environment usage so that workflow references the correct environment, and only when they need it.
This also fixes a problem where `NPM_TOKEN` was duplicated between the two environments. Going onward, we will only rely on `deployment` environment to get `NPM_TOKEN` and remove the duplicated one on `CI`.
=> chore(ci): cleanup environment secrets 

canary/apps/angular/angularcli/package.json, canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, canary/apps/react/next/package.json, canary/apps/vue/vuecli/package.json
Canary Build tests are failing with following errors:
```
Cannot find module 'caniuse-lite/data/features/css-unicode-bidi'
```
and
```
Error: Cannot find module 'autoprefixer'
```
```bash
cd canary
yarn install
yarn build
```
=> Fix canary builds due to NPMJS errors

.changeset/pretty-insects-push.md, packages/angular/projects/ui-angular/package.json, packages/ui/package.json, packages/ui/src/machines/authenticator/actors/resetPassword.ts, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/ui/src/machines/authenticator/actors/signOut.ts, packages/ui/src/machines/authenticator/index.ts, packages/ui/src/machines/authenticator/signUp.ts, yarn.lock
This sets `predictableActionArugments` to `true`, as [suggested](https://xstate.js.org/docs/guides/actions.html) in  `xstate@4.33.0+`:
> It is advised to configure predictableActionArguments: true at the top-level of your machine config.
We tried this in #2468, but we found some regressions with Authenticator usages. Xstate has resolved them now:
- https://github.com/statelyai/xstate/pull/3563
- https://github.com/statelyai/xstate/pull/3549 
- https://github.com/statelyai/xstate/pull/3541
See previous PR for technical details: #2468.
E2e test passing this time.
It's worth noting that we have some code that does not follow the best practices (https://github.com/statelyai/xstate/issues/3533#issuecomment-1220663584). That'll be a separate refactor task, but will help prevent these problems …
=> chore(xstate): Set predictableActionArguments to true

canary/apps/angular/angularcli/package.json, canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, canary/apps/react/next/package.json, canary/apps/vue/vuecli/package.json
This reverts commit 82314481220c896533010f03c40aa15675c7b498.
This revert's yesterday's fix now that the issue has been resolved:
https://github.com/browserslist/caniuse-lite/issues/102
=> Revert "Fix canary builds due to NPMJS errors (#2574)"

docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx
Fix broken links on Migration pages for React/Vue/Angular.
Fixes https://github.com/aws-amplify/amplify-ui/issues/2585
ran `yarn docs dev` and smoke tested migration page
=> chore: reorganize migration guides and fix broken link

.changeset/rich-geckos-remain.md, package.json, packages/react/src/components/Authenticator/withAuthenticator.tsx, yarn.lock
Update `withAuthenticator` typing to allow more flexibility in `Component` argument and expose HOC `props` for render props pattern
- in `withAuthenticator` generic `Props` param, replace `extend object` with a default value of `{}` to closer align with React internal typing patterns
- create `AuthenticatorHOCProps` utility type, use to type render `props` passed to `Component` param
- replace `Component` typing of `(props: Props) => JSX.Element` to more flexible `React.ComponentType` to prevent type errors when user defined `Component` arg is typed as a `React.FC` or is a `Class` component
- add `@types/react@17.0.47` to _package.json_ resolutions due to a conflict between `React.ReactNode` in `@types/react@17` and `@types/react@18` ([more info …
=> fix(ui-react): update withAuthenticator typing

canary/apps/react/cra/package.json
The latest release of `aws-amplify`, v4.3.36, introduced a small package size increase, causing our Create React App canary size-limit check to fail. This pull request increases the package size limit for the CRA canary in order to unblock the Amplify UI release.
In the `canary/apps/react/cra` canary, run `yarn && yarn build` and verify that the final `size-limit` check passes.
=> chore: Increase size limit for CRA canary

canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json
The latest release of `aws-amplify`, v4.3.36, introduced a small package size increase, causing our Create React App Typescript canary size-limit check to fail. This pull request increases the package size limit for the cra-ts canary in order to unblock the Amplify UI release.
Related to https://github.com/aws-amplify/amplify-ui/pull/2615
In the `canary/apps/react/cra` canary, run `yarn && yarn build` and verify that the final `size-limit` check passes.
=> chore: increase size limit for cra-ts canary

.github/actions/log-metric/action.yml, .github/workflows/publish-latest.yml, .github/workflows/publish-next.yml, .github/workflows/run-and-test-builds.yml
This PR is one of the steps to migrate Github Workflow related resources from aws-amplify-ui@ to aws-amplify-ui+github-workflows@.
Tested in the PoC workflow https://github.com/aws-amplify/amplify-ui/actions/runs/3095070222/jobs/5009138998
PoC branch https://github.com/aws-amplify/amplify-ui/tree/poc/gh-workflow/metric-logger-cred
=> feat: log metrics to github-workflows account

.github/workflows/poc-test-environments.yml, environments/auth/package.json, environments/datastore/package.json, environments/geo/package.json, environments/pull-environment.sh, environments/pull-environments.sh
Adds three flags to `pull-environments.sh`:
- `-r`: aws region to pull from. Defaults to `us-east-2`.
- `-i`: regex pattern that matches environment folders to pull from. Defaults to all folder in current dir to match prev behavior.
- `-e`: regex pattern that matches environment folders to ignore.
It's worth noting that  won't use these flags directly, and we will instead use `yarn` scripts that abstract those flag usages. 
We used regex over glob because it's really difficult to specify multiple folder with globs (e.g. match `phone-and-sms-mfa` and `phone-number`). 
Admittedly, it is not intuitive to use regex over glob. But IMO this is the simplest solution to filter multiple environments, which is our purpose. Eventually, we can rewrite this script in Node.js so that it's more readable …
=> feat(environments): Add CLI options to pull-environments.sh

.github/workflows/reusable-e2e.yml, packages/react-core/package.json
Build `@aws-amplify/ui-react-core` as a step of the CI workflow
NA
NA
=> chore(rwa): build react-core during CI

customHttp.yml
**issue**: We are seeing 5xx error spikes recently from `/_next/data/...`. The spikes started from 9/06, which is after we introduced `getStaticPaths` and `getCustomStaticPath` in https://github.com/aws-amplify/amplify-ui/pull/2478. which causes pre-render.
**fix**: It may help if we add a cache [ref](https://stackoverflow.com/questions/70317603/nextjs-ssr-getting-next-data-json-requst)
PoC app:
https://cache-control.d3c4lyvg8o1hf2.amplifyapp.com/
=> fix(docs): cache control for entire site

.github/workflows/build-and-runtime-test.yml, .github/workflows/publish-latest.yml, .github/workflows/publish-next.yml
1. `log-metric` action would be skipped if the needed previous action is a failure
It's because the default is `success()` ref: [Github's Docs](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions)
2. the rename in https://github.com/aws-amplify/amplify-ui/pull/2638 forgot to change the workflow's name, so change it in this PR as well.
=> Fix log failure metric

docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/to-federated-sign-in.mdx, docs/src/pages/[platform]/connected-components/authenticator/headless/headless-usage.web.mdx, packages/react/src/components/Authenticator/hooks/useAuthenticator/index.tsx
mark `useAuthenticator.toFederatedSignIn` as deprecated
NA
=> chore(ui-react): mark useAuthenticator.toFederatedSignIn as deprecated

.github/workflows/publish-next.yml
After https://github.com/aws-amplify/amplify-ui/pull/2646, the failed condition triggered, but the data was not logged.
https://github.com/aws-amplify/amplify-ui/actions/runs/3131729913
This PR is to remove the redundant condition.
=> fix(workflow): remove redundant condition

canary/environments/auth-with-email/.gitignore, canary/environments/auth-with-email/amplify/backend/auth/authwithemail/authwithemail-cloudformation-template.yml, canary/environments/auth-with-email/amplify/backend/types/amplify-dependent-resources-ref.d.ts, canary/environments/auth-with-email/amplify/cli.json, canary/environments/auth-with-email/package.json, canary/environments/pull-environments.sh
Migrates auth canary auth environment to the new account.
We should really just remove this canary-specific environment and  consolidate all environments in `environments/` folder. I'll create an internal task for that.
All workflows will be fully tested before fetaure branch is merged.
=> chore(ci): migrate canary auth environment

examples/angular/src/pages/ui/components/authenticator/custom-slots/aws-exports.js, examples/angular/src/pages/ui/components/authenticator/sign-in-totp-mfa/aws-exports.js, examples/next/pages/ui/components/authenticator/custom-slots/aws-exports.js, examples/next/pages/ui/components/authenticator/sign-in-totp-mfa/aws-exports.js, examples/vue/src/pages/ui/components/authenticator/custom-slots/aws-exports.js, examples/vue/src/pages/ui/components/authenticator/sign-in-totp-mfa/aws-exports.js
Previously, we created both `adminui-auth-with-totp-mfa` and `auth-with-totp-mfa` environments, because zero config was unstable back then and there were discrepancies between the two. 
Now these features are stable, and we can migrate away from adminui environments and just use the CLI one. 
I verified that this is the only remnant of `adminui-` environments.
Feature branch will have tests running against it before merge.
=> chore(ci): Migrate away from adminui environments

examples/react-native/storybook/stories/TextField.stories.tsx, examples/react-native/storybook/storyLoader.js, packages/react-native/src/primitives/TextField/TextField.tsx, packages/react-native/src/primitives/TextField/__tests__/TextField.spec.tsx, packages/react-native/src/primitives/TextField/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/react-native/src/primitives/TextField/index.ts, packages/react-native/src/primitives/TextField/styles.ts, packages/react-native/src/primitives/TextField/types.ts, packages/react-native/src/primitives/index.ts
This change adds TextField component:
* base component
* unit test
* storybook
Notes:
* styling, size and variant will be added as follow-up with theming.
* iOS simulator is not bringing up the keyboard, should just be a simulator issue.
Ran Storybook. Tested accessibility with Xcode Accessibility Inspector.
=> feat(ui-react-native): Add TextField component

.github/workflows/publish-next-release.yml
This adds a tagged publish step to `@next-release` on every merge to `next-release/main`. This is analogous to how we publish to `@next` on every merge to `main`.
Copy and pasted the step directly from publish-next workflow
=> ci(next-release): Add publish step to next-release/main

.github/workflows/build-and-runtime-test.yml, .github/workflows/publish-latest.yml, .github/workflows/publish-next.yml, .github/workflows/reusable-e2e.yml, examples/vue/src/pages/ui/components/authenticator/sign-in-federated/index.vue
Bump `actions/cache` to v3, and adds timeout to each cache download steps (new feature in v3).
`actions/cache` currently has a known issue (https://github.com/actions/cache/issues/810) with getting stuck in restoring cache phase. This can lead CI (especially our canaries) to be stuck for at most 6 hours. `actions/cache` team is working on getting this resolved, but meanwhile, they recommend that we add timeouts to our cache restoration steps.
- environment cache (~<1mb): they take at most 1 seconds. Rounded up to 1 min.
- cypress cache (~149mb): they take at most 10 seconds. Rounded up to 1 min.
- `dist/` (~<1mb): they take at most 1 seconds. Rounded up to 1 min.
- `node_modules/` (~728mb): they take at most a minute. Rounded up to 3 mins. We could do 2, but I'm not too concerned about …
=> chore(ci): add timeout to cache downloads

.changeset/small-turkeys-glow.md, packages/ui/src/theme/css/styles.scss
This PR fixes an issue where custom fonts set via the `ThemeProvider` aren't being applied. 
_This doesn't work_
```tsx
const theme: Theme = {
name: 'MyTheme',
tokens: {
fonts: {
default: {
variable: { value: "'Amazon Ember', sans-serif" },
static: { value: "'Amazon Ember', sans-serif" },
},
},
},
};
```
_This does work_
```css
html {
font-family: 'Raleway', sans-serif;
}
```
Fixes https://github.com/aws-amplify/amplify-ui/issues/2762
Using a test Vite app, I overrode the font using theme object and `ThemeProvider`:
```tsx
const theme: Theme = {
name: 'MyTheme',
tokens: {
fonts: {
default: {
variable: { value: "'Amazon Ember', sans-serif" },
static: { value: "'Amazon Ember', sans-serif" },
},
},
},
};
```
Before:
Then used `npm link` to test new version and saw:
After:
By submitting this …
=> fix: issue where theme cannot override default font

.github/workflows/build-and-runtime-test.yml, .github/workflows/publish-latest.yml, .github/workflows/publish-next.yml, .github/workflows/reusable-e2e.yml
Bumps `actions/checkout` to v3, which will get rid of all `Node.js 12` deprecated warnings:
This is a clean version bump. Looking at https://github.com/actions/checkout/releases/tag/v3.0.0, their only breaking change is using Node.js 16 by default. We were running on it anyway, so no changes from our end need to be made.
=> chore(ci): bump `actions/checkout` to V3

.github/workflows/build-and-runtime-test.yml, .github/workflows/publish-latest.yml
Removes erroneous `setup-node` in `publish-latest` scripts.
There was a CI regression in #2789 , where `setup-node` was mistakenly introduced before `checkout`. These `setup-node` there aren't really necessary in these step because:
-  We don't use its [caching](https://github.com/actions/setup-node#caching-global-packages-data) capability
- Actions run on `Node.js` 16 by default now too ([blog](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/)), 
So we are just removing them back.
=> chore(ci): fix `publish-latest` + `build-and-runtime-test`

packages/react-native/src/Authenticator/common/DefaultFooter/__tests__/__snapshots__/DefaultFooter.spec.tsx.snap, packages/react-native/src/Authenticator/common/FederatedProviderButton/__tests__/__snapshots__/FederatedProviderButton.spec.tsx.snap, packages/react-native/src/primitives/Button/Button.tsx, packages/react-native/src/primitives/Button/__tests__/__snapshots__/Button.spec.tsx.snap, packages/react-native/src/primitives/Button/styles.ts, packages/react-native/src/primitives/Button/types.ts, packages/react-native/src/primitives/Tabs/Tab.tsx, packages/react-native/src/primitives/Tabs/__tests__/Tab.spec.tsx, packages/react-native/src/primitives/Tabs/__tests__/Tabs.spec.tsx, packages/react-native/src/primitives/Tabs/__tests__/__snapshots__/Tab.spec.tsx.snap, packages/react-native/src/primitives/Tabs/styles.ts, packages/react-native/src/primitives/Tabs/types.ts
Add a default pressed state style to `Button`
- update unit tests
- add `readonly` prop to `Tab` to prevent opacity change on press of selected `Tab`
- 
NA
Manually tested, updated unit tests
=> chore(ui-react-native): add pressed state style to Button

packages/react-core/src/Authenticator/hooks/useAuthenticator/__tests__/__snapshots__/useAuthenticator.spec.tsx.snap, packages/react-core/src/Authenticator/hooks/useAuthenticator/__tests__/useAuthenticator.spec.tsx, packages/react-core/src/Authenticator/hooks/useAuthenticator/__tests__/utils.spec.tsx, packages/react-core/src/Authenticator/hooks/useAuthenticator/useAuthenticator.tsx, packages/react-core/src/Authenticator/hooks/useAuthenticator/utils.ts
Convert `unverifiedContactMethods` to shape of `AuthenticatorLegacyField` for passing as prop to `VerifyUser` subcomponent
NA
Manually tested, integ and unit tests
=> chore(rna): return unverifiedContactMethods as fields from useAuthenticator

package.json, yarn.lock
To fix a high risk vulnerability in `minimatch < 3.0.5`
`serve` is trying to fix it on their end but for now we will have to use `resolution`. <- https://github.com/vercel/serve/issues/737
=> fix: fix minimatch security vulnerability

.github/workflows/test-next-release-prs.yml
With `next-release/main` containing RN changes now, we need to run react-native unit tests on that branch. 
For that reason, this PR creates a `test-next-release.yml` that runs `reusable-e2e@next-release/main` instead of `reusable-e2e@main`. This is similar to how we have `test-rna.yml`, `test-in-app-messaging.yml`, etc.
=> chore(ci): run react-native tests on next-release

examples/react-native/storybook/stories/RadioGroup.stories.tsx, packages/react-core/src/__tests__/__snapshots__/index.spec.ts.snap, packages/react-core/src/index.ts, packages/react-native/src/primitives/Radio/Radio.tsx, packages/react-native/src/primitives/Radio/__tests__/__snapshots__/Radio.spec.tsx.snap, packages/react-native/src/primitives/RadioGroup/RadioGroup.tsx, packages/react-native/src/primitives/RadioGroup/__tests__/RadioGroup.spec.tsx, packages/react-native/src/primitives/RadioGroup/__tests__/__snapshots__/RadioGroup.spec.tsx.snap, packages/react-native/src/primitives/RadioGroup/types.ts
Add `RadioGroup` uncontrolled support
NA
=> feat(ui-react-native): add RadioGroup uncontrolled support

.changeset/cyan-eggs-itch.md, .changeset/strong-tips-mate.md, packages/e2e/cypress/integration/common/geo.ts, packages/e2e/features/ui/components/geo/map-with-location-search.feature, packages/react/package.json, yarn.lock
Upgrade maplibre-gl-js-amplify to v2.1.0 to support getSuggestions and getPlace
Docs PR: https://github.com/aws-amplify/docs/pull/4615
=> chore: upgrade maplibre-gl-js-amplify to v2.1.0 to support getSuggestions and getPlace

canary/apps/angular/angularcli/src/app/app.module.ts, canary/apps/react/cra-ts/src/App.tsx, canary/apps/react/cra/src/App.js, canary/apps/react/next/pages/index.js, canary/apps/react/vite/src/App.jsx, canary/apps/react/vite3/src/App.tsx, canary/apps/vue/vite/src/App.vue, canary/apps/vue/vuecli/src/App.vue, docs/src/components/home/sections/AuthenticationSection.tsx, examples/angular/src/pages/ui/components/authenticator/custom-sign-up-fields/custom-sign-up-fields.component.ts, examples/angular/src/pages/ui/components/authenticator/custom-slots/custom-slots.component.ts, examples/angular/src/pages/ui/components/authenticator/hub-events/hub-events.component.ts, examples/angular/src/pages/ui/components/authenticator/i18n/i18n.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-federated/sign-in-federated.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-with-email/sign-in-with-email.component.ts, examples/vue/src/pages/ui/components/authenticator/hub-events/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-email/index.vue
This PR updates our code to use named imports instead of default imports to import Amplify JS resources, because Amplify JS is [dropping support](https://github.com/aws-amplify/amplify-js/pull/10461) for default imports/exports.
Ran `yarn install` and `yarn build` on canaries locally.
=> chore(next-release): use named imports instead of default imports

docs/src/pages/[platform]/components/heading/demo.tsx
[Heading demo](https://ui.docs.amplify.aws/react/components/heading#demo) is not currently showing initial text or heading level.
**Before**
**After**
=> fix(docs): Heading demo showing initial text/level
