aws-amplify/amplify-ui

README.md
=> Removing FAQ

.github/workflows/tests.yml, docs/src/components/Feature.tsx, docs/src/components/Fragment.tsx
*Issue #, if available:* https://app.asana.com/0/1200334286823427/1200795341338131/f
- Fixes error on https://ui.docs.amplify.aws/ui/components/authenticator?platform=angular
- _See commit messages_
---
=> Add link to Angular examples

packages/vue/src/components/authenticator.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/index.js, packages/vue/src/components/primitives/styles.css, packages/vue/src/components/reset-password.vue, packages/vue/src/components/sign-in.vue, packages/vue/src/defaults/DefaultTexts.ts, packages/vue/src/types/index.ts
*Issue #, if available:* [Asana](https://app.asana.com/0/1200781756632584/1200777224131165/f)
Add a way to reset password for Vue
=> Vue reset password

packages/core/src/machines/actions/auth.ts, packages/core/src/machines/actors/auth/resetPassword.ts, packages/core/src/machines/actors/auth/signIn.ts, packages/core/src/machines/actors/auth/signUp.ts, packages/core/src/types/authMachine.ts
n/a
Move Xstate actions into a separate file for easy reuse across actors.
=> Reusable actions

packages/e2e/features/ui/components/authenticator/verify-user.feature
*Description of changes:* Skipping this test as it was sporadically failing due to service limits.
=> chore(e2e): skip verify-user.feature

packages/angular/projects/ui-angular/src/lib/components/amplify-force-new-password/amplify-force-new-password.component.html, packages/angular/projects/ui-angular/src/lib/components/amplify-force-new-password/amplify-force-new-password.component.ts
*Description of changes:* This reflects changes from #361.
https://user-images.githubusercontent.com/43682783/133348023-1f7dccce-54c8-482a-b9c1-c8e199170e0b.mp4
=> feat(angular): Add confirm password in forceNewPassword screen

docs/src/pages/ui/theme/responsive/react.mdx
=> Fixing responsive docs page

docs/src/pages/ui/primitives/tabs/demo.tsx, docs/src/pages/ui/primitives/tabs/react.mdx, packages/ui/src/theme/css/component/tabs.scss, packages/ui/src/theme/tokens/components/tabs.js
*Description of changes:* @eddiekeller I got you 😉 
=> Removing tab margin

.github/workflows/tests.yml, packages/e2e/cypress/integration/common/sign-in.ts, packages/e2e/cypress/integration/common/sign-up.ts, packages/e2e/cypress/support/commands.ts, packages/react/src/components/Authenticator/shared/SignInSignUpTabs.tsx
=> fix(e2e, react): Fix skipped tests and conditionally render tabs

packages/vue/src/components/confirm-sign-in.vue, packages/vue/src/components/setup-totp.vue
*Issue #, if available:* [Asana](https://app.asana.com/0/1200953035425686/1200953035425684/f)
Updated Vue Styles for Setup TOTP page and Enable MFA Code page
=> Vue: Updated styles for Setup TOTP and Enable MFA Code

packages/vue/src/components/authenticator.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/force-new-password.vue, packages/vue/src/components/sign-up.vue, packages/vue/src/defaults/DefaultTexts.ts
*Issue #, if available:* [Asana](https://app.asana.com/0/1200953035425686/1200953035425684/f)
Added new styles for force new password and confirm reset password page
=> Vue: Force New Password and Confirm Reset Password Page Styles Added

packages/vue/src/components/confirm-verify-user.vue, packages/vue/src/components/verify-user.vue, packages/vue/src/defaults/DefaultTexts.ts
*Issue #, if available:* [Asana](https://app.asana.com/0/1200953035425686/1200953035425684/f)
Added new styles for verify page and confirm verify page
=> Vue: Add styles for Verify and Confirm Verify Page

examples/angular/src/pages/ui/components/authenticator/auth-with-multi-alias/auth-with-multi-alias.component.html, examples/angular/src/pages/ui/components/authenticator/auth-with-multi-alias/auth-with-multi-alias.component.ts, examples/angular/src/pages/ui/components/authenticator/auth-with-translations/auth-with-translations.component.html, examples/angular/src/pages/ui/components/authenticator/auth-with-translations/auth-with-translations.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-federated/sign-in-federated.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-federated/sign-in-federated.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-totp-sms/sign-in-totp-sms.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-totp-sms/sign-in-totp-sms.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-with-email/sign-in-with-email.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-with-email/sign-in-with-email.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-with-phone/sign-in-with-phone.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-with-phone/sign-in-with-phone.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-in-with-username/sign-in-with-username.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-with-username/sign-in-with-username.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.html, examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-up-with-phone/sign-up-with-phone.component.html, examples/angular/src/pages/ui/components/authenticator/sign-up-with-phone/sign-up-with-phone.component.ts, examples/angular/src/pages/ui/components/authenticator/sign-up-with-username/sign-up-with-username.component.html, examples/angular/src/pages/ui/components/authenticator/sign-up-with-username/sign-up-with-username.component.ts, packages/angular/projects/ui-angular/src/lib/components/amplify-authenticator/amplify-authenticator.component.ts, packages/angular/projects/ui-angular/src/lib/services/state-machine.service.ts
Adds `loginMechanism` `@Input` prop to Angular authenticator and updates the examples.
=> Angular loginMechanisms @Input prop

examples/vue/src/pages/ui/components/authenticator/auth-with-multi-alias/index.vue, examples/vue/src/pages/ui/components/authenticator/auth-with-translations/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-federated/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-totp-mfa/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-phone/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-username/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-email/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-phone/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-username/index.vue, packages/vue/src/components/authenticator.vue
*Issue #, if available:* [Asana](https://app.asana.com/0/1201058552570744/1200974176066577/f)
Added new signout interface
=> Added new signOut interface

packages/ui/src/machines/actors/auth/signIn.ts, packages/ui/src/machines/actors/auth/signUp.ts, packages/ui/src/machines/authMachine.ts
https://app.asana.com/0/1201058552570744/1200975648174197/f
Fixing the flash of content when automatically signing in after a successful `confirmSignUp`
=> fixing flash of content on auto sign in

README.md, docs/src/pages/ui/components/authenticator/headless.vue.mdx, docs/src/pages/ui/components/authenticator/index.page.mdx, docs/src/pages/ui/components/authenticator/quick-start.vue.mdx, docs/src/pages/ui/components/authenticator/sign-up-with-email.react.mdx, docs/src/pages/ui/components/authenticator/sign-up-with-email.vue.mdx, docs/src/pages/ui/components/authenticator/sign-up-with-phone.react.mdx, docs/src/pages/ui/components/authenticator/sign-up-with-phone.vue.mdx, docs/src/pages/ui/getting-started/installation/installation.vue.mdx, examples/vue/src/pages/ui/components/authenticator/auth-with-multi-alias/index.vue, examples/vue/src/pages/ui/components/authenticator/auth-with-translations/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-federated/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-totp-mfa/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-phone/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-in-with-username/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-email/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-phone/index.vue, examples/vue/src/pages/ui/components/authenticator/sign-up-with-username/index.vue, yarn.lock
*Issue #, if available:* Cleanup Vue Docs
Clean up Vue Docs
=> Vue Clean Up Docs

packages/react/src/primitives/Button/__tests__/Button.test.tsx
This PR will be adding unit tests for `Button` primitive
=> test: adding unit tests for Button primitive

CONTRIBUTING.md
*Description of changes:* Updates CONTRIBUTING.md with latest dev scripts on each framework.
=> chore: Update CONTRIBUTING.md with latest dev scripts

docs/src/components/Banner.tsx, docs/src/pages/_app.page.tsx, docs/src/pages/ui/getting-started/installation/dependencies.angular.mdx, docs/src/pages/ui/getting-started/installation/dependencies.react.mdx, docs/src/pages/ui/getting-started/installation/dependencies.vue.mdx, docs/src/pages/ui/getting-started/installation/index.page.mdx, docs/src/pages/ui/getting-started/installation/styles.angular.mdx, docs/src/pages/ui/getting-started/installation/styles.react.mdx, docs/src/pages/ui/getting-started/installation/styles.vue.mdx, patches/amplify-docs+2.0.0.patch
> ![localhost_5000_ui_getting-started_installation_platform=react](https://user-images.githubusercontent.com/15182/135300916-d5347dd3-bfac-44cc-b6e1-7c6d1e443b94.png)
=> Document Installation > Styles

docs/src/pages/ui/components/authenticator/quick-start.angular.mdx, packages/angular/projects/ui-angular/ng-package.json, packages/angular/projects/ui-angular/src/lib/components/amplify-sign-up/amplify-sign-up.component.ts
*Description of changes:* Fix minor typos + add component stylesheet to assets.
=> fix(angular): Fix minor typos + add component stylesheet to assets

packages/angular/projects/ui-angular/src/lib/primitives/amplify-form-field/amplify-form-field.component.html, packages/angular/projects/ui-angular/src/lib/primitives/amplify-form-field/amplify-form-field.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/amplify-select/amplify-select.component.html, packages/angular/projects/ui-angular/src/lib/primitives/amplify-select/amplify-select.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/amplify-text-field/amplify-text-field.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/phone-number-field/phone-number-field.component.html, packages/angular/projects/ui-angular/src/lib/primitives/phone-number-field/phone-number-field.component.ts, packages/angular/projects/ui-angular/src/lib/ui-angular.module.ts, yarn.lock
*Description of changes:* Applies #392 to Angular. Created `amplify-phone-number-field` as another budget primitive to abstract this.
=> Add phone number parity style

docs/src/components/Fragment.tsx
See: https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react
=> Fix Angular troubleshooting docs appearing for all platforms

packages/react/src/primitives/shared/styleUtils.ts, packages/react/src/primitives/types/style.ts
This PR introduces two new style properties: `transform` and `textTransform`
=> Add transform/textTransform style props

packages/react/src/primitives/shared/styleUtils.ts, packages/react/src/primitives/types/style.ts
Add a `transformOrigin` style property to <View> derived components
=> Add transformOrigin style property

.changeset/forty-drinks-check.md, packages/react/scripts/generatePrimitivesCatalog.ts
The introduction of the `Primitive` type made impossible for the primitives catalog generator to infer any prop type (they were all defaulted to `any`). This PR fixes the primitives JSON catalog generator, also simplifying the output (no enum values).
<details>
<summary>
Click to see the output:
</summary>
```
{
"Alert": {
"properties": {
"id": {
"type": "string"
},
"area": {
"type": "string"
},
"isDisabled": {
"type": "boolean"
},
"className": {
"type": "string"
},
"testId": {
"type": "string"
},
"alignSelf": {
"type": "string"
},
"backgroundColor": {
"type": "string"
},
"border": {
"type": "string"
},
"borderRadius": {
"type": "string"
},
"bottom": {
"type": "string"
},
"boxShadow": {
"type": "string"
},
"color": {
"type": "string"
},
"display": {
"type": …
```
=> Fix primitives catalog

packages/angular/projects/ui-angular/src/lib/primitives/amplify-error/amplify-error.component.html, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/SignUp/FormFields.tsx, packages/react/src/primitives/Alert/Alert.tsx, packages/vue/src/components/authenticator-sign-up-form-fields.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/force-new-password.vue, packages/vue/src/components/primitives/base-alert.vue
#233 
Add more accessibility options for alerts and errors.
=> More a11y options for alerts

.prettierignore
*Description of changes:* Add `.changeset` to `.prettierignore`
=> chore: Add `.changeset` to `.prettierignore`

packages/ui/src/theme/css/component/authenticator.scss, packages/vue/src/components/authenticator.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/confirm-sign-in.vue, packages/vue/src/components/confirm-sign-up.vue, packages/vue/src/components/confirm-verify-user.vue, packages/vue/src/components/force-new-password.vue, packages/vue/src/components/reset-password.vue, packages/vue/src/components/setup-totp.vue, packages/vue/src/components/sign-in.vue, packages/vue/src/components/sign-up.vue, packages/vue/src/components/verify-user.vue
#637
Added new slots and cleaned up old slots for all the components.
```
<template>
<authenticator>
<template v-slot:header>
<h1 class="text-center">Authenticator Header</h1>
</template>
<template v-slot:footer>
<h1>Authenticator Footer</h1>
</template>
<template v-slot:sign-in-header>
<h2>Sign In Header</h2>
</template>
<template v-slot:sign-in-footer>
<h2>Sign In Footer</h2>
</template>
<template v-slot="{ user, signOut }">
<h1>Hello {{ user.username }}!</h1>
<button @click="signOut">Sign Out</button>
</template>
</authenticator>
</template>
```
=> Vue: Add new Slots

packages/react/src/components/Authenticator/Router/index.tsx, packages/ui/src/theme/css/component/authenticator.scss
The background color and border is missing from the React UI Authenticator
Added back in styles with wrapper div
New drop shadow box with fixed styles
=> Update react styles

docs/next.config.js, docs/src/components/Layout/FrameworkChooser.tsx, docs/src/components/Layout/Header.tsx
*Description of changes:* Lighthouse score 87 -> 100 on the homepage. Adding accessible labels to buttons in the header and adding language attribute to html element. 
=> Fixing some a11y bugs on docs

docs/src/pages/components/chatbot/chatFulfillment.angular.mdx, docs/src/pages/components/chatbot/chatFulfillment.react.mdx, docs/src/pages/components/chatbot/chatFulfillment.vue.mdx, docs/src/pages/components/chatbot/index.page.mdx, docs/src/pages/components/chatbot/migration.angular.mdx, docs/src/pages/components/chatbot/migration.react.mdx, docs/src/pages/components/chatbot/migration.vue.mdx, docs/src/pages/components/chatbot/usage.angular.mdx, docs/src/pages/components/chatbot/usage.react.mdx, docs/src/pages/components/chatbot/usage.vue.mdx, docs/src/styles/docs/main.scss
*Description of changes:* Adding legacy chatbot docs
https://user-images.githubusercontent.com/321279/141354269-114ff235-f151-431e-8246-4055c745c35c.mp4
=> Adding chatbot docs

packages/react/__tests__/exports.ts, packages/react/src/components/AmplifyProvider/index.tsx, packages/react/src/index.tsx
*Description of changes:* Fixing the issue with the Theme type. Open to suggestions on how to fix this in a better way. 
=> Fixing theme type export

packages/react/package.json, packages/ui/package.json
Fix exports section from our UI/React package.json definitions to handle both ESM/CommonJS cases on import
https://nodejs.org/api/packages.html#conditional-exports
=> Conditional exports: ESM/CommonJS

docs/src/pages/components/alert/AlertPropControls.tsx, docs/src/pages/components/badge/BadgePropControls.tsx, docs/src/styles/docs/main.scss, docs/src/styles/docs/overrides.scss, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/_fieldControl.scss, packages/ui/src/theme/css/component/field.scss, packages/ui/src/theme/css/component/fieldMessages.scss, packages/ui/src/theme/tokens/components/field.js, packages/ui/src/theme/tokens/components/fieldControl.js, packages/ui/src/theme/tokens/components/fieldMessages.js
* Removing 'hacks' in docs CSS to fix some visual issues with fields
* Added explicit tokens for field label, field message, and input color
=> Field style fixes

docs/src/pages/index.page.tsx
=> Updating hosting product card content

packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/tokens/components/link.js
*Description of changes:* Updating the visited link color to the default link color. 
=> Updating visited link color

docs/src/pages/index.page.tsx
=> Add social providers on authenticator homepage sample

docs/src/pages/components/alert/AlertPropControls.tsx, docs/src/pages/components/alert/demo.tsx, docs/src/pages/components/alert/useAlertProps.tsx, packages/react/src/primitives/Alert/Alert.tsx, packages/react/src/primitives/Alert/AlertIcon.tsx, packages/react/src/primitives/Alert/__tests__/Alert.test.tsx, packages/react/src/primitives/shared/constants.ts, packages/react/src/primitives/types/alert.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/alert.scss, packages/ui/src/theme/css/component/heading.scss, packages/ui/src/theme/tokens/components/alert.js
* Added font color tokens to match badge tokens
* Added some BEM classnames to alert innards 
* Added `color: inherit` so the dismiss button would look a bit cleaner
* Added an icon size token and removed the icon size prop (since we don't support size on `<Icon>` anymore)
* Removed `headingLevel` because it didn't really make sense semantically
https://user-images.githubusercontent.com/321279/142162014-6eae0ea2-0d74-4199-9e7a-3061319d0521.mp4
=> updating alert style

docs/src/components/Layout/Footer.tsx
- Update Discord link in Footer.tsx
=> Update Discord link in Footer.tsx

packages/react/scripts/generatePrimitivesCatalog.ts
Improves component props extraction algorithm, including `React.forwardRef` and generic function types (e.g `Collection` / `TextField`)
=> Fix primitives catalog generator

docs/src/styles/docs/example.scss
#746
Added CSS to wrap text in Icon demo
=> Docs: Fix wrapping on Icons Demo Component

.changeset/young-candles-cheer.md
*Description of changes:* Add changeset for Authenticator major bump. I added a placeholder for it for now.
=> Add changeset for Authenticator major bump

.github/workflows/publish-latest.yml, package.json
*Description of changes:* Uncomments publish scripts for @latest 😄 
=> ci: Enable publish to @latest

legacy/aws-amplify-angular/README.md
Port documentation for `aws-amplify-angular` legacy package to `README.md`
=> Port legacy aws-amplify-angular docs

legacy/aws-amplify-vue/README.md
Port legacy `aws-amplify-vue` docs to `README.MD`
=> Port legacy aws-amplify-vue docs

legacy/amplify-ui-react/README.md
Port legacy `@aws-amplify/ui-react@v1` docs to `README.md`
=> Port legacy `@aws-amplify/ui-react@v1` docs

legacy/amplify-ui-angular/README.md
Port legacy amplify-ui-angular v1 docs
=> Port legacy amplify-ui-angular v1 docs

legacy/amplify-ui-vue/README.md
Port legacy Vue web components docs.
=> Port legacy amplify-ui-vue docs

.changeset/nervous-keys-film.md, packages/react/src/primitives/shared/styleUtils.ts, packages/react/src/primitives/types/style.ts
Add a `backgroundImage` style property to Primitives
=> Add backgroundImage style property

docs/src/pages/index.page.tsx
=> Remove @next from the main page

docs/src/pages/components/authenticator/quick-start.vue.mdx, docs/src/pages/getting-started/installation/dependencies.vue.mdx
Updated links to where to find documentation to Vue 2
=> Updated Vue 2 Documentation Links

docs/src/pages/components/chatbot/index.page.mdx, docs/src/pages/components/storage/index.page.mdx
*Description of changes:* Updates the info box on Storage and ChatBot to emphasize `legacy/` path
=> Update web component info box to mention /legacy

docs/src/components/Layout/Header.tsx, docs/src/pages/_app.page.tsx, docs/src/pages/index.page.tsx, docs/src/styles/docs/home.scss
http://localhost:5000/components?platform=vue
=> Mobile-friendly Documentation

docs/src/pages/components/authenticator/quick-start.vue.mdx
Typo in vue quick start for awsconfig.
=> Fixed Vue typo

.changeset/beige-maps-fix.md, packages/react/src/primitives/Button/Button.tsx
Replace `<span>` component with a `<Text as="span">` primitive
=> Use Text primitive for Button loading text

.changeset/spotty-cameras-relax.md, packages/react/src/primitives/Expander/Expander.tsx, packages/react/src/primitives/Expander/ExpanderItem.tsx, packages/react/src/primitives/Table/Table.tsx, packages/react/src/primitives/Table/TableBody.tsx, packages/react/src/primitives/Table/TableCell.tsx, packages/react/src/primitives/Table/TableFoot.tsx, packages/react/src/primitives/Table/TableHead.tsx, packages/react/src/primitives/Table/TableRow.tsx
Add some missing `displayName` property declarations
=> Add missing displayName properties

README.md
=> Remove preview note

docs/src/components/Layout/FrameworkChooser.tsx, docs/src/components/Layout/Header.tsx, docs/src/components/Layout/SecondaryNav.tsx, docs/src/components/Layout/index.tsx, docs/src/styles/docs/header.scss
*Description of changes:* Updating the mobile nav to include the sidebar nav items and settings as well to form a super nav. 
https://user-images.githubusercontent.com/321279/142707264-176d09a2-a52f-45e5-b2ed-35358ff24139.mp4
=> Adding mobile super nav

legacy/amplify-ui-angular/README.md
Update the install path for the legacy angular UI package from to more specific `1.x.x` version. This ensures package.json is updated with semantic version number rather than just `v1`.
=> Update angular legacy docs install cmd

docs/src/pages/index.page.tsx, docs/src/styles/docs/code.scss
*Issue #, if available:* #795
*Description of changes:* Removing the use of the default sandpack theme and creating our own based on the Amplify theme. 
https://user-images.githubusercontent.com/321279/142803622-d38f4339-8c39-481f-b747-126846197627.mp4
=> Updating sandpack colors

.changeset/shiny-beers-guess.md, docs/src/components/StepperFieldPropControls.tsx, docs/src/components/useStepperFieldProps.tsx, docs/src/pages/components/stepperfield/demo.tsx, packages/react/src/primitives/StepperField/StepperField.tsx, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/stepperField.scss, packages/ui/src/theme/tokens/components/stepperField.js
* Updating quiet variation of stepper field to match what is in Figma
* Removing border color for stepper field to match other fields
https://user-images.githubusercontent.com/321279/143096693-ee2caa7b-1ea1-4f8c-b52a-543e15177156.mp4
=> Updating quiet stepper field

.github/workflows/publish-latest.yml, .github/workflows/publish-next.yml
*Description of changes:* Separates out repo environments according to use cases.
=> chore: separate repo environments

packages/react/src/primitives/Collection/Collection.tsx, packages/react/src/primitives/Collection/__tests__/utils.test.ts, packages/react/src/primitives/Collection/utils.ts
Fixes a bug when calculating available pages for a paginated `<Collection>`
=> Fix Collection page count

docs/src/pages/index.page.tsx
#875 
Updated install, so the copy value matches the value shown. 
=> Added in peer dependency install on homepage

.github/CODE_OF_CONDUCT.md, .github/ISSUE_TEMPLATE/1.bug_report.yaml, .github/ISSUE_TEMPLATE/2.feature_request.yaml, CONTRIBUTING.md
Added an issue template for bug report and feature-request that will be presented as a bucket to choose from when customer taps a new issue button on the repo. And added code of conduct! 
=> Issue chooser for UI repo

docs/src/pages/getting-started/installation/index.page.mdx, docs/src/pages/getting-started/installation/troubleshooting.react.mdx
This PR adds troubleshooting information for using our `ui-react` package with [Vite](https://vitejs.dev).
Background:
See https://github.com/aws-amplify/amplify-ui/issues/268
=> Add React / Vite troubleshooting docs

.changeset/eleven-wolves-matter.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.ts, packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts, packages/e2e/features/ui/components/authenticator/sign-up-with-username.feature, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/ui/src/helpers/auth.ts, packages/ui/src/machines/authenticator/actions.ts, packages/ui/src/machines/authenticator/signUp.ts, packages/ui/src/types/authMachine.ts, packages/vue/src/components/authenticator.vue, packages/vue/src/components/confirm-sign-up.vue, packages/vue/src/composables/useUtils.ts
Asana: https://app.asana.com/0/1200334286823427/1201377903144593/f
Update confirm sign up page so it shows where the email was sent to
Email
Phone
No codedelivery details (User is signing in with unconfirmed user)
=> Confirm sign up needs to tell the user where the code has gone to

docs/src/pages/index.page.tsx
*Description of changes:* Updating 'amplify admin' to 'amplify studio' on the homepage. 
=> Updating homepage to use amplify studio

docs/src/pages/components/authenticator/index.page.mdx
*Issue #, if available:* closes #892, https://github.com/aws-amplify/amplify-ui/pull/904#issuecomment-987090224
*Description of changes:* Links troubleshooting from Authenticator docs, as this wasn't very visible and got a [feedback](https://github.com/aws-amplify/amplify-ui/pull/904#issuecomment-987090224) that this should be on Authenticator doc as well.
Preview: https://pr-976.d3inl0muob87le.amplifyapp.com/components/authenticator#quick-start
=> Link troubleshooting guide from Authenticator docs

packages/react/__tests__/exports.ts, packages/react/src/internal.tsx, packages/react/src/primitives/shared/__tests__/utils.test.tsx, packages/react/src/primitives/shared/utils.ts
Adding helper to merge variants with supplied overrides
=> feat: helper to merge variants with overrides

docs/src/pages/components/authenticator/index.page.mdx, docs/src/pages/components/authenticator/overrides/username.angular.mdx, docs/src/pages/components/authenticator/overrides/username.react.mdx, docs/src/pages/components/authenticator/overrides/username.vue.mdx, examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue
#974
Added docs for React/Vue/Angular to override function calls
=> Added docs to override calls

README.md
*Issue #, if available:* #1016
*Description of changes:* Updating the getting started link in the README
=> Fixing broken link in readme

.github/ISSUE_TEMPLATE/1.bug_report.yaml
Often it's important to know what build system a customer is using to reproduce their issue. This PR adds a question about build systems.
=> Add build system question to bug report

.changeset/five-dolls-sing.md, packages/react/tsup.config.js
#1027 
Remove extra ` character
=> Tsup config typo fix

README.md
Update the README component list
=> Update README component list

docs/src/components/Layout/index.tsx
*Issue #, if available:* #1044
*Description of changes:* Making the selector we use to grab the headings more specific.
=> Fixing issue 1044

packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/createTheme.ts
Adding a few line breaks and spaces to make the created theme look nicer
=> chore: formatting theme

packages/ui/src/theme/css/component/text.scss
This reverts commit 754f6a3350908cff63da5a20f046c00a0ed91394.
Reverts "Add white-space (pre-wrap) behavior for Text components"
=> Revert "Add white-space (pre-wrap) behavior for Text components (#1049)"

.changeset/big-ghosts-move.md, packages/react/src/primitives/shared/styleUtils.ts, packages/react/src/primitives/types/style.ts
Add support for `white-space` style property for UI primitives (`whiteSpace`)
=> Add white-space style prop

docs/src/components/Demo.tsx, docs/src/styles/docs/base.scss, docs/src/styles/docs/code.scss
=> Update code colors to be more readable

.github/workflows/publish-next.yml, .github/workflows/tests.yml
*Description of changes:* Allows continuous deployment from `ui-svelte/main` branch to aid testing.
=> Allow continuous deployment from `ui-svelte/main` branch

packages/svelte/LICENSE, packages/svelte/package.json, packages/svelte/src/lib/components/authStore.ts, yarn.lock
`@aws-amplify/ui-svelte@next` gave errors when running. 
This fixes those errors so Svelte sees the folder correctly. 
=> Update @aws-amplify/ui-svelte@next so it installs correctly

.changeset/fifty-rivers-own.md, packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/VerifyUser/ConfirmVerifyUser.tsx, packages/react/src/components/Authenticator/VerifyUser/VerifyUser.tsx
#1070 
Disabled form on submit for sign up, sign in, Confirm Sign In, Confirm Sign Up, Force New Password, Confirm Reset Password, Reset Password, Setup TOTP, Confirm Verify User, and Verify User to match Vue and Angular implementation.
=> Disable form on Submit for React

docs/src/pages/components/phonenumberfield/react.mdx
=> docs: updating 'country' to 'country or region'

docs/src/pages/components/collection/react.mdx
=> updating 'country' to 'regions' in psx example

packages/svelte/src/lib/components/AmplifySignUpFormFields.svelte, packages/svelte/src/lib/components/Authenticator.svelte, packages/svelte/src/lib/components/ConfirmSignUp.svelte, packages/svelte/src/lib/components/SignUp.svelte, packages/svelte/src/lib/components/primitives/AmplifyTabItem.svelte, packages/svelte/src/lib/components/primitives/AmplifyTabs.svelte
Add sign up functionality.
#1144 
=> Added new sign up page for Svelte POC

.changeset/shaggy-vans-watch.md, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx
*Issue #, if available:* 
#1158 
Fixes QR code not showing correctly in QR image. 
=> Fixed error with QR Code

.changeset/orange-pans-occur.md, .changeset/wild-pugs-laugh.md
*Description of changes:* Adds missing changesets
=> Add missing changesets

.changeset/six-dancers-call.md, packages/react/src/components/Authenticator/SignUp/SignUp.tsx
=> Removed hard-coded styles from Authenticator Sign Up button

.changeset/silver-moles-mix.md
*Description of changes:* Follow-up to [PR 826](https://github.com/aws-amplify/amplify-ui/pull/826) to add a changeset for the update to phone number parsing in the Authenticator state machine.
=> Add changeset for phone number parsing in Authenticator state machine

docs/src/data/links.ts, docs/src/pages/components/heading/HeadingPropControls.tsx, docs/src/pages/components/heading/demo.tsx, docs/src/pages/components/heading/examples/DefaultHeadingExample.tsx, docs/src/pages/components/heading/examples/HeadingLevelExample.tsx, docs/src/pages/components/heading/examples/HeadingStylePropsExample.tsx, docs/src/pages/components/heading/examples/index.ts, docs/src/pages/components/heading/index.page.mdx, docs/src/pages/components/heading/react.mdx, docs/src/styles/primitives/headingStyles.css
#933 
This PR will be updating `Heading` docs
=> Docs update - Heading

.changeset/late-trainers-study.md, docs/src/pages/getting-started/installation/index.page.mdx
=> Fixed Docs broken link

.changeset/early-pugs-compete.md, packages/react/src/primitives/Collection/utils.ts, yarn.lock
#1222 
Fixing error in Collection search when `items` prop contains `null` value
=> fix: fixing null value error in Collection search

environments/adminui-auth-with-email-and-phone/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/adminui-auth-with-email-and-phone/amplify/cli.json, environments/adminui-auth-with-totp-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/adminui-auth-with-totp-mfa/amplify/cli.json, environments/auth-with-all-attributes/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-all-attributes/amplify/cli.json, environments/auth-with-email-and-custom-attributes/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-email-and-custom-attributes/amplify/cli.json, environments/auth-with-email-lambda-signup-trigger/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-email-lambda-signup-trigger/amplify/cli.json, environments/auth-with-email/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-email/amplify/cli.json, environments/auth-with-federated/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-federated/amplify/cli.json, environments/auth-with-multi-alias/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-multi-alias/amplify/cli.json, environments/auth-with-phone-and-sms-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-phone-and-sms-mfa/amplify/cli.json, environments/auth-with-phone-number/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-phone-number/amplify/cli.json, environments/auth-with-totp-and-sms-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-totp-and-sms-mfa/amplify/cli.json, environments/auth-with-totp-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-totp-mfa/amplify/cli.json, environments/auth-with-username-no-attributes/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-username-no-attributes/amplify/cli.json, environments/auth-with-username/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth-with-username/amplify/cli.json, environments/cli-auth-with-email-and-phone/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/cli-auth-with-email-and-phone/amplify/cli.json
*Description of changes:* `environments/` aren't up to date with the latest `@aws-amplify/cli`. So when you run `yarn environments pull`, you get a lot of untracked changes. This syync `amplify pull` artifacts with latest CLI behaviors.
=> Commit latest pull artifacts

examples/angular/package.json, examples/next/package.json, examples/vue/package.json, packages/e2e/package.json, packages/react/package.json, packages/ui/package.json, packages/vue/package.json
*Description of changes:* Adds "yarn clean" scripts for applicable workspaces.
Now you can run `yarn clean` at monorepo root to clear `node_modules` and `dist`.
=> add workspace clean command

package.json
*Description of changes:* Now you can run `yarn setup` at monorepo, that does `yarn && yarn build`. 
=> Add `yarn setup` and `yarn refresh` monorepo script

.changeset/four-crews-perform.md, docs/src/pages/components/authenticator/hidesignup.default.angular.mdx, docs/src/pages/components/authenticator/hidesignup.default.react.mdx, docs/src/pages/components/authenticator/hidesignup.default.vue.mdx, docs/src/pages/components/authenticator/index.page.mdx, examples/angular/src/pages/ui/components/authenticator/sign-in-with-email/sign-in-with-email.component.html, examples/next/pages/ui/components/authenticator/sign-in-with-email/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts, packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature, packages/react/src/components/Authenticator/Authenticator.tsx, packages/react/src/components/Authenticator/Router/index.tsx, packages/react/src/components/Authenticator/shared/SignInSignUpTabs.tsx, packages/vue/package.json, packages/vue/src/components/authenticator-sign-up-form-fields.vue, packages/vue/src/components/authenticator.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/confirm-sign-up.vue, packages/vue/src/components/federated-sign-in.vue, packages/vue/src/components/force-new-password.vue, packages/vue/src/components/reset-password.vue, packages/vue/src/components/sign-up.vue, packages/vue/src/composables/useAuth.ts, yarn.lock
#263 
#884 
#1078 
Added new prop to disable sign up
=> Add hide signup

docs/src/pages/components/authenticator/index.page.mdx
*Issue #, if available:* related to #1238
*Description of changes:* This adds missing import statement for using translations.
=> Add missing i18n import

docs/src/pages/components/authenticator/advanced/useAuthenticator.react.mdx
*Description of changes:* true =/= 🌴
=> Fix typo on useAuthenticator docs

package.json
*Description of changes:* `yarn clean` will now clean the root `node_modules`.
=> Update `yarn clean` to remove root `node_modules/`

canary/angular/angularcli/package.json
Bumping `karma` version from ~6.1.0 to ~6.3.14
https://github.com/aws-amplify/amplify-ui/security/dependabot/19
=> chore: bumping karma to ~6.3.14

.changeset/nine-seas-study.md, examples/angular/src/pages/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.component.html, examples/next/pages/ui/components/authenticator/sign-in-sms-mfa/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue, packages/e2e/cypress/fixtures/Auth.currentAuthenticatedUser-sms-mfa.json, packages/e2e/cypress/fixtures/confirm-sign-in-sms-mfa.json, packages/e2e/cypress/integration/common/shared.ts, packages/e2e/features/ui/components/authenticator/sign-in-sms-mfa.feature, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/ui/src/types/authMachine.ts
Fixed issue where MFA/SMS sign in was missing attributes.
#1270 
Feature test with mocks
=> Fixed Issue with MFA/SMS User Attributes

.changeset/smart-peas-return.md, docs/src/styles/docs/base.scss, docs/src/theme.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/styles.scss, packages/ui/src/theme/tokens/components/fieldControl.js, packages/ui/src/theme/tokens/lineHeights.ts
Made line heights for controls (fields and buttons) consistent.
* Removed overrides in the docs messing up the default theme
* Updated the default theme line heights
* Added some simple CSS resets and global styles
Ran the docs site locally:
https://user-images.githubusercontent.com/321279/153547457-ab57099f-bc03-48d6-a4ea-fdc532f3c042.mp4
=> Updating line-heights to be consistent and adding some simple reset

docs/src/components/TableOfContents.tsx, docs/src/styles/docs/toc.scss
Making the table of contents sidebar a bit more compact to save space and show more items. 
=> TOC updates

docs/src/pages/getting-started/installation/dependencies.react.mdx
Fixes typo on: https://ui.docs.amplify.aws/getting-started/installation#packages
```diff
- export default = () => (
+ export default () => (
```
Resolves #1312 
=> Fix default export typo

.changeset/lazy-carrots-impress.md
Delete unneeded docs changeset
=> Delete unneeded docs changeset

.changeset/hip-numbers-lay.md
updating change set file to change patch update to minor update
=> link-to-minor-changeset

packages/ui/src/i18n/dictionaries/authenticator/zh.ts
Update Chinese translation for "Change Password"
=> Change i18n for zh.ts to be more accurate

.changeset/rare-peaches-relax.md, packages/ui/src/theme/css/component/link.scss
=> Lowered priority of visited link style for link component

packages/ui/src/theme/tokens/colors.ts
Adding `overlay` to the `colors` type in the Theme. 
#822
Everything builds
=> Adding color overlay types

.changeset/purple-avocados-taste.md, docs/src/pages/components/authenticator/index.page.mdx, examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.ts, examples/next/pages/ui/components/authenticator/sign-up-with-email/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-up-with-email/index.vue, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.ts, packages/e2e/features/ui/components/authenticator/confirm-sign-up.feature, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/vue/src/components/confirm-sign-up.vue
Confirm Sign Up page did not allow changes to subtitle text. This update will allow more flexibility to translate text around the email address or phone number.
New translations available:
```
Your code is on the way. To log in, enter the code we emailed to
Your code is on the way. To log in, enter the code we texted to
Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.
It may take a minute to arrive.
```
#1182 
Feature Test
=> Added New Translations Confirm Sign Up

.changeset/super-cool-feature.md
Forgot to add a changeset for TextAreaField in my previous PR, this adds it.
=> chore: add changeset for TextAreaField

.changeset/swift-cups-cheat.md, packages/react/src/hooks/useDeprecationWarning.ts
Fixes useDeprecationWarning where `process` is undefined. 
=> hotfix: usedeprecation warning

packages/react/src/hooks/__tests__/useDeprecationWarning.test.tsx
Adding a test to cover process undefined case
Using `!process` will fail the test 
=> test: updating unit test to cover undefined case

package.json
We don't have `yarn ui test` in the test script, so when making a PR, after running `yarn test`, it's very likely to forget to update the snapshots.
So add `yarn ui test` to the `test`.
=> package.json test script add `yarn ui test`

docs/src/pages/components/geo/index.page.mdx
A minor change to initialize the publish action to the `@geo` npm tag.
N/A
N/A
=> Publish to geo tag

.github/changeset-presets/bump-react.md, .github/workflows/publish-geo.yml
Revert changes to package bump in geo publish workflow.
N/A
N/A
=> Revert changes to package bumps in geo workflow

canary/react/next/package.json, package.json
`eslint-plugin-react@7.29.0` has a false positive bug right now: https://github.com/yannickcr/eslint-plugin-react/issues/3215. 
=> Pin eslint-plugin-react to 7.28.0

docs/flutter/authenticator/pubspec.lock, docs/flutter/authenticator/pubspec.yaml
- update flutter authenticator to use v0.1.0 now that it is live.
=> chore: update flutter authenticator to use 0.1.0

packages/e2e/features/ui/components/authenticator/sign-in-totp-mfa.feature
The Cognito error message for invalid totp code has been changed. Updating our e2e test to match the new error message accordingly.
=> Updating totp error message on e2e

packages/react/src/hooks/__tests__/useControllable.test.tsx, packages/react/src/hooks/actions/__tests__/useNavigateAction.test.ts, packages/react/src/primitives/Checkbox/__tests__/Checkbox.test.tsx, packages/react/src/primitives/Icon/Icon.tsx, packages/react/src/primitives/Input/__tests__/Input.test.tsx, packages/react/src/primitives/StepperField/__tests__/StepperField.test.tsx, packages/react/src/primitives/SwitchField/__tests__/SwitchField.test.tsx, packages/react/src/primitives/Table/__tests__/TableRow.test.tsx, packages/react/src/primitives/TextField/__tests__/TextField.test.tsx
This PR cleans up all the unit tests that were causing something to get logged to the console through `console.log`, `console.warn` or `console.error`. 
I ran `yarn test` and confirmed that nothing extraneous is being logged to the console. 
=> Fix console warnings in unit tests

docs/src/components/Layout/Header.tsx, docs/src/components/Layout/LinkButton.tsx, docs/src/components/Layout/SecondaryNav.tsx
**Issue**: Our links are missing `href`.
**Code Change**:
- add `href`
- refactor to use `React.forwardRef` as suggested in [Nextjs's doc](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-functional-component)
- add missing `passHref` prop as suggested in [Nextjs's doc](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag)
- fix `NevLink` type error
- refactor `import` in `Header.tsx` and `LinkButton.tsx` for tree-shaking
https://app.asana.com/0/1201736086077838/1201759796183693/f
- ran `yarn test`
- local test
=> Add href to nav and header links

docs/src/pages/components/authenticator/formfields/qrcode/form-fields.angular.mdx, docs/src/pages/components/authenticator/formfields/qrcode/form-fields.react.mdx, docs/src/pages/components/authenticator/formfields/qrcode/form-fields.vue.mdx, examples/angular/src/pages/ui/components/authenticator/custom-slots/custom-slots.component.ts, examples/next/pages/ui/components/authenticator/custom-slots/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/custom-slots/index.vue
Fixes typo `amlify` -> `amplify`
https://github.com/aws-amplify/amplify-ui/pull/1389#pullrequestreview-898227451
e2e test
=> Fix totpUsername typo

.changeset/fair-days-hide.md, docs/src/pages/components/authenticator/css-variables.mdx, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/authenticator.scss, packages/ui/src/theme/tokens/components/authenticator.js
**Issue**:
This PR centralize authenticator on the example page. 
https://github.com/aws-amplify/amplify-ui/issues/1458
Tested on local
**Docs Web**
https://user-images.githubusercontent.com/11983489/156649300-ebd71c9c-d372-4d15-b0a3-f2e4a1b51bdc.mov
**Docs Mobile**
**Example Web**
https://user-images.githubusercontent.com/11983489/156649487-29d95886-59ba-486d-989d-4d962cf5f557.mov
=> fix authenticator horizontally center for examples

docs/src/pages/components/authenticator/customization.override-function-calls.web.mdx, docs/src/pages/components/authenticator/overrides/username.angular.mdx, docs/src/pages/components/authenticator/overrides/username.react.mdx, docs/src/pages/components/authenticator/overrides/username.vue.mdx
Updated docs to show correct implementation of `handleConfirmSignUp`
#1448 
Validated by looking at docs
=> handleConfirmSignUp is not correct in service override docs

examples/README.md
The environment README path was broken. Fix in this PR.
=> Update example README for environment path

docs/src/pages/getting-started/installation/dependencies.flutter.mdx
Updated dependencies for Flutter
Tested the changes locally using `yarn && yarn build`
- [X ] PR description included
=> Updated dependencies for Flutter

.husky/post-merge
Deleting this hook because in favor of more dev-friendly scripts like `yarn ui dev` and `yarn react dev`. This should remove some unnecessary times spent between git commands.
No actual code changes
=> Delete post-merge husky hook

packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.ts, packages/react/src/components/Authenticator/shared/FormField.tsx, packages/react/src/components/Authenticator/shared/ValidationErrors.tsx, packages/ui/src/helpers/authenticator/form.ts, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/primitives/base-form-field.vue, packages/vue/src/components/sign-up.vue
Creating a separate PR because merge conflicts from #1492 to #1484 was non-trivial.
Now this PR puts validation errors under each `FormField` instead of handling them separately.
Validated manually:
https://user-images.githubusercontent.com/43682783/157737171-c505fef2-6966-4280-a8b3-f59de4771c2b.mp4
=> Resolve conflicts #1492 -> #1484

package.json
=> Pin cssnano-simple to 3.0.0

docs/src/components/Layout/SecondaryNav.tsx, docs/src/pages/getting-started/migration/index.page.mdx, docs/src/pages/getting-started/migration/migration.angular.mdx, docs/src/pages/getting-started/migration/migration.flutter.mdx, docs/src/pages/getting-started/migration/migration.react.mdx, docs/src/pages/getting-started/migration/migration.vue.mdx
Added new migration guides for 1.x to 2.x
[Asana](https://app.asana.com/0/1201952071987914/1200209410233347)
Checked docs
=> Docs: Added Migration Guides 

.changeset/fix-typo.md
chore: add missing changeset for TextField typo
=> chore: add missing changeset for TextField typo

CONTRIBUTING.md
fixes a typo in _CONTRIBUTING.md_ that was preventing a link in the markdown from working correctly
NA
- manually tested
=> fix(docs): fix typo in CONTRIBUTING.md

docs/src/pages/components/ComponentsGrid.tsx
This PR makes the Components page layout a list when viewed on mobile, and a grid when viewed on a larger screen. 
https://github.com/aws-amplify/amplify-ui/issues/1550
=> Responsive Components Page

docs/src/pages/HomePrimitivePreview.tsx, docs/src/pages/index.page.tsx, docs/src/styles/docs/home.scss
Update responsive styling for docs home page
=> Mobile bug fixes

docs/src/pages/index.page.tsx
https://github.com/aws-amplify/amplify-ui/issues/1551
|   | Before  | After   |
|---|---|---|
| button  | ![image](https://user-images.githubusercontent.com/11983489/159093603-221d52ae-4a43-4337-931e-c157aa147d81.png)  | ![image](https://user-images.githubusercontent.com/11983489/159093413-4628f188-417e-4023-b31b-76a4b897f4a1.png)  |
=> fix(docs): authenticator button to full width

docs/src/components/Layout/FrameworkChooser.tsx, docs/src/components/Layout/Header.tsx, docs/src/pages/index.page.tsx, docs/src/styles/docs/header.scss, docs/src/styles/docs/home.scss
Fixes #1549 
Changes:
* Added framework switcher to mobile
* Decrease gutter padding to allow more horizontal space for content
* Hide main logo on mobile, since already in header
* Hide install code copy button on mobile to save horizontal space
Fixes #1549 
* Tested in iOS simulator
=> fix: mobile layout issues

docs/src/pages/components/authenticator/quick-start-intro.flutter.mdx, docs/src/pages/components/authenticator/quick-start-intro.web.mdx
=> Prerequisite typo

docs/src/data/meta.ts, docs/src/pages/_app.page.tsx
Add meta-description and title to every page on docs site
https://app.asana.com/0/1201736086077838/1201759796183699/f
=> chore(docs): add meta description

.changeset/rotten-onions-add.md, docs/src/styles/docs/example.scss, packages/ui/src/theme/css/component/authenticator.scss
| Before  | After  |
|---|---|
| ![image](https://user-images.githubusercontent.com/11983489/160055375-cbf3280d-b9d1-4e6b-a2b8-556fd8ffbffc.png)  | ![](https://user-images.githubusercontent.com/11983489/160055499-8a5dc0b5-0a3b-4708-b8c3-99c554af3c2a.png) |
Root cause: A previous change https://github.com/aws-amplify/amplify-ui/pull/1407/files#diff-97f4cda2e4938c23ff688d6e341da82945259ba351e6d19613873ae6dca77e27R4 should be made only when under `.example`.
=> fix(authenticator): example style

docs/src/data/links.ts, docs/src/data/meta.ts, docs/src/pages/components/geo/fragments/geocoder-position.react.mdx, docs/src/pages/components/geo/fragments/geocoder-quick-start.react.mdx, docs/src/pages/components/geo/fragments/standalone-geocoder.react.mdx, docs/src/pages/components/geo/index.page.mdx, yarn.lock
This Pull Request adds the documentation for `Geocoder` to our feature branch (`feat-geo`) which will be merged to `main` on the date of the scheduled GA release for Geo components. See [PR 1573](https://github.com/aws-amplify/amplify-ui/pull/1573) for the implementation of the `Geocoder` component.
This pull request is part of a series:
- https://github.com/aws-amplify/amplify-ui/pull/1573
- https://github.com/aws-amplify/amplify-ui/pull/1570
- https://github.com/aws-amplify/amplify-ui/pull/1571
- https://github.com/aws-amplify/amplify-ui/pull/1572
This pull request will be part of a series to reduce the amount of changes in each review. Validation includes documentation unit testing.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> feat(geo): Geocoder component documentation

packages/react/src/components/Geo/Geocoder/index.tsx
Add `StandaloneGeocoder` and `ControlledGeocoder` components to prevent conditional React hook calls
NA
- ran integ tests
=> fix(Geocoder): prevent conditional hook calls in Geocoder

.changeset/tasty-hornets-cover.md, examples/next/package.json, packages/react/package.json, yarn.lock
Build errors were happening due to these packages being declared as peerdeps. Moving them to direct dependencies, and pinning them as per our usual dependency runbook.
=> hotfix(react): declare geo dependencies as direct deps

.changeset/brown-berries-design.md, .changeset/heavy-frogs-grow.md, .changeset/nice-dodos-speak.md, .changeset/pretty-needles-float.md, docs/package.json, examples/angular/package.json, examples/next/package.json, examples/vue/package.json, packages/angular/projects/ui-angular/CHANGELOG.md, packages/angular/projects/ui-angular/package.json, packages/e2e/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/ui/CHANGELOG.md, packages/ui/package.json, packages/ui/src/machines/authenticator/actors/signIn.ts, packages/vue/CHANGELOG.md, packages/vue/package.json
Updating Docs as part of the weekly release
=> Release Latest Docs

package.json, yarn.lock
Adding resolution to async package to keep version above 3.2.2
=> add a resolution for async

.github/workflows/tests.yml
=> Skip cache for docs build

docs/src/pages/components/switchfield/examples/SwitchFieldIsCheckedExample.tsx
Fixing bug in `Switch` controlled example
#1704 
=> docs: fixing controlled example bug

.changeset/spicy-pugs-drive.md, packages/react/.gitignore
Add _coverage_ directory to _.gitignore_ of `ui-react`
NA
Ran `yarn react test --collectCoverage`
=> chore(ui-react): add jest generated coverage directory to .gitignore

.changeset/six-seas-join.md, packages/react/package.json, yarn.lock
Update map libre to latest
Based on this security [fix](https://github.com/maplibre/maplibre-gl-js/pull/1135)
=> chore(bump map libre)

.github/workflows/test-deploy-geo.yml, .github/workflows/test-deploy-main.yml
Updating workflow names to be more indicative of what they do.
=> ci: update workflow names

.github/workflows/test-deploy-main.yml
`cd` does not persist between steps, and we have to do this manually with `working-directory`.
=> Update working directory for canary build tests

packages/angular/projects/ui-angular/src/lib/components/authenticator/components/federated-sign-in/federated-sign-in.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.html, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.html, packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts, packages/angular/projects/ui-angular/src/lib/primitives/checkbox/checkbox.component.html, packages/angular/projects/ui-angular/src/lib/primitives/error/error.component.html, packages/angular/projects/ui-angular/src/lib/primitives/select/select.component.html
Updating the angular code to use the flattened css rules
=> flatten angular css

packages/react/src/primitives/Alert/Alert.tsx, packages/react/src/primitives/Badge/Badge.tsx, packages/react/src/primitives/Button/Button.tsx, packages/react/src/primitives/Card/Card.tsx, packages/react/src/primitives/Checkbox/Checkbox.tsx, packages/react/src/primitives/CheckboxField/CheckboxField.tsx, packages/react/src/primitives/Divider/Divider.tsx, packages/react/src/primitives/FieldGroup/FieldGroup.tsx, packages/react/src/primitives/Heading/Heading.tsx, packages/react/src/primitives/Input/Input.tsx, packages/react/src/primitives/Loader/Loader.tsx, packages/react/src/primitives/Menu/MenuButton.tsx, packages/react/src/primitives/Pagination/PaginationItem.tsx, packages/react/src/primitives/Placeholder/Placeholder.tsx, packages/react/src/primitives/Radio/Radio.tsx, packages/react/src/primitives/Rating/Rating.tsx, packages/react/src/primitives/ScrollView/ScrollView.tsx, packages/react/src/primitives/Select/Select.tsx, packages/react/src/primitives/SliderField/SliderField.tsx, packages/react/src/primitives/StepperField/StepperField.tsx, packages/react/src/primitives/SwitchField/SwitchField.tsx, packages/react/src/primitives/Table/Table.tsx, packages/react/src/primitives/Text/Text.tsx, packages/react/src/primitives/TextArea/TextArea.tsx, packages/react/src/primitives/TextField/TextField.tsx, packages/react/src/primitives/ToggleButton/ToggleButton.tsx, packages/react/src/primitives/shared/__tests__/utils.test.tsx, packages/react/src/primitives/shared/constants.ts, packages/react/src/primitives/shared/utils.ts, packages/react/src/primitives/types/select.ts
Update react code to use the flattened css selectors
=> update react code to use the flattened css selectors

.changeset/strange-feet-sleep.md, packages/ui/src/theme/css/component/authenticator.scss
Horizontally center `Authenticator` with `variation= "default"` by adding `display: grid` back to `data-amplify-authenticator` class (was removed in https://github.com/aws-amplify/amplify-ui/pull/1588/files) to 
https://github.com/aws-amplify/amplify-ui/issues/1756
**Before**
**After**
=> fix(authenticator): add display:grid to data-amplify-authenticator class

packages/vue/src/components/alias-control.vue, packages/vue/src/components/confirm-reset-password.vue, packages/vue/src/components/confirm-sign-in.vue, packages/vue/src/components/confirm-sign-up.vue, packages/vue/src/components/confirm-verify-user.vue, packages/vue/src/components/federated-sign-in-button.vue, packages/vue/src/components/federated-sign-in.vue, packages/vue/src/components/force-new-password.vue, packages/vue/src/components/password-control.vue, packages/vue/src/components/primitives/amplify-button.vue, packages/vue/src/components/primitives/amplify-check-box.vue, packages/vue/src/components/primitives/base-alert.vue, packages/vue/src/components/primitives/base-form-field.vue, packages/vue/src/components/primitives/base-heading.vue, packages/vue/src/components/reset-password.vue, packages/vue/src/components/setup-totp.vue, packages/vue/src/components/sign-in.vue, packages/vue/src/components/sign-up.vue, packages/vue/src/components/verify-user.vue
Update Vue code to use the flattened css selectors
=> use flattened css in vue

canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, canary/apps/react/next/package.json, canary/apps/react/vite/package.json
Pointing our `react` and `react-dom` dependencies to `latest` to catch errors that new customers would find.
Done a manual build check against `@next`.
=> chore(canary): Point to latest `react` and `react-dom`

packages/e2e/cypress/integration/ui/components/geo/map-with-geocoder/map-with-geocoder.steps.ts
Fix to our CI tests, since GEO test is failing.
=> Fix: Geo test failing

packages/react/.eslintrc.js
Add `__tests__` to ignored patterns in _.eslintrc.js_
NA
=> fix(ui-react): ignore top level __tests__ directory in eslint config

docs/src/data/meta.ts, docs/src/pages/components/link/examples/LinkStylePropsExample.tsx, docs/src/pages/components/switchfield/examples/SwitchFieldTrackCheckedColorExample.tsx
* Update SEO titles for a number of components
* Fix a bug on SwitchField page where the wrong prop was being used for the `trackCheckedColor` example.
* Update Link primitive prop styling example to use fontSize instead of color, since setting color makes the link not accessible (was removing the hover effect)
* yarn docs dev and checked SwitchField page
=> Misc docs fixes

packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx, packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx, packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ConfirmResetPassword.tsx, packages/react/src/components/Authenticator/ResetPassword/ResetPassword.tsx, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SignIn/SignIn.tsx, packages/react/src/components/Authenticator/SignUp/SignUp.tsx, packages/react/src/components/Authenticator/VerifyUser/ConfirmVerifyUser.tsx, packages/react/src/components/Authenticator/shared/FormField.tsx, packages/react/src/components/Authenticator/shared/FormFields.tsx
Refactor `FormFields` and `FormField` components of `Authenticator`
- replace `route` prop with `route` value from `useAuthenticator` in `FormFields`
- update form field render value in `FormFields`
- flatten `FormFieldProps`, make corresponding updates in `FormField`
NA
Ran integ tests
=> chore(ui-react): refactor Authenticator related FormField and FormFields components

README.md
Not only is this badge outdated, but it's also already shown with checks UI right next to commits on `main`. Removing it to reduce badge clutter.
https://github.com/aws-amplify/amplify-ui/blob/wlee221-patch-2/README.md
=> chore: remove test badge

.github/changeset-presets/bump-react.md
Add `ui-react-core` to _bump-react.md_
NA
NA
=> chore(ui-react-core): add ui-react-core to bump-react.md

.changeset/nice-candles-change.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-totp/setup-totp.component.ts, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SetupTOTP/__tests__/SetupTOTP.test.tsx, packages/vue/src/components/setup-totp.vue
MS Authenticator does not recognize QR codes from the Authenticator
#1837 
Manually tested and Jest test
=> fix: Issue with QR Code not being seen with MS Authenticator

yarn.lock
This updates to latest version of `yarn.lock`
This will help fix the dependabot issues
=> fix: Update to latest yarn.lock

yarn.lock
Build and deploy docs with latest yarn.lock file
=> chore: Release docs

.github/workflows/publish-latest.yml
`publish-latest` needs `contents: write` in order to push tags onto GitHub.
=> fix(ci): add missing permission

packages/react/package.json
Add size checks for Geo component after tree shaking.
`yarn react size`
=> build: add size checks for Geo

.gitignore, package.json, turbo.json, yarn.lock
This PR updates turbo to the newest version and migrates the config to `turbo.json`.
Ran `yarn build` and noted that the build cache was used:
``` 
Tasks:    4 successful, 4 total
Cached:    4 cached, 4 total
Time:    5.263s >>> FULL TURBO
```
=> chore: update turbo version

.changeset/khaki-apes-repeat.md
See https://github.com/aws-amplify/amplify-ui/pull/1863 for details
=> chore: add missing changset

.github/workflows/test-deploy-geo.yml, .github/workflows/test-deploy-main.yml, .github/workflows/test-prs.yml
`SITE_URL` is introduced in https://github.com/aws-amplify/amplify-ui/pull/1871 and we need to add the environment variable first to `main` so that the workflow works properly.
=> chore(github): add SITE_URL to github env

docs/src/pages/components/heading/index.page.mdx, docs/src/pages/components/heading/react.mdx
Small Heading page fixes:
* Update description to be more consistent with other pages.
* Call out the default heading level in the Levels description
* Update CSS example with new Heading util classes
yarn docs dev
=> Heading docs fixes

.github/workflows/test-deploy-studio.yml
Changing the workflow target branch name to `studio-release`. This aligns better with `docs-release` branch we already have.
=> ci: change target branch name to `studio-release`

packages/react-core/tsconfig.dev.json, packages/react-core/tsconfig.json, packages/react/tsconfig.json
Updates for unit testing:
- set _tsconfig.json jsx_ field to `'react'`
- add _tsconfig.dev.json_ for test file TS support
NA
Ran unit tests
=> chore(react-core): set tsconfig.json jsx field to react, add tsconfig.dev.json for test file ts support

packages/react-native/jest.config.js
Add `moduleNameMapper` field in _jest.config.js_ for unit test `React` resolution
NA
Manual testing
=> chore(ui-react-native): add moduleNameMapper field in jest.config.js

.changeset/khaki-numbers-kick.md, packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.html
Add conditional rendering to angular authenticator for authenticated routes
=> don't render authenticator on authenticated routes

.changeset/chenwz-forgot-changeset.md
Add missing changeset for #1922 
=> chore: add missing changeset for #1922

yarn.lock
Update yarn.lock file from latest main. Looks like [this pr](https://github.com/aws-amplify/amplify-ui/pull/1928) put unneeded dependencies back into the repo. I ran `yarn install` and got the following lock changes.
Ran `yarn install`
=> fix: commit yarn.lock file changes

packages/react-core/package.json, yarn.lock
Fix `prebuild` and `clean` commands, remove `react` from devDeps
NA
=> fix(ui-react-core): update prebuild and clean commands, remove react as a devDep

docs/src/components/Layout/FrameworkChooser.tsx, docs/src/pages/[platform]/index.page.tsx
small refactor to have the docs Nav bar and home page icons use `FRAMEWORKS` array constant
manually validated on local
=> chore(docs): use frameworks constants

docs/src/pages/[platform]/components/geo/fragments/map-ref.react.mdx, docs/src/pages/[platform]/components/geo/fragments/use-map.react.mdx, examples/next/pages/ui/components/geo/map-with-forward-ref/aws-exports.js, examples/next/pages/ui/components/geo/map-with-forward-ref/index.page.tsx, examples/next/pages/ui/components/geo/use-map-hook/aws-exports.js, examples/next/pages/ui/components/geo/use-map-hook/index.page.tsx, packages/e2e/cypress/integration/ui/components/geo/native-map-method/native-map-method.steps.ts, packages/e2e/features/ui/components/geo/native-map-method.feature
This PR adds examples and corresponding e2e tests for the examples using native maplibre-gl methods from the Geo docs.
N/A
Manually ran the e2e test suite.
=> feat(e2e): Add end-to-end tests for native maplibre-gl methods

docs/src/data/links.ts
The [main components page](https://ui.docs.amplify.aws/react/components) on the Amplify UI Docs site is missing several component descriptions. This PR is a temporary fix before we eventually refactor everything from `link.ts` to `frontmatter` so that descriptions stay in sync. 
Ran docs locally. 
=> chore(docs): Add missing component descriptions

docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx
This removes the CRA troubleshooting section since https://github.com/visgl/react-map-gl/pull/1872 was merged and released.
=> Revert "Add docs for cra4 troubleshooting (#1919)"

docs/src/pages/[platform]/getting-started/installation/dependencies.flutter.mdx
Flutter version bump to v0.5.0
=> Flutter version bump to v0.5.0

.github/workflows/reusable-e2e.yml, .github/workflows/test-deploy-main.yml, .github/workflows/test-deploy-studio.yml, .github/workflows/test-prs.yml
Add `SITE_URL` secret, which is required to run `yarn docs build` on ci.
=> ci: Add SITE_URL to required secrets

packages/react-core/package.json
Add `react` and `react-dom` to _@aws-amplify/ui-react-core_ devDeps
NA
Manual tested with example app
=> chore(ui-react-core): add react devDeps

docs/src/data/pages.preval.ts, docs/src/utils/getPagesManifest.ts, yarn.lock
Refactor to remove some redundant code for `getPagesManifest`
=> refactor(docs): getPagesManifest move to a separated file

.github/workflows/test-deploy-studio.yml
This is a regression from my reusable workflows pr. `needs` was pointing to an outdated job name.
=> fix(ci): update `needs` on studio release workflow

docs/scripts/generate-sitemap-robotstxt.ts, docs/src/pages/Head.tsx, docs/src/pages/_app.page.tsx, docs/src/utils/getContentPaths.ts, docs/src/utils/getPageFromSlug.ts, docs/src/utils/getPagesManifest.ts
- clean up redundant code in generate-sitemap-robotstxt.ts
- use `FRAMEWORKS` add canonical for homepage 
- move Head to a new file
- refactor times for `getPageFromSlug`, `getContentPaths`, and `getPagesManifest`
=> chore(docs): refactor and clean up docs code

docs/src/pages/[platform]/components/authenticator/sign-up-fields.web.mdx
Updated `Sign Up Form Fields` docs to explain more about why you would want to use it with custom attributes. 
#1478 
Docs Update
=> Fix: Added note about custom attributes

canary/apps/vue/vuecli/package.json
Reverting #2039, as `error-stack-parser` released their fix to `2.1.4+`.
Verified build to work locally.
=> chore(canary): Remove outdated resolution

packages/react/.eslintrc.js, packages/react/package.json, packages/react/src/components/InAppMessaging/InAppMessageDisplay/InAppMessageDisplay.tsx, packages/react/src/components/InAppMessaging/InAppMessageDisplay/__tests__/InAppMessageDisplay.spec.tsx, packages/react/src/components/InAppMessaging/InAppMessageDisplay/__tests__/__snapshots__/InAppMessageDisplay.spec.tsx.snap, packages/react/src/components/InAppMessaging/InAppMessageDisplay/index.ts, packages/react/src/components/InAppMessaging/InAppMessageDisplay/types.ts, packages/react/src/components/InAppMessaging/index.ts, packages/react/src/components/index.ts, packages/react/src/components/index.tsx
Add initial `InAppMessageDisplay` UI component
NA
=> feat(in-app-messaging): add React InAppMessageDisplay

.changeset/wise-falcons-juggle.md, packages/react/.eslintrc.js, packages/react/src/components/ThemeProvider/index.tsx
Update react `ThemeProvider` code to pass linting rules
NA
`yarn lint && yarn test`
=> chore(ui-react): lint components/ThemeProvider directory

docs/src/pages/_app.page.tsx
Move a `@ts-ignore` comment above the line it is ignoring
NA
NA
=> chore(docs): correct placement of ts-ignore statement

yarn.lock
Update yarn lock file after merging https://github.com/aws-amplify/amplify-ui/pull/2082/ with yarn.lock changes. 
Update by running `yarn` on `main` branch.
=> chore: fix yarn lock file

packages/react/.eslintrc.js
Remove exclusion of icons from eslint config after icon removal.
=> chore: remove uneeded icons lint ignore

docs/src/data/links.ts, docs/src/pages/[platform]/getting-started/introduction/index.page.mdx, docs/src/styles/docs/main.scss
Adding the 'Introduction' page to explain our vision for Amplify UI. This page is meant to be framework-agnostic. 
Also fixed the CRA and NextJS pages to not show up on non-react frameworks. 
=> docs: adding introduction page

.github/workflows/test-prs.yml
Enables run-tests on `ui-react@v2` branch.
=> Enable run-tests on `ui-react@v2` branch

docs/src/components/Demo.tsx, docs/src/styles/docs/example.scss
This PR will hide primitive demo on mobile devices
Tested locally with Chrome
=> docs: hide primitive demo on mobile devices

packages/angular/projects/ui-angular/ng-package.json
Point to _aws-amplify@in-app-messaging_ in ui-angular
=> fix(in-app-messaging): point to aws-amplify@in-app-messaging in ui-angular

docs/src/pages/[platform]/components/icon/react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
This PR adds a migration guide for major version 3.0.
=> chore: add migration guide for 3.0

docs/src/pages/[platform]/components/authenticator/customization/customization.headers-and-footers.web.mdx
Extra character was displaying on the Customization page
Manually checked
=> fix: Removed extra < character

packages/angular/README.md, packages/react/README.md, packages/vue/README.md
Update docs site links in READMEs
=> Update docs site links in READMEs

docs/src/pages/[platform]/components/link/LinkPropControls.tsx, docs/src/pages/[platform]/components/link/demo.tsx, docs/src/pages/[platform]/components/link/examples/DefaultLinkExample.tsx, docs/src/pages/[platform]/components/link/examples/ExternalLinkExample.tsx, docs/src/pages/[platform]/components/link/examples/LinkGlobalStylingExample.tsx, docs/src/pages/[platform]/components/link/examples/LinkStylePropsExample.tsx, docs/src/pages/[platform]/components/link/react.mdx, docs/src/pages/[platform]/components/link/useLinkProps.tsx, docs/src/styles/primitives/linkStyles.css
This PR updates the Link docs page. 
**Changes/fixes:**
- Include Global and Local styling examples which demonstrate how to style each of the pseudo-classes (theme example is already included in [this PR](https://github.com/aws-amplify/amplify-ui/pull/2107))
- For the Routing Libraries example, use this code: https://github.com/aws-amplify/amplify-ui/issues/705#issuecomment-1033236546
- Toggling `isExternal` in the main demo shows `undefined` as the children
- For the External Links description, mention that `isExternal` will cause the link to be opened up in a new tab. Also mention `rel=“noopenner noreferrer”`
- Links should all have an `href`, even if it’s just ui.docs.amplify.aws
- External Links and Routing Libraries should be nested under Usage
- Update main demo
- Various nits
Ran …
=> docs(chore): Update Link docs

packages/react/CONTRIBUTING.md
This PR fixes a typo.
`Depenencies` -> `Dependencies`
=> chore: fix typo Depenencies -> Dependencies

.changeset/large-elephants-leap.md, packages/react/src/primitives/types/checkbox.ts, packages/react/src/primitives/types/collection.ts, packages/react/src/primitives/types/heading.ts, packages/react/src/primitives/types/style.ts, packages/react/src/primitives/types/textArea.ts
To help with [MJ's props table PR](https://github.com/aws-amplify/amplify-ui/pull/2090), this PR adds MDN descriptions and links for all of the `BaseStyleProps`, as well as a few other randomly missing prop descriptions. 
=> docs(fix): Add descriptions for BaseStyleProps

docs/src/components/home/sections/AmplifySection.tsx, docs/src/components/home/sections/ThemingSection.tsx, packages/e2e/cypress/integration/ui/theme/theme-selector/theme-selector.steps.ts, packages/e2e/features/ui/theme/theme-selector.feature
Fix integration tests on the new homepage branch
ran `yarn e2e open` and tested the failing tests.
=> chore: fix integration tests on new homepage

.github/workflows/test-prs.yml
Since we need to do a manual pull request to the `studio-release` branch to initiate a release to the `@studio` tag, the branch should be included for the Test / PRs GitHub action.
N/A
N/A
=> chore: Add studio-release to pr target branches for Test / PRs

amplify.yml
This reverts commit 743b4af8cc2bc7f1c6f9593bd7958a21d6602468.
revert temporary change https://github.com/aws-amplify/amplify-ui/pull/2194
=> Revert "chore(docs): amplify.yml temp update to fix build (#2194)"

docs/src/styles/docs/code.scss
Fix stolen from the beta react docs site :P
=> chore(docs): fix horizontal scroll code highlight issue

.github/ISSUE_TEMPLATE/1.bug_report.yaml
Updates bug report template to ask bug submitters to:
* Try disabling their browser extensions
* Try deleting node_modules before submitting a bug.
* List browsers where they have seen the bug
=> chore: update template for bug reports

docs/src/components/ComponentClassTable.tsx, docs/src/components/ComponentVariableTable.tsx, docs/src/styles/docs/styleTable.scss
Updates responsiveness of CSS classes tables.  Converts custom properties tables to use a grid with ul/li since it is not a data table.
**Before Large**
**Before Medium**
**Before Small**
**After Large**
**After Medium**
**After Small**
I kept the CSS Variables "table" pretty similar to how it was as a table but using grid: i.e. it has a horizontal scroll, two columns, added borders:
(the Button component has a lot of possible css custom properties)
**Before**
**After**
=> fix(docs): mobilize css classes tables

packages/react/src/primitives/types/sliderField.ts
Addresses LGTM alert:
https://lgtm.com/projects/g/aws-amplify/amplify-ui/rev/pr-a762d68bf7b3df21af9bad18523e0217ac3453ed
=> chore: remove unused import AriaAttributes

docs/src/pages/[platform]/components/phonenumberfield/examples/PhoneNumberFieldThemeExample.tsx
Updates component name for PhoneNumberFieldThemeExample, which fixes this broken page https://ui.docs.amplify.aws/react/components/phonenumberfield
N/A
local docs instance
=> fix(docs): incorrect name for PhoneNumberFieldExample

yarn.lock
Adds yarn.lock changes missed after pinning eslint
=> fix: update yarn.lock file

canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, docs/package.json, docs/src/pages/[platform]/components/phonenumberfield/examples/PhoneNumberFieldThemeExample.tsx, docs/src/styles/docs/base.scss, guides/react/protected-routes/package.json, package.json, packages/react/src/primitives/types/sliderField.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/select.scss, packages/ui/src/theme/tokens/components/select.ts, yarn.lock
=> Prod docs release 6/30

docs/src/pages/[platform]/components/checkboxfield/props-table.mdx, docs/src/pages/[platform]/components/passwordfield/props-table.mdx, docs/src/pages/[platform]/components/phonenumberfield/props-table.mdx, docs/src/pages/[platform]/components/radiogroupfield/props-table.mdx, docs/src/pages/[platform]/components/searchfield/props-table.mdx, docs/src/pages/[platform]/components/sliderfield/props-table.mdx, docs/src/pages/[platform]/components/stepperfield/props-table.mdx, docs/src/pages/[platform]/components/switchfield/props-table.mdx, docs/src/pages/[platform]/components/textfield/props-table.mdx
Updates prop tables in repo for components that have the enterKeyHint type.
N/A
Local docs build/instance
=> chore(docs): update prop tables with enterKeyHint updates

docs/src/pages/[platform]/connected-components/authenticator/NextSteps.tsx, docs/src/pages/[platform]/connected-components/authenticator/amplify-cli.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/amplify-pull.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/amplify-pull.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/loginMechanisms.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/loginMechanisms.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/prerequisite.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/prerequisite.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-add.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-add.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-example.angular.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-example.react.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-pull.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-pull.web.mdx
=> chore(docs): making intro authenticator docs read better

docs/src/components/CardLink.tsx, docs/src/components/InstallScripts.tsx, docs/src/components/home/sections/HeroSection.tsx, docs/src/pages/[platform]/components/ComponentsGrid.tsx, docs/src/pages/[platform]/connected-components/authenticator/NextSteps.tsx, docs/src/pages/[platform]/connected-components/authenticator/amplify-cli.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/amplify-pull.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/amplify-pull.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/loginMechanisms.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/configuration/loginMechanisms.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/prerequisite.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/prerequisite.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-add.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-add.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-example.angular.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-example.react.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-install.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-install.web.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-pull.flutter.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-pull.web.mdx, docs/src/pages/[platform]/getting-started/accessibility/accessibility.react.mdx, docs/src/pages/[platform]/theming/default-theme/web.mdx, docs/src/styles/docs/base.scss, docs/src/styles/docs/cardLink.scss, docs/src/styles/docs/home.scss, docs/src/styles/docs/main.scss
Two  big changes in this PR:
- This PR consolidates some "card"-like components we use on the docs site into CardLink and CardLinkGroup, which also adds a way to do a "Next Steps" type of component"
- Some refactoring of the Authenticator docs
Pages affected:
- https://docs-cardlink-refactor.dvmvffzts1tcu.amplifyapp.com/
- https://docs-cardlink-refactor.dvmvffzts1tcu.amplifyapp.com/react/components
- https://docs-cardlink-refactor.dvmvffzts1tcu.amplifyapp.com/react/connected-components/authenticator#next-steps
- https://docs-cardlink-refactor.dvmvffzts1tcu.amplifyapp.com/react/theming/default-theme#explore-theme-tokens
- https://docs-cardlink-refactor.dvmvffzts1tcu.amplifyapp.com/react/getting-started/accessibility
**Home page usage (pretty similar to current in prod)**
**Components …
=> docs: refactor CardLink, add Next Steps

guides/react/protected-routes/README.md, guides/react/protected-routes/src/index.js
Some minor updates to the protect routes guide:
-  Update readme link to tutorial to point to prod  (was pointing to dev)
- Add a code comment about the path to aws-exports file. We are pointing to one from our /example directory since we run the guide repo as part of our workflow but someone running the guide repo for the sake of the tutorial would need to update this path to their own file.  Based on an issue opened here: https://github.com/aws-amplify/amplify-ui/issues/2266
=> guides: minor comment/readme updates to protected routes tutorial

docs/src/components/home/sections/HeroSection.tsx
Update tagline from "Don't just prototype" to "Supercharge your app −" since the "don't"  language sounds too negative. Validated changes by running locally:
=> chore: update tagline on docs homepage

.changeset/chilled-vans-doubt.md
Added changeset for #2264 
#2264 
Added changset
=> chore: Added changeset for #2264

docs/src/components/Layout/index.tsx
This PR adds a feedback button (actually a link) on the docs site, so that customers can easily give feedback.
- A button on all pages (except homepage) that links to a Github issue link
- Button is in meta section of page
- Directs to https://github.com/aws-amplify/amplify-ui/issues/new/choose
Ran the docs locally.
=> docs(chore): Add feedback button

docs/src/pages/[platform]/components/tabs/demo.tsx
=> doc(fix): Removed comma from Tabs example

docs/src/pages/[platform]/components/collection/CollectionPropControls.tsx, docs/src/pages/[platform]/components/collection/demo.tsx
Fixes: https://github.com/aws-amplify/amplify-ui/issues/2285
Updates Collection demo code to be complete. 
Current: https://ui.docs.amplify.aws/react/components/collection
Updated:
=> docs(fix): Update Collection demo code

.github/workflows/test-deploy-main.yml
Fix invalid workflow file issue https://github.com/aws-amplify/amplify-ui/actions/runs/2701042629/workflow
=> fix(github): workflow test-deploy-main

packages/react-native/src/InAppMessaging/components/index.ts, packages/react-native/src/InAppMessaging/components/withInAppMessaging/__tests__/__snapshots__/withInAppMessaging.spec.tsx.snap, packages/react-native/src/InAppMessaging/components/withInAppMessaging/__tests__/withInAppMessaging.spec.tsx, packages/react-native/src/InAppMessaging/components/withInAppMessaging/index.ts, packages/react-native/src/InAppMessaging/components/withInAppMessaging/withInAppMessaging.tsx, packages/react-native/src/InAppMessaging/index.ts, packages/react-native/src/index.ts
Add React Native `withInAppMessaging` HOC and basic unit test
NA
Manual tested in example app
=> feat(in-app-messaging): add React Native withInAppMessaging HOC

package.json, yarn.lock
- Added yarn resolution for terser to fix - https://github.com/aws-amplify/amplify-ui/security/dependabot/48
=> fix: add yarn resolution for terser > 5 to v5.14.2 to fix security alert

.github/workflows/publish-latest.yml, .github/workflows/run-and-test-builds.yml, .github/workflows/test-deploy-main.yml
Fix [workflow failure](https://github.com/aws-amplify/amplify-ui/runs/7455147204) from https://github.com/aws-amplify/amplify-ui/pull/2311
=> fix(github): log metric action "can't find" issue

.github/workflows/publish-latest.yml, .github/workflows/run-and-test-builds.yml, .github/workflows/test-deploy-main.yml
Only 1 check was triggered after merging...
Add `ref` as in testing repo https://github.com/0618/amplify-ui/blob/3f61c595d3af5c3e8b674c393902e973f01a9757/.github/workflows/publish-latest.yml#L98
=> fix(github): workflow for log-metric

packages/react/__tests__/exports.ts
Fix _@aws-amplify/react-ui_ `exports` snapshot
NA
`yarn react test`
=> fix(in-app-messaging): fix react-ui exports snapshot

packages/react-core/src/InAppMessaging/utils/handleMessageAction.ts, packages/react/src/components/InAppMessaging/InAppMessageDisplay/InAppMessageDisplay.tsx, packages/react/src/components/InAppMessaging/InAppMessageDisplay/__tests__/handleMessageLinkAction.spec.ts, packages/react/src/components/InAppMessaging/InAppMessageDisplay/handleMessageLinkAction.ts
Add `handleMessageLinkAction` and unit tests for In-App Message action handling in browsers
NA
unit tests, manual testing
- [] `yarn test` passes
=> feat(in-app-messaging): add React web handleMessageLinkAction

docs/src/styles/docs/cardLink.scss
Adds an animation on mouse over of the card link title in docs.
N/A
Ran docs locally.
=> docs: Update card link title style

.changeset/thirty-rivers-whisper.md, packages/ui/src/i18n/dictionaries/authenticator/ja.ts
=> chore: add translation texts for Japanese

docs/src/components/home/sections/HeroSection.tsx, docs/src/components/home/sections/PrimitiveSection.tsx, docs/src/data/links.tsx, docs/src/pages/[platform]/getting-started/accessibility/accessibility.react.mdx, docs/src/pages/[platform]/getting-started/introduction/index.page.mdx
This change updates the headline in docs, changing copy and removing unnecessary punctuation. Also various usages of the word themeable are aligned for consistency sake.
| Before  | After |
| ------------- | ------------- |
| <img width="800" alt="Screen Shot 2022-07-22 at 11 47 47 AM" src="https://user-images.githubusercontent.com/68251134/180504438-c6c73f40-8dae-4ba3-b846-ccebb6b807e1.png">  | <img width="908" alt="Screen Shot 2022-07-22 at 11 47 57 AM" src="https://user-images.githubusercontent.com/68251134/180504455-f7df1877-00ae-4f52-9ac7-d4ec0f3185cf.png">  |
N/A
Ran docs locally.
=> docs: Update hero title

.github/workflows/test-prs.yml
Enables CI on PRs against in-app-messaging/release
=> ci: enable ci in `in-app-messagging/release`

docs/src/components/home/HomeEditor.tsx
* fix homepage editor
hotfix for prod docs to fix the interactive editor on the home page
=> fix(docs): Fix UI docs homepage editor interactivity (#2357)

docs/src/components/home/sections/HeroSection.tsx, docs/src/components/home/sections/PrimitiveSection.tsx, docs/src/data/links.tsx, docs/src/pages/[platform]/getting-started/accessibility/accessibility.react.mdx, docs/src/pages/[platform]/getting-started/introduction/index.page.mdx
* docs: Update hero title
* Align usage of word themeable
=> docs: Update hero title (#2332)

.changeset/wet-hairs-perform.md, docs/src/pages/[platform]/components/icon/IconPropControls.tsx, docs/src/pages/[platform]/components/icon/demo.tsx, docs/src/pages/[platform]/components/icon/examples/AccessibilityIconExample.tsx, docs/src/pages/[platform]/components/icon/props-table.mdx, docs/src/pages/[platform]/components/icon/react.mdx, docs/src/pages/[platform]/components/icon/useIconProps.tsx, packages/react/src/primitives/Icon/__tests__/Icon.test.tsx, packages/react/src/primitives/types/icon.ts
This PR makes the `ariaLabel` prop optional on the Icon component.
**Context**
A common use case for an Icon is using it decoratively. It feels a little awkward passing an empty `aria-label` to Icon when you still need to add `aria-hidden="true"` to make it hidden in the accessibility tree. Essentially:
```
<Icon ariaLabel=""  aria-hidden="true"   ... />
```
Additionally, your custom SVG could have a title element, which means you would previously need to duplicate that title text as the ariaLabel or risk losing the label.
```
<Icon ariaLabel="Search">
<title>Search</title>
</Icon>
```
Changing the prop to be optional provides more flexibility.
**Additionally, this PR** 
- updates the tests to add an ariaLabel specific test, and remove the ariaLabel from the other tests.
- updates the …
=> fix(ui-react): ariaLabel now optional on Icon component, update Icon docs

packages/react/jest.config.js
Add jest coverage thresholds to _@aws-amplify/ui-react_
- threshold values are rounded down to the nearest whole number of their current value
NA
`yarn react test`
- [] Tests are updated
=> chore(ui-react): add jest coverage and thresholds

packages/react/package.json, packages/react/rollup.config.js, packages/react/src/components/InAppMessaging/MessageLayout/MessageLayout.tsx, packages/react/src/components/InAppMessaging/MessageLayout/__tests__/MessageLayout.test.tsx, packages/react/src/components/InAppMessaging/MessageLayout/__tests__/utils.spec.ts, packages/react/src/components/InAppMessaging/MessageLayout/constants.ts, packages/react/src/components/InAppMessaging/MessageLayout/index.ts, packages/react/src/components/InAppMessaging/MessageLayout/types.ts, packages/react/src/components/InAppMessaging/MessageLayout/utils.ts, packages/react/src/components/InAppMessaging/hooks/useMessageProps/utils.ts, packages/react/src/components/InAppMessaging/index.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/inAppMessaging/messageLayout.scss, packages/ui/src/theme/css/styles.scss, packages/ui/src/theme/tokens/components/inAppMessaging.ts, packages/ui/src/theme/tokens/components/index.ts, yarn.lock
This PR adds a MessageLayout component which is intended to be shared across all In-App Messaging message types.
Note: This PR brings in a small [library](https://github.com/bgrins/TinyColor) for color detection. Since it is only available as a CJS module, Rollup requires a CJS plugin to handle it.
Tested in local app. `yarn test`
=> feat(react): add in-app messaging shared layout

packages/react/src/components/InAppMessaging/MessageLayout/MessageLayout.tsx, packages/react/src/components/InAppMessaging/MessageLayout/__tests__/MessageLayout.test.tsx
This PR fixes an issue with MessageLayout where the calculated modifiers for buttons were applied to the wrong buttons.
Tested changes locally. Updated testing and ran `yarn test`
=> fix(react): fix button modifiers

docs/src/pages/_document.page.tsx, docs/src/utils/environment.ts
Add environment related constants to docs (related to [this comment](https://github.com/aws-amplify/amplify-ui/pull/2354#discussion_r931666984))
NA
Manual testing
=> chore(docs): add environment related constants

.changeset/unlucky-beers-agree.md
Code snippets need ``` around to be formatted correctly with markdown.
=> chore: reformat code snippet on changeset

.changeset/shaggy-pots-end.md
Fixes markdown link in the changeset.
=> chore: fix changeset link

.github/workflows/publish-next.yml
This parallelizes guides test; it can run simultaneously along e2e tests.
=> chore(ci): Parallelize guides test

packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts
Updates snapshots according to new css variables added in https://github.com/aws-amplify/amplify-ui/pull/2222.
Verified `yarn ui test` to succeed locally
=> Update snapshot with new css variables

docs/scripts/generate-sitemap-robotstxt.ts
robot.txt file host in dev stage should not point to prod.
=> fix: robot txt host

packages/react/src/components/InAppMessaging/FullScreenMessage/FullScreenMessage.tsx, packages/react/src/components/InAppMessaging/FullScreenMessage/__tests__/FullScreenMessage.test.tsx, packages/react/src/components/InAppMessaging/FullScreenMessage/constants.ts, packages/react/src/components/InAppMessaging/FullScreenMessage/index.ts, packages/react/src/components/InAppMessaging/FullScreenMessage/types.ts, packages/react/src/components/InAppMessaging/InAppMessageDisplay/InAppMessageDisplay.tsx, packages/react/src/components/InAppMessaging/hooks/useMessageProps/__tests__/useMessageProps.spec.ts, packages/react/src/components/InAppMessaging/hooks/useMessageProps/types.ts, packages/react/src/components/InAppMessaging/hooks/useMessageProps/useMessageProps.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/inAppMessaging/fullscreenMessage.scss, packages/ui/src/theme/css/component/inAppMessaging/messageLayout.scss, packages/ui/src/theme/css/styles.scss, packages/ui/src/theme/tokens/components/inAppMessaging.ts
This PR adds the full-screen message type for In-App Messaging
Tested with local app. `yarn test`. Updated/added unit tests and snapshots after validating changes were expected.
=> feat(react): add FullScreen Message for In-App Messaging

examples/angular/src/app/app-routing.module.ts, examples/angular/src/app/app.module.ts, examples/angular/src/pages/ui/primitive-poc/flex/aws-exports.d.ts, examples/angular/src/pages/ui/primitive-poc/flex/aws-exports.js, examples/angular/src/pages/ui/primitive-poc/flex/flex.component.html, examples/angular/src/pages/ui/primitive-poc/flex/flex.component.ts, packages/angular/projects/ui-angular/src/index.ts, packages/angular/projects/ui-angular/src/lib/primitives-poc/flex/flex-component/flex.component.html, packages/angular/projects/ui-angular/src/lib/primitives-poc/flex/flex-component/flex.component.ts, packages/angular/projects/ui-angular/src/lib/primitives-poc/flex/flex.module.ts, packages/angular/projects/ui-angular/src/lib/primitives-poc/flex/index.ts
1. Added flex component in new branch.
=> feat(angular): adding flex field in angular primitive

packages/react/src/components/InAppMessaging/InAppMessageDisplay/InAppMessageDisplay.tsx, packages/react/src/components/InAppMessaging/ModalMessage/ModalMessage.tsx, packages/react/src/components/InAppMessaging/ModalMessage/__tests__/ModalMessage.test.tsx, packages/react/src/components/InAppMessaging/ModalMessage/constants.ts, packages/react/src/components/InAppMessaging/ModalMessage/index.ts, packages/react/src/components/InAppMessaging/ModalMessage/types.ts, packages/ui/src/theme/css/component/inAppMessaging/modalMessage.scss, packages/ui/src/theme/css/styles.scss
This PR adds the Modal message type for the In-App Messaging feature
Tested with local app. `yarn test`
=> feat(react): add Modal Message for In-App Messaging

yarn.lock
Revert unnecessary _yarn.lock_ updates
NA
`yarn clean && yarn && yarn build`
=> chore(in-app-messaging): revert unnecessary yarn.lock updates

.github/workflows/test-in-app-messaging-prs.yml
=> chore(ci): fix typo in in-app-messaging PR workflow

.github/workflows/test-in-app-messaging-prs.yml
Sync `main` into `in-app-messaging/main` to get my typo fix PR #2455 in.
This is a clean merge.
=> chore: sync `main` into `in-app-messaging/main`

examples/react-native/App.tsx, examples/react-native/ios/Podfile.lock, examples/react-native/metro.config.js, examples/react-native/package.json, yarn.lock
add `withInAppMessaging` to React Native example app
NA
Manually tested example app
=> feat(in-app-messaging): add withInAppMessaging to RN example app

packages/react-core/README.md, packages/react-core/package.json, packages/react-native/README.md, packages/react-native/package.json
in both _@aws-amplify/ui-react-core_ and _@aws-amplify/ui-react-native_:
- remove `"private": true` from _package.json_
- update _README.md_
NA
NA
=> chore(in-app-messaging): prepare ui-react-native and ui-react-core for tagged release

packages/react/src/components/InAppMessaging/InAppMessageDisplay/InAppMessageDisplay.tsx, packages/react/src/components/InAppMessaging/InAppMessageDisplay/__tests__/__snapshots__/InAppMessageDisplay.spec.tsx.snap, packages/react/src/components/InAppMessaging/MessageLayout/__tests__/utils.spec.ts, packages/react/src/components/InAppMessaging/MessageLayout/utils.ts, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/inAppMessaging/messageLayout.scss, packages/ui/src/theme/tokens/components/inAppMessaging.ts
This PR adds default styles to In-App Messaging components (buttons) so that it reflects what the default payload would have otherwise configured.
Validated changes 
=> chore(react): update default styling for In-App Messaging components

packages/react-native/src/InAppMessaging/components/ModalMessage/__tests__/__snapshots__/ModalMessage.spec.tsx.snap, packages/react-native/src/InAppMessaging/components/ModalMessage/styles.ts
Update styling of React Native `ModalMessage` to more closely align to the React web version
NA
=> feat(in-app-messaging): center React Native InApp Modal

.changeset/forty-pants-complain.md, packages/ui/src/icons/indeterminate.svg
=> chore: add indeterminate icon svg

.github/changeset-presets/bump-react.md, .github/workflows/publish-in-app-messaging.yml
Add publishing for `in-app-messaging/release` branch
=> chore(in-app-messaging): Enable publish

.prettierignore, environments/auth/adminui-auth-with-email-and-phone/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/adminui-auth-with-totp-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-all-attributes/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-email-and-custom-attributes/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-email-lambda-signup-trigger/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-email/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-federated/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-multi-alias/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-phone-and-sms-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-phone-number/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-totp-and-sms-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-totp-mfa/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/auth/auth-with-username-no-attributes/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/datastore/action-hooks/amplify/backend/types/amplify-dependent-resources-ref.d.ts, environments/geo/basic-map/amplify/backend/types/amplify-dependent-resources-ref.d.ts, yarn.lock
=> chore(in-app-messaging): restore missing commits

packages/react-core/package.json, packages/react-core/tsconfig.json
Update React Native entry point and remove source map generation in `@aws-amplify/ui-react-core`
=> fix(in-app-messaging): fix RN entry point issue and remove source map generation

docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx
Numbered list for the Jest troubleshooting docs is formatted incorrectly.
https://ui.docs.amplify.aws/react/getting-started/troubleshooting#jest
N/A
**Before**
**After**
=> fix(docs): Formatting fix for troubleshooting docs

packages/react-native/src/InAppMessaging/components/BannerMessage/styles.ts, packages/react-native/src/InAppMessaging/components/CarouselMessage/__tests__/__snapshots__/CarouselMessageItem.spec.tsx.snap, packages/react-native/src/InAppMessaging/components/CarouselMessage/styles.ts, packages/react-native/src/InAppMessaging/components/FullScreenMessage/__tests__/__snapshots__/FullScreenMessage.spec.tsx.snap, packages/react-native/src/InAppMessaging/components/FullScreenMessage/styles.ts, packages/react-native/src/InAppMessaging/components/ModalMessage/styles.ts, packages/react-native/src/InAppMessaging/constants.ts
Update React Native message components header `fontWeight` to better align with React web implementation
NA
Manually tested in example app
=> chore(in-app-messaging): update RN message components header font weight

packages/react-native/src/InAppMessaging/components/withInAppMessaging/withInAppMessaging.tsx, packages/react/src/components/InAppMessaging/withInAppMessaging/__tests__/withInAppMessaging.spec.tsx, packages/react/src/components/InAppMessaging/withInAppMessaging/withInAppMessaging.tsx, yarn.lock
- Update _yarn.lock_ to update `aws-amplify@in-app-messaging` to latest version
- Add stricter typing to `withInAppMessaging` TS generic to remove TS errors
- Add `React` import to web `withInAppMessaging.spec.tsx` (required due to https://github.com/aws-amplify/amplify-ui/pull/2513)
NA
`yarn && yarn build`
=> chore(in-app-messaging): update yarn.lock

.github/workflows/test-prs.yml
Add `next-release/main` to Github Action PR testing
NA
NA
=> chore(next-release): test PRs on next-release/main

.github/workflows/test-next-release.yml
Add test on merge for `next-release/main`
NA
NA
=> chore(next-release): add test on merge for next-release/main

.github/workflows/test-next-release.yml
=> chore(next-release): merge main

packages/react/src/components/Authenticator/withAuthenticator.tsx
Fix `withAuthenticator` typing issues
- remove optional flag on `props` type param of  `Component` param
- extend update `Props` generic param  to extend from `object` to prevent invalid React component arguments
NA
Manually tested in example app
=> fix(ui-react): fix withAuthenticator typing

docs/src/pages/[platform]/connected-components/authenticator/customization/sign-up-fields.web.mdx
Fixes link to Zero Config details from the Authenticator Customization page.
Fixes: https://github.com/aws-amplify/amplify-ui/issues/2575
yarn docs dev
Clicked "Zero Config" link.
=> chore: fix link on authenticator customization page

docs/README.md
Fix some broken links and out of date info on the Docs README file.
=> chore: update docs README links

.github/workflows/poc-test-environments.yml, environments/datastore/action-hooks/.gitignore, environments/datastore/action-hooks/amplify/.config/project-config.json, environments/datastore/action-hooks/package.json
This migrates `environments/datastore` resources to the new account. This will go into a feature branch `split-environments/main`, which will be merged once all resources has been migrated and workflows have been updated.
See POC status check below.
=> chore(ci): split environments/datastore

docs/package.json
=> chore(docs): change dev port

.github/workflows/test-prs.yml
Allows integ tests to run against PRs made against `rwa/main`, the feature branch used for refactoring the existing React `Authenticator` and migrating shared utilities to `@aws-amplify/ui-react-core`
NA
NA
=> chore(rwa): run integ tests against PRs on rwa/main

.changeset/chilled-news-build.md, packages/react/src/components/Authenticator/Authenticator.tsx, packages/react/src/components/Authenticator/withAuthenticator.tsx
Update `signOut` function typing in `WithAuthenticatorProps` 
NA
Tested in example app
=> fix(ui-react): fix withAuthenticator signOut function typing

docs/src/pages/[platform]/connected-components/authenticator/quick-start-example.react.mdx, examples/next/pages/ui/components/authenticator/withAuthenticator/index.page.tsx
Add explicit Typescript and Javascript examples for `withAuthenticator`.
[Link to relevant changes](https://docs-add-with-authenticator-ts-example.d2wnvax2ctai8z.amplifyapp.com/react/connected-components/authenticator#3-add-the-authenticator). Click `withAuthenticator` to reveal the tabs
NA
=> chore(docs): add withAuthenticator TS example

.github/workflows/test-rwa-prs.yml
=> chore(rwa): add test-rwa-prs.yml

docs/next.config.js, docs/src/data/globalnav.ts, docs/src/pages/_app.page.tsx, docs/src/styles/docs/base.scss, docs/src/styles/docs/header.scss, docs/src/styles/docs/sidebar.scss, docs/src/utils/featureFlags.ts
Removing 'sandbox' and 'contribute' links from the global nav because those sites have not added the global nav yet. Also added an env variable check to display the global nav or not. This will allow us to deploy the docs site without having to show the global nav until it is ready. When we want to release the global nav we will add `NEXT_PUBLIC_SHOW_GLOBAL_NAV` to the amplify app's env variables and redeploy the current version. Post-launch we will remove the conditional logic and env variable. 
https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser
https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html
Global nav was added in this PR: #2554
Built and validated locally. Amplify app for testing (added the env …
=> chore(docs): remove nav items from global nav

.github/workflows/build-and-runtime-test.yml, .github/workflows/run-and-test-builds.yml
rename `RuntimeTestsFailure` to `RunAndTestBuildsFailure` which is more accurate.[ref](https://code.amazon.com/reviews/CR-76453982/revisions/2#/comments)
=> chore(workflow): rename RuntimeTestsFailure to BuildAndRuntimeTestFailure

.github/workflows/test-prs.yml
Remove `rwa/main` from _reusable-e2e.yml_ branches
NA
NA
=> chore(rwa): remove rwa/main from reusable-e2e.yml branches

.github/workflows/test-rna-prs.yml
=> chore(rna): add test-rna-prs.yml

packages/react-core/.lintstagedrc.js
add _.lintstagedrc.js_ to `ui-react-core`
NA
=> chore(ui-react-core): add .lintstagedrc.js

docs/next.config.js, docs/src/pages/_app.page.tsx, docs/src/styles/docs/header.scss, docs/src/utils/featureFlags.ts
- Remove code for handling dev center feature flag
=> Remove dev center FF

.changeset/clean-actors-rhyme.md
=> fix(ui): add missing changeset

docs/scripts/generate-sitemap-robotstxt.ts, docs/src/pages/[platform]/components/expander/props-table.mdx, docs/src/pages/[platform]/components/phonenumberfield/props-table.mdx
When doing the [404 error analyze](https://t.corp.amazon.com/V732062633/) for Dev environment, we found there are some 404s from http://www.semrush.com/bot.html. Its requests from outdated invalid URL causes those 404.
We don't want any bot to index our dev environment, so disallow them in Dev. [ref:How to disallow all using robots.txt](https://searchfacts.com/robots-txt-allow-disallow-all/#:~:text=The%20%E2%80%9CUser%2Dagent%3A%20*,access%20or%20crawl%20your%20site.)
We still allow it in Prod just in case we need to use semrush in the future. [ref: What Is Semrushbot And Should You Block It?  ](https://www.matthewwoodward.co.uk/seo/semrushbot/)
=> fix: disallow Bots in Dev

.changeset/lovely-needles-poke.md
Add changeset for useAuthenticator updates
=> chore(next-release): add changeset for useAuthenticator updates

packages/react-core/src/InAppMessaging/types.ts, packages/react-native/src/InAppMessaging/components/withInAppMessaging/withInAppMessaging.tsx, packages/react/src/components/InAppMessaging/withInAppMessaging/withInAppMessaging.tsx
Improve In-App Messaging override component and `withInAppMessaging` HOC typing to align with `Authenticator`
NA
=> chore(in-app-messaging): improve types

docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx
=> chore(docs): fix typo in migration.vue.mdx

environments/auth/auth-with-federated/package.json, packages/e2e/features/ui/hooks/actions-navigation.feature
Fixes two e2e failures that were caught in [![POC / Split Environments / E2E](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-e2e.yml/badge.svg)](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-e2e.yml).
Verified e2e tests to pass locally.
=> fix(ci): fix e2e test with split environments

docs/package.json, examples/angular/package.json, examples/vue/package.json, packages/angular/projects/ui-angular/ng-package.json, packages/angular/projects/ui-angular/package.json, packages/react-core/package.json, packages/react-native/package.json, packages/react/package.json, packages/ui/package.json, packages/vue/package.json, yarn.lock
Point `aws-amplify` dependency versions at `next` in place of `in-app-messaging`
NA
=> chore(in-app-messaging): point aws-amplify to next

docs/package.json, examples/angular/package.json, examples/vue/package.json, packages/angular/projects/ui-angular/package.json, packages/react-core/package.json, packages/react/package.json, packages/ui/package.json, packages/vue/package.json, yarn.lock
Point `aws-amplify` dependencies to `next` version
=> chore(next-release): point aws-amplify dependencies to next

.github/workflows/build-and-runtime-test.yml, .github/workflows/publish-latest.yml, .github/workflows/publish-next.yml
After https://github.com/aws-amplify/amplify-ui/pull/2613 and testing it for sometime, we can remove the metrics from Prod.
=> chore(workflow): remove Github workflow metrics from prod

.changeset/green-hounds-serve.md, packages/react-core/src/Authenticator/hooks/useAuthenticator/constants.ts, packages/react-core/src/Authenticator/hooks/useAuthenticator/types.ts, packages/react-core/src/Authenticator/hooks/useAuthenticator/utils.ts
Add missing value to `AuthenticatorRouteComponentKey` and update usage
NA
=> chore(ui-react-core): add missing value to AuthenticatorRouteComponentKey

packages/react-native/package.json, yarn.lock
Bump `@aws-amplify/ui-react-core` dependency version in `@aws-amplify/ui-react-native`
NA
NA
=> chore(ui-react-native): bump ui-react-core dep

examples/react-native/storybook/stories/ConfirmResetPassword.stories.tsx, examples/react-native/storybook/stories/ConfirmSignIn.stories.tsx, examples/react-native/storybook/stories/ConfirmSignUp.stories.tsx, examples/react-native/storybook/stories/ConfirmVerifyUser.stories.tsx, examples/react-native/storybook/stories/ForceNewPassword.stories.tsx, examples/react-native/storybook/stories/ResetPassword.stories.tsx, examples/react-native/storybook/stories/SetupTOTP.stories.tsx, examples/react-native/storybook/stories/SignIn.stories.tsx, examples/react-native/storybook/stories/SignUp.stories.tsx, examples/react-native/storybook/stories/VerifyUser.stories.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/__tests__/ConfirmResetPassword.spec.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/__tests__/ConfirmSignIn.spec.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmSignUp/__tests__/ConfirmSignUp.spec.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/__tests__/ConfirmVerifyUser.spec.tsx, packages/react-native/src/Authenticator/Defaults/ForceNewPassword/__tests__/ForceNewPassword.spec.tsx, packages/react-native/src/Authenticator/Defaults/ResetPassword/__tests__/ResetPassword.spec.tsx, packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/SetupTOTP.spec.tsx, packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/SignIn.spec.tsx, packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/SignUp.spec.tsx, packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/VerifyUser.spec.tsx
I noticed that another [PR test was failing](https://github.com/aws-amplify/amplify-ui/actions/runs/3292687920/jobs/5428398722) due to linting errors introduced in the [Subcomponent templates PR](https://github.com/aws-amplify/amplify-ui/pull/2769). 
I'm not sure why ES lint didn't catch these in the Subcomponent templates PR, but this PR fixes the issue. 
=> chore(rna): Fix linting

.changeset/shiny-melons-scream.md, .changeset/small-turkeys-glow.md, docs/src/pages/[platform]/components/checkboxfield/examples/CheckboxFieldControlledExample.tsx, docs/src/pages/[platform]/components/checkboxfield/examples/CheckboxFieldDisabledExample.tsx, docs/src/pages/[platform]/components/checkboxfield/examples/CheckboxFieldLabelHiddenExample.tsx, docs/src/pages/[platform]/components/checkboxfield/examples/CheckboxFieldSizesExample.tsx, docs/src/pages/[platform]/components/checkboxfield/examples/CheckboxFieldValueExample.tsx, docs/src/pages/[platform]/components/checkboxfield/examples/CheckboxFieldWithErrorExample.tsx, docs/src/pages/[platform]/components/checkboxfield/examples/DefaultCheckboxFieldExample.tsx, docs/src/pages/[platform]/components/checkboxfield/examples/index.ts, docs/src/pages/[platform]/components/checkboxfield/react.mdx, docs/src/pages/[platform]/components/switchfield/examples/SwitchFieldErrorExample.tsx, docs/src/pages/[platform]/components/switchfield/examples/index.ts, docs/src/pages/[platform]/components/switchfield/react.mdx, packages/react/src/primitives/SwitchField/SwitchField.tsx, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts, packages/ui/src/theme/css/component/switchField.scss, packages/ui/src/theme/css/styles.scss, packages/ui/src/theme/tokens/components/switchField.ts
Merge `main` into `next-release/main`
=> Merge `main` into `next-release/main`

packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/ConfirmResetPassword.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/ConfirmSignIn.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmSignUp/ConfirmSignUp.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/ConfirmVerifyUser.tsx, packages/react-native/src/Authenticator/Defaults/ForceNewPassword/ForceNewPassword.tsx, packages/react-native/src/Authenticator/Defaults/ResetPassword/ResetPassword.tsx, packages/react-native/src/Authenticator/Defaults/SetupTOTP/SetupTOTP.tsx, packages/react-native/src/Authenticator/Defaults/SignIn/SignIn.tsx, packages/react-native/src/Authenticator/Defaults/SignUp/SignUp.tsx, packages/react-native/src/Authenticator/Defaults/VerifyUser/VerifyUser.tsx, packages/react-native/src/Authenticator/common/DefaultFooter/DefaultFooter.tsx, packages/react-native/src/Authenticator/common/DefaultFooter/__tests__/DefaultFooter.spec.tsx, packages/react-native/src/Authenticator/common/DefaultFooter/__tests__/__snapshots__/DefaultFooter.spec.tsx.snap, packages/react-native/src/Authenticator/common/DefaultFooter/index.ts, packages/react-native/src/Authenticator/common/DefaultFooter/types.ts, packages/react-native/src/Authenticator/common/index.ts
This change adds a default footer for Authenticator sub components.
=> chore(ui-react-native): Add default footer

.github/workflows/publish-account-settings.yml, .github/workflows/test-account-settings-prs.yml
This sets up tests on `account-settings/main` feature branch. This will be reverted when feature branch is ready to be merged onto `main`.
Copy pasted `next-release` ci logics.
=> ci: setup tests on `account-settings/main` feature branch

packages/react-core/src/hooks/__tests__/useHasValueUpdated.spec.ts, packages/react-core/src/hooks/__tests__/usePreviousValue.spec.ts, packages/react-core/src/hooks/index.ts, packages/react-core/src/hooks/useHasValueUpdated.ts, packages/react-core/src/hooks/usePreviousValue.ts
Add `usePreviousValue` and `useHasValueUpdated` util hooks and unit tests
NA
=> chore(ui-react-core): add util react hooks in react-core

packages/react-native/src/Authenticator/common/FederatedProviderButton/FederatedProviderButton.tsx, packages/react-native/src/Authenticator/common/FederatedProviderButtons/FederatedProviderButtons.tsx, packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/FederatedProviderButtons.spec.tsx, packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/__snapshots__/FederatedProviderButtons.spec.tsx.snap, packages/react-native/src/Authenticator/common/FederatedProviderButtons/index.ts, packages/react-native/src/Authenticator/common/FederatedProviderButtons/styles.ts, packages/react-native/src/Authenticator/common/FederatedProviderButtons/types.ts
finish FederatedProviderButtons unit tests
Add `FederatedProviderButtons` component for use in `SignIn` and `SignUp` RNA subcomponents
NA
Manually tested, unit tests
=> feat(rna): add FederatedProviderButtons

.changeset/fuzzy-otters-cough.md
fix formatting on legacy exports changeset
=> fix: fix formatting on legacy exports changeset

examples/react-native/storybook/stories/SignIn.stories.tsx, packages/react-native/package.json, packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/ConfirmResetPassword.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/ConfirmSignIn.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmSignUp/ConfirmSignUp.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/ConfirmVerifyUser.tsx, packages/react-native/src/Authenticator/Defaults/ForceNewPassword/ForceNewPassword.tsx, packages/react-native/src/Authenticator/Defaults/FormFields.tsx, packages/react-native/src/Authenticator/Defaults/ResetPassword/ResetPassword.tsx, packages/react-native/src/Authenticator/Defaults/SetupTOTP/SetupTOTP.tsx, packages/react-native/src/Authenticator/Defaults/SignIn/SignIn.tsx, packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/SignIn.spec.tsx, packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/__snapshots__/SignIn.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SignUp/SignUp.tsx, packages/react-native/src/Authenticator/common/DefaultFormFields/DefaultFormFields.tsx, packages/react-native/src/Authenticator/common/DefaultFormFields/__tests__/DefaultFormFields.spec.tsx, packages/react-native/src/Authenticator/common/DefaultFormFields/__tests__/__snapshots__/DefaultFormFields.spec.tsx.snap, packages/react-native/src/Authenticator/common/DefaultFormFields/index.ts, packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/__snapshots__/FederatedProviderButtons.spec.tsx.snap, packages/react-native/src/Authenticator/common/index.ts, packages/react-native/src/primitives/Tabs/Tabs.tsx, packages/react-native/src/primitives/Tabs/__tests__/__snapshots__/Tab.spec.tsx.snap, packages/react-native/src/primitives/Tabs/styles.ts, yarn.lock
Add `SignIn` subcomponent
NA
Manually tested, unit tests
=> feat(rna): Add SignIn subcomponent

.github/workflows/test-next-release-prs.yml, .github/workflows/test-rna-prs.yml
Adds missing secrets in `test-rna-prs.yml` and `next-release/main.yml`.
https://github.com/aws-amplify/amplify-ui/actions/runs/3331126623
=> chore(ci): Add missing secrets

.github/workflows/publish-latest.yml, .github/workflows/publish-next.yml, .github/workflows/reusable-e2e.yml, .github/workflows/reusable-tagged-publish.yml, .github/workflows/test-next-release-prs.yml, .github/workflows/test-rna-prs.yml, .github/workflows/version-packages.yml
=> chore(next-release): merge `main` into `next-release`

packages/react-native/package.json, yarn.lock
`package.json` in `ui-react-native` was outdated, and caused build failures. This aligns the version with the current latest versions.
Verified `yarn build` and `yarn react-native test` to pass locally.
=> fix(next-release): fix outdated `package.json`

packages/react-core/src/Authenticator/index.ts, packages/react-core/src/__tests__/__snapshots__/index.spec.ts.snap, packages/react-core/src/index.ts, packages/react-native/src/Authenticator/Authenticator.tsx, packages/react-native/src/Authenticator/Defaults/index.ts, packages/react-native/src/Authenticator/Defaults/types.ts, packages/react-native/src/Authenticator/common/DefaultFormFields/DefaultFormFields.tsx, packages/react-native/src/Authenticator/hooks/index.ts, packages/react-native/src/Authenticator/hooks/useRouteTypedFields/__tests__/useRouteTypedFields.spec.ts, packages/react-native/src/Authenticator/hooks/useRouteTypedFields/constants.ts, packages/react-native/src/Authenticator/hooks/useRouteTypedFields/index.ts, packages/react-native/src/Authenticator/hooks/useRouteTypedFields/types.ts, packages/react-native/src/Authenticator/hooks/useRouteTypedFields/useRouteTypedFields.ts, packages/react-native/src/Authenticator/hooks/useRouteTypedFields/utils.ts, yarn.lock
Add `useRouteTypedFields` util hook
NA
=> feat(rna): add useRouteTypedFields util hook

examples/next/pages/ui/components/authenticator/withAuthenticator/index.page.tsx
Update `withAuthenticator` Typescript example
Fixes https://github.com/aws-amplify/amplify-ui/issues/2838
Tested example code in a CRA with Typescript app
=> chore(docs): update withAuthenticator Typescript example

environments/auth/auth-with-federated/package.json, environments/auth/auth-with-totp-mfa/package.json
=> chore(ci): update env appIds

examples/react-native/.gitignore, examples/react-native/src/features/Authenticator/Demo/Demo.tsx
Ignore `aws-exports` for testing
=> chore(rna): add aws-exports to .gitignore

examples/react-native/android/app/src/main/AndroidManifest.xml, examples/react-native/ios/ReactNative.xcodeproj/project.pbxproj, examples/react-native/ios/ReactNative.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples/react-native/ios/ReactNative/AppDelegate.mm, examples/react-native/ios/ReactNative/Info.plist, examples/react-native/src/features/Authenticator/Demo/Demo.tsx, examples/react-native/src/hooks/index.ts, examples/react-native/src/hooks/useDeepLinkingDebug.ts
Setup deep linking and add `useDeepLinkingDebug` util hook in example app
NA
Manual test
=> feat(rna): setup linking in demo app

examples/next/pages/ui/components/storage/file-uploader/index.page.tsx, packages/react/src/components/Storage/FileUploader/FileUploader.tsx, packages/react/src/components/Storage/FileUploader/Previewer/__tests__/Previewer.test.tsx, packages/react/src/components/Storage/FileUploader/Previewer/index.tsx, packages/react/src/components/Storage/FileUploader/Tracker/FileState.tsx, packages/react/src/components/Storage/FileUploader/Tracker/__tests__/Tracker.test.tsx, packages/react/src/components/Storage/FileUploader/Tracker/index.tsx, packages/react/src/components/Storage/FileUploader/hooks/useFileUploader/types.ts, packages/react/src/components/Storage/FileUploader/hooks/useFileUploader/useFileUploader.tsx, packages/react/src/components/Storage/FileUploader/types.ts, packages/ui/src/helpers/storage/fileUploader/utils/index.ts, packages/ui/src/helpers/storage/fileUploader/utils/uploader.ts
This PR is to add in new file validations:
[Asana](https://app.asana.com/0/1203229338651479/1203185241692061)
Manually tested, more tests will come later
=> feat(file-uploader): Added file validations

.github/workflows/publish-fileuploader.yml
Sets up release for fileuploader for development testing.
Copy and pasted logic from `next-release/main`
=> chore(ci): Setup fileuploader release

packages/react/src/components/Storage/FileUploader/FileUploader.tsx, packages/react/src/components/Storage/FileUploader/Tracker/index.tsx, packages/ui/src/helpers/storage/fileUploader/utils/uploader.ts
=> File Uploader Tagged Release

environments/auth/auth-with-federated/package.json, environments/auth/auth-with-totp-mfa/package.json, examples/next/pages/ui/components/authenticator/withAuthenticator/index.page.tsx
merge `main` into `next-release/main`
=> chore(next-release): merge `main` into `next-release/main`

.changeset/fast-toes-smash.md, examples/next/package.json, packages/react/src/hooks/actions/shared/types.ts, packages/react/src/hooks/actions/shared/useTypeCastFields.ts, packages/react/src/hooks/actions/useDataStoreCreateAction.ts, packages/react/src/hooks/actions/useDataStoreDeleteAction.ts, packages/react/src/hooks/actions/useDataStoreUpdateAction.ts, packages/react/src/primitives/types/datastore.ts, yarn.lock
=> fix(data): update usage of internal DataStore types

packages/react-native/src/Authenticator/Defaults/VerifyUser/VerifyUser.tsx, packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/VerifyUser.spec.tsx, packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/__snapshots__/VerifyUser.spec.tsx.snap
Scrub email and phone fields for verify user screen.
=> chore(ui-react-native): Scrub contact information in verify user subcomponent

.github/workflows/test-fileuploader-release-prs.yml
This change adds tests to run on the `fileuploader/main` release branch.
Needs to be merged before #2880
=> chore(ci): run file uploader tests on fileuploader/main release

.github/workflows/reusable-e2e.yml, environments/package.json, environments/storage/file-uploader/README.md, environments/storage/file-uploader/package.json, environments/storage/package.json, examples/next/pages/ui/components/storage/file-uploader/aws-exports.js, packages/e2e/cypress/fixtures/FileUploader-uploads-complete.xml, packages/e2e/cypress/fixtures/FileUploader-uploads-list.xml, packages/e2e/cypress/fixtures/FileUploader-uploads.xml, packages/e2e/cypress/integration/common/fileuploader.ts, packages/e2e/features/ui/components/storage/fileuploader/upload-image-to-s3.feature
Add E2E tests for the file uploader component. 
Needs to be merged after #2878 
=> chore(ci): Add E2E test for fileuploader/main branch

docs/src/data/meta.ts, docs/src/hooks/useNavigationContext.ts, docs/src/pages/[platform]/studio/create-form.page.tsx, docs/src/pages/_app.page.tsx, docs/src/styles/docs/header.scss
Add a shared context for managing state of navigation components and update styles to allow for the side menu to be collapsed on wider screens.
screen recordings were created showing before/after changes
=> Make sidebar optionally collapsible on docs screens

packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/ConfirmVerifyUser.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/__tests__/ConfirmVerifyUser.spec.tsx, packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/__tests__/__snapshots__/ConfirmVerifyUser.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SetupTOTP/SetupTOTP.tsx, packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/SetupTOTP.spec.tsx, packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/__snapshots__/SetupTOTP.spec.tsx.snap, packages/react-native/src/Authenticator/hooks/useFieldValues/__tests__/useFieldValues.spec.ts
* Fix ConfirmVerifyUser subcomponent label
* Improve unit test coverage to >90%
=> chore(ui-react-native): Improve unit test coverage and ConfirmVerifyUser fix

.github/changeset-presets/bump-versions.md, .github/workflows/publish-rna.yml
Sets up tagged release against `rna/release` branch.
1. Developer opens a PR from `rna/main` -> `rna/release`
2. Developer merges the PR once e2e tests have passed on the PR
3. Merging the PR will publish `@aws-amplify/ui-react-native` to `@rna`.
Copy-pasted `next-release` logic.
=> chore(ci): set up tagged release against `rna/release` branch

packages/react-native/jest.config.js
Revert temporary lowering of jest `branches` coverage threshold thanks to merging of https://github.com/aws-amplify/amplify-ui/pull/2893
NA
Ran unit tests
=> chore(ui-react-native): bump test jest branch coverage threshold

packages/react-native/.eslintrc.js, packages/react-native/jest.config.js, packages/react-native/jest.setup.js
This change mocks the `ClientDevice_Browser` to remove the many console warnings about browser client info during test runs:
```
[WARN] ClientDevice_Browser - No navigator object available to get browser client info
at ConsoleLogger.Object.<anonymous>.ConsoleLogger._log (../../node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:115:4)
at ConsoleLogger.Object.<anonymous>.ConsoleLogger.warn (../../node_modules/@aws-amplify/core/src/Logger/ConsoleLogger.ts:164:12)
at browserClientInfo (../../node_modules/@aws-amplify/core/src/ClientDevice/browser.ts:33:10)
at Object.clientInfo (../../node_modules/@aws-amplify/core/src/ClientDevice/browser.ts:22:9)
at Function.Object.<anonymous>.ClientDevice.clientInfo (../../node_modules/@aws-amplify/core/src/ClientDevice/index.ts:18:10)
at new …
```
=> chore(ui-react-native): Fix console warns about browser client during tests

docs/cypress/e2e/links.cy.ts
Docs builds are failing because the number of links has grown. This will add the correct number of links
This will fix the issue with dev docs not building.
=> chore(cypress e2e): Update Link checker for docs site

packages/react/src/components/Storage/FileUploader/FileUploader.tsx
=> chore: add isUploadTask

packages/ui/src/theme/tokens/components/switchField.ts, packages/ui/src/theme/tokens/components/tabs.ts, packages/ui/src/theme/tokens/components/text.ts, packages/ui/src/theme/tokens/components/textAreaField.ts, packages/ui/src/theme/tokens/components/textField.ts, packages/ui/src/theme/tokens/components/toggleButtonGroup.ts, packages/ui/src/theme/tokens/types/designToken.ts
=> [RNA] chore: component token conversion

packages/react/package.json, yarn.lock
=> chore(next-release): point maplibre-gl-js-amplify at unstable

packages/react/package.json, yarn.lock
=> chore(next-release): point maplibre-gl-js-amplify to v3.0.0

packages/react/src/components/Storage/FileUploader/FileUploader.tsx, packages/react/src/components/Storage/FileUploader/Previewer/__tests__/Previewer.test.tsx, packages/react/src/components/Storage/FileUploader/Previewer/index.tsx, packages/react/src/components/Storage/FileUploader/Tracker/index.tsx, packages/react/src/components/Storage/FileUploader/UploadButton/__tests__/UploadButton.tsx, packages/react/src/components/Storage/FileUploader/UploadButton/index.tsx, packages/react/src/components/Storage/FileUploader/UploadDropZone/__tests__/UploadDropZone.test.tsx, packages/react/src/components/Storage/FileUploader/UploadDropZone/__tests__/__snapshots__/UploadDropZone.test.tsx.snap, packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx, packages/react/src/components/Storage/FileUploader/hooks/useFileUploader/__tests__/useFileUploader.test.tsx, packages/react/src/components/Storage/FileUploader/types.ts, packages/ui/src/theme/css/component/fileUploader.scss
The purpose of this PR is to add more unit tests to the file uploader main components
[Asana](https://app.asana.com/0/1203303459000520/1203296511323717)
=> chore(file-uploader): Add unit tests to main file uploader components

canary/apps/angular/angularcli/package.json, canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, canary/apps/react/next/package.json, canary/apps/react/vite/package.json, canary/apps/react/vite3/package.json, canary/apps/vue/vite/package.json, canary/apps/vue/vite3/package.json, canary/apps/vue/vuecli/package.json, canary/e2e/package.json, docs/package.json, examples/angular/package.json, examples/next/package.json, examples/vue/package.json, guides/react/protected-routes/package.json, packages/react-core/package.json, packages/react-native/package.json, packages/react/package.json, packages/ui/package.json, yarn.lock
Point `aws-amplify` deps to `^5.0.1` and update peerDeps to `5.x.x`. A follow up PR pointing `aws-amplify` deps to `latest` is required post release.
=> chore(next-release): point aws-amplify deps at v5.0.1

.changeset/sixty-seahorses-provide.md
=> chore(in-app-messaging): add in-app release changeset

docs/cypress/e2e/links.cy.ts, docs/next.config.js, docs/src/components/ComponentVariableTable.tsx, docs/src/data/links.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/AcceptedFileTypesExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/DefaultFileUploaderExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderComponentsExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderErrorExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderThemeExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/index.ts, docs/src/pages/[platform]/connected-components/storage/fileuploader/index.page.mdx, docs/src/pages/[platform]/connected-components/storage/fileuploader/react.mdx, docs/src/pages/[platform]/connected-components/storage/index.page.mdx, docs/src/pages/[platform]/connected-components/storage/react.mdx, docs/src/pages/_app.page.tsx, docs/src/pages/_document.page.tsx, docs/src/plugins/rehype-ignore-code.js, docs/src/utils/storageMock.ts, examples/next/pages/ui/components/storage/file-uploader/index.page.tsx, packages/react/src/primitives/shared/constants.ts, packages/react/src/primitives/shared/types.ts
Got a start to the docs for FileUploader component with some neat additions to our docs:
* Added a Storage Provider mock implementation so we can show file uploader behavior without uploading files. We could potentially do this with Auth in the future. 
* Added a rehype plugin to remove lines in code that end in `// IGNORE` so we can hide lines of code we don't want to show the user
https://user-images.githubusercontent.com/321279/201225080-de5601a4-8105-4e8f-8ad3-2fb41e511df6.mp4
=> chore(fileuploader): starting docs

docs/cypress/e2e/links.cy.ts, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
Cherry pick 42b4617de41308b4deb6557d05ceb82c3be0e383 to `main`
=> chore(docs): fix links (#2960)

docs/next.config.js, docs/src/components/InstallScripts.tsx, docs/src/components/Layout/FrameworkChooser.tsx, docs/src/components/Layout/Sidebar.tsx, docs/src/data/frameworks.ts, docs/src/data/links.tsx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/custom-components.react-native.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/custom-components.react.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/custom-style.react-native.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/custom-style.react.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/getting-started.react-native.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/getting-started.react.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/use-messaging.react-native.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/examples/use-messaging.react.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/index.page.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/props/ReactPropsTable.tsx, docs/src/pages/[platform]/connected-components/in-app-messaging/props/index.ts, docs/src/pages/[platform]/connected-components/in-app-messaging/props/props.ts, docs/src/pages/[platform]/connected-components/in-app-messaging/props/styles.react-native.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/props/styles.react.mdx, docs/src/pages/[platform]/getting-started/installation/dependencies.react-native.mdx, docs/src/pages/[platform]/getting-started/introduction/index.page.mdx, docs/src/pages/[platform]/index.page.tsx, docs/src/utils/featureFlags.ts
Add React and React Native In-App Messaging UI feature documentation
=> chore(in-app-messaging): add in-app messaging documentation

docs/src/components/InstallScripts.tsx, docs/src/components/home/sections/HeroSection.tsx, docs/src/styles/docs/home.scss
Add a `hero` variant to the `TerminalCommand` on the docs home to improve the React Native experience:
---
---
---
NA
=> chore(docs): add hero variant to TerminalCommand

.github/workflows/publish-latest.yml
Temporarily skipping build test in `next-release/main`, since `build-test` is expected to fail until we and JS make the next release.
=> chore(ci): Temporarily skip `build-test`

docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/overview.react-native.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/overview.react.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/prereqs.react-native.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/prereqs.react.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/index.page.mdx
Update JS InApp Messaging links due to JS docs PR: https://github.com/aws-amplify/docs/pull/4828
=> chore(docs): update in-app links to js docs

packages/react-native/src/primitives/Checkbox/Checkbox.tsx, packages/react-native/src/primitives/Checkbox/__tests__/Checkbox.spec.tsx, packages/react-native/src/primitives/Checkbox/__tests__/__snapshots__/Checkbox.spec.tsx.snap, packages/react-native/src/primitives/Checkbox/index.ts, packages/react-native/src/primitives/Checkbox/styles.ts, packages/react-native/src/primitives/Checkbox/types.ts, packages/react-native/src/theme/types.ts
Theming for the checkbox primitive.
```
src/primitives/Checkbox                            |     100 |      100 |     100 |     100 |                   
Checkbox.tsx                                     |     100 |      100 |     100 |     100 |                   
index.ts                                         |       0 |        0 |       0 |       0 |                   
styles.ts                                        |     100 |      100 |     100 |     100 |                   
types.ts                                         |       0 |        0 |       0 |       0 |  
```
=> feat(ui-react-native): Add theming for Checkbox primitive

docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/overview.react.mdx
=> fix(docs): fix broken link

docs/src/pages/[platform]/components/autocomplete/props-table.mdx, docs/src/pages/[platform]/components/checkboxfield/props-table.mdx, docs/src/pages/[platform]/components/passwordfield/props-table.mdx, docs/src/pages/[platform]/components/phonenumberfield/props-table.mdx, docs/src/pages/[platform]/components/radiogroupfield/props-table.mdx, docs/src/pages/[platform]/components/searchfield/props-table.mdx, docs/src/pages/[platform]/components/selectfield/props-table.mdx, docs/src/pages/[platform]/components/sliderfield/props-table.mdx, docs/src/pages/[platform]/components/stepperfield/props-table.mdx, docs/src/pages/[platform]/components/switchfield/props-table.mdx, docs/src/pages/[platform]/components/textareafield/props-table.mdx, docs/src/pages/[platform]/components/textfield/props-table.mdx
Update props table in the repo.
It's a chore because even though we don't update it here, it was already auto-updated at the build time.
=> chore(docs): update props table

.github/workflows/publish-latest.yml, docs/src/pages/[platform]/components/autocomplete/props-table.mdx, docs/src/pages/[platform]/components/checkboxfield/props-table.mdx, docs/src/pages/[platform]/components/passwordfield/props-table.mdx, docs/src/pages/[platform]/components/phonenumberfield/props-table.mdx, docs/src/pages/[platform]/components/radiogroupfield/props-table.mdx, docs/src/pages/[platform]/components/searchfield/props-table.mdx, docs/src/pages/[platform]/components/selectfield/props-table.mdx, docs/src/pages/[platform]/components/sliderfield/props-table.mdx, docs/src/pages/[platform]/components/stepperfield/props-table.mdx, docs/src/pages/[platform]/components/switchfield/props-table.mdx, docs/src/pages/[platform]/components/textareafield/props-table.mdx, docs/src/pages/[platform]/components/textfield/props-table.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/overview.react.mdx
=> Docs release hotfix

packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/__tests__/__snapshots__/useAuthenticatorRoute.spec.ts.snap, packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/__tests__/utils.spec.ts, packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/constants.ts
=> fix(rna): add missing skipVerification value to VerifyUser props

docs/src/styles/docs/propsTable.scss
=> fix: props table expander focus style

packages/react-native/src/Authenticator/types.ts
Omit `formFields` prop
NA
Ran linting
=> chore(rna): omit formFields prop

docs/next.config.js, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
=> Docs migration fix

packages/ui/package.json, yarn.lock
=> chore(ui): add csstype devDep to ui package

packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/__tests__/__snapshots__/ConfirmResetPassword.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/__tests__/__snapshots__/ConfirmSignIn.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/ResetPassword/__tests__/__snapshots__/ResetPassword.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/__snapshots__/SetupTOTP.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/__snapshots__/SignIn.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/__snapshots__/SignUp.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/__snapshots__/VerifyUser.spec.tsx.snap, packages/react-native/src/Authenticator/common/FederatedProviderButton/__tests__/__snapshots__/FederatedProviderButton.spec.tsx.snap, packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/__snapshots__/FederatedProviderButtons.spec.tsx.snap, packages/react-native/src/primitives/Checkbox/__tests__/__snapshots__/Checkbox.spec.tsx.snap, packages/react-native/src/primitives/Divider/__tests__/__snapshots__/Divider.spec.tsx.snap, packages/react-native/src/primitives/Label/__tests__/__snapshots__/Label.spec.tsx.snap, packages/react-native/src/primitives/Label/styles.ts, packages/react-native/src/primitives/PasswordField/__tests__/__snapshots__/PasswordField.spec.tsx.snap, packages/react-native/src/primitives/PasswordField/styles.ts, packages/react-native/src/primitives/PhoneNumberField/__tests__/__snapshots__/PhoneNumberField.spec.tsx.snap, packages/react-native/src/primitives/Radio/__tests__/__snapshots__/Radio.spec.tsx.snap, packages/react-native/src/primitives/RadioGroup/__tests__/__snapshots__/RadioGroup.spec.tsx.snap, packages/react-native/src/primitives/TextField/TextField.tsx, packages/react-native/src/primitives/TextField/__tests__/__snapshots__/TextField.spec.tsx.snap, packages/react-native/src/primitives/TextField/styles.ts
=> chore(rna): update TextField style

packages/react-core/package.json
Remove `react-dom` peerDep from `ui-react-core`
=> chore(ui-react-core): remove react dom peerDep from ui-react-core

.changeset/grumpy-apricots-sparkle.md, packages/react/src/primitives/Autocomplete/__tests__/Autocomplete.test.tsx, packages/react/src/primitives/Autocomplete/useAutocomplete.tsx, packages/react/src/primitives/HighlightMatch/HighlightMatch.tsx
Update Autocomplete filter to be case insensitive and add unit tests
=> chore: update Autocomplete filter to be case insensitive

packages/react-native/src/theme/types.ts
=> chore(ui-react-native): omit checkbox from themed Components

packages/react-native/src/Authenticator/Authenticator.tsx, packages/react-native/src/Authenticator/__tests__/Authenticator.spec.tsx, packages/react-native/src/Authenticator/__tests__/__snapshots__/Authenticator.spec.tsx.snap, packages/react-native/src/Authenticator/__tests__/__snapshots__/withAuthenticator.spec.tsx.snap, packages/react-native/src/Authenticator/__tests__/withAuthenticator.spec.tsx, packages/react-native/src/Authenticator/common/DefaultContainer/DefaultContainer.tsx, packages/react-native/src/Authenticator/common/DefaultContainer/InnerContainer.tsx, packages/react-native/src/Authenticator/common/DefaultContainer/__tests__/__snapshots__/DefaultContainer.spec.tsx.snap, packages/react-native/src/Authenticator/common/DefaultContainer/styles.ts, packages/react-native/src/Authenticator/common/DefaultContainer/types.ts, packages/react-native/src/__mocks__/react-native-safe-area-context.ts, packages/react-native/src/utils/font.ts, packages/react-native/src/utils/index.ts, packages/react-native/src/utils/platform.ts, packages/react-native/src/utils/utils.ts
Refactor RNA `DefaultContainer` to prevent `TextField` components from getting covered by the keyboard. This is a v1 component, will be updated to allow programmatic positioning based on current focused input in the future.
NA
A ton of manual testing
=> chore(rna): refactor DefaultContainer

docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.react-native.mdx, docs/src/pages/[platform]/connected-components/authenticator/customization/i18n/i18n.react-native.mdx
=> chore(docs): Add I18n section for RN

docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/form-fields.react-native.mdx, docs/src/pages/[platform]/connected-components/authenticator/customization/index.page.mdx
=> chore(docs): RNA Form Field customization and Label hidden

packages/react-native/src/Authenticator/Defaults/SetupTOTP/SetupTOTP.tsx, packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/SetupTOTP.spec.tsx, packages/react-native/src/Authenticator/Defaults/SetupTOTP/styles.ts, packages/ui/src/helpers/authenticator/textUtil.ts
* add instructions about what to do with secret key
* style fixes
=> chore(ui-react-native): SetupTOTP small fixes

docs/src/pages/[platform]/connected-components/authenticator/customization/customization.headers-and-footers.react-native.mdx, docs/src/pages/[platform]/connected-components/authenticator/customization/index.page.mdx, examples/react-native/src/features/Authenticator/Basic/aws-exports.js, examples/react-native/src/features/Authenticator/Demo/Example.tsx, examples/react-native/src/features/Authenticator/Demo/aws-exports.js, examples/react-native/src/features/Authenticator/Fields/Example.tsx, examples/react-native/src/features/Authenticator/Fields/aws-exports.js, examples/react-native/src/features/Authenticator/LabelHidden/Example.tsx, examples/react-native/src/features/Authenticator/LabelHidden/aws-exports.js, examples/react-native/src/features/Authenticator/Slots/Example.tsx, examples/react-native/src/features/Authenticator/Slots/aws-exports.js, examples/react-native/src/features/Authenticator/Styles/Example.tsx, examples/react-native/src/features/Authenticator/Styles/aws-exports.js, examples/react-native/src/features/Authenticator/WithAuthenticator/Example.tsx, examples/react-native/src/features/Authenticator/WithAuthenticator/aws-exports.js
Also align all examples to use the same pattern for `aws-exports`
=> chore(docs): Add section for customizing slots

docs/src/pages/[platform]/connected-components/authenticator/customization/customization.override-function-calls.react-native.mdx, docs/src/pages/[platform]/connected-components/authenticator/customization/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/customization/overrides/username.react-native.mdx, examples/react-native/src/features/Authenticator/OverrideServices/Example.tsx, examples/react-native/src/features/Authenticator/OverrideServices/aws-exports.js
=> docs(rna): override function calls

docs/src/data/frameworks.ts, docs/src/pages/[platform]/getting-started/installation/dependencies.react-native.mdx
=> chore(docs): add expo quick start and missing rn vanilla dep

examples/react-native/ios/Podfile.lock, examples/react-native/package.json, packages/react-native/package.json, yarn.lock
=> chore(rna): remove picker dep

docs/src/pages/[platform]/connected-components/authenticator/DeveloperPreview.tsx, docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/customization/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/headless/index.page.mdx, docs/src/pages/[platform]/connected-components/authenticator/index.page.mdx
=> chore(docs): add dev preview banner on RNA

docs/src/components/home/sections/AuthenticationSection.tsx, docs/src/components/home/sections/CompatibleSection.tsx, docs/src/pages/[platform]/index.react-native.tsx
=> chore(docs): update react-native homepage

.changeset/happy-cats-agree.md
=> chore: Add RNA changeset

docs/src/pages/[platform]/connected-components/authenticator/customization/customization.headers-and-footers.react-native.mdx, docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.react-native.mdx
Fix typos on react native authenticator docs
=> fix(docs): fix typos on react native authenticator docs

docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.react-native.mdx
Remove link to "Protected Routes Guide" from RNA docs
fixes [3088](https://github.com/aws-amplify/amplify-ui/issues/3088)
=> fix(docs): remove unsupported link from rna docs

packages/react/src/components/Storage/FileUploader/__tests__/__snapshots__/FileUploader.test.tsx.snap, packages/ui/src/theme/__tests__/defaultTheme.test.ts, packages/ui/src/theme/__tests__/overrides.test.ts
=> fix(fileuploader): fix snapshots

docs/cypress/e2e/links.cy.ts, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx, docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx, docs/src/pages/[platform]/getting-started/usage/index.page.mdx
- fix a few links
- remove the # check from link checker. Because the `#` doesn't change the status code of a request, the test doesn't really check for if a # exist. A ticket is cut to follow up on the test.
=> fix(docs): links and link checker

docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/AcceptedFileTypesExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/AutoProceedExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/DefaultFileUploaderExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderComponentsExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderErrorExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderSuccessExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderThemeExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/IsPreviewerVisibleExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/MaxFilesExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/MaxSizeExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/MultipleExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/PreviewerComponentsExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/ResumableExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/ShowImagesExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/TrackerComponentsExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/UploadButtonComponentsExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/VariationExample.tsx, examples/next/pages/ui/components/storage/file-uploader/index.page.tsx, packages/react/src/components/Storage/FileUploader/FileUploader.tsx, packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx, packages/react/src/components/Storage/FileUploader/types.ts
=> chore(fileuploader): remove components api

.changeset/gold-kiwis-mate.md, packages/react/package.json, packages/ui/package.json
Adding "types" to react and UI package JSON
Fixes #2714
=> chore(react): adding types to exports in package json

docs/src/components/Layout/FrameworkChooser.tsx
Making the framework chooser links instead of buttons
=> chore(docs): fix framework switcher links

packages/ui/.eslintrc.js
Turn off `eslint:recommneded` `no-unused-vars` rule in favor of ` @typescript-eslint` `no-unused-vars` version to prevent false positives on TS constructs, for example `enum` types:
=> chore(ui): update eslint config to prefer @typescript-eslint no-unused-vars

docs/src/components/CopyButton.tsx, docs/src/pages/[platform]/connected-components/authenticator/amplify-cli.mdx
* use the TerminalCommand component so that there is a copy button
* Update the CopyButton code to not show the loader, it looks like it is broken...
| - | - |
| <img width="829" alt="CleanShot 2022-11-30 at 11 01 20@2x" src="https://user-images.githubusercontent.com/321279/204885791-6a2a1974-3d58-4867-ae65-dc222e87e78b.png"> <video src="https://user-images.githubusercontent.com/321279/204886227-5d2a49f4-201b-49f9-8c55-0e4907e62524.mp4" />  |  <video src="https://user-images.githubusercontent.com/321279/204885885-05d6f8a6-803c-4bca-9ba1-29aee312b749.mp4" /> |
=> chore(docs): add copy button to cli install instructions

package.json, yarn.lock
Add `highlight.js` resolution, fixes: 
- https://github.com/aws-amplify/amplify-ui/security/dependabot/52
- https://github.com/aws-amplify/amplify-ui/security/dependabot/53
=> chore(deps): add highlight.js resolution

packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx, packages/react/src/components/AccountSettings/DeleteUser/__tests__/__snapshots__/DeleteUser.test.tsx.snap, packages/react/src/components/AccountSettings/DeleteUser/defaults.tsx
Uses the new button variants from #3133.
https://user-images.githubusercontent.com/43682783/205743095-eed5769a-59ad-43f3-9ed4-4b556fcd2527.mp4
See video above, and also validated locally
=> feat(account-settings): use new button variants

.github/workflows/build-and-runtime-test.yml
This adds a way to upload artifacts when run and build errors fails.
=> chore(ci): Upload artifacts on error

.changeset/cold-hats-fix.md
Changeset for preview release 😈 
=> chore(account-settings): add changeset

docs/src/pages/[platform]/connected-components/account-settings/change-password/react.mdx, docs/src/pages/[platform]/connected-components/account-settings/delete-user/react.mdx
- Fix copy paste error
- Wrap example code in actual React app
- Fix typos `NewPassword` -> `NewPasswordField` (and same with other password field overrides)
=> docs(account-settings): fix typo + copy paste errors

.changeset/rotten-poems-exercise.md, examples/react-native/src/App/App.tsx, examples/react-native/src/features/Authenticator/Theming/aws-exports.js, packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/__tests__/__snapshots__/ConfirmResetPassword.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/__tests__/__snapshots__/ConfirmSignIn.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/ConfirmSignUp/__tests__/__snapshots__/ConfirmSignUp.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/__tests__/__snapshots__/ConfirmVerifyUser.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/ForceNewPassword/__tests__/__snapshots__/ForceNewPassword.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/ResetPassword/__tests__/__snapshots__/ResetPassword.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/__snapshots__/SetupTOTP.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/__snapshots__/SignIn.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/__snapshots__/SignUp.spec.tsx.snap, packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/__snapshots__/VerifyUser.spec.tsx.snap, packages/react-native/src/Authenticator/common/DefaultContent/DefaultContent.tsx, packages/react-native/src/Authenticator/common/DefaultContent/styles.ts, packages/react-native/src/Authenticator/common/DefaultContent/types.ts, packages/react-native/src/primitives/ErrorMessage/ErrorMessage.tsx, packages/react-native/src/primitives/ErrorMessage/__tests__/__snapshots__/ErrorMessage.spec.tsx.snap, packages/react-native/src/primitives/ErrorMessage/styles.ts, packages/react-native/src/primitives/ErrorMessage/types.ts
Update React Native `ErrorMessage` style
**Before:**
**After:**
=> fix(ui-react-native): update ErrorMessage style

packages/react/package.json, packages/ui/package.json, yarn.lock
=> chore: upgrade dependencies for AppSec

.github/workflows/version-packages.yml
`yarn version:latest` contains `yarn angular build`. This is only necessary for release but not for the "Version Packages" PR. Updating "Version Packages" workflow to omit `yarn angular build`.
=> fix(ci): fix version packages workflow

.github/workflows/version-packages.yml, package.json
Fixes
```
$ /home/runner/work/amplify-ui/amplify-ui/node_modules/.bin/changeset version '&&' yarn generateVersions
🦋  error Too many arguments passed to changesets - we only accept the command name as an argument
```
https://github.com/aws-amplify/amplify-ui/actions/runs/3707305180/jobs/6283556926#step:6:21
POC done in https://github.com/aws-amplify/amplify-ui/pull/3175, with branch at https://github.com/aws-amplify/amplify-ui/tree/fix-version-packages-poc
=> fix(ci): fix version packages workflow script

.github/ISSUE_TEMPLATE/1.bug_report.yaml, .github/ISSUE_TEMPLATE/2.feature_request.yaml
Update issue templates with new components
=> Update issue templates with new UI components

packages/react/src/primitives/Autocomplete/useAutocomplete.tsx, packages/react/src/primitives/Badge/__tests__/Badge.test.tsx, packages/react/src/primitives/Button/__tests__/Button.test.tsx, packages/react/src/primitives/ButtonGroup/__tests__/ButtonGroup.test.tsx, packages/react/src/primitives/Card/__test__/Card.test.tsx, packages/react/src/primitives/shared/__tests__/utils.test.tsx, packages/react/src/primitives/shared/utils.ts, packages/react/src/primitives/types/autocomplete.ts
Fixes TS Strict type errors for `Autocomplete`, `Badge`, `Button`, `ButtonGroup` and `Card`
=> chore: fix ts strict errors Autocomplete, Badge, Button, Card

docs/src/pages/[platform]/connected-components/storage/fileuploader/react.mdx
Fixes small typo in the file uploader docs:
=> chore: fix typo in fileuploader docs

.changeset/pretty-pumas-obey.md
This updates the changeset file for the Authenticator resetPassword and forceNewPassword password validation change.
=> chore: update Authenticator feature changeset file

.changeset/pretty-pumas-obey.md
fix: changeset to minor bump all packages using ui package
=> fix: changeset to minor bump all packages using ui

README.md
=> chore: update README to include new React primitives

.changeset/serious-pets-turn.md, examples/angular/src/pages/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.component.html, examples/angular/src/pages/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.component.ts, examples/next/pages/ui/components/authenticator/sign-in-totp-mfa/index.page.tsx, examples/vue/src/pages/ui/components/authenticator/sign-in-totp-mfa/index.vue, packages/e2e/cypress/integration/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.steps.ts, packages/e2e/features/ui/components/authenticator/sign-in-totp-mfa.feature, packages/e2e/package.json, packages/react-core/src/Authenticator/hooks/useAuthenticator/__tests__/__snapshots__/useAuthenticator.spec.tsx.snap, packages/react-core/src/Authenticator/hooks/useAuthenticator/__tests__/utils.spec.tsx, packages/react-core/src/Authenticator/hooks/useAuthenticator/types.ts, packages/react-core/src/Authenticator/hooks/useAuthenticator/useAuthenticator.tsx, packages/react-core/src/Authenticator/hooks/useAuthenticator/utils.ts, packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx, packages/react/src/components/Authenticator/SetupTOTP/__tests__/SetupTOTP.test.tsx, yarn.lock
The `totpIssuer` and `totpUsername` is not displaying after being updated
#3092 
Added test
=> fix(MFA Issuer React): MFA Issuer is not displaying

canary/apps/react/cra-ts/package.json, canary/apps/react/cra/package.json, guides/react/protected-routes/package.json
Babel fix is in place, so we can remove these overrides.
Fixes https://github.com/aws-amplify/amplify-ui/issues/3210
=> chore: revert babel plugin overrides

packages/react/jest.config.js
Bump unit test coverage thresholds
NA
`yarn react test`
=> chore(ui-react): bump unit test coverage thresholds

.changeset/eleven-beers-design.md, packages/react/src/components/Storage/FileUploader/FileUploader.tsx, packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
When uploading a zero byte file to the uploader it freezes
#3195 
Added test
=> fix(file-uploader): Zero byte file causes uploader to freeze

docs/src/pages/[platform]/theming/theme-provider/react.mdx
=> fix(docs): theming link

packages/angular/package.json, packages/angular/projects/ui-angular/src/setup.jest.ts, packages/angular/tsconfig.spec.json
Sets up `@testing-library/jest-dom` for #2875 and other primitive PRs to come.
=> chore(angular): set up @testing-library/jest-dom

docs/src/pages/[platform]/connected-components/storage/fileuploader/index.page.mdx
Fix the `Theme Source` link on https://www.dev.ui.docs.amplify.aws/react/connected-components/storage/fileuploader
=> fix(docs): file uploader link

.github/workflows/test-prs.yml
Add the [dependency review action](https://github.com/actions/dependency-review-action) to PR tests.
=> feat(ci): add dependency-review

packages/react/src/primitives/RadioGroupField/RadioGroupField.tsx
Fix `RadioGrpupField` linting issue caused by https://github.com/aws-amplify/amplify-ui/pull/3279
NA
`yarn react lint`
=> fix(ui-react): fix linting issue exposed post merge of #3265

canary/apps/react/cra/package.json
=> fix(cra): remove eslint config

docs/src/data/test/__snapshots__/props-table.test.ts.snap, packages/react/__tests__/__snapshots__/exports.ts.snap, packages/react/src/primitives/Expander/ExpanderItem.tsx, packages/react/src/primitives/Pagination/usePaginationItems.tsx, packages/react/src/primitives/ToggleButton/useToggleButton.ts, packages/react/src/primitives/types/pagination.ts, packages/react/src/primitives/types/toggleButton.ts
TS strict fixes for `Pagination`, `ExpanderItem`, `useToggleButton`
https://github.com/aws-amplify/amplify-ui/issues/1018
yarn build
=> fix(primitives): TS strict fixes for Pagination, ExpanderItem, useToggleButton

docs/cypress.config.ts
Adding `heapStatistics` so that we'll be able to see the information in the log, which will help us identify the memory leaking issue in Amplify Hosting.
```
{
total_heap_size: 116137984,
total_heap_size_executable: 6324224,
total_physical_size: 114786512,
total_available_size: 4261209728,
used_heap_size: 81930720,
heap_size_limit: 4345298944,
malloced_memory: 1581176,
peak_malloced_memory: 12804552,
does_zap_garbage: 0,
number_of_native_contexts: 1,
number_of_detached_contexts: 0
}
```
=> chore(docs): e2e test add heap Statistics

amplify.yml, docs/cypress.config.ts
Follow up https://github.com/aws-amplify/amplify-ui/pull/3320, to 
- add more space to `--max-old-space-size`
- add more logs
- Cypress log https://docs.cypress.io/guides/references/troubleshooting#Log-memory-and-CPU-usage
- Process memory usage log
=> chore(docs): link checker add space and logs

README.md
Update the README to include React Native and to add missing connected components
Viewed markdown preview
=> chore: update README to include RN / missing connected components

.github/workflows/build-and-runtime-test.yml
Fixes some minor typos.
Only typo changes
=> chore(workflows): fix typos in canary workflow

amplify.yml
=> chore: pin to flutter 3.3.10

examples/react-native/README.md
=> chore(rn): update readme

docs/src/pages/[platform]/getting-started/installation/fonts.web.mdx, docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx, docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx, docs/src/pages/[platform]/guides/auth-protected/auth-protected.react.mdx
Fix missing TerminalCommand imports
=> fix(docs): fix missing TerminalCommand import

docs/src/pages/[platform]/getting-started/installation/fonts.web.mdx, docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx, docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx, docs/src/pages/[platform]/guides/auth-protected/auth-protected.react.mdx
Co-authored-by: Heather Buchel <buchel@amazon.com>
=> fix(docs): fix missing TerminalCommand import (#3354)

docs/src/pages/[platform]/getting-started/installation/fonts.web.mdx, docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx, docs/src/pages/[platform]/guides/auth-protected/auth-protected.react.mdx
Fix the issue caused by https://github.com/aws-amplify/amplify-ui/pull/3339
=> fix(docs): import Tab, TabItem

docs/src/pages/[platform]/getting-started/installation/fonts.web.mdx, docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx, docs/src/pages/[platform]/guides/auth-protected/auth-protected.react.mdx
Co-authored-by: 0618 <o.6180339@gmail.com>
=> fix(docs): import Tab, TabItem (#3356)

packages/react/src/components/InAppMessaging/MessageLayout/MessageLayout.tsx, packages/react/src/components/InAppMessaging/MessageLayout/__tests__/MessageLayout.test.tsx, packages/react/src/components/InAppMessaging/MessageLayout/constants.ts
Add some unit tests to `MessageLayout`
=> chore(ui-react): add some unit tests to MessageLayout

.github/workflows/build-and-runtime-test.yml, examples/next/pages/ui/components/account-settings/delete-user/index.page.tsx
- Cypress test screenshots don't upload for the following error. Fixed it by changing the workflow matrix
> Error: Artifact name is not valid: canary-cypress-error-react/next. Contains the following character:  Forward slash /
- add user email to the account-setting/delete-user example to prevent accidental deletion.
=> fix(workflow): artifact upload error 

.github/workflows/build-and-runtime-test.yml, .github/workflows/publish-latest.yml, .github/workflows/publish-next.yml, .github/workflows/reusable-e2e.yml, environments/pull-environments.sh
This PR disables environment cache, and instead runs pull on every workflow.
Note that GHA has fixed issue with parallelization, so we take advantage of it here to speed up each pull.
POC is running on #3371.
- [![POC / Build and Runtime Canary Test](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-canary-test.yml/badge.svg)](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-canary-test.yml)
- [![POC / Test / PRs](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-test-prs.yml/badge.svg)](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-test-prs.yml)
- [![POC / Test and Publish / latest](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-publish-latest.yml/badge.svg)](https://github.com/aws-amplify/amplify-ui/actions/wor …
=> chore(ci): disable environment cache

docs/src/pages/[platform]/components/alert/react.mdx, docs/src/pages/[platform]/components/menu/index.page.mdx, docs/src/pages/[platform]/components/tabs/react.mdx
Update links found during the broken link check.
=> fix(docs): update redirectored external links

.changeset/red-moles-look.md, packages/react/src/hooks/useThemeBreakpoint.ts, packages/react/src/primitives/shared/styleUtils.ts, packages/ui/src/theme/breakpoints.ts
=> chore(theme): better typing for breakpoints

.changeset/gold-keys-applaud.md, docs/tests/__snapshots__/props-table.test.ts.snap, packages/react/src/primitives/Pagination/PaginationItem.tsx, packages/react/src/primitives/Pagination/usePagination.ts, packages/react/src/primitives/Pagination/usePaginationItems.tsx, packages/react/src/primitives/SwitchField/useSwitch.ts, packages/react/src/primitives/ToggleButtonGroup/ToggleButtonGroup.tsx, packages/react/src/primitives/ToggleButtonGroup/useToggleButtonGroup.tsx, packages/react/src/primitives/types/pagination.ts, packages/react/src/primitives/types/toggleButton.ts
Fixes to
* usePagination
* useSwitch
* useToggleButtonGroup
* ToggleButtonGroup
#1018 
=> chore(primitives): ts strict fixes for primitives

.github/workflows/test-prs.yml
This reverts commit 257ece5371af8d63991ec37c8a8333728dd1abc4.
=> [Don't Merge] PoC workflow

package.json, yarn.lock
Add `@sideway/formula` resolution to address:
* https://github.com/aws-amplify/amplify-ui/security/dependabot/80
The package is used in `react-native` and `react-native-example`:
```
❯ yarn why @sideway/formula
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@sideway/formula"...?
[2/4] 🚚  Initialising dependency graph...
...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@sideway/formula@3.0.0"
- "_project_#wait-on#joi" depends on it
- Hoisted from "_project_#wait-on#joi#@sideway#formula"
...
=> Found "react-native-example#@sideway/formula@3.0.0"
- "_project_#react-native-example#react-native#@react-native-community#cli#joi" depends on it
- Hoisted from …
```
=> chore(deps): Add sideway/formula resolution

packages/react-native/src/Authenticator/common/FederatedProviderButtons/FederatedProviderButtons.tsx, packages/react-native/src/primitives/Button/Button.tsx, packages/react-native/src/primitives/Radio/__tests__/Radio.spec.tsx, packages/react-native/src/primitives/Radio/getRadioDimensions.ts, packages/react-native/src/utils/index.ts, packages/react-native/src/utils/utils.ts, packages/ui/src/utils/__tests__/index.test.ts, packages/ui/src/utils/index.ts
Migrate `capitalize` util from `@aws-amplify/ui-react-native` to `@aws-amplify/ui` and add some unit tests
NA
=> chore(ui): migrate capitalize util

.changeset/strange-jokes-clean.md
Add missing changeset for https://github.com/aws-amplify/amplify-ui/pull/3416
=> chore(ui): add missing changeset for #3416

docs/src/components/Example.tsx, docs/src/components/InstallScripts.tsx, docs/src/pages/[platform]/guides/auth-protected/auth-protected.react.mdx, docs/src/styles/docs/install-code.scss
* Made the InstallScripts and ExampleCode copy buttons consistent
* Fixing some of the code blocks
Before
After
=> chore(docs): fix protected routes code examples

examples/react-native/src/App/App.tsx
This change  updates the name import of InAppMessaging demo app to match the component name in App.tsx.
Without this change, running smoke tests for InAppMessaging requires updating by hand before running.
=> chore(examples): Fix InAppMessaging demo app import

examples/next/pages/ui/components/account-settings/change-password/index.page.tsx
This fixes two bugs:
- typo in `onSuccess` message string
- success message would persist after signing out and signing in back in
- fixed this by using `withAuthenticator` so that the states get reset after unmounting.
Confirmed this code doesn't get used in docs, and also confirmed manually.
=> chore(examples): fix success message in change-password example

examples/next/pages/ui/components/in-app-messaging/demo/index.page.tsx, examples/next/pages/ui/components/in-app-messaging/demo/utils.ts
Update in-app-messaging demo app to use Analytics.record
With displayMessage from useInAppMessaging:
With Analytics.record:
=> chore: update in-app-messaging demo app to use Analytics.record

docs/cypress.config.ts, docs/cypress/e2e/links.cy.ts
Even though the Cypress broken link checker only works at local environment, it'd be helpful to have the page number information when running before release.
The log will look like this 
```
🎉 134 pages tested.
┌───────────────────────────────────────────────────────────────┬────────┐
│                            (index)                            │ Values │
├───────────────────────────────────────────────────────────────┼────────┤
│                            ......                             │        │
│                         react-native                          │   17   │
│        react-native/connected-components/authenticator        │   29   │
│ react-native/connected-components/authenticator/configuration │   25   │
│ react-native/connected-components/authenticator/customization …
```
=> test(docs): add total number of pages and links

.changeset/good-tables-serve.md, packages/react-native/package.json, packages/ui/package.json, packages/ui/src/theme/types.ts, packages/ui/src/types/util.ts, yarn.lock
Add `PartialDeep` utility type and remove `type-fest` dependency
=> chore(ui): remove type-fest

docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/DefaultFileUploaderExample.tsx, packages/react/src/components/Storage/FileUploader/FileUploader/FileUploader.tsx, packages/react/src/components/Storage/FileUploader/FileUploader/types.ts, packages/react/src/components/Storage/FileUploader/UploadDropZone/UploadDropZone.tsx, packages/react/src/components/Storage/FileUploader/UploadDropZone/__tests__/UploadDropZone.test.tsx, packages/react/src/components/Storage/FileUploader/UploadDropZone/types.ts, packages/react/src/components/Storage/FileUploader/UploadMessage/UploadMessage.tsx, packages/react/src/components/Storage/FileUploader/UploadMessage/__tests__/UploadMessage.test.tsx, packages/react/src/components/Storage/FileUploader/UploadMessage/types.ts, packages/react/src/components/Storage/FileUploader/UploadPreviewer/UploadPreviewer.tsx, packages/react/src/components/Storage/FileUploader/UploadPreviewer/__tests__/UploadPreviewer.test.tsx, packages/react/src/components/Storage/FileUploader/UploadPreviewer/types.ts, packages/react/src/components/Storage/FileUploader/UploadTracker/UploadTracker.tsx, packages/react/src/components/Storage/FileUploader/UploadTracker/__tests__/UploadTracker.test.tsx, packages/react/src/components/Storage/FileUploader/UploadTracker/types.ts, packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx, packages/react/src/components/Storage/FileUploader/displayText.ts
=> FileUploader strings refactor

.changeset/cold-bulldogs-fail.md, packages/react-native/.eslintrc.js, packages/react-native/src/Authenticator/hooks/useFieldValues/__tests__/useFieldValues.spec.ts, packages/react-native/src/InAppMessaging/components/InAppMessageDisplay/__tests__/InAppMessageDisplay.spec.tsx, packages/react-native/src/InAppMessaging/hooks/useMessageImage/__tests__/useMessageImage.spec.ts, packages/react-native/src/InAppMessaging/hooks/useMessageProps/__tests__/utils.spec.ts, packages/react-native/src/InAppMessaging/hooks/useMessageProps/utils.ts, packages/react-native/src/__mocks__/@react-native-community/netinfo.ts, packages/react-native/src/hooks/useDeviceOrientation/__tests__/useDeviceOrientation.spec.ts, packages/react-native/src/hooks/useDeviceOrientation/useDeviceOrientation.ts, packages/react-native/src/hooks/usePressableContainerStyles/usePressableContainerStyles.ts, packages/react-native/src/primitives/Carousel/Carousel.tsx, packages/react-native/src/primitives/Checkbox/__tests__/Checkbox.spec.tsx, packages/react-native/src/theme/createTheme.ts, packages/react-native/tsconfig.dist.json, packages/react-native/tsconfig.json
Add TS `noImplicitAny: true` for `dist` builds
- fix implicit `any` usage
- replace function type checks with `isFunction`
- clean up extraneous arrays in _.eslintrc.js_
- turn off https://typescript-eslint.io/rules/unbound-method/
=> chore(ui-react-native): set TS noImplicitAny to true

docs/package.json, packages/react-core/package.json, packages/react-core/tsconfig.json, packages/react-native/tsconfig.json, packages/react/tsconfig.json, packages/ui/package.json, packages/ui/tsconfig.json, yarn.lock
=> chore(tsconfig): align react, react-core, react-native, and ui tsconfig files

docs/src/components/home/HomeEditor.tsx
Ran docs build. Tested locally. No CSP error on homepage. 
=> chore(docs): fix final csp rule

.changeset/fuzzy-carrots-return.md, packages/ui/src/helpers/accountSettings/validator.ts, packages/ui/src/helpers/storage/fileUploader/utils/uploader.ts
Fixes TS strict errors in `ui/helpers/storage` and `ui/helpers/accountSettings`
`yarn ui test` 
=> fix(ui): TS strict errors in ui helpers

.changeset/friendly-schools-lay.md, packages/ui/src/theme/css/component/checkbox.scss, packages/ui/src/theme/css/component/radio.scss
Adding `position: relative` to radio and checkbox primitives to fix an issue with hidden inputs getting focus. 
Fixes #3165 
=> fix(primitives): fix hidden inputs breaking some interfaces

docs/scripts/data/constants.ts, docs/scripts/link-checker-puppeteer.ts, docs/scripts/util/checkLink.ts, docs/scripts/util/crawlAllLinks.ts
- It's a follow-up PR for https://github.com/aws-amplify/amplify-ui/pull/3494 to take special care of links from "https://docs.amplify.aws/"
- all-cap the constants https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const#examples
Tested on local and caught "https://docs.amplify.aws/lib/auth/getarted/q/platform/js" 
=> test(docs): check docs.amplify.aws

.github/workflows/reusable-e2e.yml
This PR is a follow-up for https://github.com/aws-amplify/amplify-ui/pull/3494.
After the AppSec approval, this PR is to enable the link checker on Github Action.
Tested on PoC PR https://github.com/0618/amplify-ui/pull/19
Happy path: https://github.com/0618/amplify-ui/actions/runs/4359021524/jobs/7620504997
Catch bad links: https://github.com/0618/amplify-ui/actions/runs/4359240980/jobs/7620799673
=> test(workflow): add pptr link checker

.github/workflows/reusable-e2e.yml
This reverts commit 743f271ddfa681ca7435bfb36bc3d4e405ba6662.
The link checker didn't work as expected https://github.com/aws-amplify/amplify-ui/actions/runs/4367802459/jobs/7639863231
=> Revert "test(workflow): add pptr link checker (#3516)"

.github/workflows/reusable-e2e.yml, packages/angular/package.json, packages/react-core/package.json, packages/react-native/package.json, packages/react/package.json, packages/ui/package.json, packages/vue/package.json
Add `test:ci` commands and update CI workflow. Follow up to https://github.com/aws-amplify/amplify-ui/pull/3515
=> chore(amplify-ui): add test:ci commands

.github/workflows/codeql.yml, .github/workflows/test-prs.yml
* Update workflows to process github context value through intermediate environment variables.
* Update version of `actions/github-script` from `0.3.0` to `6.4.0` and reference through commit sha.
Added `run-codeql` label: https://github.com/aws-amplify/amplify-ui/actions/runs/4369276594/jobs/7642888820
Added `run-tests` label: https://github.com/aws-amplify/amplify-ui/actions/runs/4369287597/jobs/7642916838
=> chore(ci): Process github context values through env vars

docs/src/data/links.tsx
Found the 301 from https://github.com/aws-amplify/amplify-ui/actions/runs/4387397015/jobs/7682890461
=> fix(docs): fix discord link

.changeset/tiny-eggs-eat.md, packages/react/package.json, yarn.lock
Bump `maplibre-gl-js-amplify` to the latest 3.0.5 as a follow-up item from last oncall week
=> chore: bump maplibre-gl-js-amplify to 3.0.5

.changeset/weak-toes-explode.md
=> chore: update feature changeset to minor bump

.github/workflows/test-prs.yml
=> chore(workflow): fix typo contributor

docs/src/pages/[platform]/components/shared/forwardRefAlert.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-add.react-native.mdx, docs/src/pages/[platform]/connected-components/authenticator/quick-start-example.react.mdx, docs/src/pages/[platform]/connected-components/geo/react.mdx, docs/src/pages/[platform]/connected-components/in-app-messaging/index.page.mdx, docs/src/utils/demoState.ts
This PR is to update redirected links caught by link checker https://github.com/aws-amplify/amplify-ui/actions/runs/4441848112/jobs/7797678711
=> docs(cra): update links

docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx, docs/src/pages/[platform]/getting-started/usage/create-react-app/react.mdx
- Add CRA 4 mjs trouble shooting
- Fix typo on CRA Geo components trouble shooting
- Change page organization
- Add alert saying that only CRA5 is supported
=> docs(cra): trouble shooting cra4

docs/src/pages/[platform]/connected-components/geo/react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx, docs/src/pages/[platform]/getting-started/migration/migration.react.mdx, docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx
- add `onAuthUiStateChange` to docs to make it searchable.
- React
- Vue
- Angular
- Geo Trouble Shooting
=> docs(auth): add alert for onAuthUiStateChange

.changeset/missing changeset for #3557
=> chore: adding missing changeset for #3557

.github/workflows/run-unit-on-fork.yml
This adds workflow for running unit tests against fork PRs.
Unit test will run on every commit to fork PRs, to help contributors catch test failures early.
POC running on #3569: 
https://github.com/aws-amplify/amplify-ui/actions/workflows/run-unit-on-fork.yml
=> ci: add `run-unit-on-fork.yml`

packages/e2e/features/ui/components/authenticator/modal.feature, packages/e2e/features/ui/components/authenticator/withAuthenticator.feature
This change fixes e2e scenarios for the Authenticator tests:
* point modal scenario to correct example
* remove `@skip` directives
`yarn e2e test:authenticator`
=> chore(e2e): fix scenarios for authenticator tests

.github/workflow-samples/tagged-release.yml, .github/workflows/test-account-settings-prs.yml
Add needs to specify order of job execution
=> ci: add needs to specify order of job execution

.github/workflows/tagged-release.yml
=> chore: add tagged release

.github/workflows/receive-fork-review.yml, .github/workflows/test-fork-prs.yml
Found few bugs after trying out GitHub's new GHA extension, as well as doing some manual testing on #3599.
POC in progress: https://github.com/aws-amplify/amplify-ui/actions/runs/4546060875/jobs/8014211459?pr=3601
Checked the fork workflow changes: https://github.com/wlee221/amplify-ui/pull/17
=> ci: workflow bug fixes

package.json, packages/react-auth/.eslintrc.js, packages/react-auth/.gitignore, packages/react-auth/LICENSE, packages/react-auth/README.md, packages/react-auth/jest.config.js, packages/react-auth/package.json, packages/react-auth/rollup.config.js, packages/react-auth/src/__tests__/__snapshots__/index.spec.ts.snap, packages/react-auth/src/__tests__/index.spec.ts, packages/react-auth/src/index.ts, packages/react-auth/src/styles.css, packages/react-auth/src/styles.ts, packages/react-auth/src/version.ts, packages/react-auth/tsconfig.dist.json, packages/react-auth/tsconfig.json
Add `@aws-amplify/ui-react-auth` package boilerplate
=> chore(ui-react-auth): add package boilerplate

package.json, packages/react-core-auth/.eslintrc.js, packages/react-core-auth/.gitignore, packages/react-core-auth/.lintstagedrc.js, packages/react-core-auth/CHANGELOG.md, packages/react-core-auth/LICENSE, packages/react-core-auth/README.md, packages/react-core-auth/jest.config.js, packages/react-core-auth/package.json, packages/react-core-auth/rollup.config.js, packages/react-core-auth/src/__tests__/__snapshots__/index.spec.ts.snap, packages/react-core-auth/src/__tests__/index.spec.ts, packages/react-core-auth/src/index.ts, packages/react-core-auth/tsconfig.dist.json, packages/react-core-auth/tsconfig.json
Add `@aws-amplify/ui-react-core-auth` package boilerplate
=> chore(ui-react-auth): add ui-react-core-auth boilerplate

packages/react/src/components/Storage/StorageManager/StorageManager/types.ts, packages/react/src/components/Storage/StorageManager/hooks/useStorageManager/reducer.ts, packages/react/src/components/Storage/StorageManager/hooks/useStorageManager/useStorageManager.tsx
=> chore: remove onFilesChange

packages/react-storage/src/components/StorageManager/StorageManager.tsx, packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts, packages/react-storage/src/components/StorageManager/types.ts
=> Add path prop to StorageManager

packages/react-storage/.lintstagedrc.js
Add `.lintstagedrc.js` to lint on precommit
=> chore(ui-react-storage): add .lintstagedrc.js

.github/workflows/reusable-unit.yml, packages/react-storage/package.json, packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileList.test.tsx, packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileStatusMessage.test.tsx, packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/__snapshots__/FileList.test.tsx.snap
Fix unit tests and add `react-storage` to unit test workflow.
=> chore(react-storage): Add more unit tests

packages/react-auth/.lintstagedrc.js
Add `.lintstagedrc.js` to lint precommit
=> chore(ui-react-auth): add .lintstagedrc.js

.github/workflows/reusable-e2e.yml
=> StorageManager fix e2e tests

docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerComponentOverridesExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerDisplayTextExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerProcessFileExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/index.ts, docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts, docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx, packages/react-storage/src/components/StorageManager/index.ts, packages/react-storage/src/index.ts
=> Storage Manager docs updates

packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx, packages/react-storage/src/components/StorageManager/__tests__/__snapshots__/StorageManager.test.tsx.snap, packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/actions.test.ts, packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/reducer.test.ts, packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/useStorageManager.test.ts, packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileList.test.tsx
* Fix FileList test
* Add tests for useStorageManager reducer, actions, hook
* Add more tests to bring coverage up to threshold
```
---------------------------------------------------|---------|----------|---------|---------|-------------------------------------------
File                                               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                         
---------------------------------------------------|---------|----------|---------|---------|-------------------------------------------
All files                                          |   92.18 |    80.27 |   85.71 |   92.02 |   
```
=> chore(react-storage): Add remaining unit tests

.github/workflows/reusable-unit.yml, packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileControl.test.tsx, packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileThumbnail.test.tsx
Fix unit test workflow dependencies and linter errors.
[![POC / Test / Fork / Unit](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-run-unit-on-fork.yml/badge.svg)](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-run-unit-on-fork.yml)
=> chore(react-storage): Fix workflow and lint errors

packages/ui/src/theme/css/component/StorageManager/storageManager.scss, packages/ui/src/theme/tokens/components/index.ts, packages/ui/src/theme/tokens/components/storagemanager.ts
=> chore: add storagemanager to theme

docs/src/components/propsTable/ReactPropsTable.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/AutoUploadExample.tsx, docs/src/pages/[platform]/connected-components/storage/fileuploader/react.mdx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/DefaultStorageManagerExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerComponentOverridesExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerDisplayTextExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerEventExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerFileTypesExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerProcessFileExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerResumableExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerThemeExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManageri18nExample.tsx, docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/index.ts, docs/src/pages/[platform]/connected-components/storage/storagemanager/index.page.mdx, docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx, docs/tests/__snapshots__/cssvars-table.test.ts.snap
=> chore: update storagemanager docs

packages/react-storage/package.json, yarn.lock
Add missing ui-react dep, update ui-react-core dep version
=> fix(ui-react-storage): add missing ui-react dep, update ui-react-core dep version

.changeset/my-bad.md
=> fix: bump ui package

docs/scripts/link-checker-puppeteer.ts, docs/scripts/util/checkLink.ts
- Update comment to make it more readable.
- Update error message for internal unnecessary 308
=> docs(docs): update link checker comments and error msg

.github/workflows/reusable-e2e.yml
Run docs e2e before link checker tests
e2e tests are skipped if link checker tests fails (in cases where there are new pages added)
=> ci: run docs e2e before link checker tests

packages/react-auth/package.json, packages/react-core-auth/package.json
Update ui, ui-react, and ui-react-core versions used in auth packages
=> chore(ui-react-auth): update internal dep versions

packages/react-liveness/jest.config.js
=> chore: update react-liveness function coverage

docs/src/components/InstallScripts.tsx
=> fix: install script for base package

.github/workflows/test-internal-prs.yml
- Temporarily switched branch to liveness-main to get e2e testing passing in PR, switching it back to main now that we have merged
=> chore: switch e2e branch back to main from liveness-main

.changeset/pink-pillows-impress.md, packages/react-liveness/src/components/FaceLivenessDetector/StartLiveness/StartLiveness.tsx, packages/react-liveness/src/components/FaceLivenessDetector/displayText.ts, packages/react-liveness/src/components/FaceLivenessDetector/utils/getDisplayText.ts
- add legal disclaimer to Liveness component
=> chore(liveness): add legal disclaimer

.github/workflows/test-fork-prs.yml
`test-fork-prs.yml` was missing `LIVENESS_E2E_ROLE_ARN` secret.
Copied directly from https://github.com/aws-amplify/amplify-ui/blob/3fa0a29f21dd72db02c24e90fa03843fabea9330/.github/workflows/test-internal-prs.yml#L126.
=> ci: add missing liveness secret to `test-fork-prs.yml`

.changeset/pink-pillows-impress.md, .changeset/soft-walls-know.md, packages/react-liveness/src/components/FaceLivenessDetector/StartLiveness/StartLiveness.tsx, packages/react-liveness/src/components/FaceLivenessDetector/displayText.ts, packages/react-liveness/src/components/FaceLivenessDetector/utils/getDisplayText.ts
This reverts commit 83569f1bf138773903c06682b3caf84d47c39e8f.
- Queueing up a PR to remove legal text change since we are not sure if it will be required
=> Revert "chore(liveness): add legal disclaimer (#3695)"

docs/src/pages/[platform]/connected-components/liveness/QuickStartReact.tsx, docs/src/pages/[platform]/connected-components/liveness/customization/customization.theming.react.mdx, docs/src/pages/[platform]/connected-components/liveness/customization/index.page.mdx, docs/src/pages/[platform]/connected-components/liveness/index.page.mdx
- Update meta description
- Add sentence describing video 
- Add link to YouTube video
- Add warning about liveness demo not working and that its just for demo-ing the theme example (like we do for i18n)
- Add best practices section about customizations
=> chore: update liveness docs
