aws-amplify/amplify-ui

- .changeset/hungry-lizards-melt.md
- packages/ui/src/i18n/dictionaries/authenticator/it.ts
> Fix italian grammar in translation and improve accuracy

- examples/next/pages/ui/components/in-app-messaging/basic-usage-hoc/aws-exports.js
- examples/next/pages/ui/components/in-app-messaging/basic-usage-hoc/index.page.tsx
- examples/next/pages/ui/components/in-app-messaging/basic-usage-provider/aws-exports.js
- examples/next/pages/ui/components/in-app-messaging/basic-usage-provider/index.page.tsx
- examples/next/pages/ui/components/in-app-messaging/override-component/aws-exports.js
- examples/next/pages/ui/components/in-app-messaging/override-component/index.page.tsx
- examples/next/pages/ui/components/in-app-messaging/override-styling/index.page.tsx
Add In-App Messaging NextJS example apps:
- basic usage with `InAppMessagingProvider`
- basic usage with `withInAppMessaging`
- component override
- update style override
NA
Manually tested sample apps
> feat(in-app-messaging): add NextJS example apps

- amplify.yml
recent build failed with the following errors:
```
2022-11-07T19:56:01.173Z [INFO]: # Executing command: npm install
2022-11-07T19:56:17.417Z [WARNING]: npm
2022-11-07T19:56:17.419Z [WARNING]: WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1102.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-optimizer@0.1102.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE } …
```
> test: change npm to yarn

- canary/apps/angular/angularcli/package.json
- canary/apps/react/cra-ts/package.json
- canary/apps/react/cra/package.json
- canary/apps/react/next/package.json
- canary/apps/react/vite/package.json
- canary/apps/react/vite3/package.json
- canary/apps/vue/vite/package.json
- canary/apps/vue/vite3/package.json
- canary/apps/vue/vuecli/package.json
- docs/package.json
- examples/angular/package.json
- examples/next/package.json
- examples/vue/package.json
- guides/react/protected-routes/package.json
- packages/react-core/package.json
- packages/react-native/package.json
- packages/react/package.json
- packages/react/src/hooks/useDataStore.tsx
- packages/react/src/primitives/types/datastore.ts
- packages/ui/package.json
- yarn.lock
Removes workarounds for DataStore types in https://github.com/aws-amplify/amplify-ui/pull/2922
NA
Ran type checking, linting and unit tests in ui-react, built other packages
> chore(next-release): update useDataStoreCollection param types

- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/Previewer/index.tsx
- packages/react/src/components/Storage/FileUploader/Tracker/FileState.tsx
- packages/react/src/components/Storage/FileUploader/Tracker/__tests__/FileState.test.tsx
- packages/react/src/components/Storage/FileUploader/Tracker/index.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
- packages/react/src/components/Storage/FileUploader/types.ts
- packages/ui/src/helpers/storage/fileUploader/utils/uploader.ts
- packages/ui/src/theme/css/component/fileUploader.scss
Added the ability for uploads to be resumable or not. In doing so had to write a hack to fix the Storage lib's code. 
Need some help on my Typescript. 
https://user-images.githubusercontent.com/321279/200904115-714aaf32-631a-4cf8-ad37-e909a9a960d2.mp4
> feat: add resumable as a prop

- canary/apps/angular/angularcli/package.json
- canary/apps/react/cra-ts/package.json
- canary/apps/react/cra/package.json
- canary/apps/react/next/package.json
- canary/apps/react/vite/package.json
- canary/apps/react/vite3/package.json
- canary/apps/vue/vite/package.json
- canary/apps/vue/vite3/package.json
- canary/apps/vue/vuecli/package.json
Due to the latest JS update, we are setting our canaries to run on v4 for now.
> chore(canary): Updated canaries to v4

- docs/src/components/Layout/PageTabLayout.tsx
**Issue**: When using a link with `?tab=props` on a component's page, the tab doesn't change to the Props tab. e.g. https://ui.docs.amplify.aws/react/components/flex?tab=props
https://user-images.githubusercontent.com/11983489/201013047-b19384fc-bfd9-40de-a958-366781fb788c.mov
**Reason**: the `tab` param is an empty string first and then updated, but since the value's already set, the component won't re-render.
**Fix**: update whenever `tab` changes.
**Other code change**: before this PR, `PageTabLayout` component only works for `props` tab in the current scenario. This PR makes `PageTabLayout` generic.
Local and Amplify Hosting https://fix-pagetablayout.drxs1ztvfjtps.amplifyapp.com/
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix(docs): url param to set tab

- packages/e2e/features/ui/components/authenticator/hub-events.feature
SignUp wasn't getting mocked in `hub-events.feature` tests, and was throwing SES limit errors.
> fix(e2e): mock sign up call in autosignin test

- docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx
This edits migration guide:
- align each subtitle to read "`@aws-amplify/ui-react@4.x` does something"
- Prefer `@aws-amplify/ui-react@4.x` over pronoun "we"
- remove passive voices
- no comment in JSON
> docs(next-release): improve wordings in migration guide

- .github/workflows/publish-latest.yml
This was only a temporarily workaround to get v4 release process unblocked, and is ready to be reverted after release stabilizes.
> Revert "chore(ci): Temporarily skip `build-test`"

- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/Previewer/__tests__/Previewer.test.tsx
- packages/react/src/components/Storage/FileUploader/Previewer/__tests__/__snapshots__/Previewer.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/Previewer/index.tsx
- packages/react/src/components/Storage/FileUploader/Tracker/__tests__/Tracker.test.tsx
- packages/react/src/components/Storage/FileUploader/Tracker/__tests__/__snapshots__/Tracker.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/Tracker/index.tsx
- packages/react/src/components/Storage/FileUploader/UploadButton/index.tsx
- packages/react/src/components/Storage/FileUploader/UploadDropZone/__tests__/__snapshots__/UploadDropZone.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/UploadDropZone/index.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/__snapshots__/FileUploader.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/types.ts
* Editing a file name is now cancel-able. Edits to the filename are in a local state rather than global
* Removed `isEditing` in place of the existing 'editing' fileStatus
* Added some visually hidden text for icon buttons and `ariaHidden` for icons
* Made sure input is not tab-able
* Auto-focus file name text input after hitting edit button and save after pressing enter
https://user-images.githubusercontent.com/321279/201443669-9f9fd503-1138-40c7-9e27-7296d4d10959.mp4
https://user-images.githubusercontent.com/321279/201730985-25d6bd20-5991-4be1-b22b-a1b96a80f23a.mp4
> feat(fileuploader): cancel file name edit, a11y improvements

- .github/workflows/publish-account-settings.yml
Now that most of account settings component, we're now ready to start running tagged release to `@account-settings`. This will run on every merge to `account-settings/main` (just like how we release `@next`), and will be available for preview purposes. 
> ci(account-settings): start publishing to `@account-settings` tag

- .changeset/many-masks-play.md
- packages/react/src/primitives/Button/Button.tsx
- packages/react/src/primitives/Button/__tests__/Button.test.tsx
This change fixes an issue where the Button loading spinner is not rendered unless the `loadingText` prop is supplied, which is contrary to what our docs state:
https://github.com/aws-amplify/amplify-ui/blob/11c7d9c602af211cd0b378742e8975f936d61fc5/packages/react/src/primitives/types/button.ts#L28-L33
Also added unit test to catch any potential future regressions.
| Before  | After |
| ------------- | ------------- |
|<img width="1215" alt="Screen Shot 2022-11-13 at 10 47 57 AM" src="https://user-images.githubusercontent.com/68251134/201539319-98524963-84ec-460c-a7b3-9da098bd94e6.png">  | <img width="1217" alt="Screen Shot 2022-11-13 at 10 47 09 AM" src="https://user-images.githubusercontent.com/68251134/201539333-d05d7a21-198a-4d23-804c-948a981f9802.png">  |
Fixes: #2914 
By submitting …
> fix(button): Fix loading state for Button

- .changeset/gorgeous-pumas-glow.md
- .changeset/loud-apes-fail.md
- packages/react/src/hooks/__tests__/useDataStore.test.ts
- packages/react/src/primitives/shared/__tests__/datastore.test.ts
- packages/react/src/primitives/shared/datastore.ts
This change updates the  `useDataStore` hook to generate predicates in accordance with the new syntax: https://docs.amplify.aws/lib/datastore/data-access/q/platform/js/#predicates.
To make this future-proof, e2e tests that don't rely on mocks need to be added as follow-up.
> fix(ui-react): Update useDataStore hook predicate generation logic

- packages/react-native/src/Authenticator/Defaults/VerifyUser/VerifyUser.tsx
- packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/VerifyUser.spec.tsx
In `VerifyUser`, radio buttons were submitting its actual phone/email value like so:
```json
{
"unverifiedAttr": "example@example.com"
}
```
but underlying state machine expects just the string `"email"` or `"phone_number"` and not its actual value. 
This PR updates `VerifyUser` to use `name` instead of `value` for its form handling.
New unit tests!
> fix(rna): update radio button to submit name instead of value

- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
- packages/react/src/components/Storage/FileUploader/hooks/useFileUploader/types.ts
- packages/react/src/components/Storage/FileUploader/hooks/useFileUploader/useFileUploader.tsx
- packages/react/src/components/Storage/FileUploader/types.ts
Added new prop `autoProceed` that will automatically start the download after a file is selected, instead of waiting for the customer to click the upload button.
[Asana](https://app.asana.com/0/1203303459000520/1203373828802431)
Test
> feat(file-uploader): Prop for Auto Proceed

- examples/next/pages/ui/components/storage/file-uploader/index.page.tsx
- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/Tracker/__tests__/Tracker.test.tsx
- packages/react/src/components/Storage/FileUploader/Tracker/index.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
- packages/react/src/components/Storage/FileUploader/types.ts
This new prop allows customers to turn on or off images to display in the tracker component
[Asana](https://app.asana.com/0/1203303459000520/1203373828802426)
Add test
> feat(file-uploader): Prop to turn off or on images in Tracker

- packages/react-core/src/Authenticator/hooks/types.ts
- packages/react-core/src/Authenticator/hooks/useAuthenticator/__mock__/useAuthenticator.ts
- packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/__tests__/__snapshots__/useAuthenticatorRoute.spec.ts.snap
- packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/__tests__/utils.spec.ts
- packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/constants.ts
- packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/types.ts
- packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/utils.ts
Remove extraneous `totpIssuer` and `totpUsername` keys from `SetupTOTPProps` as RNA does not generate a QR code
NA
Ran tests
> chore(rna): remove web only keys from SetupTOTPProps

- packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/__tests__/utils.spec.ts
- packages/react-core/src/Authenticator/hooks/useAuthenticatorRoute/utils.ts
Fixes memoization issue in `useAuthenticatorRoute`. The default selector was too restrictive, because it kept its memoization even when `route` changed. 
This PR changes the default selectors to always include "route".
> fix(rna): Fix memoization issue in `useAuthenticatorRoute`

- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
- packages/react/src/components/Storage/FileUploader/types.ts
- packages/ui/src/helpers/storage/fileUploader/utils/__tests__/uploader.test.tsx
- packages/ui/src/helpers/storage/fileUploader/utils/index.ts
- packages/ui/src/helpers/storage/fileUploader/utils/uploader.ts
After some discuss with @dbanksdesign we are removing the `fileNames` prop, since it is not obvious to use. Also added warning if users add the file-uploader without the correct props.
Removed test not needed
> chore(file-uploader): Removed fileNames prop and added warning for users for required props

- .changeset/good-donuts-obey.md
- packages/react/src/primitives/Autocomplete/Autocomplete.tsx
- packages/react/src/primitives/Autocomplete/__tests__/Autocomplete.test.tsx
- packages/react/src/primitives/Autocomplete/useAutocomplete.tsx
- packages/react/src/primitives/types/autocomplete.ts
In a special case(#3030), opening dropdown menu on focus is annoying.
Fix #3030 
Add new unit tests 
> fix(Autocomplete): remove handler to open menu on focus

- packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/__tests__/__snapshots__/ConfirmResetPassword.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/__tests__/__snapshots__/ConfirmSignIn.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/ConfirmSignUp/__tests__/__snapshots__/ConfirmSignUp.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/ResetPassword/__tests__/__snapshots__/ResetPassword.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/__snapshots__/SetupTOTP.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/__snapshots__/SignIn.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/__snapshots__/SignUp.spec.tsx.snap
- packages/react-native/src/Authenticator/common/DefaultContent/styles.ts
- packages/react-native/src/Authenticator/common/DefaultContent/types.ts
- packages/react-native/src/primitives/PasswordField/PasswordField.tsx
- packages/react-native/src/primitives/PasswordField/__tests__/PasswordField.spec.tsx
- packages/react-native/src/primitives/PasswordField/__tests__/__snapshots__/PasswordField.spec.tsx.snap
- packages/react-native/src/primitives/PhoneNumberField/__tests__/__snapshots__/PhoneNumberField.spec.tsx.snap
- packages/react-native/src/primitives/TextField/TextField.tsx
- packages/react-native/src/primitives/TextField/__tests__/TextField.spec.tsx
- packages/react-native/src/primitives/TextField/__tests__/__snapshots__/TextField.spec.tsx.snap
- packages/react-native/src/primitives/TextField/styles.ts
- packages/ui/src/helpers/authenticator/textUtil.ts
This change addresses accessibility issues found by XCode Accessibility inspector:
* Hit area was too small for all text fields
* For text fields with accessory the icon button was not announced by voiceover
Things I was looking out for with voiceover:
* labels being announced multiple times
* fields/buttons not being announced at all
Only issue remaining is about Dynamic text not being supported. 
Also fixed a small issue with secondary button styling:
> chore(ui-react-native): Fix accessibility audit issues

- examples/react-native/src/App/App.tsx
- examples/react-native/src/features/Authenticator/Fields/Example.tsx
- examples/react-native/src/features/Authenticator/LabelHidden/Example.tsx
- packages/react-native/src/Authenticator/hooks/types.ts
- packages/react-native/src/Authenticator/hooks/useFieldValues/__tests__/useFieldValues.spec.ts
- packages/react-native/src/Authenticator/hooks/useFieldValues/useFieldValues.ts
Add `labelHidden` support and example apps for hiding labels and passing custom fields
> chore(rna): add labelHidden support and example apps

- .changeset/popular-pigs-glow.md
- packages/react/src/components/ThemeProvider/__tests__/ThemeProvider.test.tsx
- packages/react/src/components/ThemeProvider/index.tsx
- packages/ui/src/theme/createTheme.ts
One use-case of theming is to extend from a theme, for example the Studio generated theme. To do this, customers pass in the studio theme as the 2nd argument to the `createTheme` method. The issue is `createTheme` returns a `WebTheme` type and not a `Theme` type which is what the `ThemeProvider` expects. Loosening up the type of the `ThemeProvider` theme prop to allow either `Theme` or `WebTheme`
```javascript
const theme = createTheme({
}, studioTheme);
<ThemeProvider theme={theme}>
</ThemeProvider>
```
> fix(theme): update types for ThemeProvider to accept output of createTheme

- package.json
- yarn.lock
To resolve two dependabot issues:
- https://github.com/aws-amplify/amplify-ui/security/dependabot/62
- https://github.com/aws-amplify/amplify-ui/security/dependabot/63
> chore: Upgrade loader-utils from 2.0.3 to 2.0.4

- .changeset/small-planes-train.md
- packages/ui/src/theme/css/component/radio.scss
Added `flex-shrink` to the radio button so if the label is too large it doesn't get squeezed. 
fixes #2756
|-|-|
| <img width="618" alt="CleanShot 2022-11-22 at 15 20 19@2x" src="https://user-images.githubusercontent.com/321279/203440690-28969a3a-00a0-4e0a-b2a8-067101438a03.png"> |  <img width="613" alt="CleanShot 2022-11-22 at 15 04 31@2x" src="https://user-images.githubusercontent.com/321279/203440716-9573e48f-0943-4660-9642-51e9db3499a5.png"> |
> fix(primitives): fix radio button sizing issue

- canary/e2e/cypress/integration/common/shared.ts
- canary/e2e/yarn.lock
Fix Cypress issue caused by removal of unused `window` [here](https://github.com/aws-amplify/amplify-ui/pull/3113/files#diff-8b4dccfced007ccaaefa5311e071983452d0f44c47a192e73c9228aebb6b2287L9)
NA
Ran canary e2e tests for:
- `vue/vite3`
- `angular`
- `react/next`
> fix(canaries): remove window variable mutation

- .changeset/fuzzy-icons-jog.md
- packages/ui/src/theme/css/component/autocomplete.scss
Disable scroll chaining on Autocomplete to improve UX.
When Autocomplete menu scroll boundary is reached, the underlying page will then start to scroll. This could be annoying for users.
After disabling it, the outer page will not start to scroll when the bottom is reached even though I keep scrolling
> style: disable scroll chaining on Autocomplete menu to improve UX

- packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
- packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
- packages/react/src/components/AccountSettings/DeleteUser/__tests__/DeleteUser.test.tsx
- packages/react/src/components/AccountSettings/DeleteUser/__tests__/__snapshots__/DeleteUser.test.tsx.snap
- packages/react/src/components/AccountSettings/DeleteUser/defaults.tsx
- packages/react/src/components/AccountSettings/DeleteUser/types.ts
Enables component override in `DeleteUser`.
New unit tests!
> feat(account-settings): Enable component override for <DeleteUser />

- .changeset/many-cats-allow.md
- packages/ui/src/theme/css/component/alert.scss
Adding `color` to the alert default styles to prevent color contrast issues because the color is being inherited. The design token already existed, we just weren't using it. 
fixes #2610
| - | - |
| <img width="1584" alt="CleanShot 2022-12-01 at 15 11 31@2x" src="https://user-images.githubusercontent.com/321279/205179504-0e44cb0c-b155-43b0-abd7-8d8d3bf06c06.png"> |  <img width="1580" alt="CleanShot 2022-12-01 at 15 11 08@2x" src="https://user-images.githubusercontent.com/321279/205179523-b8b34dd0-a984-445a-b844-ae2a9a25eb73.png"> |
> fix(primitives): fix default text color for alert primitive

- .changeset/pretty-crews-repeat.md
- packages/ui/src/theme/__tests__/themeType.test.ts
- packages/ui/src/theme/tokens/components/button.ts
- packages/ui/src/theme/tokens/components/collection.ts
- packages/ui/src/theme/tokens/components/fileUploader.ts
- packages/ui/src/theme/tokens/components/heading.ts
- packages/ui/src/theme/tokens/components/link.ts
- packages/ui/src/theme/tokens/components/rating.ts
- packages/ui/src/theme/tokens/components/select.ts
- packages/ui/src/theme/tokens/components/stepperField.ts
- packages/ui/src/theme/tokens/components/switchField.ts
- packages/ui/src/theme/tokens/components/table.ts
- packages/ui/src/theme/tokens/components/text.ts
- packages/ui/src/theme/tokens/components/textAreaField.ts
- packages/ui/src/theme/tokens/components/textField.ts
In the large theme type refactor @calebpollman and I did, there were some misses. Some component theme types were not marking all properties as optional, which causes some TS issues. This fixes those issues and adds a test to ensure this doesn't happen again
Tests pass (after making the test which failed)
> fix(theme): making all component tokens optional

- packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
- packages/react/src/components/AccountSettings/ChangePassword/__tests__/ChangePassword.test.tsx
- packages/react/src/components/AccountSettings/ChangePassword/defaults.tsx
- packages/react/src/components/AccountSettings/ChangePassword/types.ts
- packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
- packages/react/src/components/AccountSettings/DeleteUser/__tests__/DeleteUser.test.tsx
- packages/react/src/components/AccountSettings/DeleteUser/defaults.tsx
- packages/react/src/components/AccountSettings/DeleteUser/types.ts
- packages/react/src/components/AccountSettings/types.ts
Update `AccountSettings` subcomponent names and types
NA
`yarn react lint && yarn react test`
> chore(AccountSettings): update subcomponent names and types

- packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
Changes the order of early returns, so that it checks `isLoading` before it checks `!user`. This ensures that component does not prematurely log that user isn't present to console.
> fix(account-settings): early return if `isPending` is true

- docs/src/pages/[platform]/connected-components/account-settings/change-password/props.ts
Docs shows `Error alert that displays on delete user errors` for `Change Password` component. This fix updates that text.
> fix(change password docs): Update component overrides docs on change password ErrorMessage

- packages/ui/src/i18n/dictionaries/authenticator/it.ts
Missing quote mark in italian translation
running react native app, looking at the sign in screen, seeing the non translated text
re-running react native app. adding 
```
I18n.putVocabularies({
it: {
'Forgot Password?': 'Password Dimenticata?',
},
});
acknowledging the string is correctly translated
Then reporting the fix into amplify-ui repo 
```
- [x ] PR description included
> Italian translation - fix

- docs/src/components/home/sections/A11ySection.tsx
- docs/src/components/home/sections/AmplifySection.tsx
- docs/src/components/home/sections/AuthenticationSection.tsx
- docs/src/components/home/sections/CompatibleSection.tsx
- docs/src/components/home/sections/FigmaSection.tsx
- docs/src/components/home/sections/HeroSection.tsx
- docs/src/components/home/sections/LiveSection.tsx
- docs/src/components/home/sections/PrimitiveSection.tsx
- docs/src/components/home/sections/ThemingSection.tsx
- docs/src/styles/docs/base.scss
This change an animation to the heading on the main docs page, making the text expand outward as it's being rendered.
Manual test in Chrome, Safari and firefox.
> chore(docs): Add expand animation to headings

- .github/workflows/publish-latest.yml
- .github/workflows/publish-next.yml
- .github/workflows/reusable-e2e.yml
- .github/workflows/reusable-tagged-publish.yml
- .github/workflows/version-packages.yml
This is continuation of https://github.com/aws-amplify/amplify-ui/pull/2755. GitHub Actions has a caching issue  https://github.com/actions/cache/issues/810, which causes cache step to be stuck indefinitely. See [example](https://github.com/aws-amplify/amplify-ui/actions/runs/3734904700/jobs/6337614939) for a recent workflow.
Resolving this by adding timeout to cache steps. If cache doesn't get restored during that timeout, it'll abort cache download and recompute the cache. 
Set the timeout to 2 minutes, because this step usually took 20~40 seconds. Gave it a padding for any network slowdown issues. 
Followed the same code changes I used in #2755.
> chore(ci): Add timeout to setup-node

- docs/cypress/e2e/links.cy.ts
- docs/src/components/Layout/FrameworkChooser.tsx
**Issue**: on the components overview page (https://ui.docs.amplify.aws/react/components), the framework chooser 1)  add a `#` to the disabled links and 2) all the links are pointing to react (unimportant since they are disabled). 
Also The wrong links breaks the tests in links.cy.ts.
**Fix**: remove the link from disabled frameworks
> fix(docs): Framework chooser link for components overview

- packages/react-native/src/InAppMessaging/components/BannerMessage/__tests__/BannerMessage.spec.tsx
- packages/react-native/src/InAppMessaging/components/BannerMessage/__tests__/__snapshots__/BannerMessage.spec.tsx.snap
- packages/react-native/src/InAppMessaging/components/CarouselMessage/CarouselMessage.tsx
- packages/react-native/src/InAppMessaging/components/CarouselMessage/__tests__/CarouselMessage.spec.tsx
- packages/react-native/src/InAppMessaging/components/CarouselMessage/__tests__/CarouselMessageItem.spec.tsx
- packages/react-native/src/InAppMessaging/components/CarouselMessage/__tests__/__snapshots__/CarouselMessage.spec.tsx.snap
- packages/react-native/src/InAppMessaging/components/FullScreenMessage/__tests__/FullScreenMessage.spec.tsx
- packages/react-native/src/InAppMessaging/components/InAppMessageDisplay/__tests__/InAppMessageDisplay.spec.tsx
- packages/react-native/src/InAppMessaging/components/MessageWrapper/__tests__/MessageWrapper.spec.tsx
- packages/react-native/src/InAppMessaging/components/ModalMessage/__tests__/ModalMessage.spec.tsx
- packages/react-native/src/InAppMessaging/components/ModalMessage/__tests__/__snapshots__/ModalMessage.spec.tsx.snap
- packages/react-native/src/InAppMessaging/components/withInAppMessaging/__tests__/withInAppMessaging.spec.tsx
- packages/react-native/src/InAppMessaging/constants.ts
- packages/react-native/src/primitives/Carousel/__tests__/Carousel.spec.tsx
- packages/react-native/src/primitives/Carousel/__tests__/CarouselPageIndicator.spec.tsx
- packages/react-native/src/primitives/Carousel/__tests__/__snapshots__/Carousel.spec.tsx.snap
- packages/react-native/src/primitives/Carousel/types.ts
This change refactors existing React Native tests to use @testing-library instead of react-test-renderer. Also adds some assertions and tests to improve coverage.
> chore(ui-react-native): Refactor unit tests

- canary/apps/react/cra-ts/package.json
Apparently we've been running the cra-ts canary against version 2 of our library and never `latest`, so this fixes that.
> fix: update ts canary to run ui-react latest

- canary/apps/react/cra-ts/package.json
- canary/apps/react/cra/package.json
- guides/react/protected-routes/package.json
cra app no longer using `npm install`, so updating the fix for "@babel/plugin-transform-block-scoping" to yarn compatible `resolutions`
Update cra app babel plugin override since `cra` now using `yarn install` and not `npm install` like I previously thought.
> fix: update cra app babel plugin override

- docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/form-fields.web.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/orderformfields/form-fields.angular.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/orderformfields/form-fields.react.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/orderformfields/form-fields.vue.mdx
Documentation for the sign up fields order for the authenticator is not clear. If customers copy this code they may see an issue where the fields repeat. Added note to make it clear how to use the code and added sign up attributes prop.
#2699
Docs update, manually
> fix(docs): Added note on zero configuration on sign up fields

- .changeset/rich-peaches-trade.md
- packages/e2e/cypress/fixtures/force-reset-password.json
- packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature
- packages/ui/src/machines/authenticator/actions.ts
- packages/ui/src/machines/authenticator/actors/resetPassword.ts
When customer imports a set of users, and the users log in for the first time, they never receive an email for them to reset their password.
#2488 
Added e2e test
> fix(forced password reset): Update logic for emails sent out on forced password reset

- packages/react/package.json
Add back the `--ext` flag and file types for the `lint` command removed in https://github.com/aws-amplify/amplify-ui/pull/3204
NA
Ran linting with erroneous code to validate errors would be picked up
> fix(ui-react): fix lint command

- .github/workflows/codeql.yml
This adds logic for manually running `codeql` when `run-codeql` label is added, just like `run-tests` label.
POC'd on this PR: 
> chore(ci): manually run codeql when `run-codeql` label is added

- .changeset/smart-masks-drop.md
- packages/ui/src/theme/css/component/image.scss
- packages/ui/src/theme/css/styles.scss
Chrome 108 has a breaking change https://developer.chrome.com/blog/overflow-replaced-elements/ on how it handles image clipping. 
This specifically breaks our customers because we do `unset: all` on `amplify-image`, which also unsets `overflow` too. This needs to be set to `clip` (see above blog). 
> fix(react): Manually add overflow: clip to fix chrome regression

- packages/react/package.json
- yarn.lock
We do not need `degit` in our repo now. Remove it in the PR
> chore: remove unused degit

- package.json
- yarn.lock
Fix prototype pollution in JSON5 
https://github.com/aws-amplify/amplify-ui/security/dependabot/76
> fix: fix json5 vulnerability

- package.json
- yarn.lock
This is a miss from #3233. `nth-check` resolution is still needed:
```
=> Found "svgo#nth-check@1.0.2"
- "react-scripts#@svgr#webpack#@svgr#plugin-svgo#svgo#css-select" depends on it
```
CI
> chore(deps): Add nth-check to resolutions

- .github/workflows/build-and-runtime-test.yml
- .github/workflows/publish-next.yml
- .github/workflows/reusable-e2e.yml
Uploads cypress videos and screenshots on CI failures. We did this for canaries in https://github.com/aws-amplify/amplify-ui/pull/3138, but not for other tests.
Did a poc in #3234, where I intentionally failed the tests and confirmed that videos/images get uploaded as expected.
- e2e: [link](https://github.com/aws-amplify/amplify-ui/actions/runs/3802683371)
- canary: [link](https://github.com/aws-amplify/amplify-ui/actions/runs/3802683352)
- guides: [link](https://github.com/aws-amplify/amplify-ui/actions/runs/3802683354)
> chore(ci): upload cypress videos/screenshots on failure

- .changeset/tasty-icons-join.md
- docs/src/data/test/__snapshots__/props-table.test.ts.snap
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/primitives/Tabs/Tabs.tsx
- packages/react/src/primitives/Tabs/__tests__/Tabs.test.tsx
- packages/react/src/primitives/types/tabs.ts
There are 2 separate issues here:
1. TS issue where `null` is not allowed as a child of `Tabs`
2. A tangential issue where passing `null` as a child messes up the tab indices: https://codesandbox.io/s/async-flower-772qr1?file=/src/App.js
#3256
> fix(tabs): fixing null tabs

- .changeset/young-foxes-hide.md
- packages/e2e/features/ui/components/storage/fileuploader/upload-image-to-s3.feature
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/__tests__/UploadPreviewer.test.tsx
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/__tests__/__snapshots__/UploadPreviewer.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/index.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
The text for file selected and uploaded are wrong when only 1 file is selected or uploaded. 
[Asana](https://app.asana.com/0/1203642744275140/1203495483940621)
Added test
> fix(file-uploader): Updated selected and uploaded text for singular files

- .changeset/gorgeous-pants-check.md
- docs/src/data/test/__snapshots__/props-table.test.ts.snap
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/primitives/View/View.tsx
- packages/react/src/primitives/View/__tests__/View.test.tsx
- packages/react/src/primitives/types/base.ts
Adds support for the HTML `inert` attribute: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert
React elements do not support the prop by default, so adding it in to make it work like any other HTML attribute. 
#2632
Added unit test and also tried it on the docs site:
> feat(primitives): support inert prop

- .changeset/purple-badgers-greet.md
- packages/angular/projects/ui-angular/src/lib/primitives/password-field/__tests__/__snapshots__/password-field.component.test.ts.snap
- packages/angular/projects/ui-angular/src/lib/primitives/password-field/password-field.component.html
- packages/vue/src/components/__tests__/__snapshots__/password-control.spec.ts.snap
- packages/vue/src/components/password-control.vue
#2875 *removed* some classnames to match passwordfield parity. But this was a breaking change and so this PR adds them back.
All the additive changes in #2875 are still preserved.
> chore(angular,vue): add back classnames removed in #2875

- .changeset/tricky-days-rule.md
- packages/ui/src/helpers/authenticator/formFields/__tests__/formFields.spec.ts
- packages/ui/src/helpers/authenticator/formFields/formFields.ts
Remove `order` value from `formFields` after sorting to prevent passing it to `TextField` components
Fixes #3281 
Manually tested React, Angular, Vue and React Native example apps. Added unit test
> fix(authenticator): remove order keys from formFields after sorting

- .changeset/nine-ears-think.md
- packages/react/src/primitives/RadioGroupField/RadioGroupField.tsx
- packages/react/src/primitives/RadioGroupField/__tests__/RadioGroupField.test.tsx
This PR addresses the accessibility issues identified in [this PR](https://github.com/aws-amplify/amplify-ui/issues/1805) through the following changes (inspired by this [blog post](https://adrianroselli.com/2022/07/use-legend-and-fieldset.html#Hide)):
- Render the outer `Flex` as a `fieldset` element
- Include a visually-hidden `legend` element
- Add `aria-hidden="true"` to the visible label
I was able to confirm the changes on web and my own iOS device using VoiceOver. For iOS, VoiceOver says `“{label} form start”` and then `Form end` at the end of the RadioGroup. Before these changes it didn't say anything about the user being inside a form or group. 
https://user-images.githubusercontent.com/48109584/211429842-b9877c16-e4e2-46f2-9d07-2dabae1cc623.mov
Fixes: …
> fix(ui-react): Add fieldset and legend to RadioGroupField

- packages/react/src/primitives/Alert/Alert.tsx
- packages/react/src/primitives/Alert/AlertIcon.tsx
- packages/react/src/primitives/types/autocomplete.ts
Fixes TS Strict errors in Alert and Autocomplete primitives.
yarn react build
> fix(primitives): fixes ts strict errors Alert/Autocomplete

- canary/apps/.gitignore
- canary/apps/.yarnrc
- canary/apps/angular/angularcli/.npmrc
- canary/apps/react/cra-ts/.npmrc
- canary/apps/react/cra/.npmrc
- canary/apps/react/next/.npmrc
- canary/apps/react/vite/.npmrc
- canary/apps/react/vite3/.npmrc
- canary/apps/vue/vite/.npmrc
- canary/apps/vue/vite3/.npmrc
- canary/apps/vue/vuecli/.npmrc
This PR disables lockfile generation in canary apps in `canary/apps`, for both yarn and npm. This will prevent **local development** from generating lockfiles in your directory, which can be misleading when you're debugging canary apps. 
The purpose of canary test is to check whether these apps work against latest downstream dependency, so this PR aligns with that purpose. Note that CI/CD [already does this](https://github.com/aws-amplify/amplify-ui/blob/fd9e863629976447bac3b3a8183ff30634d83ebb/.github/workflows/build-and-runtime-test.yml#L38).
locally.
> chore(canary): disable lockfile generation in `canary/apps`

- .changeset/purple-insects-move.md
- docs/README.md
- docs/src/data/test/__snapshots__/props-table.test.ts.snap
- packages/react/.eslintrc.js
- packages/react/src/primitives/Tabs/Tabs.tsx
- packages/react/src/primitives/Tabs/__tests__/Tabs.test.tsx
- packages/react/src/primitives/Text/__test__/Text.test.tsx
- packages/react/src/primitives/ToggleButton/useToggleButton.ts
- packages/react/src/primitives/ToggleButtonGroup/ToggleButtonGroup.tsx
- packages/react/src/primitives/ToggleButtonGroup/useToggleButtonGroup.tsx
- packages/react/src/primitives/types/autocomplete.ts
- packages/react/src/primitives/types/select.ts
Lint primitives `T*` - `Z*`
NA
`yarn react lint && yarn react test`
> chore(ui-react): lint primitives (T - Z)

- packages/react/package.json
Add missing bundle size checks for FileUploader, AccountSettings, and InAppMessaging
This adds bundle size checks for ui-react package - InAppMessaging, AccountSettings and FileUploader
ran `yarn react size`, and added 10kB over the current size.
> fix: add more bundle size checks

- .changeset/small-stingrays-admire.md
- examples/next/pages/ui/components/storage/file-uploader/index.page.tsx
- packages/react/src/components/Storage/FileUploader/UploadTracker/__tests__/__snapshots__/UploadTracker.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/UploadTracker/index.tsx
- packages/react/src/primitives/shared/constants.ts
- packages/react/src/primitives/shared/types.ts
- packages/ui/src/helpers/storage/fileUploader/utils/uploader.ts
- packages/ui/src/theme/__tests__/defaultTheme.test.ts
- packages/ui/src/theme/__tests__/overrides.test.ts
- packages/ui/src/theme/css/component/fileUploader.scss
- packages/ui/src/theme/tokens/components/fileUploader.ts
- packages/ui/src/types/primitives/componentClassName.ts
The max file size error message, is short, and confusing. This PR adds more information to the max file size errors. 
Also in smaller screens the message gets cut off. So now it's on its own line. 
[Asana](https://app.asana.com/0/1202067479136208/1203495483940613/f)
Before:
Updated text:
Updated snapshots
> fix(file-uploader): Make over max file size errors more verbose

- packages/react/src/primitives/shared/datastore.ts
Add type predicates for usage `createDataStorePredicate` with to allow TS strict mode
> chore(ui-react): strict type createDataStorePredicate

- packages/ui/src/theme/createTheme.ts
- packages/ui/src/theme/utils.ts
- packages/ui/src/types/style-dictionary.d.ts
Built the UI package with TS strict turned on (there are still other errors, but none in the theme section) and ran tests
> chore(ui): make theme code ts strict

- packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
- packages/react/src/components/AccountSettings/ChangePassword/defaults.tsx
- packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
- packages/react/src/components/AccountSettings/types.ts
- packages/react/src/components/shared/ValidationErrors.tsx
Fixes `strict: true` errors in the Account Settings components.
> chore(account-settings): fix strict ts errors for account settings components

- docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx
Adds migration guide to how to use legacy s3 or chatbot components. This uses npm alias trick to do so.
#3169
Ran locally:
> docs(angular): add migration notes for legacy components

- .changeset/strong-mugs-enjoy.md
- packages/ui/src/helpers/storage/fileUploader/utils/__tests__/uploader.test.tsx
- packages/ui/src/helpers/storage/fileUploader/utils/uploader.ts
When uploading files using the file uploader the content type is never set. Instead all content types default to `binary/octet-stream`. This causes an issue since files like svg won't have the correct contentType in S3 storage. When using `Storage.get` the file cannot be displayed in an `image` tag with the wrong content type.
To fix this now all uploads will default to the correct file type listed in the `file.type`. If none exists it will fall back to `binary/octet-stream`
Users can still change this by updating the prop `contentType` if needed back to `binary/octet-stream` for all uploads.
#3257 
Added additional tests
> fix(file-uploader): Add default contentType for Uploads

- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.react-native.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.web.mdx
Previous link: https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/translations.ts
Updated link: https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/en.ts
Fixes: https://github.com/aws-amplify/amplify-ui/issues/3310
> fix(docs): Change docs link to Authenticator translation keys

- .changeset/purple-hotels-tease.md
- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/__tests__/UploadPreviewer.test.tsx
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/index.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
- packages/react/src/components/Storage/FileUploader/types.ts
The maximum number of files error message was not clear. Added more explicit text.
Updated error text
Updated text for test that tests out message when user is over max file limit
> fix(file-uploader): Added better error text for over max files

- .changeset/afraid-maps-speak.md
- packages/react/src/components/Storage/FileUploader/UploadTracker/index.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
To adhere to best practices, we are swapping the placement of the save and cancel buttons when editing a file.
Before
After
We have extensive tests that test edit and save.
> fix:(file-uploader): Swap Save and Cancel Button

- .changeset/thirty-kangaroos-develop.md
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/__tests__/__snapshots__/UploadPreviewer.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/index.tsx
To adhere to best practices, we are swapping the placement of the upload and clear all buttons when uploading a file.
Before:
After:
Test cases cover these buttons , regenerated snap shot
> fix:(file-uploader): Swap Upload and Clear all Buttons

- .changeset/stale-rabbits-pretend.md
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileUploaderThemeExample.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/MaxFilesExample.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/react.mdx
- examples/next/pages/ui/components/storage/file-uploader/index.page.tsx
- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/__tests__/UploadPreviewer.test.tsx
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/index.tsx
- packages/react/src/components/Storage/FileUploader/__tests__/FileUploader.test.tsx
- packages/react/src/components/Storage/FileUploader/types.ts
Renamed the `maxFiles` prop to `maxFilesCount` as discussed [here](https://github.com/aws-amplify/amplify-ui/pull/3344#discussion_r1086899622)
updated tests
> fix(fileUploader): Rename maxFiles to maxFilesCount

- docs/src/pages/[platform]/components/tabs/TabsPropControls.tsx
- docs/src/pages/[platform]/components/tabs/demo.tsx
- docs/src/pages/[platform]/components/tabs/useTabsProps.tsx
Docs demo should not be controlled otherwise the copied code is not workable out of the box. This confused me either if I do not look into it carefully. Also, it does not make sense to have a select to update the current index because you can switch to a disabled tab via it 🥴 
> docs(fix): update tabs demo to be uncontrolled

- docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.angular.mdx
- docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.react-native.mdx
- docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.react.mdx
- docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.vue.mdx
There's been significant customer confusion on how to use the `useAuthenticator` hook/composable/service. In particular customers have been trying to use it without the Authenticator UI, which causes unexpected behavior (since the state machine isn't initialized). This PR adds a notice to the headless page for each framework each headless that the hook should be used alongside the Authenticator UI components. 
Angular:
React:
React Native:
Vue:
Fixes: https://github.com/aws-amplify/amplify-ui/issues/2657
`yarn doc dev`
> chore(docs): add clarification for auth hook usage

- .changeset/popular-news-perform.md
- packages/react/src/primitives/Autocomplete/__tests__/Autocomplete.test.tsx
- packages/react/src/primitives/PasswordField/__tests__/PasswordField.test.tsx
- packages/react/src/primitives/PhoneNumberField/__tests__/PhoneNumberField.test.tsx
- packages/react/src/primitives/RadioGroupField/RadioGroupField.tsx
- packages/react/src/primitives/RadioGroupField/__tests__/RadioGroupField.test.tsx
- packages/react/src/primitives/SearchField/__tests__/SearchField.test.tsx
- packages/react/src/primitives/SelectField/SelectField.tsx
- packages/react/src/primitives/SelectField/__tests__/SelectField.test.tsx
- packages/react/src/primitives/SliderField/SliderField.tsx
- packages/react/src/primitives/SliderField/__tests__/SliderField.test.tsx
- packages/react/src/primitives/StepperField/__tests__/StepperField.test.tsx
- packages/react/src/primitives/TextAreaField/TextAreaField.tsx
- packages/react/src/primitives/TextAreaField/__tests__/TextAreaField.test.tsx
Adds missing `amplify-field--${size}` class to some components that were missing it on their `.amplify-field` wrapper. This was causing those components to not get the proper flex gap and font size.  Updated tests across components for size class. 
**Affected components:**
- SelectField
- RadioGroupField
- TextAreaField
- SliderField
**Before**
Notice how labels/form controls for affected components do not line up across the text fields when placed in a row.
**After**
Fixes https://github.com/aws-amplify/amplify-ui/issues/3346
> fix(react): add missing size field classes to some form field components

- docs/src/pages/[platform]/components/phonenumberfield/react.mdx
- docs/src/pages/[platform]/components/radiogroupfield/react.mdx
- docs/src/pages/[platform]/components/stepperfield/react.mdx
- docs/src/pages/[platform]/components/textareafield/react.mdx
- docs/src/pages/[platform]/components/textfield/react.mdx
Fixes typo on all the field primitive docs that support the `isReadOnly` prop.
1. ran yarn docs dev
2. smoke tested each page
> chore: fix typo on field primitive docs

- .changeset/tidy-fans-clean.md
- packages/ui/src/theme/types/style-dictionary.d.ts
- packages/ui/src/theme/utils.ts
> chore: ts strict fixes for ui theme

- docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/form-fields.angular.mdx
Reorder the Angular Authenticator setup steps because they confused me. 😅 Updated so that the TS formFields changes are done before trying to use formFields in the html template.
Validated that page renders in right order now:
> chore: reorder angular authenticator docs

- .changeset/tame-dolphins-swim.md
- packages/react/src/components/Storage/FileUploader/UploadTracker/__tests__/__snapshots__/UploadTracker.test.tsx.snap
- packages/react/src/components/Storage/FileUploader/UploadTracker/index.tsx
Moved edit pencil icon
Before:
After:
Based on Asana and this [discussion](https://github.com/aws-amplify/amplify-ui/pull/3349#issuecomment-1404326011)
Updated snapshot
> chore(file-uploader): Move edit icon in between picture and text

- packages/react/src/components/InAppMessaging/hooks/useMessageProps/utils.ts
Fixes the final TS Strict error in InAppMessaging!
> chore: fix inappmessaging ts strict errors

- .changeset/silent-jeans-bake.md
- packages/react/package.json
- yarn.lock
Bump `maplibre-gl-js-amplify` to `3.0.2`.
Fixes  #3367 #3393.
yarn build
> chore: bump maplibre-gl-js-amplify to 3.0.2

- examples/react-native/metro.config.js
Prevent metro bundler start up from breaking due to the lookup of `.DS_Store/package.json` by resolving only used internal packages
> fix(example/react-native): filter unused internal packages from metro package lookup

- .github/workflows/build-and-runtime-test.yml
- .github/workflows/poc-build-and-runtime-test.yml
Set explicit usage of `node@v16` in the "Build and Runtime Tests" workflow to prevent issues with `node@v18` and the Vue CLI
NA
https://github.com/aws-amplify/amplify-ui/actions/runs/4207700712
> fix(ci): set build-and-runtime workflow node version to 16

- docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx
- docs/src/pages/[platform]/connected-components/authenticator/headless/advanced/useAuthenticator.react.mdx
* Fix link to protected guides on the Headless Usage react page.
* Fix link to quick start page from Authenticator Configuration pages to stay on same framework
Fixes: 
> fix(docs): broken internal links

- .changeset/selfish-timers-deliver.md
- packages/react-native/src/Authenticator/common/DefaultContainer/DefaultContainer.tsx
Removes `keyboardVerticalOffset` logic passed to the `KeyboardAvoidingView` of the RNA `DefaultContainer` component to improve the end user DX input focus events
Closes https://github.com/aws-amplify/amplify-ui/issues/3444
Manually tested on iOS and Android
> refactor(ui-react-native): update default keyboardVerticalOffset handling of RNA DefaultContainer

- packages/react/src/components/Storage/FileUploader/FileUploader/FileUploader.tsx
- packages/react/src/components/Storage/FileUploader/FileUploader/types.ts
- packages/react/src/components/Storage/FileUploader/FileUploader/utils.ts
- packages/react/src/components/Storage/FileUploader/UploadDropZone/UploadDropZone.tsx
- packages/react/src/components/Storage/FileUploader/UploadDropZone/types.ts
- packages/react/src/components/Storage/FileUploader/UploadMessage/UploadMessage.tsx
- packages/react/src/components/Storage/FileUploader/UploadMessage/types.ts
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/UploadPreviewer.tsx
- packages/react/src/components/Storage/FileUploader/UploadPreviewer/types.ts
- packages/react/src/components/Storage/FileUploader/UploadTracker/UploadTracker.tsx
- packages/react/src/components/Storage/FileUploader/UploadTracker/types.ts
- packages/react/src/components/Storage/FileUploader/hooks/useFileUploader/useFileUploader.ts
- packages/react/src/components/Storage/FileUploader/types.ts
Small refactor, moving types to comonent folders and reording import statements
> chore: move types to component folders

- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/LevelExample.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/react.mdx
Fixes issue where the first sample code in FileUploader docs will break for customers because it doesn't include the required `accessLevel` prop. It currently uses the `level` prop, which was renamed to `accessLevel`, which means if customers copy the existing code sample it will not work, leading to a broken customer experience.
Before fix (current UI Docs site: https://ui.docs.amplify.aws/react/connected-components/storage/fileuploader#file-level-access)
TS error as shown in LevelExample demo file:
After fix:
> fix(docs): fix invalidfileuploader code sample

- .changeset/brown-mails-pull.md
- packages/ui/src/theme/tokens/components/autocomplete.ts
- packages/ui/src/theme/tokens/components/checkbox.ts
Make theme design tokens optional for AutoComplete and Checkbox primitives. This was causing an issue where customers couldn't provide partial overrides to the theme without getting a TS error. See:
https://github.com/aws-amplify/amplify-ui/pull/3468/files#r1116349656
Opened the theme examples and checked that TS errors were gone.
- [z] PR description included
> fix(ui): make theme design tokens optional

- .changeset/good-cooks-crash.md
- packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
- packages/react/src/primitives/Collection/Collection.tsx
- packages/ui/src/machines/authenticator/actors/signIn.ts
- packages/ui/src/machines/authenticator/signUp.ts
- packages/ui/src/theme/utils.ts
- packages/ui/src/utils/index.ts
- packages/ui/src/validators/index.ts
This PR is a follow up fix to https://github.com/aws-amplify/amplify-ui/pull/3373. This PR broke TS Strict, and was creating TS errors at build time like so:
`yarn build` against ec881c6a8aab507636816e3b3560fcabb87f59c8 (against [tagged release](https://github.com/aws-amplify/amplify-ui/actions/runs/4068624270/jobs/7007902895#step:10:22)):
```
Error: node_modules/@aws-amplify/ui/dist/types/utils/index.d.ts:7:37 - error TS7016: Could not find a declaration file for module 'lodash/debounce.js'. '/Users/willeea/Documents/spark/angular-15/amplify-app/node_modules/lodash/debounce.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash/debounce.js';`
7 export { default as debounce } from …
```
> fix(ui): use lodash imports directly 

- packages/react/src/primitives/Field/FieldClearButton.tsx
- packages/react/src/primitives/Icon/icons/IconClose.tsx
- packages/react/src/primitives/SearchField/SearchFieldButton.tsx
Aligns the close icon correctly in SearchField and Autocomplete. The size of the icons (IconClose, IconSearch) adapt to the size of the fields: small, default, large. 
**Before:** 
**After:**
**Affected components:**
- SearchField
- Autocomplete
- IconClose (internal)
#3465 
@calebpollman  This is my first contribution to this project. If I have I have missed something, let me know what I can improve.
> fix(react): close icon alignment and size SearchField and Autocomplete

- .changeset/nasty-lies-hunt.md
- packages/react/src/components/Authenticator/Authenticator.tsx
- packages/react/src/helpers/constants.ts
- packages/react/src/hooks/useComposeRefsCallback.tsx
- packages/react/src/primitives/Alert/Alert.tsx
- packages/react/src/primitives/Autocomplete/Autocomplete.tsx
- packages/react/src/primitives/Autocomplete/useAutocomplete.tsx
- packages/react/src/primitives/Checkbox/useCheckbox.ts
- packages/react/src/primitives/SearchField/useSearchField.tsx
- packages/react/src/primitives/SliderField/SliderField.tsx
- packages/react/src/primitives/StepperField/useStepper.ts
- packages/react/src/primitives/SwitchField/useSwitch.ts
- packages/react/src/primitives/ToggleButton/useToggleButton.ts
- packages/react/src/primitives/ToggleButtonGroup/useToggleButtonGroup.tsx
- packages/react/src/primitives/shared/utils.ts
- packages/ui/src/utils/__tests__/index.test.ts
- packages/ui/src/utils/index.ts
Migrate `isFunction` to `@aws-amplify/ui`:
- add `isFunction` unit tests
- update util tests in `@aws-amplify/ui` to use `toBe` in place of `toStrictEqual`, which is used for object matching: https://jestjs.io/docs/expect#tostrictequalvalue
- replace usage of `typeof SOME_VALUE === 'function` in `@aws-amplify/ui-react`
> chore(ui): migrate isFunction util to ui package

- .changeset/healthy-beds-warn.md
- packages/react-native/src/primitives/Carousel/Carousel.tsx
Remove extraneous optional chaining and remove some casting in `Carousel`
> chore(ui-react-native): remove extraneous optional chaining

- packages/react/package.json
- packages/react/tsconfig.json
- yarn.lock
Add `@types/mapbox__mapbox-gl-draw` to allow removal of the `skipLibCheck` TS compiler option
Related https://github.com/aws-amplify/maplibre-gl-js-amplify/issues/205
> chore(ui-react): remove skipLibCheck

- .changeset/little-bears-hide.md
- packages/react/src/primitives/Pagination/PaginationItem.tsx
Fixes TS strict errors in `PaginationItem` component due to `onClick` possibly being undefined.
> fix: ts strict errors in paginationitem

- docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.angular.mdx
Adds docs on how to polyfill `global` and `process` on Angular 15.
Angular 15 doesn't create `src/polyfills.ts` anymore (see "CLI improvements" section on [blog](https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8)), so developers need to manually create that file now.
https://user-images.githubusercontent.com/43682783/223600470-a0a00509-8ee7-4678-a0a5-02886038c7fd.mp4
> docs(angular): Add troubleshooting for Angular 15 polyfills

- docs/scripts/data/constants.ts
- docs/scripts/util/checkLink.ts
- docs/src/pages/[platform]/components/alert/index.page.mdx
- docs/src/pages/[platform]/components/button/index.page.mdx
- docs/src/pages/[platform]/components/checkboxfield/index.page.mdx
- docs/src/pages/[platform]/components/expander/index.page.mdx
- docs/src/pages/[platform]/components/icon/react.mdx
- docs/src/pages/[platform]/components/link/index.page.mdx
- docs/src/pages/[platform]/components/phonenumberfield/react.mdx
- docs/src/pages/[platform]/components/radiogroupfield/index.page.mdx
- docs/src/pages/[platform]/components/sliderfield/index.page.mdx
- docs/src/pages/[platform]/components/stepperfield/index.page.mdx
- docs/src/pages/[platform]/components/switchfield/index.page.mdx
- docs/src/pages/[platform]/components/table/index.page.mdx
- docs/src/pages/[platform]/components/tabs/index.page.mdx
- docs/src/pages/[platform]/components/togglebutton/index.page.mdx
- docs/src/pages/[platform]/connected-components/authenticator/configuration/socialProviders.web.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.flutter.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.react-native.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.web.mdx
- docs/src/pages/[platform]/connected-components/geo/react.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
- docs/src/pages/[platform]/guides/auth-protected/auth-protected.react.mdx
- docs/src/pages/[platform]/theming/theme-provider/react.mdx
- packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature
- packages/e2e/features/ui/components/authenticator/sign-in-with-phone.feature
- packages/e2e/features/ui/components/authenticator/sign-up-with-email.feature
- packages/e2e/features/ui/components/authenticator/sign-up-with-phone.feature
- packages/react/src/components/Geo/MapView/index.tsx
[301](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301), [303](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303) status code should not be acceptable.
Note: We still double check 301 from docs.amplify.aws ([code](https://github.com/aws-amplify/amplify-ui/blob/main/docs/scripts/util/checkLink.ts#L31)) because its broken link returns 301 (https://github.com/aws-amplify/docs/issues/5221). e.g. 'https://www.w3.org/WAI/ARIA/apg/patterns/radtton' returns 404, but 'https://docs.amplify.aws/lib/auth/getarted/q/platform/js' returns 301
> fix(docs): alert on 301, 303 links

- .github/actions/add-check/action.yml
- .github/actions/add-checks/action.yml
- .github/actions/update-check/action.yml
Add github actions for status checks to use it approval based workflows.
- create-check: Creates a status check of a specified head-sha
- update-check: Updates status of an existing check
Tested against POC to run actions on pull request --> https://github.com/wlee221/amplify-ui/pull/8
[![POC / Test checks](https://github.com/wlee221/amplify-ui/actions/workflows/test-checks.yml/badge.svg)](https://github.com/wlee221/amplify-ui/actions/workflows/test-checks.yml)
Tested that a workflow can update the status of a check multiple times.
For example, we tested that a check called 'POC check' is updated from 'in_progress' to 'completed'.
> chore: add github actions for status checks

- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.react-native.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.web.mdx
- packages/ui/src/i18n/translations.ts
export Korean translations to `ko` key
fixes #3552 
> fix: export Korean tranlsations to the right key(ko)

- .github/workflows/test-fork-prs.yml
- .github/workflows/test-internal-prs.yml
This updates test runner workflows to use absolute path to call `set-status` action. 
This ensures that workflows only run the version of action defined on `main`. We can consider using relative paths in the future for better DX, but for now let's keep this consistent with the others.
n/a
> ci: use absolute path to call reusable action

- packages/e2e/.detoxrc.json
- packages/e2e/README.md
- packages/e2e/detox/hooks.js
- packages/e2e/package.json
- yarn.lock
This change adds Detox and Cucumber configuration to run React Native tests.
> chore(e2e): Add Detox for React Native testing

- .github/workflows/codeql.yml
After #3591, we run codeql on PRs but do not run codeql on push to main.
Adding this PR to run codeql on push as well as on PRs.
Steps are copied from existing workflow.
> ci: run codeql on push to `main`

- packages/react/src/components/Storage/FileUploader/FileUploader.tsx
Update FileUploader deprecation warning to only show up in dev mode.
* yarn next-example build && yarn next-example start
* Validated warning is missing in prod mode.
> chore: fileuploader deprecation warning only dev mode

- .changeset/olive-adults-walk.md
- packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/__tests__/__snapshots__/ConfirmResetPassword.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/__tests__/__snapshots__/ConfirmSignIn.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/ForceNewPassword/__tests__/__snapshots__/ForceNewPassword.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/ResetPassword/__tests__/__snapshots__/ResetPassword.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/__snapshots__/SetupTOTP.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/__snapshots__/SignIn.spec.tsx.snap
- packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/__snapshots__/SignUp.spec.tsx.snap
- packages/react-native/src/primitives/PasswordField/__tests__/__snapshots__/PasswordField.spec.tsx.snap
- packages/react-native/src/primitives/PhoneNumberField/__tests__/__snapshots__/PhoneNumberField.spec.tsx.snap
- packages/react-native/src/primitives/TextField/TextField.tsx
- packages/react-native/src/primitives/TextField/__tests__/__snapshots__/TextField.spec.tsx.snap
Remove themed `selectionColor` and memo themed style in `TextField`.
Fixes https://github.com/aws-amplify/amplify-ui/issues/3618
> fix(ui-react-native): remove themed selectionColor from TextField

- .changeset/small-buses-dance.md
- docs/tests/__snapshots__/cssvars-table.test.ts.snap
- examples/next/pages/ui/components/storage/storage-manager/index.page.tsx
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/internal.ts
- packages/react/src/primitives/Field/Field.tsx
- packages/react/src/primitives/Field/index.ts
- packages/ui/src/theme/__tests__/defaultTheme.test.ts
- packages/ui/src/theme/__tests__/overrides.test.ts
- packages/ui/src/theme/css/component/field.scss
- packages/ui/src/theme/css/component/textField.scss
- packages/ui/src/theme/tokens/components/field.ts
Adding an internal Field primitive for custom fields like a StorageManagerField
```jsx
<Field
label="Images"
isReadOnly={false}
isRequired={false}
errorMessage={'error'}
hasError={false}
>
<StorageManager
acceptedFileTypes={['image/*']}
accessLevel="private"
maxFileCount={3}
isResumable
showThumbnails={true}
/>
</Field>
```
> internal: add Field primitive

- .github/actions/log-metric/action.yml
- .github/workflows/build-and-runtime-test.yml
- .github/workflows/publish-latest.yml
- .github/workflows/publish-next.yml
This migrates `log-metric` action to use IAM roles instead of IAM user credentials.
https://github.com/aws-amplify/amplify-ui/actions/runs/4625009086/jobs/8180374983
> ci: use IAM role for metrics logger

- .changeset/fifty-berries-shout.md
- examples/next/pages/ui/components/storage/storage-manager/default-files/index.page.tsx
- packages/e2e/features/ui/components/storage/storage-manager/upload-file-to-S3-private-multipart.feature
- packages/e2e/features/ui/components/storage/storage-manager/upload-file-to-S3-public-default-files.feature
- packages/e2e/features/ui/components/storage/storage-manager/upload-file-to-S3-public-multipart.feature
- packages/e2e/package.json
- packages/react-storage/src/components/StorageManager/StorageManager.tsx
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/useStorageManager.test.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/useStorageManager.tsx
- packages/react-storage/src/components/StorageManager/utils/displayText.ts
`defaultFiles` had some weird behavior. This fixes it and ensures the prop being passed isn't null and the key isn't null. 
| Current | Fixed |
| - | - |
| <img width="815" alt="CleanShot 2023-04-05 at 22 36 59@2x" src="https://user-images.githubusercontent.com/321279/230284543-28e96f78-73ac-4c81-8086-0672ece6fdf0.png"> |  <img width="813" alt="CleanShot 2023-04-05 at 22 34 51@2x" src="https://user-images.githubusercontent.com/321279/230284591-dacd528d-df1c-48ff-963e-2a2a27e9e567.png"> |
|  <img width="813" alt="CleanShot 2023-04-05 at 22 35 58@2x" src="https://user-images.githubusercontent.com/321279/230284634-abb08078-ab7c-4f42-9f3d-c5366d6c1fdf.png"> | <img width="813" alt="CleanShot 2023-04-05 at 22 34 51@2x" src="https://user-images.githubusercontent.com/321279/230284591-dacd528d-df1c …
> fix(storage): fix defaultFiles

- .changeset/slow-rice-cover.md
- packages/react/src/primitives/Field/Field.tsx
- packages/react/src/primitives/Field/__tests__/Field.test.tsx
- packages/react/src/primitives/Field/__tests__/__snapshots__/Field.test.tsx.snap
Field description wasn't showing up for the internal Field component. This fixes that. 
Added tests
> fix(field): making description show up

- .changeset/tough-flies-begin.md
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.headers-and-footers.react-native.mdx
- packages/react-native/src/Authenticator/__tests__/Authenticator.spec.tsx
- packages/react-native/src/Authenticator/common/DefaultContainer/types.ts
Loosen strictness on `children` prop of `Authenticator.Container` and update docs to make it clear that `Container` prop of `Authenticator` can be any `View` component
Related https://github.com/aws-amplify/amplify-ui/discussions/3665
> chore(ui-react-native): loosen Authenticator.Container children prop, update docs

- .github/workflows/reusable-e2e.yml
- docs/src/data/ignoredLinks.ts
- PR to enable link checker once liveness URLs are live
- Ignores apple link that results in 401
> fix: reenable link checker, ignore apple 401 link

- docs/src/components/Layout/Sidebar.tsx
- docs/src/components/home/sections/HeroSection.tsx
- docs/src/data/links.tsx
- docs/src/pages/[platform]/getting-started/installation/dependencies.android.mdx
- docs/src/pages/[platform]/getting-started/installation/index.page.mdx
- docs/src/pages/[platform]/getting-started/introduction/index.page.mdx
- docs/src/pages/[platform]/index.page.tsx
- docs/tests/__snapshots__/sitemap.test.ts.snap
Add getting started intro and installation pages for Android.
> feat(android): add android getting started pages

- packages/e2e/package.json
- yarn.lock
`e2e dev` command broke after we last bumped lockfile in #3711. This is because `@bahmutov/cypress-esbuild-preprocessor` got bumped to the latest version which is incompatible with our current esbuild version (0.13/0.14).
See https://github.com/bahmutov/cypress-esbuild-preprocessor#esbuild-version-support.
> fix(e2e): fix `yarn e2e dev` command

- packages/vue/tsconfig.json
Add `outDir` key to Vue _tsconfig.json_ to remove overwrite warnings:
```
Cannot write file 'SOME_PATH/packages/vue/dist/index.js' because it would overwrite input file.
```
> fix(ui-vue): prevent TS overwrite warnings

- package.json
- yarn.lock
Fix https://github.com/aws-amplify/amplify-ui/security/dependabot/84
> chore: add yaml to resolutions

- docs/src/pages/[platform]/connected-components/authenticator/customization/sign-up-fields.web.mdx
This change adds an example for customizing signup attributes, the docs currently mention that the name of the attribute must have the `custom` prefix but the implementation detail is missing and is causing confusion for customers.
* https://github.com/aws-amplify/docs/issues/2208
* https://discord.com/channels/705853757799399426/1100996158052106310/1100996158052106310
Ran docs locally
> chore(docs): Add example for custom attributes for signup

- .changeset/honest-taxis-search.md
- packages/ui/src/theme/css/component/input.scss
This change fixes an issue where the input primitive doesn't render properly for date types
| Before  | After |
| ------------- | ------------- |
| <img width="572" alt="Screen Shot 2023-04-28 at 9 21 52 AM" src="https://user-images.githubusercontent.com/68251134/235202458-77734496-1e2c-4989-8e39-563657a9b8e0.png"> |  <img width="572" alt="Screen Shot 2023-04-28 at 9 22 06 AM" src="https://user-images.githubusercontent.com/68251134/235202542-04ae6eca-aed0-44b7-9470-575de6a18116.png"> |
Tested on mobile devices as well:
> chore(ui): Fix input styling

- docs/src/pages/[platform]/components/text/TextPropControls.tsx
- docs/src/pages/[platform]/components/text/demo.tsx
- docs/src/pages/[platform]/components/text/useTextPropControlProps.tsx
Removes the default value set for the color prop control on the Text demo and hides the prop in the demo code if field is empty. Adds a static placeholder
Currently on [the Text demo](https://ui.docs.amplify.aws/react/components/text), changing the variation dropdown does nothing unless you first type something into the color field and then delete it.
**Before**
Changing the variation does nothing even though the color prop text field is empty because we set an initial color of blue in our component state
**After**
With variation selected
With custom color entered
> fix(docs): allow variation prop to work on Text demo

- .changeset/new-bears-hide.md
- docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerMetadataExample.tsx
- docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/index.ts
- docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts
- docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
- examples/next/pages/ui/components/storage/storage-manager/metadata/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/metadata/index.page.tsx
- packages/react-storage/src/components/StorageManager/StorageManager.tsx
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts
- packages/react-storage/src/components/StorageManager/types.ts
- packages/react-storage/src/components/StorageManager/utils/__tests__/uploadFile.test.ts
- packages/react-storage/src/components/StorageManager/utils/uploadFile.ts
- packages/ui/src/theme/tokens/components/fileUploader.ts
Adding `metadata` prop to StorageManager and to the `processFile` function so users can add metadata per-session and per-file. 
#3683
Added an example
> feat(storage-manager): add metadata

- .changeset/hungry-owls-admire.md
- docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerHashExample.tsx
- docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/index.ts
- docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts
- docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
- examples/next/pages/ui/components/storage/storage-manager/process-file/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/process-file/index.page.tsx
- packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/__tests__/useUploadFiles.spec.ts
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/resolveFile.ts
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts
- packages/react-storage/src/components/StorageManager/types.ts
- packages/react-storage/src/components/StorageManager/utils/__tests__/uploadFile.test.ts
- packages/react-storage/src/components/StorageManager/utils/uploadFile.ts
Allowing the `processFile` prop to return a Promise or immediately returning. This allows for doing things like reading the file before upload. 
> feat(storage-manager): let processFile be async or sync

- packages/angular/.eslintrc.js
- packages/angular/projects/ui-angular/src/lib/components/authenticator/components/verify-user/verify-user.component.html
- packages/angular/projects/ui-angular/src/lib/components/authenticator/components/verify-user/verify-user.component.ts
- packages/angular/projects/ui-angular/src/lib/services/__tests__/authenticator.service.test.ts
Fixes the following eslint rule errors:
- @typescript-eslint/no-unsafe-argument
- @typescript-eslint/no-unsafe-assignment
- @typescript-eslint/no-unsafe-member-access
CI below
> fix(angular): fix `unsafe-*` eslint rule errors

- .github/scripts/mega-app-create-app.sh
**Issue**: Mega-app _react-17-next-11-node-16-ts_ started to fail since May 5. https://github.com/aws-amplify/amplify-ui/actions/runs/4887947902/jobs/8725120905?pr=3751
**Reason**: On May 4,  *create-next-app* released a change (https://github.com/vercel/next.js/pull/49111) to ask a interactive question on command line to for the App Router and set the default to `Yes`
**Fix**: This PR is to add a `--no-app` flag so that it'll create a `pages/` folder instead of a `app/` folder.
POC PR: https://github.com/aws-amplify/amplify-ui/pull/3751/
[![PoC / Build System Test Canary](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-build-system-test.yml/badge.svg)](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-build-system-test.yml) …
> fix: react-17-next-11-node-16-ts

- packages/e2e/features/ui/components/in-app-messaging/demo.feature
Temporarily remove InApp Messaging tests, they are flaky in CI. Cannot repro locally yet, skipping to unblock CI.
First run fail: https://github.com/aws-amplify/amplify-ui/actions/runs/4983174972/jobs/8920223658
Rerun successful: https://github.com/aws-amplify/amplify-ui/actions/runs/4983174972/jobs/8923056879
At first only one test failed, skipped that one, but then a different one started failing in IOS on this PR. Skipping all until we figure out what is happening. Will perform manual testing of InAppMessaging for release purposes until fixed.
> chore(e2e): Remove flaky inapp test temporarily

- canary/apps/react/cra-ts/package.json
- canary/apps/react/cra/package.json
Build and Runtime canaries are failing for react CRA and CRA-ts
```
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.
HookWebpackError: Cannot read properties of undefined (reading 'e')
-- inner error --
TypeError: Cannot read properties of undefined (reading 'e')
Generated code for /home/runner/work/amplify-ui/amplify-ui/canary/apps/react/cra-ts/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!/home/runner/work/amplify-ui/amplify-ui/canary/apps/react/cra-ts/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!/home/runner/work/amplify-ui/amplify-ui/canary/apps/react/cra-ts/node_modules/source-map-loader/dist/cjs.js!/home/runner/work/amplify-ui/amplify-ui/canary/apps/react/cra-ts/node_modules/@aws-amplify/ …
```
> fix: Pin webpack version to unblock react canaries

- canary/apps/react/cra-ts/package.json
- canary/apps/react/cra/package.json
This reverts commit 9ecbe7e8e0be902cd59940d8020b35b94b0748c7.
Reverting the change to pin Webpack to older version, the fix is released in patch 5.83.1.
https://github.com/aws-amplify/amplify-ui/issues/3911
Ran yarn install && yarn build for cra canary apps
```
yarn run v1.22.19
$ react-app-rewired build
Creating an optimized production build...
Compiled successfully.
```
> Revert "fix: Pin webpack version to unblock react canaries (#3909)"

- docs/src/pages/[platform]/connected-components/authenticator/DeveloperPreview.tsx
- docs/src/pages/[platform]/connected-components/authenticator/quick-start-install.android.mdx
- Remove the dev-preview callout for Android Authenticator.
- Update the dependency version to 1.0.0
N/A
Run locally
> Remove dev preview callout for Android Authenticator

- docs/src/components/AppDirectoryAlert.tsx
- docs/src/pages/[platform]/connected-components/account-settings/account-settings.react.mdx
- docs/src/pages/[platform]/connected-components/authenticator/index.page.mdx
- docs/src/pages/[platform]/connected-components/geo/react.mdx
- docs/src/pages/[platform]/connected-components/in-app-messaging/index.page.mdx
- docs/src/pages/[platform]/connected-components/liveness/quick-start-add.react.mdx
- docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
Fix issue where the Next App Directory alert was showing on all platforms.
Manually smoke tested each connected component page
> fix (docs): limit app router alert to react platform

- packages/react-core-notifications/package.json
- packages/react-core-notifications/rollup.config.js
- packages/react-geo/package.json
- packages/react-geo/rollup.config.js
- packages/react-notifications/package.json
- packages/react-notifications/rollup.config.js
- Removes .mjs support from categorical packages
- reference PR - https://github.com/aws-amplify/amplify-ui/pull/3733
> fix: remove mjs support for new categorical packages

- packages/vue/package.json
- yarn.lock
- Fix for security alert in `@antfu/utils` is in version 0.73.0
- `@antfu/utils` is a dependency of `unplugin-vue-components`
- `unplugin-vue-components` v0.25.0 has `@antfu/utils` v0.73.0 ([reference](https://github.com/antfu/unplugin-vue-components/blob/main/package.json#L104))
https://github.com/aws-amplify/amplify-ui/security/dependabot/87
> chore: fix dependabot alert for @antfu/utils

- docs/src/pages/[platform]/connected-components/in-app-messaging/examples/getting-started.react.mdx
- docs/src/styles/docs/tabs.scss
- docs/src/styles/index.scss
Fixes the example code button overlapping the tabs buttons on the InAppMessaging docs. Also a small fix for the long tab names causing a horizontal scroll. Not the greatest fix (scrollable regions should also be keyboard scrollable) but with shorter names at least they are both visible in the UI.
**Note:** there are some long titles further down the page that also cause a horizontal scrollbar on mobile but will need a different fix.
**Before**
**After**
Fixes: https://github.com/aws-amplify/amplify-ui/issues/3723
> fix(docs): inAppMessaging tabs copy button overlap and scrolling

- .changeset/polite-ants-wonder.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
- Previously errors when establishing connection were uncaught by the xstate machine and would just print to the logs
- After putting the one line into the try catch errors are now caught and handled correctly. This should stop the endless `connecting...` errors
> fix(liveness): catch websocket connection errors

- .changeset/big-oranges-hang.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts
- Original WS connection timeout was 2s
- On slower connections we would see the connection timing out and retrying 3 additional times
- Tested with Slow 3G throttle profile on chrome which adds 2s of latency to each request
> chore(liveness): increase ws connection timeout to 10s, default was 2s

- .github/workflows/publish-next-release.yml
- .github/workflows/test-angular-major-release-prs.yml
- Set up ci to run unit, e2e and publish to `next-release` tag
- This will be reverted before we merge `angular-major-release/main` to `main`.
> ci: set up ci to run unit, e2e and publish to next-release tag

- canary/apps/react/cra-ts/package.json
The upstream issue has been fixed: https://github.com/A11yance/aria-query/issues/502
> Revert "chore(canary): pin aria-query deps temporarily"

- .changeset/wild-rocks-invent.md
- docs/tests/__snapshots__/props-table.test.ts.snap
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/primitives/types/collection.ts
Prevent `CollectionProp['children']` from resolving to unsatisfiable type union
fixes https://github.com/aws-amplify/amplify-ui/issues/4098
Manually tested in sample app
> fix(react): omit ReactNode from Collection children prop

- examples/react-native/package.json
- packages/react-liveness/package.json
- packages/react/package.json
- yarn.lock
This led to e2e failures on ios and e2e react-native tests. Will unblock the CI first, and fix later.
> Revert "chore: use same version of @xstate/react across amplify-ui"

- docs/tests/__snapshots__/props-table.test.ts.snap
- packages/react/src/primitives/types/collection.ts
Update `children` omission  for `CollectionProps` and extend to `BaseCollectionProps`
> fix(react): fix CollectionProps and BaseCollectionProps

- .changeset/clever-eagles-design.md
- packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/__snapshots__/VerifyUser.spec.tsx.snap
- packages/react-native/src/primitives/Radio/__tests__/__snapshots__/Radio.spec.tsx.snap
- packages/react-native/src/primitives/Radio/styles.ts
- packages/react-native/src/primitives/RadioGroup/__tests__/__snapshots__/RadioGroup.spec.tsx.snap
Add `margin` to `Radio` "dot" icon container
**Screenshots**
**Before:**
**After:**
NA
> fix(react-native): add spacing between Radio icon and label

- .changeset/angry-ligers-enjoy.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts
- packages/react-liveness/src/components/FaceLivenessDetector/utils/__tests__/platform.test.ts
- packages/react-liveness/src/components/FaceLivenessDetector/utils/platform.ts
- Updated custom user agent to include liveness package version
- New User agent - `aws-sdk-js/3.348.0 ua/2.0 os/macOS#10.15.7 lang/js md/browser#Chrome_114.0.0.0 api/rekognitionstreaming#3.348.0 aws-amplify/5.1.7-js-ui-react-liveness-1.0.2`
- Old user agent - `aws-sdk-js/3.309.0 os/Android/13 lang/js md/browser/Chrome_113.0.5672.132 api/rekognitionstreaming/3.309.0 aws-amplify/5.2.1_js`
- Seems like aws sdk converts spaces to dashes in custom user agent
> chore(liveness): add liveness version user agent to rekognition streaming api call

- docs/src/pages/[platform]/components/rating/RatingPropControls.tsx
Updates the Ratings demo inputs for value and maxValue to use number type input and removes the parseInt on the onChange. 
Unrelated, there is a small rendering bug in the Ratings element itself which causes a height discrepancy when you use a value less than 1 that I will open a issue for (verified here https://codesandbox.io/p/sandbox/ratings-height-bug-68rgd5?file=%2Fsrc%2FApp.tsx%3A8%2C40 and you can see it in the demo if you change the value to .5 there is a small shift)
**Before**
Hit backspace in the value and maxValue inputs to see current behavior on [Ratings demo](https://ui.docs.amplify.aws/react/components/rating)
**After**
https://github.com/aws-amplify/amplify-ui/assets/376920/84473d6f-10a2-40d2-b1ac-be348faa7684
Fixes https://github.com/aws-amplify/amplify-ui/issues/4090
By …
> fix(docs): ratings demo values inputs

- .changeset/purple-beans-roll.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
- Fixes issue - https://github.com/aws-amplify/amplify-ui/issues/4123
- Previously a websocket connection is already closed error would show up after successful liveness checks
- This was happening because when closing the input stream the aws sdk client would try to send another websocket event, but if we have already sent the `stopVideo` event then the server will have already closed the connection. Hence we no longer need to close the input stream ourselves since the server will have already closed the connection
> fix(liveness): remove websocket error showing up after connection closes

- docs/src/pages/[platform]/components/card/demo.tsx
Minor fix for an error that only shows when running `yarn docs dev` on the Card docs page that I noticed when checking out a different PR. Not present on built docs site.  Remove some unused imports.
```React does not recognize the setVariation prop on a DOM element``` 
> fix(docs): card demo setVariations prop error in dev

- .changeset/strong-guests-look.md
- packages/react-liveness/package.json
- yarn.lock
Bumps Amplify JS and `@aws-sdk`version to remove vulnerability warnings from `fast-xml-parser@<=4.2.4`.
Existing CI.
```bash
$ yarn why fast-xml-parser
=> Found "fast-xml-parser@4.2.5"
- "_project_#@aws-sdk#client-sts" depends on it
- Hoisted from "_project_#@aws-sdk#client-sts#fast-xml-parser"
- Hoisted from "_project_#@aws-amplify#ui-react-liveness#@aws-sdk#client-rekognitionstreaming#@aws-sdk#client-sts#fast-xml-parser"
- Hoisted from "_project_#@aws-amplify#ui-docs#aws-amplify#@aws-amplify#storage#@aws-sdk#client-s3#fast-xml-parser"
```
> chore: bump aws-amplify deps

- .vscode/settings.json
Adds vscode config to turn on word wrap in mdx files. This will make long paragraphs in the mdx files easier to read.
> chore(vscode): turn on word wrap for mdx files

- .changeset/calm-swans-divide.md
- packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/shared/MatchIndicator.tsx
- Previously in a single 7 second session the face match percentage bar would re-render up to 800 times
- Reduced re-renders by rounding face match percentage values up and memoizing the component
- Now renders are down ~80 renders in a 7 second session
- To further reduce renders we can perform fewer face detection calls to Blazeface, but having a higher number of calls helps increase accuracy of sessions as we get more granularity into face match position
> chore(liveness): improve face match percentage performance

- .github/workflow-samples/tagged-release.yml
- .github/workflows/publish-next.yml
References `reusable-tagged-publish` using absolute path instead of relative path for the sake of consistency.
Double checked the syntaax.
> chore(ci): use absolute path to reference reusable-tagged-publish

- docs/src/pages/[platform]/connected-components/geo/react.mdx
`https://visgl.github.io/react-map-gl/docs/api-reference/map/` and `https://visgl.github.io/react-map-gl/docs/api-reference/use-map/` are returning 404 and failing CI, update links to remove the trailing `/`
```
❌ [RETURNING STATUS...] 404 for page #95 link #49 -- https://visgl.github.io/react-map-gl/docs/api-reference/map/ from A tag "default map" on  page ***/react/connected-components/geo
❌ [RETURNING STATUS...] 404 for page #95 link #57 -- https://visgl.github.io/react-map-gl/docs/api-reference/use-map/ from A tag "useMap hook from react-map-gl" on  page ***/react/connected-components/geo
```
> fix(docs): Update react-map-gl links

- canary/e2e/package.json
- canary/e2e/yarn.lock
- package.json
- yarn.lock
- Fixes dependabot alerts for `tough-cookie`
- https://github.com/aws-amplify/amplify-ui/security/dependabot/97
- https://github.com/aws-amplify/amplify-ui/security/dependabot/96
- package `@cypress/request` has a `~` dependency on `tough-cookie@2.5.0` which will spit out a warning, they have an issue to fix this - https://github.com/cypress-io/request/issues/31
> fix(dependabot): fix tough-cookie security vulnerability

- packages/vue/jest.config.cjs
- packages/vue/src/components/__tests__/__snapshots__/confirm-reset-password.spec.ts.snap
- packages/vue/src/components/__tests__/__snapshots__/force-new-password.spec.ts.snap
- packages/vue/src/components/__tests__/__snapshots__/reset-password.spec.ts.snap
- packages/vue/src/components/__tests__/confirm-reset-password.spec.ts
- packages/vue/src/components/__tests__/force-new-password.spec.ts
- packages/vue/src/components/__tests__/reset-password.spec.ts
- packages/vue/src/components/confirm-reset-password.vue
- packages/vue/src/components/force-new-password.vue
- packages/vue/src/components/reset-password.vue
Refactors `reset-password`, `confirm-reset-password`, and `force-new-password` components to use `useAuthenticator` instead of explicit state machine lookup.
Existing CI, wrote unit test, and did smoke tests:
<video src="https://github.com/aws-amplify/amplify-ui/assets/43682783/c8a41c03-03ed-4568-b1d2-ecdd5a21b000" /> | <video src="https://github.com/aws-amplify/amplify-ui/assets/43682783/b324d43c-d939-4621-be48-db1797ebff24" />
|---|---|
> refactor(vue): refactor reset-password and force-new-password components

- docs/.eslintrc.json
- docs/package.json
- docs/src/components/FlutterAuthenticatorExample.tsx
- docs/src/components/Fragment.tsx
- docs/src/components/Layout/PageTabLayout.tsx
- docs/src/components/home/themes/classicTheme.ts
- docs/src/components/home/themes/defaultTheme.ts
- docs/src/components/home/themes/synthwaveTheme.ts
- docs/src/components/home/themes/terminalTheme.ts
- docs/src/pages/[platform]/components/passwordfield/examples/refs.tsx
- docs/src/pages/[platform]/index.page.tsx
- yarn.lock
Docs are no longer being linted, there seems to be some issue with the newer version of eslint. Found this comment saying what version of eslint is compatible with Next 11:
https://github.com/vercel/next.js/issues/30182#issuecomment-965686256
**Before:** 
No linting errors showing, just an error:
```bash
error - ESLint must be installed in order to run during builds: yarn add --dev eslint
```
See [Build Docs Package step](https://github.com/aws-amplify/amplify-ui/actions/runs/5488767177/jobs/10006266188)
**After:** 
Now seeing our favorite linting errors... 😆 
```bash
./src/pages/[platform]/components/passwordfield/examples/refs.tsx
21:33  Warning: The ref value 'showPasswordButtonRef.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a …
```
> chore: fix docs linting

- .github/workflows/build-and-runtime-test.yml
- .github/workflows/publish-next.yml
- .github/workflows/reusable-e2e.yml
Configures `configure-aws-credentials` to v2, which bumps the default node version to 16.
E2e changes are running against this PR.
> ci: bump configure-aws-credentials to v2

- .changeset/cold-grapes-collect.md
- examples/react-native/src/features/Authenticator/Styles/Example.tsx
- packages/react-native/src/theme/__tests__/createTheme.spec.ts
- packages/react-native/src/theme/createTheme.ts
- packages/ui/src/theme/tokens/types/designToken.ts
* Fixed a typing issue where the theme would only accept strings as borderWidths
* Made sure borderWidths and space values turn into numbers even without 'rem' or 'px'
> fix(react-native): border widths in the theme don't throw runtime errors

- docs/src/pages/[platform]/connected-components/geo/react.mdx
- Maplibre changed their docs urls from maplibre.org/maplibre-gl-js-docs/api/ to maplibre.org/maplibre-gl-js/docs/API/
> fix(docs): update maplibre urls

- docs/src/components/Layout/Footer.tsx
- docs/src/components/Layout/Header.tsx
Adds `aria-hidden="true"` to a few unlabelled icons on the docs site. The related links these icons are used for already have accessible labels so the icons are safe to hide.
> fix(docs): hide icons from accessibility tree

- packages/ui/src/theme/tokens/components/checkbox.ts
Part of the checkbox theme was not passing Output generic, making the design tokens underneath required. This fixes that. 
> fix(theme): making checkbox icon checked optional

- docs/src/data/links.tsx
- docs/src/pages/[platform]/connected-components/storage/storageimage/examples/DefaultStorageImageExample.tsx
- docs/src/pages/[platform]/connected-components/storage/storageimage/examples/StorageImageErrorHandlingExample.tsx
- docs/src/pages/[platform]/connected-components/storage/storageimage/examples/index.ts
- docs/src/pages/[platform]/connected-components/storage/storageimage/index.page.mdx
- docs/src/pages/[platform]/connected-components/storage/storageimage/props.ts
- docs/src/pages/[platform]/connected-components/storage/storageimage/react.mdx
- docs/src/utils/storageMock.ts
- packages/react/src/primitives/shared/constants.ts
Add documentation for `StorageImage`
> docs: add docs for StorageImage

- packages/ui/src/theme/css/component/scrollView.scss
Remove deprecated scrollview css from a couple versions back. I did a search for usage of `.amplify-scrollview--horizontal` and `.amplify-scrollview--vertical` and couldn't find any.
> chore(ui): remove deprecated scrollview css

- .changeset/hip-llamas-cover.md
- docs/src/pages/[platform]/components/switchfield/examples/SwitchFieldThemeExample.tsx
- docs/tests/__snapshots__/cssvars-table.test.ts.snap
- packages/ui/src/theme/__tests__/defaultTheme.test.ts
- packages/ui/src/theme/__tests__/overrides.test.ts
- packages/ui/src/theme/css/component/switchField.scss
- packages/ui/src/theme/tokens/components/switchField.ts
We exposed a `borderColor` token for the thumb of the SwitchField, but because we weren't setting borderWidth or borderStyle, that token wasn't doing anything. Also added the pointer cursor so it looks interactive on hover. 
> fix(primitives): fix border color token for SwitchField thumb

- .vscode/settings.json
- docs/src/styles/docs/_variables.scss
- docs/src/styles/docs/algolia.scss
- docs/src/styles/docs/code.scss
- docs/src/styles/docs/component.scss
- docs/src/styles/docs/framework-chooser.scss
- docs/src/styles/docs/home.scss
- docs/src/styles/docs/install-code.scss
- docs/src/styles/docs/responsiveTable.scss
- docs/src/styles/docs/tokenList.scss
- packages/ui/src/theme/css/component/button.scss
- packages/ui/src/theme/css/component/field.scss
- packages/ui/src/theme/css/component/switchField.scss
- packages/ui/src/theme/css/component/toggleButtonGroup.scss
Sets prettier as the default formatter in vscode settings for css.
In the recent Button PR I opened, some of the variable names are quite long and the default formatting was adding extra spaces to custom css properties, like `var(  --variable )` instead of `var(--variable)` which breaks the css. I tested this change in my Button branch and it fixes the broken variables.
I went through and re-saved all of the css/scss files I could find so there are some formatting changes in some of the files.
Can smoke test here: https://fixprettiercss.dvmvffzts1tcu.amplifyapp.com/
> chore: fix prettier css formatting

- packages/e2e/features/ui/components/authenticator/verify-user.feature
- packages/e2e/features/ui/components/liveness/disable-start-screen.feature
- packages/e2e/features/ui/components/liveness/liveness-detector.feature
- packages/e2e/features/ui/components/liveness/with-credential-provider.feature
The verify user e2e test has been failing for [angular](https://github.com/aws-amplify/amplify-ui/actions/runs/5685875411/job/15412098132?pr=4290) and [vue](https://github.com/aws-amplify/amplify-ui/actions/runs/5696499143/job/15441917416?pr=4295) platforms, this change temporarily skips it to unblock PRs. Ongoing work to follow in #4295. 
Also skip liveness tests for now to unblock pipeline.
> chore(e2e): skip flaky e2e for vue and angular platforms

- .github/workflows/reusable-e2e.yml
- packages/e2e/.detoxrc.json
- packages/e2e/detox/init.ts
- packages/e2e/features/ui/components/authenticator/confirm-sign-up.feature
- packages/e2e/features/ui/components/authenticator/verify-user.feature
- yarn.lock
This change:
* updates the timeout for app initialization to help address tests failures, both iOS and Android are timing out recently:
https://github.com/aws-amplify/amplify-ui/actions/runs/5729414515/job/15531648865
https://github.com/aws-amplify/amplify-ui/actions/runs/5729414515/job/15531649133
* refreshes yarn.lock file to update Detox version to latest.
* switches runner for ios tests to previous version (macos-12), the tests failures started happening with updated runners: https://github.com/actions/runner-images/issues/8027
* temporarily skip `Confirm new password page has correct translations` has been consistently failing in CI for both platforms, loses connection to Metro.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> chore(e2e): increase timeouts, bump Detox, update macos runner

- .changeset/grumpy-feet-raise.md
- packages/angular/projects/ui-angular/package.json
- packages/react-core-notifications/package.json
- packages/react-core/package.json
- packages/react-geo/package.json
- packages/react-liveness/package.json
- packages/react-native/package.json
- packages/react-notifications/package.json
- packages/react-storage/package.json
- packages/react/package.json
- packages/ui/package.json
- packages/vue/package.json
- Ensure that when aws-amplify upgrades to 6.x we do not break our peerDeps for customers, set the aws-amplify dep in our packages to be ^ instead of >=
Screenshot showing no other packages in our package.json seem to have the >=
> chore: set amplify dependencies to be ^ instead of >=

- docs/src/pages/[platform]/components/rating/RatingPropControls.tsx
- the size option in right hand navigation was taking  user to size drop down instead of 'Size section' [here](https://ui.docs.amplify.aws/react/components/rating#size).
- It was caused by `id='root'` property of that dropdown.
- removed the `id=root` that fixed the issue
build and ran the docs in localhost
>  fix(Docs): Clicking on Size on Ratings docs takes you to select dropdown instead of Size section #4096 

- docs/src/pages/[platform]/components/textareafield/TextAreaFieldPropControls.tsx
- docs/src/pages/[platform]/components/textareafield/demo.tsx
- docs/src/pages/[platform]/components/textareafield/useTextAreaFieldProps.tsx
The TextAreaField demo had a lot of verbose props that are documented elsewhere or aren't really useful in the demo. Removed a bunch of those so that the demo code is more copy/paste-able and doesn't show false/empty props.
**Before**
**After**
> chore(docs): clean up TextAreaField demos

- .changeset/sour-dogs-turn.md
- packages/ui/src/theme/css/component/searchField.scss
Re-orders the disabled styles to come after the other state styles for the search field button to fix the disabled hover state.
Fixes https://github.com/aws-amplify/amplify-ui/issues/4337
**Before**
**After**
> fix(ui): disabled styles for search field button

- .changeset/unlucky-teachers-kneel.md
- packages/react-native/src/Authenticator/hooks/useFieldValues/__tests__/utils.spec.ts
- packages/react-native/src/Authenticator/hooks/useFieldValues/utils.ts
This change fixes an issue where the RN Authenticator shows validation errors for email fields with leading or trailing spaces on blur/change validations.
https://github.com/aws-amplify/amplify-ui/assets/68251134/8a8c1bcf-d3c9-4a79-9480-642e9649e4db
Fixes: https://github.com/aws-amplify/amplify-ui/issues/4336
> fix(ui-react-native): Fix RN Authenticator not trimming values before validation

- build-system-tests/scripts/mega-app-create-app.sh
Skips the tailwind install for next in our mega-app. 
Our build system test started failing today because Next does not include it as a dev dependency.
Reproduced the error 
```Type error: Cannot find module 'tailwindcss' or its corresponding type declarations.``` locally.
Ran `npm run react-17-next-11-ts` with this change locally and verified successful build.
> chore(build-system-tests): skip tailwind install in create-next-app

- docs/src/styles/docs/base.scss
Our styles for links on the docs site are overriding our updated Button primitive styles which broke our home page "Get started building" Button hover style.
Updated our link override styles on docs site to only target links with no classes (so basically links that are generated in markdown or plain <a></a> links used in documentation)
**After**
> fix(docs): plain link styles

- .changeset/chatty-terms-brake.md
- docs/__tests__/__snapshots__/cssvars-table.test.ts.snap
- docs/src/pages/[platform]/components/button/examples/ButtonThemeExample.tsx
- packages/ui/src/theme/__tests__/defaultTheme.test.ts
- packages/ui/src/theme/__tests__/overrides.test.ts
- packages/ui/src/theme/css/component/button.scss
- packages/ui/src/theme/tokens/components/button.ts
Our default Button variation/colorTheme did not have a backgroundColor token set. This updates it to use a token set to `transparent` so that it can be themed just like the other Button variations/colorThemes.
Also updated the Button theming demo to show customizing some of the default Button tokens; now including backgroundColor. (first button on the left in below screenshot)
> fix(ui): add backgroundColor token for default Button style

- docs/src/styles/docs/base.scss
Fix the focus styles I broke in https://github.com/aws-amplify/amplify-ui/pull/4362 😣 
A few of our special link classes do not have a focus style defined and were relying on the previous base focus-visible style that was broadly applied via `a {}` (like the cards on the home page). I went through and checked other pages and link types (plain links, special links with classes like in the sidebar/ToC, `<Link>` elements, etc)
> fix(docs): fix missing focus styles for some links

- docs/src/components/ThemeExample.mdx
- docs/src/pages/[platform]/theming/getting-started.react.mdx
This PR removes the "AmplifyProvider was renamed" message from most pages except for the ThemeProvider page itself. Leaving it there allows people to still search for AmplifyProvider via Google and find a result.
> chore: remove ThemeAlert from primitives pages

- docs/__tests__/__snapshots__/props-table.test.ts.snap
- packages/react/src/primitives/types/fieldset.ts
We don't need to export the variation type for Fieldset.
> chore(react): inline type for Fieldset varatiation

- .changeset/ninety-laws-share.md
- packages/react-liveness/package.json
- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
- yarn.lock
This reverts commit 86991203de757fe607a0b71e556382d2c0af4216.
> Revert "chore(liveness): get oval fit timeout from server (#4365)"

- .changeset/mean-vans-attend.md
- packages/react/src/primitives/ButtonGroup/ButtonGroup.tsx
- packages/react/src/primitives/ButtonGroup/__tests__/ButtonGroup.test.tsx
- packages/react/src/primitives/types/buttonGroup.ts
Prevent `ButtonGroup` child element cloning from ignoring child `props`
NA
> fix(ui-react): update ButtonGroup to respect child props and allow optional children

- packages/react-core-auth/src/components/Authenticator/Machine/MachineContext.tsx
- packages/react-core-auth/src/components/Authenticator/Machine/__mocks__/useMachine.ts
- packages/react-core-auth/src/components/Authenticator/Machine/__tests__/MachineContext.spec.tsx
- packages/react-core-auth/src/components/Authenticator/Machine/__tests__/__snapshots__/MachineContext.spec.tsx.snap
- packages/react-core-auth/src/components/Authenticator/Machine/__tests__/utils.spec.tsx
- packages/react-core-auth/src/components/Authenticator/Machine/index.ts
- packages/react-core-auth/src/components/Authenticator/Machine/types.ts
- packages/react-core-auth/src/components/Authenticator/Machine/utils.ts
- packages/react-core-auth/src/exported.ts
- packages/react-core-auth/src/index.ts
- packages/ui/src/helpers/authenticator/__tests__/facade.test.ts
- packages/ui/src/helpers/authenticator/constants.ts
- packages/ui/src/helpers/authenticator/facade.ts
- packages/ui/src/helpers/authenticator/utils.ts
- packages/ui/src/machines/authenticator/index.ts
- packages/ui/src/types/authenticator/attributes.ts
- packages/ui/src/types/authenticator/stateMachine/context.ts
- packages/ui/src/types/authenticator/user.ts
- packages/ui/src/utils/index.ts
Add `MachineProvider` and `useMachine` and state machine utils for `A.Next`:
- `MachineProvider` and `useMachine` correspond to existing `AuthenticatorProvider` and `useAuthenticator` with only required functionality
- add `overrideServices` to `createAuthenticatorMachine` to allow `A.Next` to bypass extraneous configuration updates
NA
Manual tests, some unit tests
> feat(A.Next): add machine context

- .changeset/cold-news-jump.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts
- Originally we though the streamprovider would live in the predictions category hence the implementation of a predictions provider. Since this is no longer true we should remove this in preparation for v6
> chore(liveness): remove predictions super class

- packages/configs/ts/tsconfig.base.json
- packages/react/jest.config.js
- packages/react/src/primitives/shared/constants.ts
- Update TS config `compiler.target` value to `ES2020`
- Remove the `Authenticator` from `jest` coverage reporting
File                                                             | % Stmts | % Branch | % Funcs | % Lines |
-----------------------------------------------------------------|---------|----------|---------|---------|
Without Authenticator coverage - All files                       |   97.05 |    90.26 |   84.98 |   96.89 |
With Authenticator coverage - All files                          |   91.27 |    80.89 |   69.89 |   91.39 |
NA
`yarn build`
> Next release/update react tsconfig target

- .changeset/modern-melons-doubt.md
- docs/src/pages/[platform]/components/breadcrumbs/examples/BreadcrumbsStyleExample.tsx
- packages/react/src/primitives/Breadcrumbs/Breadcrumbs.tsx
Fix subtle issue with `key` used in `BreadCrumbs`
> fix(ui-react): use guaranteed value for BreadCrumbs key

- docs/src/pages/[platform]/connected-components/account-settings/change-password/props.ts
- docs/src/pages/[platform]/connected-components/account-settings/change-password/react.mdx
- docs/src/pages/[platform]/connected-components/account-settings/delete-user/props.ts
- docs/src/pages/[platform]/connected-components/account-settings/delete-user/react.mdx
- packages/e2e/features/ui/components/account-settings/delete-user.feature
- packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
- packages/react/src/components/AccountSettings/ChangePassword/__tests__/ChangePassword.test.tsx
- packages/react/src/components/AccountSettings/ChangePassword/types.ts
- packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
- packages/react/src/components/AccountSettings/DeleteUser/__tests__/DeleteUser.test.tsx
- packages/react/src/components/AccountSettings/DeleteUser/defaults.tsx
- packages/react/src/components/AccountSettings/DeleteUser/types.ts
- packages/react/src/components/AccountSettings/utils/displayText.ts
- packages/react/src/components/AccountSettings/utils/index.ts
* Replace i18n module with displayText for Account Settings components.
* Add unit tests for text overrides.
* Add docs sections for each component.
> chore(react): Use displayText for Account Settings

- docs/__tests__/__snapshots__/cssvars-table.test.ts.snap
- docs/src/pages/[platform]/components/radiogroupfield/examples/RadioGroupFieldThemeExample.tsx
- packages/react/src/primitives/Radio/Radio.tsx
- packages/ui/src/theme/__tests__/defaultTheme.test.ts
- packages/ui/src/theme/__tests__/overrides.test.ts
- packages/ui/src/theme/css/component/radio.scss
- packages/ui/src/theme/css/component/radioGroupField.scss
- packages/ui/src/theme/tokens/components/radioGroup.ts
- Add disabled class to .amplify-radio__label so it can have proper disabled styling/theming
- remove unneeded disabled attribute on label
- Add tokens for theming legend of RadioGroupField, remove old top level label tokens.
- Update theme example for RadioGroupField in docs
- snapshots
> fix radio disabled label color and radioGroup legend theming

- build-system-tests/scripts/checkReactNativeLog.ts
Increase timeout for checking logs for build system tests on ios, to mitigate several transient failures.
Example: https://github.com/aws-amplify/amplify-ui/actions/runs/6321587860/job/17165846938
> chore: Increase time to wait to check build system tests

- .changeset/fuzzy-worms-wait.md
- packages/vue/src/components/primitives/styles.css
Fixes an issue where warnings related to unused css that has `@apply` directive appear while building with nuxt.
Also experienced in CI while building our mega-app with nuxt: https://github.com/aws-amplify/amplify-ui/actions/runs/6329587438/job/17190179520
```
[warn] warnings when minifying css:
Warning: G] Expected ";" but found "}" [css-syntax-error]
<stdin>:1:278009:
1 │ ...ta-amplify-spacer]{@apply flex-1}[data-amplify-lostcode]{@apply ...
│                                    ^
╵                                    ;
Warning: G] Expected ";" but found "}" [css-syntax-error]
<stdin>:1:278066:
1 │ ...@apply flex flex-col items-start}[data-amplify-select]{@apply bl...
│                                    ^
╵                                    ;
Warning: G] Expected ";" but found "}" …
```
> chore(ui-vue): Clean up unused css

- .vscode/settings.json
- build-system-tests/scripts/checkReactNativeLog.ts
Fix unused var issue in https://github.com/aws-amplify/amplify-ui/security/code-scanning/159
> chore: Fix unused var

- packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
- packages/react/src/components/AccountSettings/ChangePassword/__tests__/ChangePassword.test.tsx
- packages/ui/src/helpers/accountSettings/__tests__/utils.test.ts
- packages/ui/src/helpers/accountSettings/utils.ts
- yarn.lock
Update to latest `console-preview` and migrate Account Settings.
> chore: Migrate Account Settings

- docs/scripts/util/getAllTypesData.ts
- examples/react-native/package.json
- package.json
- packages/angular/package.json
- packages/react-auth/package.json
- packages/react-core-auth/package.json
- packages/react-core/package.json
- packages/react-geo/package.json
- packages/react-liveness/package.json
- packages/react-storage/package.json
- packages/react/package.json
- packages/ui/package.json
- packages/vue/package.json
- yarn.lock
> chore: bump tslib and typescript versions

- package.json
- yarn.lock
- Addresses dependabot alert - https://github.com/aws-amplify/amplify-ui/security/dependabot/110
- Codelyzer is only used for linting, possibly should just remove all together but can be addressed as a follow up since we have an alert open
> fix(dependabot): update @angular/core dep for codelyzer to be angular 10

- examples/next/pages/ui/components/account-settings/change-password-with-overrides/index.page.tsx
- examples/next/pages/ui/components/account-settings/change-password/index.page.tsx
- examples/next/pages/ui/components/account-settings/delete-user-with-overrides/index.page.tsx
- examples/next/pages/ui/components/account-settings/delete-user/index.page.tsx
- packages/e2e/features/ui/components/account-settings/change-password-overrides.feature
- packages/e2e/features/ui/components/account-settings/change-password.feature
- packages/e2e/features/ui/components/account-settings/delete-user-overrides.feature
- packages/e2e/features/ui/components/account-settings/delete-user.feature
- packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
- packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
- packages/react/src/components/AccountSettings/DeleteUser/__tests__/DeleteUser.test.tsx
- packages/ui/src/helpers/accountSettings/__tests__/validator.test.ts
- packages/ui/src/helpers/accountSettings/utils.ts
- packages/ui/src/helpers/accountSettings/validator.ts
- packages/ui/src/helpers/authenticator/utils.ts
- packages/ui/src/helpers/utils.ts
- packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts
- packages/ui/src/machines/authenticator/actions.ts
- packages/ui/src/machines/authenticator/defaultServices.ts
- packages/ui/src/types/authenticator/form.ts
- packages/ui/src/validators/__tests__/index.test.ts
- yarn.lock
* Update password validators to conform to Amplify configure changes.
* Re-enable Change Password e2es
* Re-enable Delete User e2es.
> chore: Migrate password validators

- docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/components/ThemeProvider/ThemeContext.tsx
- packages/react/src/components/ThemeProvider/ThemeProvider.tsx
- packages/react/src/components/ThemeProvider/__tests__/AmplifyContext.test.tsx
- packages/react/src/components/ThemeProvider/index.ts
- packages/react/src/hooks/__tests__/useTheme.test.tsx
- packages/react/src/hooks/useTheme.ts
This PR removes AmplifyProvider which was renamed to ThemeProvider in v2. It has been documented as ThemeProvider for 3 releases, so it's time to clean it up.
* Ran Unit and Integration tests
* Ran Docs and validated that custom themes are rendering
> breaking: remove old AmplifyProvider

- canary/apps/react/cra-ts/src/App.tsx
- canary/apps/react/cra/src/App.js
- canary/apps/react/next/pages/index.js
Remove deprecated and removed `AmplifyProvider` from canary apps
See failing [Test and Publish / next-release](https://github.com/aws-amplify/amplify-ui/actions/runs/6599227979/job/17928381193#step:11:31) workflow
> fix(canary): remove AmplifyProvider

- examples/react-native/src/ui/components/authenticator/sign-up-with-attributes/Example.tsx
Add missing fields from signup with attributes RNA example app.
> chore: Add missing form fields to RNA example app

- docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx
- docs/src/pages/[platform]/connected-components/authenticator/configuration/totpIssuer.swift.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.full-ui-customization.swift.mdx
The PR aims to update docs to add details of TOTP  in Authenticator for Swift. The changes updates the following 2 things:
* How a customer can pass in a configuration to udpate the issuer. 
* How a customer can customize the TOTP Setup Experience. 
> chore(docs): Updating docs to reflect TOTP support in Authenticator for Swift

- examples/react-native/src/ui/components/authenticator/reset-password/Example.tsx
- examples/react-native/src/ui/components/authenticator/sign-up-with-attributes/Example.tsx
- examples/react-native/src/ui/components/authenticator/sign-up-with-email/Example.tsx
- examples/react-native/src/ui/components/authenticator/sign-up-with-phone/Example.tsx
- examples/react-native/src/ui/components/authenticator/sign-up-with-username/Example.tsx
- packages/e2e/cypress/fixtures/AWSCognitoIdentityProviderService.ConfirmSignUp-invalid-code.json
- packages/e2e/detox/integration/common/authenticator.ts
- packages/e2e/detox/mockServer.js
- packages/e2e/features/ui/components/authenticator/confirm-sign-up.feature
- packages/e2e/features/ui/components/authenticator/sign-up-with-username.feature
> chore: fix RN e2e tests

- .changeset/dull-cheetahs-deliver.md
- examples/next/pages/ui/components/storage/storage-manager/accept-file-extension/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/accept-file-extension/index.page.tsx
- packages/react/src/primitives/DropZone/__tests__/filterAllowedFiles.test.ts
- packages/react/src/primitives/DropZone/filterAllowedFiles.ts
- packages/react/src/primitives/DropZone/useDropZone.ts
StorageManager was not handling file extension file types for drag and drop properly. This fixes it. 
| - | - |
| ![CleanShot 2023-11-06 at 16 28 49](https://github.com/aws-amplify/amplify-ui/assets/321279/f601cf99-85ea-4bdd-9d22-03072f0b6651) | ![CleanShot 2023-11-06 at 16 29 54](https://github.com/aws-amplify/amplify-ui/assets/321279/8ed6a900-c9c0-4e64-8c80-33a6bb8cb01f) | 
> fix(storage): fixing drop handler for file extensions

- packages/react/src/components/Authenticator/FederatedSignIn/FederatedSignInButtons/__tests__/__snapshots__/FederatedSignInButton.test.tsx.snap
- packages/ui/src/types/authenticator/user.ts
Updates the federated auth enum to match the strings expected by js v6
Was able to use Login with Amazon after updating the enums.
> chore: update federated auth enums for v6

- packages/e2e/cypress/integration/common/shared.ts
- packages/e2e/cypress/support/commands.ts
- packages/ui/src/helpers/authenticator/constants.ts
This updates the confirmation code field type from number (which never made since) to text. 
> chore: update confirmation code to text field type

- .changeset/dull-cheetahs-deliver.md
- docs/package.json
- docs/src/components/ExpoSnack.tsx
- examples/next/package.json
- examples/next/pages/ui/components/storage/storage-manager/accept-file-extension/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/accept-file-extension/index.page.tsx
- packages/react-liveness/CHANGELOG.md
- packages/react-liveness/package.json
- packages/react-liveness/src/version.ts
- packages/react-notifications/CHANGELOG.md
- packages/react-notifications/package.json
- packages/react-storage/CHANGELOG.md
- packages/react-storage/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/src/primitives/DropZone/__tests__/filterAllowedFiles.test.ts
- packages/react/src/primitives/DropZone/filterAllowedFiles.ts
- packages/react/src/primitives/DropZone/useDropZone.ts
- packages/react/src/version.ts
> Merge main into next-release/main

- .github/workflows/build-system-test.yml
- .github/workflows/publish-next-release-unstable.yml
1. Publishes a next-release-unstable tag we can use for the bug bash which will not wait for tests before publishing
2. Fixes the Web build system test for main as well (when we merge)
> chore: publish next-release-unstable tag

- examples/react-native/ios/ReactNative/AppDelegate.mm
- packages/react-native/src/Authenticator/common/FederatedProviderButtons/FederatedProviderButtons.tsx
`Auth.signInWithRedirect({ provider })` expects the provider to have a capitalized name. In the React authenticator we have a silly switch statement. This is just a temporary fix. 
> fix(react-native): skip cognito hosted ui for social providers

- .github/workflows/build-system-test.yml
Our build system test for Angular is failing due to the recent Angular CLI 17 release. This updates the test to use the previous version 16 until our library supports 17.
> fix(build-system-tests): pin angular cli to 16 to unblock tests

- build-system-tests/package.json
Updates the package.json script for angular CLI 16 in our build system test.
I updated the Github workflow, but the package.json also needs to be updated because it was now giving this error:
```
npm ERR! Missing script: "angular-latest-angular-cli-16-ts"
```
> fix missing package.json update for angular cli 16 build system test

- examples/react-native/src/App/App.tsx
- examples/react-native/src/ui/components/authenticator/sign-in-totp-mfa/Example.tsx
- examples/react-native/src/ui/components/authenticator/sign-in-totp-mfa/aws-exports.js
- packages/ui/src/machines/authenticator/actors/signUp.ts
- packages/ui/src/machines/authenticator/index.ts
- packages/ui/src/machines/authenticator/types.ts
- Pass all values of `actorDoneData` to actors on spawn
- add `totpSecretCode` to `ActorDoneData`
> fix(authenticator): persist totp secret code between actors

- .changeset/selfish-zebras-decide.md
- examples/react-native/src/App/App.tsx
- packages/react-native/src/Authenticator/Authenticator.tsx
- packages/react-native/src/Authenticator/__tests__/Authenticator.spec.tsx
- packages/react-native/src/Authenticator/__tests__/__snapshots__/Authenticator.spec.tsx.snap
- packages/react-native/src/Authenticator/__tests__/withAuthenticator.spec.tsx
Update `Authenticator` to delay rendering `children` until attribute verification flow has been completed
NA
> fix(rna): prefer route over authStatus for rendering children

- .changeset/plenty-meals-cross.md
- examples/react-native/src/ui/components/authenticator/social-providers/Example.tsx
- packages/react-native/src/Authenticator/common/FederatedProviderButtons/FederatedProviderButtons.tsx
- packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/FederatedProviderButtons.spec.tsx
- packages/ui/src/helpers/authenticator/defaultAuthHubHandler.ts
- packages/ui/src/machines/authenticator/index.ts
- packages/ui/src/machines/authenticator/types.ts
Refactor RN federated sign in
- use `signInWithRedirect` directly in place of `toFederatedSignIn` in `FederatedProviderButtons`
- send `SIGN_IN_WITH_REDIRECT` state machine event on `signInWithRedirect` Hub event to set state to `authenticated` on federated sign in
> fix(rna): refactor fed sign in

- docs/src/pages/[platform]/connected-components/authenticator/configuration/InitialStateTabs.tsx
- docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx
> fix(docs): fix Authenticator initialState tabs

- package.json
- packages/e2e/package.json
- yarn.lock
Upgrading aws-crt and cmake-js to keep axios ^1.6.0
> fix(dependabot): upgrading aws-crt to bump axios version

- .changeset/eleven-beers-marry.md
- packages/ui/src/machines/authenticator/__tests__/utils.test.ts
- packages/ui/src/machines/authenticator/actors/signUp.ts
- packages/ui/src/machines/authenticator/utils.ts
Prevent empty string values for `phone_number` from being included in `SignUpInput`
https://github.com/aws-amplify/amplify-ui/issues/4794
Manual test and unit tests
> fix(authenticator): exclude empty phone_number values from sign up submit

- .changeset/poor-jeans-lie.md
- docs/__tests__/__snapshots__/cssvars-table.test.ts.snap
- packages/ui/src/theme/__tests__/__snapshots__/defaultTheme.test.ts.snap
- packages/ui/src/theme/__tests__/__snapshots__/overrides.test.ts.snap
- packages/ui/src/theme/css/component/_fieldControl.scss
- packages/ui/src/theme/tokens/components/button.ts
- packages/ui/src/theme/tokens/components/checkbox.ts
- packages/ui/src/theme/tokens/components/fieldControl.ts
- packages/ui/src/theme/tokens/components/sliderField.ts
- packages/ui/src/theme/tokens/components/switchField.ts
Updates our defaultTheme focus indicator used across primitives to comply with WCAG 2.2 Focus appearance. This is a AAA requirement, but a pretty easy one for us to hit with some changes.
- Our focus indicator ring already meets 3:1 contrast ratio in its contrast area. Our indicator ring sits OUTSIDE of the element since we use a box shadow, so the contrast area is the area taken up by that box shadow; currently a 1px perimeter. That means our box shadow color must be 3:1 against the background color it sits on.
**This PR:**
- Updates the contrast area to a 2px perimeter to meet WCAG 2.2 Focus Appearance; so our boxShadow spread increases from 1px to 2px.
- Adds `info`, `warning`, and `success` fieldControl focus box shadows. fieldControl already has a default focus boxShadow and `error`. …
> chore: update focus ring indicators

- .changeset/chilled-donkeys-decide.md
- packages/react-liveness/src/components/FaceLivenessDetector/shared/MatchIndicator.tsx
- packages/ui/src/theme/css/component/liveness.scss
- Updated color to match 300 : 1 ratio and added aria tags
> fix(liveness): add a11y tags to match indicator bar

- .changeset/curly-lamps-love.md
- examples/angular/src/pages/ui/components/authenticator/sign-in-with-email/sign-in-with-email.component.ts
- examples/next/pages/ui/components/authenticator/sign-in-with-email/index.page.tsx
- examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue
- packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature
- packages/ui/src/machines/authenticator/__tests__/index.test.ts
- packages/ui/src/machines/authenticator/index.ts
- https://github.com/aws-amplify/amplify-ui/issues/4818
- Bug where refreshing the page when signed in does not honor custom form fields or services
- This was happening because when refreshing the page while logged in the xstate machine was not hitting the `setup` state in the machine which we use to determine when to hydrate the machine's initial configuration
- https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-core/src/Authenticator/hooks/useAuthenticatorInitMachine/useAuthenticatorInitMachine.tsx#L19
- InitializeMachine is only called if `route === 'setup'`
- Fixed this by changing the existing signedIn refresh logic to hit the setup state
> fix(auth): fix refreshing page not hydrating custom formfields/services into the auth machine

- .changeset/khaki-glasses-deny.md
- packages/react-liveness/src/components/FaceLivenessDetector/shared/Hint.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/shared/ToastWithLoader.tsx
- This adds explicitly aria labels to the hint component. Screen readers were already working previously but this just makes it more obvious
> chore: add explicit aria tags to hints

- docs/scripts/generate-props-tables-data.ts
- docs/scripts/types/catalog.d.ts
- docs/src/components/Layout/PageTabLayout.tsx
- docs/src/components/propsTable/PropsTableTab.tsx
- docs/src/pages/[platform]/components/heading/react.mdx
- docs/src/pages/_document.page.tsx
- remove `PropsData` from `PropsTableTab` props in favor of importing the JSON file
- remove extraneous code from `PageTabLayout`
- fix a "class" warning in a `Header` example
- remove an unused font
NA
> chore(docs): refactor PageTabLayout and PropsTableTab, fix some console warnings

- .changeset/rotten-terms-own.md
- packages/react-liveness/src/components/FaceLivenessDetector/shared/Hint.tsx
- UX design is asking that the text on screen be read no matter what. When aria-live is set to polite these hint messages can be cut off or superseded by other a11y messages
- For example, previously the `center your face` message would not be read automatically by some screen readers as it would be overriden by the title being read, this ensures that it is now read
> chore: update toasts to be assertive

- docs/src/components/CopyButton.tsx
- docs/src/components/Demo.tsx
- docs/src/components/Example.tsx
- docs/src/components/InstallScripts.tsx
- docs/src/styles/docs/example.scss
Align the position and variation of the `CopyButton` used in the UI Primitives `Demo` component
**Screenshots:**
_Baseline Code Snippet Example_
_After: Demo Code Snippet Example_
_Before: Demo Code Snippet Example_
NA
> chore: align docs Demo CopyButton with other code examples

- .changeset/loud-dolphins-listen.md
- packages/ui/src/theme/css/component/table.scss
Fix styling for Table primitive `striped` variation
| --- | --- |
| <img width="914" alt="Screenshot 2024-01-05 at 12 37 15 PM" src="https://github.com/aws-amplify/amplify-ui/assets/68251134/b95f6f79-33d7-47ae-aaf4-0048aa1d00c3"> | <img width="895" alt="Screenshot 2024-01-05 at 12 36 48 PM" src="https://github.com/aws-amplify/amplify-ui/assets/68251134/1614fc4e-d4ce-484c-bc48-c6c04900245a"> |
Fixes: https://github.com/aws-amplify/amplify-ui/issues/4885
> fix: Fix table styling for striped variation

- packages/react-notifications/jest.config.ts
- packages/react-notifications/src/components/InAppMessaging/MessageLayout/__tests__/MessageLayout.test.tsx
Fix a couple unit tests broken during the MV migration and bump the unit test coverage thresholds for `@aws-amplify/ui-react-notifications`
NA
`yarn react-notifications test`
> fix(react-notifications): add async to skipped unit tests

- .changeset/lemon-windows-invite.md
- packages/ui/src/theme/css/component/liveness.scss
> fix: update liveness button focus border to have a gap

- .changeset/moody-badgers-punch.md
- packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts
- packages/ui/src/theme/css/component/liveness.scss
- When no face is on screen we should not show the oval canvas
- new behavior:
- current:
- On mobile we should ensure we have full screen camera on the same screen
- new behavior:
- current:
> fix(liveness): fix styling when no face on screen by not showing oval canvas and ensuring full screen camera

- .changeset/silver-tips-shake.md
- packages/react-liveness/src/components/FaceLivenessDetector/shared/Hint.tsx
- Previously the hint component was re-rendering the hint message when checking face is on screen or when face is far enough, this pr makes it so we show the same hint for both those states
- Removed a unnecessary function for rendering the toast component as it was also causing extra renders
> fix: reduce re-renders on hint component

- build-system-tests/package.json
The recent release of [Vue@3.4](https://github.com/vuejs/core/blob/main/CHANGELOG.md#340-slam-dunk-2023-12-29) caused some breaking changes for our vue + vite@2 test. Bumping vue-tsc to ^1.8.27 allowed it to build but given:
- Vue's recommendation to use @vitejs/plugin-vue@^5.0.0 (which has a peer dependency of vite@5)
- Vite is now on v5 and [notes that only the previous major version will receive important fixes/security updates](https://vitejs.dev/releases#release-cycle%E2%80%8B)
we'll bump up to the next working version which is vite@3 as our lowest version to test.
Tested locally by running `npm run vue-latest-vite-3-ts` in build-system-tests folder with no parent node_modules folders.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> chore(build-system-tests): bump vue/vite2 test to vite3

- .github/workflows/build-system-test.yml
Tells the Github workflow to use vite@3 for the build test (that we just changed here https://github.com/aws-amplify/amplify-ui/commit/ff3bf8a283cc7fb0e0d9b09913247cecd8b3cd5c)
> chore(build-system-tests): update workflow for vue(latest)/vite(3)

- .changeset/small-masks-fail.md
- docs/src/components/home/HomeFeatureCard.tsx
- docs/src/components/home/ThemeSwitcher.tsx
- docs/src/pages/[platform]/components/accordion/examples/StylePropsExample.tsx
- docs/src/pages/[platform]/components/input/examples/InputStylePropsExample.tsx
- docs/src/pages/[platform]/components/passwordfield/examples/PasswordFieldStyledPropsExample.tsx
- docs/src/pages/[platform]/components/phonenumberfield/examples/StylePropsExample.tsx
- docs/src/pages/[platform]/components/selectfield/examples/SelectFieldStylePropsExample.tsx
- docs/src/pages/[platform]/components/stepperfield/examples/StepperFieldStylePropsExample.tsx
- docs/src/pages/[platform]/components/tabs/examples/StyleProps.tsx
- docs/src/pages/[platform]/components/textareafield/examples/TextAreaFieldStylePropsExample.tsx
- docs/src/pages/[platform]/components/textfield/examples/TextFieldStylePropsExample.tsx
- docs/src/pages/[platform]/connected-components/authenticator/customization/AuthStyle.tsx
- docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerComponentOverridesExample.tsx
- docs/src/pages/[platform]/theming/style-props/examples/BackgroundExamples.tsx
- docs/src/pages/[platform]/theming/style-props/examples/ColorExamples.tsx
- docs/src/pages/[platform]/theming/style-props/examples/SizeExamples.tsx
- docs/src/pages/[platform]/theming/theming.react-native.mdx
- examples/react-native/src/features/Theming/Basic/Example.tsx
- examples/react-native/src/features/Theming/DarkMode/Example.tsx
- packages/react-native/src/theme/__tests__/useTheme.spec.tsx
- packages/react/src/primitives/types/theme.ts
Removes usage of brand namespace in docs, tests, examples, and types.
We had some straggler cases of the brand color namespace still being used, namely in the following packages:
- **ui-react:** the BrandColorKeys type
- **react-native:** a test for theme provider
And also scattered throughout the docs and some react-native examples.
> chore: remove usage of brand color namespace in docs/types/tests

- .github/workflows/build-system-test-react-native.yml
Removes CLI from the react native build system tests matrix while we trouble shoot CLI test issue.
> chore(build-system-tests-react-native): temp disable CLI tests in RN

- packages/e2e/cypress/fixtures/code-mismatch-exception.json
- packages/e2e/features/ui/components/authenticator/sign-in-sms-mfa.feature
Add and integrate code mismatch exception fixture for "Incorrect SMS code with translated text" e2e test ensuring that a  stable error is returned in CI. 
Too many subsequent calls to `AWSCognitoIdentityProviderService.RespondToAuthChallenge` for the same test user results in a `NotAuthorizedException`:
```json
{
"__type": "NotAuthorizedException",
"message": "Too many invalid credentials attempts. User temporarily locked. Please try again after few seconds."
}
```
Leading to transient errors in CI ([example failure](https://github.com/aws-amplify/amplify-ui/actions/runs/7577363730/job/20638173520#step:40:911)) as the test expects a `CodeMismatchException`.
NA
Ran e2e tests locally, verified fixture usage in cypress test "ROUTES"
By submitting this pull request, I confirm that my …
> fix(e2e): add error fixture for sign-in-sms-mfa invalid code test

- .changeset/nice-pens-wait.md
- packages/react-native/src/Authenticator/index.ts
- packages/react-native/src/Authenticator/useAuthenticator.ts
Update React Native `useAuthenticator` to use `signOut` from `aws-amplify/auth` version due to iOS specifc requirements for federated sign out handling with `@aws-amplify/rtn-web-browser`. On iOS sign out, the end user is prompted with a native alert requesting confirmation of sign out. If the end user cancels they will have already been signed out of the state machine, but will still continue to be authenticated on the JS singleton.
Fixes https://github.com/aws-amplify/amplify-ui/issues/4910
Manual testing
> fix(rna): replace useAuthenticator signOut with default version

- .changeset/proud-kiwis-smash.md
- docs/src/pages/[platform]/connected-components/authenticator/customization/sign-up-fields.web.mdx
- examples/angular/src/pages/ui/components/authenticator/custom-sign-up-fields/custom-sign-up-fields.component.html
- examples/angular/src/pages/ui/components/authenticator/custom-sign-up-fields/custom-sign-up-fields.component.ts
- examples/next/pages/ui/components/authenticator/custom-sign-up-fields/index.page.tsx
- examples/vue/src/pages/ui/components/authenticator/custom-sign-up-fields/index.vue
- packages/e2e/features/ui/components/authenticator/custom-sign-up-fields.feature
- packages/vue/src/components/primitives/amplify-check-box.vue
Add Vue checkbox element label translation
- update hardcoded label value in Vue checkbox to read from Amplify JS `I18n` module using `translate` util
- replace ampersands with `and` in examples and e2e tests
Fixes https://github.com/aws-amplify/amplify-ui/issues/4891
Manual tests, run e2e tests
> fix(vue): translate checkbox label

- .gitignore
- docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx
- docs/src/pages/[platform]/getting-started/usage/vite/react.mdx
Update the Vite getting started guide to remove unneeded workarounds. These are no longer necessary due to fixes in `aws-amplify@6`. Updated the troubleshooting guide to callout that the workarounds for Vite/Webpack/Astro are only needed in older versions of `aws-amplify`.
Before:
After:
Message showing in Troubleshooting:
> fix: update vite.js guide to remove polyfill workarounds

- .changeset/clever-queens-relate.md
- examples/next/pages/ui/components/account-settings/delete-user-display-text/aws-exports.js
- examples/next/pages/ui/components/account-settings/delete-user-display-text/index.page.tsx
- packages/e2e/features/ui/components/account-settings/delete-user-display-text.feature
- packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
Pass `displayText` prop to `WarningView` from `DeleteUser`
Fixes https://github.com/aws-amplify/amplify-ui/issues/4963
- add an e2e test
> fix(AccountSettings): pass displayText to WarningView

- build-system-tests/package.json
- build-system-tests/scripts/mega-app-copy-files.sh
Fixes angular 14 build system tests. `@types/node` > 20.11.7 is incompatible with angular 14, so pin at 20.11.7. 
Passing workflow: https://github.com/aws-amplify/amplify-ui/actions/runs/7715263726
> fix(build-system-tests-angular): pin @types/node to 20.11.7

- docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.react-native.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx
Fixes naming of `CognitoAttributes` in migration docs, which was misspelled as `CognitpAttributes`.
```diff
interface AmplifyUser {
challengeName?: ChallengeName;
-   attributes?: CognitpAttributes;
+   attributes?: CognitoAttributes;
username: string;
}
```
Completed the steps outlined in https://github.com/aws-amplify/amplify-ui/blob/main/docs/README.md#contributing
```
yarn install
yarn setup
yarn docs dev
```
> chore(docs): fix spelling of CognitoAttributes in migration guides

- docs/src/pages/[platform]/connected-components/authenticator/customization/AuthStyle.tsx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.styling.web.mdx
Updates our Authenticator styling/theme examples to work with the latest UI changes.
Fixes https://github.com/aws-amplify/amplify-ui/issues/4977
**Fixes overriding amplify classes example**
- Removes mention of hiding sign up tab with css since users can now use the `hideSignUp` prop instead
- Updates class name used
| Before        | After       | 
| ------------- | ------------ | 
| <img width="400" alt="Screenshot 2024-02-06 at 12 07 52 PM" src="https://github.com/aws-amplify/amplify-ui/assets/376920/7d57cfec-173d-45d2-bca9-9f18dcb22699">      | <img width="400" alt="Screenshot 2024-02-06 at 12 07 18 PM" src="https://github.com/aws-amplify/amplify-ui/assets/376920/75432997-d170-4c07-9787-9364c5030dfa"> |
**Fixes CSS style example**
- I removed mention of making it a dark theme because …
> fix(docs): update style and theming examples for Authenticator

- docs/src/pages/[platform]/getting-started/troubleshooting/shared/vite-polyfill.mdx
This just fixes the react() reference in the Vite `plugins: [] config` when you're on the Vue platform. 
**Before**
**After**
> fix(docs): removes the react reference in vite plugin when on vue docs

- docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx
Updates the tabs on the migration pages to use the correct format.
**Before**
**After**
> fix(docs): migration page tabs

- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.react-native.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.web.mdx
Updates the code examples for i18n from 
```js
import { I18n } from 'aws-amplify';
``` 
to
```js
import { I18n } from 'aws-amplify/utils';
```
which is the correct path for v6
> fix(docs) incorrect i18n import path in code examples

- .changeset/curvy-grapes-clean.md
- packages/react-storage/src/components/StorageImage/StorageImage.tsx
Updates the property passed to useStorageUrl from `identityId` to `targetIdentityId`
Currently we're building the URL for StorageImage with these options:
```js
{
accessLevel,
identityId
validateObjectExistence
}
```
However, `indentityId` should be `targetIdentityId` based [on the storage docs ](https://docs.amplify.aws/javascript/build-a-backend/storage/download/#generate-a-download-url). 
Fixes https://github.com/aws-amplify/amplify-ui/issues/4990
I setup a new Auth + storage Amplify app, and used "protected" accessLevel on `<StorageManager />`. I uploaded a test image with "User A" then looked up its identityId to load it with `<StorageImage />`. Then I logged in with "User B" to verify that the image 404's.
After making the change from this PR and testing in next-example dev, I can …
> fix(react-storage): use targetIdentityId to get url

- docs/__tests__/__snapshots__/sitemap.test.ts.snap
- docs/src/pages/[platform]/theming/responsive/index.page.mdx
- Removing `angular` and `vue` from list of supported frameworks for the `/theming/responsive` page since responsive theming doesn't exist for angular and vue
> Remove angular and vue from list of supported frameworks

- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.full-ui-customization.swift.mdx
This PR adds an explicit example on how to customize the **Sign Up** step in the Authenticator for Swift.
Since this particular step is different than the others, customers might get confused on how to proceed.
I've also added some additional context to the original customization example (for other steps), plus updated other code snippets in this file to be consistent with each other.
- https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/36
Manually tested by deploying locally
> chore(docs): Adding Sign Up customization example for Swift

- docs/src/pages/[platform]/connected-components/authenticator/quick-start.mdx
- docs/src/pages/[platform]/getting-started/installation/dependencies.mdx
A React Native specific Getting Started callout was added at the release of `aws-amplify@6` as it introduced two new React Native packages, `@aws-amplify/react-native` and `@aws-amplify/rtn-web-browser`, both of which required consumers to manually updated the iOS deployment target to meet the version required by the packages.
Starting with React Native version `0.73`, the callout is no longer required as version `0.73` ships with an iOS deployment target that meets the version required by the new packages.
As React Native version `<0.73` are still supported, move the callout in to an `Accordion` and highlight that it is only required for projects using React Native version `0.72` or below
NA
Manual validation of both pages where the callout exists …
> chore(docs): move iOS min deployment target callout in to Accordion

- .changeset/young-plums-fold.md
- packages/ui/src/theme/css/component/liveness.scss
The flex-direction was not set properly on `.amplify-liveness-landscape-error-modal {}`
**Before**
**After**
> fix(ui/liveness): fix flex-direction of landscape error message

- packages/e2e/cypress/integration/common/liveness.ts
- packages/e2e/features/ui/components/liveness/disable-start-screen.feature
- packages/e2e/features/ui/components/liveness/liveness-detector.feature
- packages/e2e/features/ui/components/liveness/with-credential-provider.feature
Add a new cucumber util for extended assertion timeouts for error toasts. Also reverts https://github.com/aws-amplify/amplify-ui/pull/5061
NA
Run e2e tests locally
> fix(e2e): add extended assertion timeout util for liveness

- .changeset/slow-pumpkins-notice.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts
Please make sure to read the Pull Request Guidelines:
https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md
Change empty VideoChunk from `[]` to `new Uint8Array([])`, and use typed AsyncIterator instead of `any`.
https://github.com/smithy-lang/smithy-typescript/pull/1185
https://github.com/aws-amplify/amplify-ui/issues/5057
https://github.com/aws-amplify/amplify-ui/issues/5058
Updated behavior and unit tests in https://github.com/smithy-lang/smithy-typescript/pull/1185.
> fix(react-liveness): use Uint8Array for VideoChunk

- packages/ui/src/helpers/authenticator/__tests__/textUtil.test.ts
- packages/ui/src/helpers/authenticator/textUtil.ts
- packages/ui/src/i18n/dictionaries/authenticator/defaultTexts.ts
- packages/ui/src/i18n/dictionaries/authenticator/en.ts
- packages/ui/src/machines/authenticator/index.ts
- packages/ui/src/machines/authenticator/types.ts
> fix(Authenticator): fix sms no challengeName

- packages/ui/src/helpers/authenticator/facade.ts
"useAutenticator" should be "useAuthenticator"
Helpful for external users who might be searching the codebase for their entry point.
> Fixing typo in facade.ts

- .github/workflows/codeql.yml
This PR updates the official CodeQL GH Action to the latest version.
> chore: update codeql gh action to latest

- packages/react-storage/jest.config.ts
- packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/__tests__/useUploadFiles.spec.ts
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileStatusMessage.test.tsx
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/__snapshots__/FileStatusMessage.test.tsx.snap
- packages/react-storage/src/components/StorageManager/utils/__tests__/uploadFile.test.ts
- packages/react-storage/src/components/StorageManager/utils/uploadFile.ts
Clean up _ui-react-storage_ unit test extraneous typing and async tests  
- remove manual typing of `uploadData` spies
- bump unit test coverage thresholds
- fix a DOM warning emiited from a unit test in [FileStatusMessage.test.tsx](https://github.com/aws-amplify/amplify-ui/compare/chore/clean-up-storage-unit-tests?expand=1#diff-d07b37b39948250e6ebfc88c9b0be7f376d230b7c66cf44531499ea8f87803f0)
unblocks https://github.com/aws-amplify/amplify-ui/pull/5121 (issues surfaced [here](https://github.com/aws-amplify/amplify-ui/actions/runs/8516464231/job/23325713643#step:14:11))
Run unit tests
> chore(react-storage): clean up unit tests

- .changeset/tricky-eels-tie.md
- docs/package.json
- examples/angular/package.json
- examples/next/package.json
- examples/react-native/package.json
- examples/vue/package.json
- package.json
- packages/angular/projects/ui-angular/package.json
- packages/react-auth/package.json
- packages/react-core-auth/package.json
- packages/react-core-notifications/package.json
- packages/react-core/package.json
- packages/react-geo/package.json
- packages/react-geo/src/components/MapView/MapView.tsx
- packages/react-liveness/package.json
- packages/react-native-auth/package.json
- packages/react-native/package.json
- packages/react-notifications/package.json
- packages/react-storage/package.json
- packages/react/package.json
- packages/ui/package.json
- packages/vue/package.json
- yarn.lock
…
Upgrade `aws-amplify` depedencies:
- update all public package `aws-amplify` versions to point at a minimum version of `6.0.26`
- point docs and example apps used in e2e tests to `latest`
- remove extraneous peerDep on `@aws-amplify/geo` from `@aws-amplify/ui-react-geo`
NA
- Verified changes in _yarn.lock_
- Pending e2e tests in CI
> chore(deps): update peerDep versions in public packages, point installed version to latest

- docs/src/pages/[platform]/connected-components/liveness/customization/CustomizationCdn.tsx
- docs/src/pages/[platform]/connected-components/liveness/customization/customization.cdn.react.mdx
This PR fixes missing documentation on downloading and hosting the default and multithreaded versions of the WASM file mentioned [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/README.md#using-bundlers) and [here](https://blog.tensorflow.org/2020/09/supercharging-tensorflowjs-webassembly.html).
Fixes: https://github.com/aws-amplify/amplify-ui/issues/5128
* Verified that each file is available at the jsdelivr.net url via links in the doc changes:
> fix(docs): update instructions for Liveness custom CDN  / use of wasm files

- .github/workflows/publish-hotfix.yml
- .github/workflows/publish-latest.yml
- .github/workflows/version-packages.yml
This PR reverts the aws-amplify/amplify-ui#5091 because it broke the [Version Packages workflow](https://github.com/aws-amplify/amplify-ui/actions/workflows/version-packages.yml) as well as the [Test and Publish workflow](https://github.com/aws-amplify/amplify-ui/actions/workflows/publish-latest.yml).
> Revert "chore(deps): bump changesets/action from b98cec97583b917ff1dc6179dd4d230d3e439894 to 63ffd93140be6000b385d611d886a82c86214719"

- .github/workflows/publish-hotfix.yml
- .github/workflows/publish-latest.yml
- .github/workflows/version-packages.yml
This adds back the change to bump to changesets/action latest version which supports Node 20. This was previously reverted because we hadn't specified the new hash in our Github settings as an allowable GH action.
> Revert "Revert "chore(deps): bump changesets/action from b98cec97583b917ff1dc6179dd4d230d3e439894 to 63ffd93140be6000b385d611d886a82c86214719""

- .github/workflows/publish-hotfix.yml
- .github/workflows/publish-latest.yml
- .github/workflows/version-packages.yml
Reverts aws-amplify/amplify-ui#5147. We need to update changesets in the repo first based on this [gh action run](https://github.com/aws-amplify/amplify-ui/actions/runs/8651412736).
> Revert "chore(deps): bump changesets/action from b98cec97583b917ff1dc6179dd4d230d3e439894 to 63ffd93140be6000"b385d611d886a82c86214719"

- .changeset/smooth-windows-relate.md
- package.json
- yarn.lock
Downgrade `@vitejs/plugin-vue` from `^5.0.4` to `^2.3.4` due to issues with Vite lib compilation mode and type declaration exposed in `@vitejs/plugin-vue@^3` and greater
NA
Validated type build outputs
> fix(vue): downgrade @vitejs/plugin-vue

- .changeset/clean-fireants-argue.md
- packages/react/src/primitives/ButtonGroup/ButtonGroup.tsx
- packages/react/src/primitives/Menu/Menu.tsx
- packages/react/src/primitives/Menu/MenuButton.tsx
- packages/react/src/primitives/Menu/__tests__/menu.test.tsx
- Actually disables the Menu component when `isDisabled` prop is passed in 
- Applies disabled styling and prevents the menu from opening on click
#5164 
> fix(Menu): Fix ability to disable menu component

- docs/src/pages/[platform]/connected-components/authenticator/quick-start.mdx
Updates the quick start example for Authenticator on Android to be more complete, showing a bare-bones implementation of an example `SignedInContent`. The indentation in this block is now also consistent with elsewhere in the document.
https://github.com/aws-amplify/amplify-ui-android/issues/134
- Ran the code sample change in a test app and validated it compiled and ran correctly.
- Ran the docs site locally and validated the changes appeared as desired.
> chore(authenticator): Make the quick start example complete

- .changeset/fair-tips-deliver.md
- packages/react-storage/package.json
- packages/react-storage/src/components/StorageManager/StorageManager.tsx
- packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/actions.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/reducer.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/types.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/useStorageManager.tsx
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/__tests__/useUploadFiles.spec.ts
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts
- packages/react-storage/src/components/StorageManager/types.ts
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileList.test.tsx
- packages/react-storage/src/components/StorageManager/ui/FileList/types.ts
- packages/react-storage/src/components/StorageManager/utils/__tests__/uploadFile.test.ts
- packages/react-storage/src/components/StorageManager/utils/uploadFile.ts
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/internal.ts
- This PR will add `prefix` prop to `StorageManger` to support the Gen2 use cases while maintaining backwards compatibility with `accessLevel` and `path` props, both of which will be deprecated in the future in favor of `prefix`
- Docs updates and e2e tests will be added in separate PRs
> feat(storage-manager): add prefix prop to support gen2 use cases

- .changeset/fair-tips-deliver.md
- examples/next/pages/ui/components/storage/storage-manager/accept-file-extension/index.page.tsx
- packages/react-storage/jest.config.ts
- packages/react-storage/package.json
- packages/react-storage/src/components/StorageManager/StorageManager.tsx
- packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
- packages/react-storage/src/components/StorageManager/__tests__/__snapshots__/StorageManager.test.tsx.snap
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/useStorageManager.test.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/actions.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/types.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/useStorageManager.ts
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/__tests__/useUploadFiles.spec.ts
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts
- packages/react-storage/src/components/StorageManager/types.ts
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileList.test.tsx
- packages/react-storage/src/components/StorageManager/ui/FileList/types.ts
- packages/react-storage/src/components/StorageManager/utils/__tests__/getInput.spec.ts
- packages/react-storage/src/components/StorageManager/utils/__tests__/uploadFile.test.ts
- packages/react-storage/src/components/StorageManager/utils/getInput.ts
- packages/react-storage/src/components/StorageManager/utils/index.ts
- packages/react-storage/src/components/StorageManager/utils/resolveFile.ts
- packages/react-storage/src/components/StorageManager/utils/uploadFile.ts
Add first class support for `path` as callback
- remove `prefix` prop
- allow `accessLevel` to be `undefined` to support `path` only use cases
- remove default `accessLevel` value
NA
> chore(storage-manager): add first-class support for path

- .changeset/rude-yaks-kiss.md
- packages/react-storage/src/components/StorageImage/StorageImage.tsx
- packages/react-storage/src/components/StorageImage/types.ts
Update `StorageImage` deprecation warnings to point to props table in docs 
> chore(gen2 storage): update StorageImage deprecation warnings

- docs/src/pages/[platform]/connected-components/storage/react.mdx
- docs/src/pages/[platform]/connected-components/storage/storageimage/react.mdx
- docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
> fix(docs): update storage links that need to point to gen1 pages still

- docs/src/pages/[platform]/connected-components/storage/react.mdx
- docs/src/pages/[platform]/connected-components/storage/storageimage/props.ts
- docs/src/pages/[platform]/connected-components/storage/storageimage/react.mdx
- docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts
- docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
- Updates storage docs to point to gen1/gen2 links where relevant 
- Update quickstart guide to include gen 2 and gen 1
> chore(docs): update links in storage docs to reference gen1/gen2

- .changeset/fifty-clouds-fry.md
- packages/react-native/package.json
[`react-native@0.74.1`](https://www.npmjs.com/package/react-native/v/0.74.1) was recently released and is above the maximum allowed peerDep of `@aws-amplify/ui-react-native`. This PR increases the allowed peerDep of `@aws-amplify/ui-react-native` to include `^0.74`
NA
Manually tested Authenticator flows in an `expo@latest` app using `react-native@0.74`
> deps(react-native): include 0.74.x in allowed peerDep range

- environments/.gitignore
- environments/storage/gen2/package.json
- environments/storage/package.json
- examples/next/pages/ui/components/storage/storage-image/error/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-image/error/aws-exports.js
- examples/next/pages/ui/components/storage/storage-image/error/index.page.tsx
- examples/next/pages/ui/components/storage/storage-image/private-image/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-image/private-image/aws-exports.js
- examples/next/pages/ui/components/storage/storage-image/private-image/index.page.tsx
- examples/next/pages/ui/components/storage/storage-image/protected-image/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-image/protected-image/aws-exports.js
- examples/next/pages/ui/components/storage/storage-image/protected-image/index.page.tsx
- examples/next/pages/ui/components/storage/storage-image/public-image/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-image/public-image/aws-exports.js
- examples/next/pages/ui/components/storage/storage-image/public-image/index.page.tsx
- examples/next/pages/ui/components/storage/storage-manager/accept-all-file-types/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-manager/accept-all-file-types/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/accept-all-file-types/index.page.tsx
- examples/next/pages/ui/components/storage/storage-manager/authenticated-multipart/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-manager/authenticated-multipart/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/authenticated-multipart/index.page.tsx
- examples/next/pages/ui/components/storage/storage-manager/default-files/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-manager/default-files/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/default-files/index.page.tsx
- examples/next/pages/ui/components/storage/storage-manager/guest-multipart/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-manager/guest-multipart/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/guest-multipart/index.page.tsx
- examples/next/pages/ui/components/storage/storage-manager/upload-actions/amplify_outputs.js
- examples/next/pages/ui/components/storage/storage-manager/upload-actions/aws-exports.js
- examples/next/pages/ui/components/storage/storage-manager/upload-actions/index.page.tsx
Add gen2 storage environment for e2e testing. The backend resource code is stored in the staging repo https://github.com/aws-amplify/amplify-ui-staging/tree/gen2-storage-backend
Note: new permission is required to be added to `AmplifyCLIPull` policy: `"cloudformation:GetTemplateSummary"`
> test(storage): update to use gen2 environment

- docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/form-fields.web.mdx
Add a note to make it clear you need to re-declare defaults when using form fields, per https://github.com/aws-amplify/amplify-ui/issues/5225
> chore(docs): Add a note about re-declaring defaults on form fields

- amplify.yml
- docs/package.json
- examples/next/package.json
- yarn.lock
Upgrade `next.js` in docs and next example to ^14.1.1 to resolve security vulnerability in versions >= 13.4.0, < 14.1.1
Update node version in amplify.yml to 18.17, minimum supported by next.js@14
NOTE BEFORE MERGING we need to
Then before docs release we'll need to update prod build image
Fixes https://github.com/aws-amplify/amplify-ui/security/dependabot/142  
Fixes https://github.com/aws-amplify/amplify-ui/security/dependabot/141
Smoke tested docs site locally. Checked each framework and looked at internal/external links, embedded components, tested functionality like copy button/toggles, and looked to see css/theming was being applied. Looked at console and saw no new errors/warnings being printed. 
Smoked tested next example app locally. Looked at each connected component and tested …
> fix(deps): upgrade next.js in docs package and next example 

- .changeset/spicy-items-destroy.md
- examples/next/package.json
- examples/react-native/package.json
- package.json
- packages/angular/projects/ui-angular/package.json
- packages/react-auth/package.json
- packages/react-core-auth/package.json
- packages/react-core-notifications/package.json
- packages/react-core/package.json
- packages/react-geo/package.json
- packages/react-liveness/package.json
- packages/react-native-auth/package.json
- packages/react-native/package.json
- packages/react-notifications/package.json
- packages/react-storage/package.json
- packages/react/package.json
- packages/ui/package.json
- packages/vue/package.json
- yarn.lock
Update `aws-amplify` peerDep versions in public packages and direct dep versions in example apps
NA
NA
> chore(deps): update amplify scoped and RN dep versions

- .changeset/chilly-penguins-relate.md
- packages/react/src/primitives/Select/Select.tsx
Add `aria-hidden="true"` to the Select drop-down icon to remove it from the accessibility tree.
fix https://github.com/aws-amplify/amplify-ui/issues/5253
> fix(ui-react): add aria-hidden to Select expand icon

- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/TelemetryReporter/TelemetryReporter.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/TelemetryReporter/__tests__/TelemetryReporter.test.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/TelemetryReporter/index.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/__tests__/createStreamingClient.test.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/createStreamingClient.ts
- Added a telemetry middleware to the streaming client which appends values to the query
- Appends `attempt-count` and `precheck-view-enabled`
- Attempt count is counted as the number of attempts that are less than 5 minutes apart, once 5 minutes has passed without an attempt we will reset the count
> chore(liveness): Added Liveness telemetry

- examples/next/pages/ui/components/liveness/components/LivenessInlineResults.tsx
The conversion to base 64 string happens in the lambda so removing from frontend so the audit image shows up.
Ran example app and verified audit image shows up
> chore(liveness): Remove audit image processing from example app

- .changeset/odd-bats-smile.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/videoRecorder.ts
- packages/react-liveness/src/components/FaceLivenessDetector/utils/__tests__/device.test.ts
- packages/react-liveness/src/components/FaceLivenessDetector/utils/device.ts
- There is a known bug on Chrome 125 where the the H264 encoder fails silently - https://issues.chromium.org/issues/343199623
- This has caused issues on certain devices where it will attempt to record video but nothing will be recorded in memory
- Added a solution where we choose an alternate mimetype for Android devices running the known chrome affected version
> fix(liveness): target android chrome 125 to use alternate mime type

- canary/script/yarn.lock
Fixes https://github.com/aws-amplify/amplify-ui/security/dependabot/144
> chore(deps): bump braces in canary/script from 3.0.2 to 3.0.3

- CONTRIBUTING.md
I ran into an error when running ```yarn setup``` with an M3 Mac and Python 3.12. One of the required dependencies for canvas installation (distutils) is deprecated for Python 3.12. There is a recommended replacement package called python-setuptools that solves the issue when you download it. I believe that many people are likely to run into a similar issue if they use a recent Python version.
I modified the CONTRIBUTING.md document to include the error and the solution. For more trust, I also linked an article showing that this is Python’s recommended solution. I added bolded headers to the different troubleshooting steps for more organization.
Reviewed CONTRIBUTING.md code as a markdown file to ensure valid appearance.
By submitting this pull request, I confirm that my contribution is …
> docs: CONTRIBUTING.md troubleshooting section addition

- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/StreamRecorder/StreamRecorder.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/StreamRecorder/__tests__/StreamRecorder.test.ts
- Issue: with no-light feature we decided to open the websocket connection on the camera check screen, the websocket connection takes in a readable stream derived from the MediaRecorder as an input, and we don't have a way to change that mid connection
- Potential solution: Now when users change camera we create a new MediaRecorder object and feed it's even stream into the originally set MediaRecorder that was used as an input to the websocket connection. Any events that are sent to the new camera / MediaRecorder are passed through to the original mediaRecorder which we maintain a reference to
> fix(liveness): fix camera switching after ws connection established

- build-system-tests/scripts/mega-app-copy-files.sh
- build-system-tests/templates/components/react/vite/template-tsconfig-vite-latest.json
- Update `template-tsconfig-vite-latest.json` based on this PR: https://github.com/vitejs/vite/pull/15913:
- to not reference `tsconfig.node.json`
- add `"composite": true` 
> fix(build-system-tests): update tsconfig for create-vite@latest

- .changeset/short-doors-flash.md
- packages/react-storage/jest.config.ts
- packages/react-storage/src/components/StorageManager/StorageManager.tsx
- packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/reducer.test.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/useStorageManager.test.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/actions.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/reducer.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/types.ts
- packages/react-storage/src/components/StorageManager/hooks/useStorageManager/useStorageManager.ts
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/__tests__/useUploadFiles.spec.ts
- packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts
- packages/react-storage/src/components/StorageManager/types.ts
- packages/react-storage/src/components/StorageManager/ui/FileList/FileRemoveButton.tsx
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/__snapshots__/FileControl.test.tsx.snap
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/__snapshots__/FileList.test.tsx.snap
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/__snapshots__/FileRemoveButton.test.tsx.snap
- packages/react-storage/src/components/StorageManager/utils/__tests__/getInput.spec.ts
- packages/react-storage/src/components/StorageManager/utils/getInput.ts
Prefer `processedKey` as `key` parameter to provided `onRemoveUpload` callback
- add `processedKey` to `StorageFile` interface
- add `setProcessedFileKey` action
- provide value of `processedKey` to `onRemoveUpload` callback if provided alongside `processFile`
fixes https://github.com/aws-amplify/amplify-ui/issues/5327
Manual tests, add unit tests
File                                    | % Stmts | % Branch | % Funcs | % Lines |
------------------------|-----------|----------|-----------|-------|
Before: All files                              |   93.86 |    86.34 |   87.91 |   93.76 |
After: All files                               |   95.33 |     87.5 |   90.32 |   95.07 |
> fix(storage-manager): update file processedKey on process file complete

- .changeset/eighty-candles-complain.md
- packages/react/src/primitives/SearchField/SearchField.tsx
- packages/react/src/primitives/SearchField/__tests__/SearchField.test.tsx
Accessibility review found that having the clear button excluded from the tab order does not meet accessibility standards for keyboard users.
This PR addresses this finding by removing the `excludeFromTabOrder` property on the clear button in the SearchField component
addresses #5375 
changes validated locally by building and verifying the updated behavior in local instance of the docs site
https://github.com/aws-amplify/amplify-ui/assets/100880084/153fec20-f408-4fa2-b047-a05a8e201f3d
> fix(SearchField): accessibility - do not exclude clear button from tab order

- .changeset/grumpy-crews-laugh.md
- packages/react/src/primitives/Rating/RatingIcon.tsx
- packages/react/src/primitives/Rating/__tests__/RatingIcon.test.tsx
- packages/ui/src/theme/css/component/rating.scss
Currently, icons that are completely filled and completely unfilled have classes amplify-rating__icon–filled and amplify-rating__icon–empty, respectively. The mixed icons act as an overlaid combination of the 2 icons, and have an additional class: amplify-rating__icon. This gives the mixed icons absolute position to ensure an accurate overlay. The problem arises due to the fact that the absolute position (combined with inline-flex display of the flex container) resulted in the icon having bottom space, pushing down the text. Note that this space still exists in the filled and empty icons – just on top, which was not noted in the bug report.
To fix the misalignment, I passed in the amplify-rating__icon class into the empty and filled icons to give all an absolute position. To fix the …
> fix(ui & ui-react): Resolves ratings height discrepancy in edge case 

- examples/next/pages/ui/components/storage/storage-browser/composable-playground/index.page.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Search.tsx
- packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
This fixes the below error when running the next-example and a minor fix to Search control that was referencing Label instead of FieldLabel
> fix(storage-browser): max callstack error

- .changeset/silver-dolls-report.md
- packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx
- packages/react/src/components/Authenticator/FederatedSignIn/FederatedSignInButtons/FederatedSignInButton.tsx
- packages/react/src/components/Authenticator/FederatedSignIn/FederatedSignInButtons/__tests__/__snapshots__/FederatedSignInButton.test.tsx.snap
- packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx
- packages/react/src/components/Authenticator/SignIn/SignIn.tsx
- packages/react/src/components/Authenticator/SignUp/SignUp.tsx
- packages/react/src/components/Authenticator/shared/ConfirmSignInFooter.tsx
- packages/react/src/components/Authenticator/shared/TwoButtonSubmitFooter.tsx
- Removing any style props from buttons on authenticator to fix font weight inconsistencies
- Moved the in the Authenticator to be in the same location in the DOM in each view
- Made the link buttons consistent across Authenticator views
#5156 
> fix(authenticator): fixing visual inconsistencies

- packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/__tests__/MessagesControl.spec.tsx
Add `renderMessage` function to `MessagesControl` props, which optionally allows customer to override the way we render messages  
> chore(raven): Add ability to pass in custom renderMessage function

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
- Use the latest changes for `Icon` in order to use the `variant` property
> chore(storage-browser): use Icon variant in TableControl

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Controls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Target.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Target.spec.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/index.ts
- packages/react-storage/src/styles/storage-browser.css
Currently, the two sub controls are output together.
**Field**
**Destination**
> chore(storage-browser): scaffold TargetControl

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Message.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Paginate.tsx
- packages/react-storage/src/components/StorageBrowser/Views/types.ts
- Removes composability of Message
- Moves `OmitElements` to /types.ts so it can be shared
Tested that variants still work, and you can no longer access subcontrols.
**Message with error variant**
**Just double checking autocomplete for subcontrols (none)**
> chore(storage-browser): remove composability of Message

- .changeset/four-apricots-compete.md
- examples/next/pages/ui/components/storage/storage-manager/process-file-access-level/index.page.tsx
- packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
- packages/react-storage/src/components/StorageManager/utils/__tests__/getInput.spec.ts
- packages/react-storage/src/components/StorageManager/utils/getInput.ts
- Using a combination of `processFile` and `path` would cause the processFile to be called on loop
- Seems to be caused by the `setProcessKey` being called before the getting the `identityId` for use with the path callback
- Moved the call to setPRocessedKey` after the call to `fetchAuthSession` and that seems to resolve the issue
- Updated e2e test to use `path` with `processFile`
- fixes https://github.com/aws-amplify/amplify-ui/issues/5467
> fix(storage): fix looping calls to processFile

- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createRequestStreamGenerator/__tests__/createRequestStreamGenerator.test.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createRequestStreamGenerator/createRequestStreamGenerator.ts
- We previously had this but it got lost in the refactor - https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts#L166
- Seems like some devices send an empty video event randomly so this helps fix that
> fix(liveness): skip empty video events

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Navigate.tsx
- packages/react-storage/src/components/StorageBrowser/Views/types.ts
Removes composability of Navigate
**Output**
**Verifying subcontrols aren't accessible**
> chore(storage-browser): update composability of Navigate

- packages/react-storage/src/components/StorageBrowser/ErrorBoundary/__tests__/ErrorBoundary.spec.tsx
- Mock implementation of `console.error()` to suppress console logs during `ErrorBoundary` tests
> chore(storage-browser): Mock implementation for console.error() for error boundary test

- packages/react-storage/src/components/StorageBrowser/Controller.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Navigate.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Navigate.spec.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/LocationDetailView.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx
- packages/react-storage/src/components/StorageBrowser/context/actions/index.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/listLocationItemsAction.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/listLocationsAction.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/testUtils.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/types.ts
- packages/react-storage/src/components/StorageBrowser/context/controls/Navigate/Navigate.tsx
- packages/react-storage/src/components/StorageBrowser/context/controls/Navigate/__tests__/Navigate.spec.tsx
- packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
- packages/react-storage/src/styles/storage-browser.css
- Updated `NavigateState` 
- to have `history`, which is a string array of the folder names we are navigating through
- Updated `Navigate` control to use the navigate context to create the `NavigateItems` 
- Moved `listLocationItems` loading logic out of `Controller.tsx` to `LocationDetailView`
> chore(storage-browser): Add Navigate control to LocationDetailView

- packages/react-storage/src/components/StorageBrowser/Controller.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/Controls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/LocationActionView.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
- packages/react-storage/src/components/StorageBrowser/context/controls/ActionSelect/ActionSelect.tsx
- packages/react-storage/src/components/StorageBrowser/context/controls/ActionSelect/__tests__/ActionSelect.spec.tsx
- packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
- Displays ActionView when an action is selected from the ActionSelect menu
- Added a quick "cancel" button to this view to test the "DESELECT_ACTION" state
> chore(storage-browser): use ActionView when action is selected

- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/StreamRecorder/StreamRecorder.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/StreamRecorder/__tests__/StreamRecorder.test.ts
- Mimics more of what we have in `main` to handle empty video events and recording starts
> bug(liveness): handle empty video events

- examples/next/pages/ui/components/authenticator/use-is-signed-in/aws-exports.js
- examples/next/pages/ui/components/authenticator/use-is-signed-in/index.page.tsx
- packages/e2e/features/ui/components/authenticator/use-is-signed-in.feature
- packages/react-core/src/__tests__/__snapshots__/index.spec.ts.snap
- packages/react-core/src/hooks/__tests__/useIsSignedIn.test.ts
- packages/react-core/src/hooks/index.ts
- packages/react-core/src/hooks/useIsSignedIn.ts
- packages/react-core/src/index.ts
Updated the useIsSignedIn hook to use the data state hook. This allows for an isLoading field in the state, as well as an error message.
This hook uses the useDataState hook in a unique way, since the action function (getCurrentUser) is not returned to the customer. On top of this, signedIn state needs to use hub events to update state. Therefore, I decided to call getCurrentUser after each hub event update. Also, since the false state throws an error, I needed to add a condition to the action that allowed for setting the data state vs setting the error state, and made 2 calls to the action to update each.
I created a test file to go over possible cases and ran yarn test.
> Feat(IdentityProviders): useIsSignedIn with data state

- .changeset/tall-olives-beam.md
- docs/src/pages/[platform]/components/tabs/examples/ComposedTabsExample.tsx
- packages/react/src/primitives/Tabs/TabsContainer.tsx
- packages/react/src/primitives/Tabs/TabsContext.tsx
- packages/react/src/primitives/Tabs/TabsItem.tsx
- packages/react/src/primitives/Tabs/TabsPanel.tsx
- packages/react/src/primitives/Tabs/__tests__/Tabs.test.tsx
- packages/react/src/primitives/Tabs/constants.ts
Adds `groupId` to TabsContext such that unique IDs can be created for each tab group. IDs are of the form `${groupId}-tab-${idValue}` for tabs, and`${groupId}-panel-${idValue}` for panels. `idValue` is the given `value` stripped of its whitespace using the added constant `WHITESPACE_VALUE`. `idValue` is created in TabsPanel and TabsItem, so assuming the developer enters the same values for these two elements the functionality works. `defaultValue` and controlled tab functionality still works because the actual `value` of the tabs is not altered in any way, but it is highly recommended to not assign `value` to a string containing whitespace. 
Outer html output for a tablist with given values: ['Tab 1', 'Tab 2', 'Tab 3']: `<div role="tablist" class="amplify-tabs__list" …
> fix(ui-react): Whitespace in Tab IDs

- examples/next/pages/ui/components/ai/ai-conversation/index.page.tsx
- packages/react-ai/src/ai-conversation-styles.css
- packages/react-ai/src/components/AIConversation/context/MessageVariantContext.tsx
- packages/react-ai/src/components/AIConversation/context/MessagesContext.tsx
- packages/react-ai/src/components/AIConversation/context/index.ts
- packages/react-ai/src/components/AIConversation/createAIConversation.tsx
- packages/react-ai/src/components/AIConversation/createProvider.tsx
- packages/react-ai/src/components/AIConversation/types.ts
- packages/react-ai/src/components/AIConversation/views/Controls/AvatarControl.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/__tests__/AvatarControl.spec.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/__tests__/MessagesControl.spec.tsx
- Add `MessageVariantContext` and `RoleContext` 
- Generate classnames for diff variants/roles following BEM syntax 
> chore(raven): Add context providers for message variants/roles 

- packages/angular/projects/ui-angular/package.json
- packages/react-auth/package.json
- packages/react-core-auth/package.json
- packages/react-core-notifications/package.json
- packages/react-core/package.json
- packages/react-geo/package.json
- packages/react-liveness/package.json
- packages/react-native-auth/package.json
- packages/react-native/package.json
- packages/react-notifications/package.json
- packages/react-storage/package.json
- packages/react/package.json
- packages/ui/package.json
- packages/vue/package.json
- yarn.lock
Point `aws-amplify` peerDeps to "storage-browser" to resolve dep conflicts during install of `@aws-amplify/ui-react-storage@storage-browser` tagged version
NA
NA
> chore(storage-browser): point aws-amplify deps at storage-browser tag

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Download.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Download.spec.tsx
- packages/react-storage/src/components/StorageBrowser/context/actions/__tests__/downloadAction.spec.tsx
- packages/react-storage/src/components/StorageBrowser/context/actions/actions.tsx
- packages/react-storage/src/components/StorageBrowser/context/actions/downloadAction.ts
- packages/react-storage/src/components/StorageBrowser/context/types.ts
- Use `getUrl` to create a signed url and download the file when clicked
> chore(storage-browser): use getUrl to download

- packages/react/src/components/Authenticator/FederatedIdentities/context/ProviderDataListContext.tsx
- packages/react/src/components/Authenticator/FederatedIdentities/context/__tests__/ProviderDataListContext.test.tsx
- packages/react/src/components/Authenticator/FederatedIdentities/controls/types.ts
This adds the ProviderDataListContext, which will be used to reference provider data in context. Adjusted types to accommodate more flexible Icon field, as well as a few minor changes.
Created a series of tests to make sure context was created accurately and threw errors when necessary.
> Feat(react): FederatedIdentities provider data list context

- packages/react-ai/src/ai-conversation-styles.css
- packages/react-ai/src/components/AIConversation/context/elements/definitions.ts
- packages/react-ai/src/components/AIConversation/views/Controls/ActionsBarControl.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/FieldControl.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/__tests__/MessagesControl.spec.tsx
- Added keyboard navigation to mimic Facebook Messenger and other chat applications
- Tabbing through the component only hits the most recent message and it's action buttons
- Once focused on a message, arrow navigation up and down goes to other messages
- Also set autofocus to the input area
> chore(ai): add keyboard navigation for conversation

- examples/next/pages/ui/components/authenticator/use-is-signed-in/index.page.tsx
- packages/react-core/src/hooks/__tests__/useIsSignedIn.test.ts
- packages/react-core/src/hooks/useIsSignedIn.ts
- packages/react/src/components/Authenticator/FederatedIdentities/context/elements/IconElement.tsx
This is a simple PR that changes the type of useIsSignedIn's data from {isSignedIn: boolean} to just a boolean.
Used example app with new data state and re-ran unit test
> Feat(react-core): Updates useIsSignedIn data 

- packages/react-storage/src/components/StorageBrowser/Controller.tsx
- packages/react-storage/src/components/StorageBrowser/__tests__/Controller.spec.tsx
Fix issue with locations loading always resetting to the default state
> fix(storage-browser): update locations loading init to use refresh flag

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Download.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Download.spec.tsx
- Add `useGetLocationConfig` to `DownloadControl` so that config can be passed to `handleDownload` call to create the `getUrl` API call
> Feat storage browser/fix download managed auth

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Navigate.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Navigate.spec.tsx
- packages/react-storage/src/styles/storage-browser.css
- Nests the Separator inside of the `<li>` so there is valid list markup
- Passes down an `isCurrent` prop to the last NavigateItem to properly apply aria-current to the button and not show the separator for the last item
```
<nav aria-label="Breadcrumbs" class="storage-browser__navigate">
<ol class="storage-browser__navigate__list">
<li class="storage-browser__navigate__item">
<button class="storage-browser__navigate__button">Home</button>
<span class="storage-browser__navigate__separator" aria-hidden="true">/</span>
</li>
<li class="storage-browser__navigate__item">
<button class="storage-browser__navigate__button">fileuploaderbucket121216-dev/public</button>
<span class="storage-browser__navigate__separator" aria-hidden="true">/</span>
</li>
<li class="storage-browser__navigate__item"> …
```
> chore(storage-browser): fix list markup for Navigate and use aria-current

- examples/next/pages/ui/components/storage/storage-browser/default-auth/custom-elements.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Cancel.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Controls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Cancel.spec.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/index.ts
- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
- packages/react-storage/src/components/StorageBrowser/context/elements/definitions.ts
This is used in the Upload controls table for cancelling an item you've selected to download. 
```
<button
class="storage-browser__cancel"
aria-label="Cancel upload for Screenshot 2024-08-13 at 3.36.21 PM.png"
>
<svg
aria-hidden="true"
width="24"
height="24"
viewBox="0 -960 960 960"
fill="none"
xmlns="http://www.w3.org/2000/svg"
class="storage-browser__cancel__icon"
>
<path
d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"
fill="currentColor"
></path>
</svg>
</button>
```
> chore(storage-browser): adds theme-able Cancel button

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Download.tsx
- Noticed a bug where a download would automatically happen when you navigate between prefixes. Added a flag to make sure that the download only happens on a click.
**Steps to reproduce bug**:
1. Navigate to a nested prefix with files to download
2. Download a file
3. Navigate up a prefix using the navigate breadcrumbs
4. Observe that the file that was just downloaded, gets downloaded again
- I think this might be happening because of the `useEffect` in the `DownloadControl` component and how it will call the function to download if the`signedUrl` is valid. When we first download a file, it saves the `signedUrl` in its state and so navigating will cause each of the `DownloadControls` to re-render which causes it to download the file again since it has a valid `signedUrl`?
By submitting …
> fix(storage-browser): set flag to specify when to download file so that it only happens on click

- examples/next/pages/ui/components/storage/storage-browser/default-auth/custom-elements.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
- packages/react-storage/src/styles/storage-browser.css
- Adds File/Folder icons depending on the key/row type to LocationsView and LocationDetailView tables
- Adds a container for table cells. Since buttons inside of the table have padding, developers can use this to make a consistent padding around cells that don't have a button (so now the icons can line up)
- Added var(--storage-browser-gap-small) to use in cases like the Navigate item gap, and smaller gaps between text and icons.
- Some adjustments to the next-example custom UI
**LocationsView**
**LocationDetailView**
> chore(storage-browser): Add file/folder icons to table, some css cleanup

- .changeset/tame-toys-agree.md
- docs/package.json
- packages/react-native/package.json
`style-dictionary` is a required dependency of docs/ and packages/react-native/
Previously, this dependency had been indirectly provided via ui/, which caused regression when `style-dictionary` was reclassified as a dev dependency in ui/
These changes seek to resolve the issue by adding `style-dictionary` as a dependency to docs/ and packages/react-native/
https://github.com/aws-amplify/amplify-ui/issues/5590
This was confirmed by validating attached issue using latest version of `@aws-amplify/ui-react-native`, followed by validating the resolution of the issue by rolling back to a version of `@aws-amplify/ui-react-native` in which the dependency was provided.
> fix: add style-dictionary dependency to docs and react-native package

- .changeset/few-geese-exist.md
- packages/react-native/package.json
Update _@aws-amplify/ui-react-native_ peerDeps to support `react-native@^0.75`
NA
Verified Authenticator federated sign in on iOS using a vanilla RN example app
> fix(react-native): bump rn peerDep range

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Message.tsx
- packages/react-storage/src/components/StorageBrowser/context/elements/IconElement.tsx
The dismiss icon got lost in the shuffle when we switched the <- Back and Cancel icons around.
**before**
**after**
> fix(storage-browser): Message dismiss icon

- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/components/FileSelect/FileSelect.tsx
- packages/react/src/components/FileSelect/__tests__/FileSelect.spec.tsx
- packages/react/src/components/FileSelect/index.ts
- packages/react/src/internal.ts
Add `FileSelect` component and `useFileSelect` utility
```tsx
function MyUploadButton() {
const [files, setFiles] = React.useState<File[]>([]);
const [fileSelect, handleSelect] = useFileSelect(setFiles);
return (
<>
{fileSelect}
<Button
onClick={() => {
handleSelect('file');
}}
/>
</>
);
}
```
NA
Manual testing
> chore(FileSelect): add useFileSelect

- packages/react-storage/src/styles/storage-browser.css
Fixes some table styling when just using the default styles.
**before (stretched and weird buttons)**
**after**
> chore(storage-browser): fix various default styles

- packages/ui/src/i18n/dictionaries/authenticator/de.ts
Use consistent spelling for E-Mail in the german translation.  Before the change, it was sometimes EMail, Email or e-mail, but only "E-Mail" is correct.
> fix: Use consistent spelling for E-Mail in german

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Table.spec.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationsView/__tests__/LocationsView.spec.tsx
- packages/react-storage/src/components/StorageBrowser/context/controls/Table/index.ts
- packages/react-storage/src/components/StorageBrowser/context/controls/Table/sortCompareUtils.ts
Splitting this up from https://github.com/aws-amplify/amplify-ui/pull/5583
- Add `sortCompareUtils.ts` to hold compare functions for sorting
- Update `LocationsViewTable` to have columns that sort the table
- Update `TableControl` to have `renderHeaderItem` to render the table header items
> chore(storage-browser): add sorting to locations view table

- packages/react-storage/src/components/StorageBrowser/context/controls/locationActions/__tests__/__snapshots__/defaults.spec.ts.snap
- packages/react-storage/src/components/StorageBrowser/context/controls/locationActions/__tests__/defaults.spec.ts
- packages/react-storage/src/components/StorageBrowser/context/controls/locationActions/defaults.tsx
- packages/react-storage/src/components/StorageBrowser/context/controls/locationActions/types.ts
Add unit tests for default `actions`
NA
unit tests
> chore(storage-browser): add ACTIONS_DEFAULT unit tests

- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/useHandleUpload.ts
- Set file key as `webkitrelativepath` if it exists so that folders can be created based on the `/` delimeter
> chore(storage-browser): use webkitrelativepath if it exists when creating cancelable task

- packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/__tests__/LocationDetailView.spec.tsx
- Add `delimiter: '/'` to refresh call so that it works as expected
> chore(storage-browser): add delimiter to refresh list location items call

- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/CreateFolderControls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
- packages/react-storage/src/components/StorageBrowser/context/elements/__tests__/defaults.spec.tsx
- packages/react-storage/src/components/StorageBrowser/context/elements/defaults.tsx
- packages/react-storage/src/styles/storage-browser.css
- Moves the Back button to where the breadcrumbs are, updates style
- Moves the Message for Create Folder to appear below the input field
- Some other CSS cleanup for elements we're not using, fixes left alignment, etc
**Upload files screen**
**Create folder screen**
> chore(storage-browser): move back button, UI cleanup

- packages/react-storage/src/components/StorageBrowser/Controller.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Table.spec.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationsView/Controls/__tests__/DataTable.spec.tsx
- packages/react-storage/src/components/StorageBrowser/__tests__/Controller.spec.tsx
- Move out `LIST_LOCATION_ITEMS` action call from location detail view table into `Controller`
- Note: separating this into it's own separate PR in preparation for refactoring location detail view table with `DataTable`
> chore(storage-browser): move list location items fetch into controller

- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/useHandleUpload.ts
- Previously, was using an updated `file.key` that contained `webkitRelativePath` value. Forgot to update the `remoteTask` call to use the same value so that items could be removed. This PR updates that
> fix(storage-browser): use updated key to remove tasks

- packages/react-storage/src/components/StorageBrowser/Controller.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx
- packages/react-storage/src/components/StorageBrowser/__tests__/Controller.spec.tsx
- packages/react-storage/src/components/StorageBrowser/context/actions/__tests__/listLocationsAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/listLocationsAction.ts
Overview
- On the `LocationsView` when a location is clicked we drill down to `LocationDetailView` listing it's items.
- location permission types: READ, WRITE, READWRITE
- location object types: bucket, bucket prefix, bucket object
Requirement
- While we can list bucket and bucket prefix items, we can't list a bucket object. (it's already a single item)
- We can only list bucket and bucket prefix items which have read permission    
- exclude `permission:WRITE` and `type:Object`
- Unit tests
- Tested on sample app to make sure locations with write permission and object types aren't displayed
> feat(stroage-browser): exclude locations with write permission and object type

- packages/react-ai/src/components/AIConversation/utils.ts
- packages/react-ai/src/components/AIConversation/views/Controls/FieldControl.tsx
- packages/react-ai/src/components/AIConversation/views/default/Form.tsx
- Previously we were not awaiting the image buffer before allowing sending an image
- Fix to await the file buffer
- Update default send button to also key off files
> fix(ai): fix attaching images to messages

- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
- Disable buttons on any status other than `INITIAL`
> fix(storage-browser): disable buttons on any status other than initial

- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/__tests__/UploadControls.spec.tsx
- For now, added two `input` elements for selecting files and one for folder
> fix(storage-browser): add input element for adding files and one for adding a folder

- packages/react-storage/src/components/StorageBrowser/Views/utils.ts
Currently if there is only one item to show, it will always show a pagination next button.
**Before**
https://github.com/user-attachments/assets/4fa295c2-c25b-40de-9508-ac758d1f28ea
**After**
> fix(storage-browser): single page pagination

- packages/react-storage/src/components/StorageBrowser/Views/Controls/Navigate.tsx
- packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Navigate.spec.tsx
- packages/react-storage/src/components/StorageBrowser/context/elements/defaults.tsx
Rendered a span with plain text for current Navigate item instead of a button
**After**
> chore(storage-browser): use plain text for current breadcrumb item

- packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/__tests__/CreateFolderControls.spec.tsx
Bumps up our branch coverage a teeny tiny bit for this missing CreateFolderMessage render when there is a FAILED or COMPLETE status.
> chore(storage-browser): update CreateFolder test for conditional in parent component

- packages/react-storage/src/components/StorageBrowser/ErrorBoundary/ErrorBoundary.tsx
- packages/react-storage/src/components/StorageBrowser/ErrorBoundary/__tests__/ErrorBoundary.spec.tsx
- packages/react-storage/src/styles/storage-browser.css
Adds some specific styles for the ErrorBoundary message. 
- Since this sits above the elements provider, it has color/background styles associated with it.
- Wraps it in our CLASS_BASE so it can pick up CSS custom props and grid styles.
> chore(storage-browser): add ErrorBoundary styling

- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/ComponentOverrides.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/Default.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/DisplayText.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/Event.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/FileTypes.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/Handle.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/Hash.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/Metadata.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/PathProp.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/Resumable.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/Theme.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/UploadActions.tsx
- docs/src/pages/[platform]/connected-components/storage/fileuploader/examples/i18n.tsx
- docs/src/pages/[platform]/theming/icons/IconSwitcher.tsx
* Changes use of `StorageManager` to `FileUploader` in FileUploader docs examples
> fix: update FileUploader docs to use FileUploader in examples

- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.react-native.mdx
- docs/src/pages/[platform]/connected-components/authenticator/customization/customization.i18n.web.mdx
* Added reference to Thai support to both web and React Native i18n language lists
* Updated React Native i18n language list to include Hebrew, Norwegian, and Ukrainian as well
> chore(docs): update i18n list in authenticator docs to reflect supported languages

- package.json
- yarn.lock
* Resolution was added to ensure `send` is at least version 0.19.0
https://github.com/aws-amplify/amplify-ui/security/dependabot/160
> fix(dependabot): add resolution to update send to at least 0.19.0

- .changeset/olive-bats-obey.md
- docs/__tests__/__snapshots__/props-table.test.ts.snap
- docs/src/components/ComponentsMetadata.ts
- docs/src/pages/[platform]/components/avatar/examples/AvatarLoadingExample.tsx
- docs/src/pages/[platform]/components/avatar/examples/index.ts
- docs/src/pages/[platform]/components/avatar/react.mdx
- packages/react-ai/src/components/AIConversation/views/default/MessageList.tsx
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/primitives/Avatar/Avatar.tsx
- packages/react/src/primitives/Avatar/types.ts
- packages/ui/src/theme/components/avatar.ts
- packages/ui/src/theme/css/component/avatar.scss
- packages/ui/src/theme/tokens/components/avatar.ts
- packages/ui/src/types/primitives/componentClassName.ts
Added `isLoading` prop to Avatar primitive and added a loading state in the AIConversation which uses it. 
> feat(avatar): add loading state to avatar and AIConversation

- packages/e2e/detox/integration/common/shared.ts
- Noticed when running e2e RN android tests locally this placeholder test would consistently fail
- Updated to match by testId
- Updated to check attribute on element
- Example failure screenshot below to see what throwing looking like
> fix(e2e): fix placeholder matching rn e2e android

- .changeset/ten-beds-jump.md
- packages/react-ai/src/components/AIConversation/context/ResponseComponentsContext.tsx
- packages/react-ai/src/components/AIConversation/context/index.ts
- packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx
- packages/react-ai/src/components/AIConversation/views/Controls/__tests__/MessagesControl.spec.tsx
- packages/react-ai/src/components/AIConversation/views/default/MessageList.tsx
- Developer can override the `sendMessage` utility to send messages with tools that are not renderable in the AIConversation component example below:
- Updates all of our response components to be prefixed with `UI_` to be easier to tell as response component tool uses rather than regular tool uses
- Filters out messages that are not renderable, i.e only render empty tool use blocks
```
handleSendMessage={(content) =>
sendMessage({
...content,
toolConfiguration: {
tools: {
generateRecipe: {
description: "List ingredients needed for a recipe",
inputSchema: {
json: {
type: "object",
properties: {
ingredients: {
type: "array",
items: {
type: "object",
properties: {
ingredientName: { type: "string" },
quantity: { type: "number" },
unit: { type: "string" },
}
},
},
},
},
},
},
}
}
})
}
```
By …
> fix(ai): fix renders for empty toolUse messages

- canary/apps/react/vite/package.json
- canary/apps/vue/vite/package.json
- Vite v2 is no longer supported and has security vulnerabilities so replacing it with `latest` in canaries to resolve the dependabot alerts 
https://github.com/aws-amplify/amplify-ui/security/dependabot/166
https://github.com/aws-amplify/amplify-ui/security/dependabot/165
https://github.com/aws-amplify/amplify-ui/security/dependabot/164
https://github.com/aws-amplify/amplify-ui/security/dependabot/163
Passing POC workflow https://github.com/aws-amplify/amplify-ui/actions/runs/10927229890
> chore(dependabot): Upgrade vite in canaries

- .changeset/few-houses-grow.md
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/components/ThemeProvider/ComponentStyle.tsx
- packages/react/src/components/ThemeProvider/Style.tsx
- packages/react/src/components/ThemeProvider/ThemeStyle.tsx
- packages/react/src/components/ThemeProvider/__tests__/ComponentStyle.test.tsx
- packages/react/src/server.ts
- packages/ui/src/theme/createTheme/__tests__/__snapshots__/defineComponentTheme.test.ts.snap
- packages/ui/src/theme/createTheme/__tests__/createComponentCSS.test.ts
- packages/ui/src/theme/createTheme/__tests__/defineComponentTheme.test.ts
- packages/ui/src/theme/createTheme/createComponentCSS.ts
- packages/ui/src/theme/createTheme/createTheme.ts
- packages/ui/src/theme/createTheme/defineComponentTheme.ts
- packages/ui/src/theme/createTheme/index.ts
- packages/ui/src/theme/index.ts
This is a new feature of the experimental theme v2 work. 
We have come across a use-case where a customer wants to create a custom component theme in a separate package, but cannot add that theme to the `createTheme` function due to a circular dependency. This functionality allows customers to just write the CSS that only their component needs, whenever they need to. 
> feat(theming) add custom component style rendering

- .github/workflows/label-new-issues.yml
* `pending-maintainer-response` is now only added to issues not opened by a maintainer
* `pending-triage` is now applied to new issues _in addition to_ `pending-maintainer-response`, as they indicate different meanings
* Previously, `pending-triage` had been replaced by `pending-maintainer-response`. This was inadequate, as it did not properly communicate the status of an issue.
> chore: Update pending-maintainer-response and restore pending-triage

- .changeset/red-fans-pretend.md
- packages/react/__tests__/__snapshots__/exports.ts.snap
- packages/react/src/components/ThemeProvider/ComponentStyle.tsx
- packages/react/src/components/ThemeProvider/GlobalStyle.tsx
- packages/react/src/components/ThemeProvider/Style.tsx
- packages/react/src/components/ThemeProvider/ThemeStyle.tsx
- packages/react/src/components/ThemeProvider/__tests__/GlobalStyle.test.tsx
- packages/react/src/server.ts
- packages/ui/src/theme/createTheme/__tests__/__snapshots__/createGlobalCSS.test.ts.snap
- packages/ui/src/theme/createTheme/__tests__/createGlobalCSS.test.ts
- packages/ui/src/theme/createTheme/createComponentCSS.ts
- packages/ui/src/theme/createTheme/createGlobalCSS.ts
- packages/ui/src/theme/createTheme/index.ts
- packages/ui/src/theme/index.ts
Adding the ability to create global styles with the experimental theming APIs
```jsx
<GlobalStyle styles={{
'body': {
backgroundColor: 'purple'
// supports design tokens!
color: theme.tokens.colors.font.primary
}
}} />
```
> feat(theming): add global style ability

- packages/react-storage/browser/package.json
- packages/react-storage/package.json
Fix _dist_ path resolution of `StorageBrowser`  subpath exports
NA
- `yarn build && yarn size`
- smoke test default and managed auth apps
> fix(storage-browser): update subpath exports post rollup mv bump

- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/copyAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/createFolderAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/deleteAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/downloadAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/listLocationItemsAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/listLocationsAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/uploadAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/copyAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/createFolderAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/deleteAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/downloadAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/index.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/listLocationItemsAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/listLocationsAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/uploadAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/index.ts
- packages/react-storage/src/components/StorageBrowser/actions/types.ts
Add standardized action handler interfaces for default `StorageBrowser` actions
NA
NA
> chore(storage-browser): add standardized action handler types

- .github/workflows/issue-comment.yml
* Modify workflow triggered by new comments on GitHub issues when "discussion" label is present
* If an issue has a "discussion" label, new community comments will not trigger the addition of the "pending-maintainer-response" label
> feat(GitHub): Add support for 'discussion' label on issues

- .changeset/silly-knives-wash.md
- packages/react-ai/src/components/AIConversation/AIConversation.tsx
There was a bug with the allowAttachments for the Amplify UI AIConversation component that was making it so the attachment button was never showing up. 
> fix(ai-conversation): allow attachments on amplify component

- packages/react-storage/package.json
- packages/react-storage/src/components/StorageBrowser/actions/handlers/copyAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/listLocationsAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/types.ts
- packages/react-storage/src/components/StorageBrowser/adapters/createAmplifyAuthAdapter.ts
- packages/react-storage/src/components/StorageBrowser/adapters/createManagedAuthAdapter.ts
- packages/react-storage/src/components/StorageBrowser/adapters/types.ts
- packages/react-storage/src/components/StorageBrowser/context/__tests__/useGetCredentialsProvider.spec.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/__tests__/listLocationsAction.spec.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/listLocationItemsAction.ts
- packages/react-storage/src/components/StorageBrowser/context/actions/listLocationsAction.ts
- packages/react-storage/src/components/StorageBrowser/context/config.tsx
- packages/react-storage/src/components/StorageBrowser/context/types.ts
- packages/react-storage/src/components/StorageBrowser/context/useGetCredentialsProvider.ts
- packages/react-storage/src/components/StorageBrowser/createProvider.tsx
- packages/react-storage/src/components/StorageBrowser/storage-internal.ts
Add _/StorageBrowser/storage-internal.ts_ re-export file pointing to `@aws-amplify/storage/internals`
- disable eslint `import/no-extraneous-dependencies` for _storage-internal.ts_ to prevent need for adding a peerDep for `@aws-amplify/storage` to minimize risk of mismatching install versions
`yarn lint && yarn build`
NA
> chore: add aws-amplify/storage/internals export file to remove peerDep

- packages/react-storage/jest.config.ts
- packages/react-storage/src/components/StorageBrowser/actions/configs/__tests__/__snapshots__/defaults.spec.ts.snap
- packages/react-storage/src/components/StorageBrowser/actions/configs/__tests__/context.spec.tsx
- packages/react-storage/src/components/StorageBrowser/actions/configs/__tests__/defaults.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/configs/context.ts
- packages/react-storage/src/components/StorageBrowser/actions/configs/defaults.ts
- packages/react-storage/src/components/StorageBrowser/actions/configs/index.ts
- packages/react-storage/src/components/StorageBrowser/actions/configs/types.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/copyAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/createFolderAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/deleteAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/downloadAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/listLocationItemsAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/listLocationsAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/uploadAction.ts
- packages/react-storage/src/components/StorageBrowser/actions/index.ts
- packages/react-storage/src/components/StorageBrowser/actions/types.ts
Add standardized action config interfaces
NA
Manual tests
> feat(storage-browser): add action configs

- packages/react/src/components/FileSelect/FileSelect.tsx
- packages/react/src/components/FileSelect/__tests__/FileSelect.spec.tsx
Fix `useFileSelect` to handle folder selection and move clearing of `inputProps` to `onChange`
NA
> fix(useFileSelect): fix useFileSelect to handle folder selection

- .changeset/dirty-cups-chew.md
- packages/react-ai/src/hooks/__tests__/createAIHooks.test.tsx
- packages/react-ai/src/hooks/useAIGeneration.tsx
- Danny noticed an error where simple string type returns from the client were returning malformed objects
- This is because we were assuming all return types from the generate client would be spreadable objects
- Updated called to useDataState to just return the data and massage the return type to add graphqlErrors after to avoid having to spread the return data
> fix(ai): update useAIGeneration to add graphqlErrors before return

- package.json
- yarn.lock
> chore: pin cookie to 0.7.0

- .changeset/fresh-parents-invent.md
- examples/next/pages/ui/components/ai/use-ai-generation/index.page.tsx
- packages/react-ai/src/hooks/__tests__/createAIHooks.test.tsx
- packages/react-ai/src/hooks/useAIGeneration.tsx
Errors in GraphQL for AI generation routes are currently being sent to the client in the `errors` part of the response, but the `useAIGeneration` hook wasn't setting the `hasError`. I also moved the error to the `message` part of the hook. It seemed weird that there could be different places to check for the error message?
> chore(ai): add graphql errors to useAIGeneration

- .changeset/rich-bags-smile.md
- package.json
- packages/angular/projects/ui-angular/package.json
- packages/react-ai/package.json
- packages/react-ai/src/components/AIConversation/AIConversation.tsx
- packages/react-ai/src/types.ts
- packages/react-ai/src/version.ts
- packages/react-auth/package.json
- packages/react-core-auth/package.json
- packages/react-core-notifications/package.json
- packages/react-core/package.json
- packages/react-geo/package.json
- packages/react-liveness/package.json
- packages/react-native-auth/package.json
- packages/react-native/package.json
- packages/react-notifications/package.json
- packages/react-storage/package.json
- packages/react/package.json
- packages/ui/package.json
- packages/ui/src/utils/setUserAgent/constants.ts
- packages/ui/src/utils/setUserAgent/setUserAgent.ts
- packages/vue/package.json
- scripts/generateVersion.js
- yarn.lock
Adds custom UA string for AIConversation component. Bumps the minimum aws-amplify version to 6.6.5 for all packages. 
> chore(ai): adding UA string for AIConversation

- packages/react-storage/src/components/StorageBrowser/composables/context.ts
- packages/react-storage/src/components/StorageBrowser/composables/types.ts
- packages/react-storage/src/components/StorageBrowser/controls/DataTableControl.tsx
- packages/react-storage/src/components/StorageBrowser/controls/StatusDisplayControl.tsx
- packages/react-storage/src/components/StorageBrowser/controls/__tests__/DataTableControl.spec.tsx
- packages/react-storage/src/components/StorageBrowser/controls/__tests__/StatusDisplayControl.spec.tsx
- packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useDataTable.spec.tsx
- packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useStatusDisplay.spec.tsx
- packages/react-storage/src/components/StorageBrowser/controls/hooks/useDataTable.ts
- packages/react-storage/src/components/StorageBrowser/controls/hooks/useResolvedComposable.tsx
- packages/react-storage/src/components/StorageBrowser/controls/hooks/useStatusDisplay.ts
- packages/react-storage/src/components/StorageBrowser/controls/types.ts
This PR flattens control hooks to just vend the props directly rather than nested under `props` field.
> chore(storage-browser): flatten control hooks to return props directly

- packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/CameraSelector.test.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCameraModule.test.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/machine.test.ts
- packages/react-liveness/src/components/FaceLivenessDetector/types/classNames.ts
- packages/react-liveness/src/components/FaceLivenessDetector/utils/__tests__/device.test.ts
- packages/react-liveness/src/components/FaceLivenessDetector/utils/device.ts
- packages/ui/src/theme/css/component/liveness.scss
- Check whether video is user-facing or not based on the device label
- If video is user-facing, apply `transform: scaleX(-1);` to mirror the video 
- Assume video is user-facing by default since our component/most devices default to choosing user-facing cameras 
- added unit tests
- Manually tested on iOS/desktop on https://main.d2pnskzbmchcgk.amplifyapp.com/ (this deployment contains a few unrelated changes so the relevant part is just whether or not the video mirrors or doesn't mirror depending on which camera you select) 
> fix(liveness): Only apply transform style on user-facing video

- packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCameraModule.test.tsx
- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts
- Fix for an issue where the oval renders in the wrong location when switching cameras to unblock data collection
- Add an event listener to make sure video metadata (which includes `video.videoHeight` and `video.videoWidth`) is loaded before attempting to draw the oval
- Remove `drawStaticOval` from state machine because we already call it in the LivenessCameraModule. Calling from multiple places caused weird/unpredictable behavior 
- Deployment https://testing.d2pnskzbmchcgk.amplifyapp.com/
- Compare to https://alpha.d3v0f004886eky.amplifyapp.com/
> fix(liveness): Fix oval render when switching cameras 

- packages/react-storage/src/components/StorageBrowser/actions/__tests__/createEnhancedListHandler.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/createEnhancedListHandler.ts
- Adds a handler that can wrap list handlers to add reset, refresh and search functionality.
- Add unit tests
Includes feedback from https://github.com/aws-amplify/amplify-ui/pull/5994.
> feat(storage-browser): add enhanced list handler

- packages/react-storage/src/components/StorageBrowser/providers/store/files/__tests__/utils.spec.ts
- packages/react-storage/src/components/StorageBrowser/providers/store/files/utils.ts
Minor improvements to file state on add and remove:
- sort file items on add in `fileReducer` and return 
- return previous items on remove if next items length matchs previous items length
NA
Manual test, unit tests
> chore(storage-browser): sort files on add

- packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__mocks__/testUtils.ts
- packages/react-liveness/src/components/FaceLivenessDetector/utils/helpers.ts
- Remove existingDeviceId and add facingMode: 'user' to tell camera to prefer 
- This fixes an issue where the back camera would be chosen for FaceMovementAndLight if it was used most recently (FaceMovementAndLight only works with front camera)
Deployment: https://testing.d2pnskzbmchcgk.amplifyapp.com/
Compare to: https://alpha.d3v0f004886eky.amplifyapp.com/
Selected FaceMovementChallenge and chose a back camera, then went back to FaceMovement + light and verified that front camera was used 
> chore(liveness): update video constraints for selected camera

- packages/e2e/features/ui/components/storage/storage-browser/drag-and-drop.feature
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/__tests__/useLocationDetailView.spec.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/useLocationDetailView.ts
This PR reintroduces a conditional which determines whether a drag and dropped items are files, folders or both. This determination subsequently triggers either routing to the upload file or folder actions. In the case of a mix of files/folders being dropped, the action will be treated as uploading files.
This should also fix the drag and drop e2e test which currently fails locally.
> fix(storage-browser): Reintroduce folder conditional on drag and drop

- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/getLocationDetailViewTableData/constants.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/getLocationDetailViewTableData/getFileRowContent.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/getLocationDetailViewTableData/getFolderRowContent.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/getLocationDetailViewTableData/getLocationDetailViewTableData.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/getLocationDetailViewTableData/types.ts
Move `LOCATION_DETAIL_VIEW_HEADERS` to a shared constants file to resolve circular deps between the `LocationDetailView` table data generation utils and address import from _dist/types/components/StorageBrowser/actions_
```
rollup v4.22.4
bundles src/index.ts, src/components/StorageBrowser/index.ts → dist...
(!) [plugin typescript] @rollup/plugin-typescript TS5055: Cannot write file '/Users/cpollman/Amplify/back_back_up/amplify-ui/packages/react-storage/dist/types/components/StorageBrowser/actions/configs/context.d.ts' because it would overwrite input file.
(!) [plugin typescript] @rollup/plugin-typescript TS5055: Cannot write file '/Users/cpollman/Amplify/back_back_up/amplify-ui/packages/react-storage/dist/types/components/StorageBrowser/actions/configs/defaults.d.ts' because it would …
```
> fix(storage-browser): move LOCATION_DETAIL_VIEW_HEADERS to constants file

- .changeset/input-compositionevent.md
- packages/react-ai/src/components/AIConversation/context/elements/definitions.ts
- packages/react-ai/src/components/AIConversation/views/Controls/FormControl.tsx
- packages/react-ai/src/components/AIConversation/views/default/Form.tsx
When to push Return/Enter key in the Form about AIConversation component, it can decide to send a message by whether in editing the text. I used the CompositionEvent that whether to know whether in editing the text.
https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent/data
https://react.dev/reference/react-dom/components/common#compositionevent-handler
I used the AIConversation component in Japanese.
Japanese IME need to conversion of Hiragana to Kanji. We use the Return/Enter key when confirm this conversion. But, AIConversation component send the message whenever press Return/Enter key for confirming the conversion.
AIConversation component cannot send the full message in Japanese.
For example, I want to send "今日の東京の天気はなんですか?".
Japanese IME need to press the Enter key for …
> fix: AIConversation doesn't care about conversion, for example Hira to Kanji in Japanese

- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/getActionViewTableData.ts
When uploading a single file, instead of displaying `'/'` as the folder, display `'-'`
> fix(storage-browser): Display '-' instead when uploading files

- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/copy.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/copy.ts
Add URI encoding to the copy source to handle copying the object key containing special characters. Techinically it should be added to the Amplify JS library. However, since customers may have already encode the copy source to workaround this problem, it's not safe to introduce the change in Amplify JS library. 
Add this change to StorageBrowser will prevent breaking change but also handle the scpecial characters in the source.
> fix(react-storage): url encode copy source

- packages/react-storage/src/components/StorageBrowser/actions/__tests__/search.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/createEnhancedListHandler.ts
previously, we only checked for paths matching the prefix, but we also want to ignore paths that are part of the prefix.
e.g. if `prefix = "photos/album/"`, `path= "photos/album/random-photos/pic.jpg"` and `query="photo"` -- we only want to match `photos/album/random-photos/`
> fix: search matches items in prefix

- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/LocationDetailView.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/__tests__/LocationDetailView.spec.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/useLocationDetailView.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationsView/LocationsView.tsx
* Use the result returned by the `useProcessTasks(downloadHandler)` in `useLocationDetailView` to derive download error flag and message
* Render download error message using the existing MessageControl integration
* sample app testing
* unit testing
> chore(sto-bro): surfacing download error from location detail view

- packages/e2e/cypress/integration/common/shared.ts
- packages/e2e/features/ui/components/storage/storage-browser/filter-locations.feature
Add an e2e test for filtering locations
> chore(sto-bro): add filter locations e2e test

- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/getLocationDetailViewTableData/__tests__/getLocationDetailViewTableData.spec.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/getLocationDetailViewTableData/constants.ts
Makes "Last Modified" column header into sentence case for fit and finish
> fix(storage-browser): makes Last Modified heading into sentence case

- packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/copyView.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/CopyViewProvider.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/FoldersMessageControl.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/__tests__/CopyViewProvider.spec.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/__tests__/__snapshots__/useFolders.spec.ts.snap
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/types.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/useFolders.ts
> feat(storage-browser): add search exhausted message to copy view

- examples/next/pages/ui/components/storage/storage-browser/composable-playground/index.page.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/CopyView.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/useCopyView.ts
This PR moves the folders listing behavior into the `useCopyView` hook to support composability in the same way as the other views which auto-list data within the view hooks.
> fix(storage-browser): Move folder init into copy hook

- packages/react-storage/src/components/StorageBrowser/actions/configs/__tests__/defaults.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/configs/defaults.tsx
Made the `disable` callback function of the default `uploadActionConfig` and `createFolderActionConfig` to always return `true` so these two actions won't get disabled when selecting/deselecting items in the location details view.
- unit tests
- manual tests with the example apps
> fix(sto-bro): keep create folder and upload actions always enabled

- packages/e2e/cypress/integration/common/storagebrowser.ts
- packages/e2e/features/ui/components/storage/storage-browser/download.feature
- Adds download e2e test for storage browser
> [feat] Add Storage browser download tests

- packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/__tests__/__snapshots__/locationDetailView.spec.ts.snap
- packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/__tests__/scenarios.ts
- packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/locationDetailView.ts
- fixes an issue where search results message is incorrect when no results are found 
- add test
> fix(storage-browser): show search exhausted message on empty results

- packages/e2e/cypress/integration/common/fileuploader.ts
- packages/e2e/cypress/integration/common/shared.ts
- packages/e2e/cypress/support/commands.d.ts
- packages/e2e/cypress/support/commands.ts
- packages/e2e/features/ui/components/storage/storage-browser/action-menu.feature
- Follow up PR to [address comment](https://github.com/aws-amplify/amplify-ui/pull/6147#discussion_r1852947313) to refactor common cy utils to commands.
- The `upload a folder` test is also cleaned up to only performed required checks
- Add TS doc string to `cypress/support/commands.d.ts`
- update fileuploader e2e tests to use cy.fileInputUpload
Tested cypress locally
> test(e2e): add cy commands for storage-browser

- packages/react-storage/src/components/StorageBrowser/providers/store/__tests__/useStore.spec.ts
This PR adds unit tests `useStore`
> test(storage-browser): Add unit tests

- packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
- packages/react-storage/src/components/StorageBrowser/types.ts
expose [additional storage browser types](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx#L128)
linked and tested `react-storage` package locally
> fix(react-storage): fix createStorageBrowser type issue

- .changeset/custom-actions-now.md
> chore(storage-browser): add missing changeset

- .changeset/gentle-countries-kneel.md
- packages/react-geo/package.json
- yarn.lock
Bump `maplibre-gl-js-amplify` dep to `4.0.2` in `@aws-amplify/ui-react-geo` to resolve build failures in NextJS pages router apps
NA
Manually tested locally
> fix: bump maplibre-gl-js-amplify dep

- .github/workflows/build-system-test-react-native.yml
- build-system-tests/scripts/mega-app-install.sh
* The mega app used in cli React Native canary build tests uses the dependency `react-native-safe-area-context`
* Currently, the workflow to run the build test is set to use the latest version of `react-native-safe-area-context`
* The release of version 5.0.0 increased the minimum required version of React Native to 0.75.0+, while support for lower versions is still being included in tests
* This caused an incompatibility on tests using versions of React Native below 0.75.0, resulting in test failure.
* Build test was confirmed to pass with this change
* Set version of `react-native-safe-area-context` used in pipeline build tests to latest minor change within v4, as v5 includes breaking changes to React Native versions required in testing process. …
> fix: resolve React Native build test failure

- build-system-tests/scripts/mega-app-install.sh
- docs/src/components/ExpoSnack.tsx
- docs/src/data/frameworks.ts
* Update hard-coded version of `react-native-safe-area-context` to `^4.2.5` to match other usage within repo
* Add comment explaining why the latest version is not used
* Update commands in docs to install correct version
* Fix minor typo
> chore: denote react native safe area dep limitation and update quickstart commands

- docs/src/pages/[platform]/connected-components/storage/fileuploader/props.ts
Fix a bug in the FileUploader props docs where it takes a key instead of "s3key".
> fix (FileUploader): update FileUploader prop docs for defaultFiles

- .changeset/many-feet-appear.md
- packages/react-native/package.json
Update `@aws-amplify/ui-react-native` to support v0.76
- update `react-native` peerDep to allow all versions >=0.70
```diff
-   "react-native": "^0.70 || ^0.71 || ^0.72 || ^0.73 || ^0.74 || ^0.75",
+   "react-native": ">=0.70",
```
Resolves https://github.com/aws-amplify/amplify-ui/issues/5973
Manual verification of installation and smoke testing of `@aws-amplify/ui-react-native` in a `react-native@0.76` example app (thanks @jordanvn)
> chore(react-native): update allowed peerDep to >=0.70

- docs/src/pages/[platform]/connected-components/liveness/full-api.react.mdx
* Fix typo in reference to "FaceLivenessDetectorCore"
> fix(docs): remove typo from liveness detector core docs

- .github/workflows/receive-fork-review.yml
- .github/workflows/reusable-build-system-test.yml
- .github/workflows/reusable-e2e.yml
Update `upload-artifact` github action to `v4.5.0`, addresses usage of deprecated major version (`v3.x`)
NA
NA
> fix(github-actions): bump upload-artifact to v4

- .github/workflows/reusable-build-system-test.yml
Temporarily ignore react@latest in build tests until react@19 support is released
> chore(build-system-tests): disable react@latest tests

- packages/react/src/primitives/SliderField/SliderField.tsx
- packages/react/src/primitives/SliderField/__tests__/SliderField.test.tsx
Fixes an issue where the label value for the slider was not updating on external update. TBH there might be a cleaner way to do this, but I'm rusty. 
To repro:
1. set a value via props
2. unmount the component
3. mount the component again with a different value
4. Observe the slider bar has repositioned while the label still reports the original value
Added a test and built a test page to validate with my own 👁️ 
(the top slider is controlled, bottom one uncontrolled, the button just sets a random value)
Previous:
With the fix:
> fix(slider): remounted controlled value not updating

- .changeset/large-swans-repair.md
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/createFolder.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/constants.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/createFolder.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/upload.ts
The purpose of this change is to add the default checksum algorithm header to create folder requests originating from storage browser. This allows the create folder action to be compatible with S3 buckets that have object lock enabled and a default retention set.
- unit testing
> fix(react-storage): enable default checksum algorithm for create folder action 

- docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.react-native.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.react.mdx
- docs/src/pages/[platform]/getting-started/migration/migration.vue.mdx
* Changing `fetchUserAttribues` to `fetchUserAttributes` in all instances the typo was present
https://github.com/aws-amplify/amplify-ui/issues/6321
> fix(docs): fix typo of fetchUserAttributes

- package.json
- yarn.lock
Remove out of date `browserslist` resolution andd run`npx update-browserslist-db@latest` from the monorepo root to clear docs `dev` and `build` warnings from `can-i-use-lite`
NA
`yarn && yarn docs dev`
> chore(deps): remove out of date browserslist resolution

- .changeset/warm-mirrors-begin.md
- packages/react-storage/src/components/FileUploader/FileUploader.tsx
The purpose of this pull request is to update the deprecation message when access level is used to point to the correct URL.
https://github.com/aws-amplify/amplify-ui/issues/6368
> chore(react-storage): update access level deprecation message

- docs/src/components/Layout/index.tsx
Fix rendering of Table of Contents links that are not visible in the current page
**Before**
**After**
NA
Manual test
> fix(docs): remove non-visible header rendering in TOC

- build-system-tests/scripts/mega-app-install.sh
React Native v0.78 was released last night and `react-native-safe-area-context` v5.2.0 is explicitly required to support this version. The purpose of this pull request is to update the build test script to install the correct version of this package depending on the target RN version.
Sample Run:
https://github.com/aws-amplify/amplify-ui/actions/runs/13425426394
> chore(ci): specify react-native-safe-area-context version

- packages/e2e/features/ui/components/authenticator/sign-in-with-phone.feature
The purpose of this change is to reduce flakiness associated with E2E tests by initializing intercept listeners earlier in test execution step (prior to firing intercept target).
Sample run:
https://github.com/aws-amplify/amplify-ui/actions/runs/13442552437?pr=6373
- e2e tests
> chore(ci): reduce angular e2e flakiness

- .changeset/eight-socks-approve.md
- packages/react/src/primitives/shared/__tests__/styleUtils.test.tsx
- packages/react/src/primitives/shared/styleUtils.ts
Set a property on a primitive component to Numeric 0, the property will be set to 0 in the browser.
#6380
> fix: Numeric 0 can be set in the property

- examples/next/pages/ui/components/storage/storage-browser/custom-actions/index.page.tsx
- examples/next/pages/ui/components/storage/storage-browser/custom-actions/styles.css
- packages/e2e/cypress/integration/common/shared.ts
- packages/e2e/features/ui/components/storage/storage-browser/observability.feature
- packages/react-storage/src/components/StorageBrowser/ComponentsProvider.tsx
- packages/react-storage/src/components/StorageBrowser/ErrorBoundary/ErrorBoundary.tsx
- packages/react-storage/src/components/StorageBrowser/ErrorBoundary/index.ts
- packages/react-storage/src/components/StorageBrowser/__tests__/createStorageBrowser.spec.tsx
- packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
- packages/react-storage/src/components/StorageBrowser/types.ts
Allow overwriting the default ErrorBoundary to catch the potential unexpected errors.
```jsx
createStorageBrowser({
ErrorBoundary: MyErrorBoundaryClass
})
```
Or disable the default error boundary
```jsx
createStorageBrowser({
ErrorBoundary: null
})
```
Unit test, Integ test,
> feat(ui-react-storage): allow custom error boundary

- build-system-tests/scripts/mega-app-install.sh
The purpose of this pull request is to remove an override in the build system test now that the updated peer dependency version for `react-native-safe-area-context` has been released to the `latest` tag.
Force installation override in build system test. was first introduced with release of `react-native@0.78` which requires `react-native-safe-area-context@5.x`, leading to a conflict with the peer dependency version specified by `ui-react-native` of `^4.2.5`. This peer dependency conflict has been resolved with latest release.
- https://github.com/aws-amplify/amplify-ui/pull/6383
- https://github.com/aws-amplify/amplify-ui/pull/6372
- [Successful Build Test](https://github.com/aws-amplify/amplify-ui/actions/runs/13974840006)
By submitting this pull request, I confirm that my contribution …
> chore: revert build system override for peer dep installation

- .changeset/metal-dogs-attack.md
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/CopyViewProvider.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/__tests__/CopyViewProvider.spec.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/__tests__/utils.spec.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/utils.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DeleteView/DeleteViewProvider.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DeleteView/__tests__/useDeleteView.spec.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DeleteView/__tests__/utils.spec.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DeleteView/useDeleteView.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DeleteView/utils.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/UploadView/UploadViewProvider.tsx
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/UploadView/__tests__/utils.spec.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/UploadView/utils.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/__tests__/__snapshots__/getActionViewTableData.spec.ts.snap
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/__tests__/getActionViewTableData.spec.ts
- packages/react-storage/src/components/StorageBrowser/views/LocationActionView/getActionViewTableData.ts
Fix passing of invalid item `key` provided to `delete` handler from `LocationDetailView` search results:
- remove `key` parsing in `useDeleteView`
- refactor "Folder" column value extraction in action views
- add missing `title` value to `CopyViewProvider`
fixes #6449
- manual testng
- unit tests
> fix(storage-browser): remove key parsing in useDeleteView

- packages/angular/projects/ui-angular/src/lib/components/authenticator/components/select-mfa-type/select-mfa-type.component.spec.ts
- packages/ui/src/helpers/authenticator/formFields/defaults.ts
- packages/ui/src/types/authenticator/form.ts
This should have been removed as part of an earlier refactor. There is no functional impact but it affects the exposed interface when overriding form fields for customization.
> fix(email-mfa): remove select-mfa-type from form fields union

- .github/workflows/test-internal-prs.yml
- examples/next-app-router/package.json
- examples/next-app-router/src/components/ThemeToggle.tsx
- examples/next/package.json
- package.json
- yarn.lock
Downgrade `react-icons`
- update `next-app-router` example app to use material icons in place of missing lucide icons
- reapply changes to allow CI to run against feature branch
> chore(deps): downgrade react-icons

- .changeset/forty-hotels-tan.md
- docs/src/pages/[platform]/connected-components/storage/storage-browser/react.mdx
- examples/next/pages/ui/components/storage/storage-browser/default-auth/routed/StorageBrowser.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/copy.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/createFolder.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/delete.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/download.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/upload.spec.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/copy.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/createFolder.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/delete.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/download.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/types.ts
- packages/react-storage/src/components/StorageBrowser/actions/handlers/upload.ts
- packages/react-storage/src/components/StorageBrowser/tasks/__tests__/useProcessTasks.spec.ts
- packages/react-storage/src/components/StorageBrowser/tasks/useProcessTasks.ts
- packages/test-utils/src/storage-browser/mock-handlers.ts
Update `useProcessTasks` to include `error` in `task` result, update on status callback handling logic to update `task` before providing to callbacks
- return `error` from all handlers in error cases ('FAILED', 'OVERWRITE_PREVENTED', 'CANCELED')
- refactor `updateTask` in `useProcessTasks` to return updated `task` for providing to on status callbacks
NA
Unit tests, manual tests
> fix(storage-browser): update task statuses before passing to callbacks, add error to TaskResult

- examples/next-app-router/src/app/storage-browser/controlled-value/page.tsx
- examples/react-router/src/App.tsx
- examples/react-router/src/main.tsx
- examples/react-router/src/storage-browser/controlled-value/index.tsx
- examples/react-router/src/storage-browser/default-value/index.tsx
- examples/react-router/src/storage-browser/index.ts
- examples/react-router/src/storage-browser/props-validation/index.tsx
- packages/react-storage/src/components/StorageBrowser/providers/index.ts
- packages/react-storage/src/components/StorageBrowser/providers/store/index.ts
- packages/react-storage/src/components/StorageBrowser/providers/store/value/index.ts
- packages/react-storage/src/components/StorageBrowser/providers/store/value/types.ts
- packages/react-storage/src/components/StorageBrowser/types.ts
- packages/react-storage/src/components/StorageBrowser/useAction/types.ts
- add `defaultValue`, `onValueChange` and `value` to `StorageBrowserProps` and `StorageBrowserProviderProps` interfaces
- add initial controlled property related interfaces in _react-storage/src/components/StorageBrowser/providers/store/value/index.ts_
- add props validation examples in `react-router` example app
NA
> feat(storage-browser): add defaultValue, onValueChange, and value props

- .changeset/five-pandas-wash.md
- packages/react-storage/src/components/FileUploader/ui/FileList/__tests__/__snapshots__/FileControl.test.tsx.snap
- packages/react-storage/src/components/FileUploader/ui/FileList/__tests__/__snapshots__/FileList.test.tsx.snap
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/__snapshots__/FileControl.test.tsx.snap
- packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/__snapshots__/FileList.test.tsx.snap
- packages/react/src/primitives/Button/__tests__/Button.test.tsx
- packages/react/src/primitives/Loader/Loader.tsx
- packages/react/src/primitives/Loader/__tests__/Loader.test.tsx
Change the accessibility role of an loader to `progressbar` instead of an `img`, and accessibly hide the `Loader` when  in `indeterminate` state. 
The changes was validated using manual testing through VoiceOver. The VoiceOver now identifies the Loader with 20% determinate value as `20% loading indicator` instead of an `image`. 
> fix(ui-react): Loader primitive accessibility role

- packages/react-storage/src/components/StorageBrowser/store/__tests__/context.spec.tsx
- packages/react-storage/src/components/StorageBrowser/store/__tests__/storeReducer.spec.ts
- packages/react-storage/src/components/StorageBrowser/store/__tests__/useStoreReducer.spec.ts
- packages/react-storage/src/components/StorageBrowser/store/__tests__/utils.spec.ts
- packages/react-storage/src/components/StorageBrowser/store/__tests__/validateStoreProps.spec.ts
- packages/react-storage/src/components/StorageBrowser/store/constants.ts
- packages/react-storage/src/components/StorageBrowser/store/context.tsx
- packages/react-storage/src/components/StorageBrowser/store/index.ts
- packages/react-storage/src/components/StorageBrowser/store/storeReducer.ts
- packages/react-storage/src/components/StorageBrowser/store/types.ts
- packages/react-storage/src/components/StorageBrowser/store/useStoreReducer.ts
- packages/react-storage/src/components/StorageBrowser/store/utils.ts
- packages/react-storage/src/components/StorageBrowser/store/validateStoreProps.ts
- packages/ui/src/utils/utils.ts
Add refactored `StoreProvider` responsible for state management of `location`, `actionType`, `path` and `key` values
- add `StoreProvider`/`useStore` and unit tests
- add `useStoreProvider` and unit tests
- add `validateStoreProps` and unit tests
- add `storeReducer` and unit tests
- add related utils and unit tests
- add/update related types
NA
- manual testing and e2e testing on _feat-sb-controllled/dev_ branch
- unit tests
> feat(storage-browser): add refactored store context

- build-system-tests/scripts/mega-app-install.sh
Temporarily pin webpack version to bypass build test failures.
- https://github.com/aws-amplify/amplify-ui/actions/runs/14318033966/job/40128570900
> chore: pin webpack version in vue-cli build test

- .changeset/fast-pigs-clap.md
- packages/react-storage/src/components/StorageBrowser/components/index.ts
- packages/react-storage/src/components/StorageBrowser/index.ts
- packages/react-storage/src/components/StorageBrowser/views/hooks/useResolveTableData/__tests__/useResolveTableData.spec.ts
- packages/react-storage/src/components/StorageBrowser/views/hooks/useResolveTableData/useResolveTableData.ts
- packages/react/package.json
- packages/react/src/primitives/Icon/context/IconsContext.tsx
Fix `StorageBrowserIconType` resolving to `any` for consumers of _@aws-amplify/ui-react-storage_
**Before**
**After**
**Changes**
- add missing `export.fields` field to _react/package.json_
- remove duplicated `StorageBrowserIconType` type from ui-react
- expose `StorageBrowserIconType` from _@aws-amplify/ui-react-storage/browser_
- fix naming `useResolveDataTable`/`useResolveTableData` naming discrepancy in ui-react-storage
NA
`yarn build` and validate appropriate typing in vscode
> fix(react): add export.types for internal subpath

- .github/workflow-samples/tagged-release.yml
- .github/workflows/reusable-e2e.yml
Update _.github/workflows/reusable-e2e.yml_ to include configurable `resource-path` provided to e2e example app on start to allow running of example apps that do not include `Authenticator` tests
NA
- validate commands locally
- CI
> chore(ci): add configurable resource-path to e2e example start

- .changeset/nasty-months-teach.md
- packages/react-storage/src/components/StorageBrowser/tasks/__tests__/useProcessTasks.spec.ts
- packages/react-storage/src/components/StorageBrowser/tasks/types.ts
- packages/react-storage/src/components/StorageBrowser/tasks/useProcessTasks.ts
- packages/react-storage/src/components/StorageBrowser/useAction/__tests__/useHandler.spec.ts
- packages/react-storage/src/components/StorageBrowser/useAction/useHandler.ts
- update `useProcessTasks` dispatch handler to accept `concurrency` option
- remove `concurrency` from `useProcessTasks` options
- update `useHandler` to provide `concurrency` only to dispatch handler on batch calls
fixes #6522
- manual tests
- existing unit tests
- updated unit tests
> fix(storage-browser): move useProcessTasks concurrency option to dispatch handler

- .changeset/nasty-months-teach.md
- docs/package.json
- examples/next-app-router/package.json
- examples/next/package.json
- examples/react-router/package.json
- packages/react-storage/CHANGELOG.md
- packages/react-storage/package.json
- packages/react-storage/src/version.ts
- packages/test-utils/CHANGELOG.md
- packages/test-utils/package.json
- Merging HotFix branch back to main. This is after we released a hotFix for https://github.com/aws-amplify/amplify-ui/pull/6525.
- Since we had merged the hotFix PR to main first, we need to manually remove it's changeSet since this is already released by the hotFix branch  
…atch handler (#6528)
* fix(storage-browser): move useProcessTasks concurrency option to dispatch handler (#6525)
* chore: fix publish-hotfix actions (#6527)
* Version Packages
* chore: bump size limit
---------
Co-authored-by: Caleb Pollman <cpollman@amazon.com>
> fix(storage-browser): hotfix move useProcessTasks concurrency option to dispatch handler

- .changeset/brave-bears-teach.md
- packages/react-ai/src/components/AIConversation/AIConversation.tsx
- packages/react-ai/src/components/AIConversation/__tests__/useConversationScrollProps.test.ts
- packages/react-ai/src/components/AIConversation/useConversationScrollProps.ts
Updates `AIConversation` streaming message scroll behavior. 
Previously, the underlying `ScrollView` always received an `autoScroll` of "smooth", leading to scenarios where long message streams forced the rendered content above the visible window of the `ScrollView`. With the updates in this PR, `autoScroll` is set conditionally, setting `autoScroll` to `undefined`  on scroll up events and resetting `autoScroll` to "smooth" on the next message received, allowing for end users to control scroll position while a message is streaming
https://github.com/user-attachments/assets/d8f91502-4c72-4b05-9499-3b683111cafa
NA
- added unit tests
> feat(ai-conversation): add conditional autoScroll handling

- packages/e2e/cypress/integration/common/liveness.ts
Currently multiple liveness e2e test fails due file definition lacking (error details below). This PR will fix that by adding a step definition to handle the selection element. 
```
Error: 
Step implementation missing for "I click the "FaceMovementAndLightChallenge" selectfield and select the "FaceMovementChallenge" option".
We tried searching for files containing step definitions using the following search pattern templates:
```
- By running the liveness e2e test successfully `yarn test:liveness `
> fix(liveness): cypress/e2e liveness test issue

- build-system-tests/scripts/mega-app-copy-files.sh
- package.json
- packages/angular/package.json
- yarn.lock
[stylus](https://github.com/stylus/stylus/issues/2938) gets removed from npm due to security issue. This PR apply a work around to resolve the issue.
- Running angualr example locally 
- Run `yarn test` locally 
- Trigger publish work flow and all passing. [link](https://github.com/aws-amplify/amplify-ui/actions/runs/16475959526/job/46578076758)
> fix(angular) stylus build issue

- packages/e2e/cypress/integration/common/shared.ts
- packages/e2e/features/ui/components/storage/storage-browser/action-menu.feature
This PR adds missing e2e test for the pagination on the UploadView
> e2e(storage-browser): add tests for upload pagination

- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/liveness.test.ts
This PR removes the unused import found in [Code-Scan-644](https://github.com/aws-amplify/amplify-ui/security/code-scanning/644).
> chore: remove unused SessionInformation import

- .changeset/twelve-bags-watch.md
- packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts
Fix the oval size by increase the ratio to original value. The original value gets accidentally decreased previously in a previous [PR](https://github.com/aws-amplify/amplify-ui/pull/6599) 
> fix(ui-react-liveness): oval ratio multiplier

- build-system-tests/scripts/mega-app-create-app.sh
Build with next consistently fails since new release of next@15.5.0. With the new version create-next-app enables turbopack by default which breaks the build. This PR disables turbopack for the next build.
Local build
> fix: disable turbopack for next build

- docs/next.config.js
- docs/src/pages/[platform]/connected-components/storage/storage-browser/examples/CustomFilePreview.tsx
- docs/src/pages/[platform]/connected-components/storage/storage-browser/examples/defaultActions.ts
- docs/src/pages/[platform]/connected-components/storage/storage-browser/examples/mockStorageInternal.ts
Since we are using mocked data with no actual bucket in the storage browser, the file preview will always return an error. To avoid this, the `getUrl` function will be mocked.
- run the docs locally.
> Add mocking for file preview

- docs/package.json
- examples/next-app-router/package.json
- examples/next/package.json
- yarn.lock
bump next.js to `^14.2.31` to fix the following dependant bot issues
- https://github.com/aws-amplify/amplify-ui/security/dependabot/240
- https://github.com/aws-amplify/amplify-ui/security/dependabot/239
- https://github.com/aws-amplify/amplify-ui/security/dependabot/238
> fix(dependant-bot) : bump next.js version to fix a security alert

- build-system-tests/scripts/mega-app-start.sh
The build system test([build / build (vue, latest, nuxt, latest, npm, 20)](https://github.com/aws-amplify/amplify-ui/actions/runs/17296163700/job/49094772655#logs)) failed regularly due to failure to fetch dynamically imported module.
Therefore, we're running the tests in production mode to avoid the impact from such flaky error.
Run build system tests locally.
> chore: run production build for nuxt build system tests

- docs/src/pages/[platform]/connected-components/storage/storage-browser/examples/ComponentOverride.tsx
- docs/src/pages/[platform]/connected-components/storage/storage-browser/examples/index.ts
- docs/src/pages/[platform]/connected-components/storage/storage-browser/react.mdx
Add a new section "Component Override" to the storage browser component. 
- Run the docs locally 
> chore(docs): update storage browser to include components override section

- .changeset/young-avocados-talk.md
- packages/react-native/src/Authenticator/hooks/useFieldValues/useFieldValues.ts
Fixed password manager autofill validation issue in React Native Authenticator. When using password managers like Dashlane, the email field was incorrectly marked as invalid even when containing a valid email address.
The issue occurred because the `onBlur` handler in `useFieldValues` was using stale React state (`values[name]`) instead of the actual field value from the native event. This caused validation to run against empty state rather than the autofilled value.
**Changes:**
- Modified `onBlur` handler to use `values[name] || event?.nativeEvent?.text`
- Ensures validation uses actual field value for both manual input and autofilled values
- Maintains backward compatibility with existing functionality
#6648
- Tested with IOS native password manger that autofill the Authenticator …
> fix(authenticator-react-native): password manager autofill validation
