aws-amplify/amplify-ui

docs/src/pages/[platform]/connected-components/liveness/index.page.mdx

Let's merge this after the docs launch (since that's somewhat time sensitive) but before we re-enable link checker. That way we won't delay Liveness docs release and we won't have to add an ignored link for it.

chore: update youtube link to not be shortened

---

package.json
packages/react-geo/.eslintrc.js
packages/react-geo/.gitignore
packages/react-geo/LICENSE
packages/react-geo/README.md
packages/react-geo/jest.config.js
packages/react-geo/package.json
packages/react-geo/rollup.config.js
packages/react-geo/src/__tests__/__snapshots__/index.spec.ts.snap
packages/react-geo/src/__tests__/index.spec.ts
packages/react-geo/src/index.ts
packages/react-geo/src/styles.css
packages/react-geo/src/styles.ts
packages/react-geo/src/version.ts
packages/react-geo/tsconfig.dist.json
packages/react-geo/tsconfig.json

Add `@aws-amplify/ui-react-geo` package boilerplate

chore(ui-react-geo): add package boilerplate

---

docs/src/pages/[platform]/connected-components/liveness/customization/customization.theming.android.mdx

Add "Theming" title on the Android Liveness Customization page.
N/A

chore(liveness): Add theming title for liveness customization page

---

canary/apps/react/next/package.json
canary/apps/react/next/pages/index.js
canary/e2e/features/liveness/face-detect.feature

- PR to enable the faceLivenessDetector canary now that things are available on npm

chore: add FaceLivenessDetector canary

---

examples/next/pages/ui/components/liveness/components/LivenessDefault.tsx
examples/next/pages/ui/components/liveness/components/LivenessInlineResults.tsx
packages/react-liveness/src/components/FaceLivenessDetector/hooks/__tests__/useMediaStreamInVideo.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/index.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/freshnessColorDisplay.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/liveness.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/streamProvider.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/shared/__tests__/FaceLivenessErrorModal.test.tsx

- Fixed various codeql lint errors for unused variables - https://github.com/aws-amplify/amplify-ui/security/code-scanning

chore: remove unused variables in react-liveness

---

examples/next/pages/ui/components/liveness/components/LivenessDefault.tsx

- Remove import to fix codeql https://github.com/aws-amplify/amplify-ui/security/code-scanning/136

chore(liveness): remove unused import

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Add Docs Contributing Section and update Pull Request template to include contributing process acknowledgement

chore(contributing): add docs contributing section and update PR template

---

docs/src/pages/[platform]/connected-components/authenticator/advanced/useAuthenticator.react.mdx
docs/src/pages/[platform]/getting-started/accessibility/accessibility.react.mdx

`yarn docs test` from root of local repo

fixed a couple of small typos in react docs

---

packages/react-core/package.json
packages/react-core/rollup.config.js
packages/react-liveness/package.json
packages/react-liveness/rollup.config.js
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-storage/package.json
packages/react-storage/rollup.config.js
packages/react/internal/package.json
packages/react/package.json
packages/react/rollup.config.js
packages/ui/package.json
packages/ui/rollup.config.js

Remove usage of `.mjs` for Studio tagged release

chore(studio): remove .mjs support

---

packages/react/.eslintrc.js
packages/react/scripts/generatePrimitiveCatalog.ts
packages/react/tsconfig.dist.json
packages/react/tsconfig.json

Turn on linting for _scripts_ directory in ui-react package

chore(ui-react): lint scripts dir

---

.github/workflow-samples/tagged-release.yml

Update _tagged-release.yml_ template

chore(ci): update tagged-release template

---

packages/react/src/hooks/__tests__/useDataStore.test.ts
packages/react/src/primitives/shared/__tests__/datastore.test.ts

Add typing and lint `Datastore` hook and util test files

chore(ui-react): type and lint datastore test files

---

docs/src/pages/[platform]/connected-components/liveness/prerequisite.android.mdx

Update the Android version description in the Android Liveness quick start prerequisites.

chore: update android version in liveness prerequisites

---

examples/next/package.json
packages/react-geo/package.json
packages/react-geo/src/components/MapView/MapView.tsx
packages/react/package.json
packages/react/src/components/Geo/MapView/index.tsx
yarn.lock

Upgrade react-map-gl to have same version as in main branch
Ran unit and e2e tests

chore(ui-react-geo): upgrade react-map-gl to have same version as in main branch

---

docs/README.md

add link checking section to README

chore(docs): add link checking section to README

---

docs/src/pages/[platform]/connected-components/liveness/full-api.react.mdx
docs/src/pages/[platform]/connected-components/liveness/index.page.mdx
docs/src/pages/[platform]/connected-components/liveness/react-props.ts

- Adds an api ref doc to liveness docs

chore(docs): add liveness api reference for react web

---

docs/README.md

- Docs amplify hosting deployment can fail due to GC/memory issues, this flag that was use on the dev docs site helps resolve this issue

chore: update docs readme for hosting

---

packages/react-liveness/src/components/FaceLivenessDetector/service/types/faceDetection.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/liveness.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/blazefaceFaceDetection.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/blazefaceFaceDetection.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts

- Added types for blazefaceFaceDetection.ts
- Added types for liveness utils file

chore(liveness): add strict typing for react-liveness

---

docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx

Add the Amplify Auth dependency when setting up Liveness for Android.

fix(liveness): add auth dependency to android install instructions

---

docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
packages/react-liveness/src/components/FaceLivenessDetector/service/types/faceDetection.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/liveness.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/blazefaceFaceDetection.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/blazefaceFaceDetection.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts

Docs release pr 2023 04 28 for liveness android fix

---

docs/src/data/ignoredLinks.ts
docs/src/pages/[platform]/connected-components/liveness/index.page.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.react.mdx

- Added a direct link to a guide on creating identity pools for liveness

chore: update link for identity pool guide

---

packages/angular/.eslintrc.js
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-in/confirm-sign-in.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-totp/setup-totp.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/verify-user/verify-user.component.ts
packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts
packages/angular/projects/ui-angular/src/lib/utilities/amplify-slot/amplify-slot.directive.ts

Fixes `'@typescript-eslint/member-ordering'` errors.
CI below.

fix(angular): fix member ordering eslint errors

---

docs/src/pages/[platform]/components/icon/react.mdx
docs/src/pages/[platform]/getting-started/usage/nextjs/react.mdx

- removes link to [https://css.gg/](https://css.gg/), which is broken right now
- update link to `Next.js` getting started, which has changed this morning.
ci

fix(docs): fix broken links

---

package.json

This was missing.
Ran `yarn e2e test:authenticator` locally

fix: fix e2e workspace script

---

package.json

Fixes `yarn build`.
Ran `yarn build`, `yarn setup`, and `yarn refresh` locally 😓 This wasn't caught in my last POC because CI usually installs packages individually.

chore: update yarn build script

---

examples/react-native/src/App/App.tsx
examples/react-native/src/ui/components/authenticator/reset-password/Example.tsx
examples/react-native/src/ui/components/authenticator/reset-password/aws-exports.js
examples/react-native/src/ui/components/authenticator/sign-in-with-email/Example.tsx
examples/react-native/src/ui/components/authenticator/with-authenticator/Example.tsx
examples/react-native/src/ui/components/authenticator/with-authenticator/aws-exports.js
packages/e2e/detox/integration/common/authenticator.ts
packages/e2e/detox/integration/common/shared.ts
packages/e2e/detox/integration/in-app-messaging.ts
packages/e2e/detox/mockServer.js
packages/e2e/features/ui/components/authenticator/confirm-sign-up.feature
packages/e2e/features/ui/components/authenticator/reset-password.feature
packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature
packages/e2e/features/ui/components/authenticator/sign-in-with-phone.feature
packages/e2e/features/ui/components/authenticator/sign-in-with-username.feature
packages/e2e/features/ui/components/authenticator/verify-user.feature
packages/e2e/features/ui/components/authenticator/withAuthenticator.feature
packages/e2e/features/ui/components/in-app-messaging/demo.feature
packages/react-native/src/InAppMessaging/components/BannerMessage/BannerMessage.tsx
packages/react-native/src/InAppMessaging/components/BannerMessage/__tests__/__snapshots__/BannerMessage.spec.tsx.snap
packages/react-native/src/InAppMessaging/components/FullScreenMessage/FullScreenMessage.tsx
packages/react-native/src/InAppMessaging/components/FullScreenMessage/__tests__/__snapshots__/FullScreenMessage.spec.tsx.snap
packages/react-native/src/InAppMessaging/components/MessageLayout/MessageLayout.tsx
packages/react-native/src/InAppMessaging/components/MessageLayout/types.ts
packages/react-native/src/InAppMessaging/components/ModalMessage/ModalMessage.tsx
packages/react-native/src/InAppMessaging/components/ModalMessage/__tests__/__snapshots__/ModalMessage.spec.tsx.snap

Add tests for:
* confirm sign-in
* confirm sign-up
* reset password
* Inapp Messagging

chore(e2e): Add more RN e2e tests

---

.github/workflows/reusable-e2e.yml
docs/src/data/ignoredLinks.ts

- Build react-core-react-notifications in ios/android e2e workflows
- Fix ignoreLinks list
POC PR:
- https://github.com/aws-amplify/amplify-ui/pull/3838
[![POC / Test / Internal PRs](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-test-internal-prs.yml/badge.svg)](https://github.com/aws-amplify/amplify-ui/actions/workflows/poc-test-internal-prs.yml)

fix: build react-core-react-notifications in ios/android e2e workflows and fix link-checker

---

packages/angular/.eslintrc.js
packages/angular/projects/ui-angular/src/lib/common/types/auth-types.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-in/confirm-sign-in.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-verify-user/amplify-confirm-verify-user.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/force-new-password/force-new-password.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/reset-password/reset-password.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-totp/setup-totp.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-up/sign-up.component.ts
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/verify-user/verify-user.component.ts
packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts
packages/angular/projects/ui-angular/src/lib/primitives/checkbox/checkbox.component.ts
packages/angular/projects/ui-angular/src/lib/primitives/error/error.component.ts
packages/angular/projects/ui-angular/src/lib/primitives/password-field/password-field.component.ts
packages/angular/projects/ui-angular/src/lib/primitives/tabs/tabs.component.ts
packages/angular/projects/ui-angular/src/lib/services/__tests__/authenticator.service.test.ts
packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts

Fixes `@typescript-eslint/explicit-module-boundary-types` errors, ie. functions without return types.
CI

fix(angular): fix `explicit-module-boundary-types` eslint errors

---

.changeset/metal-parrots-smoke.md
packages/react-geo/.eslintrc.js
packages/react-geo/jest.config.js
packages/react-geo/package.json
packages/react-geo/src/version.ts

Use latest versions of `ui`, `ui-react` and `ui-react-core` and some cleanup
- Ran tests locally

chore(ui-react-geo): use latest versions of deps and some cleanup

---

.changeset/lemon-pumas-guess.md
.changeset/metal-parrots-smoke.md
.changeset/selfish-sheep-unite.md

chore: update changeset messages

chore: update changeset messages

---

.changeset/thick-birds-retire.md
packages/react-core-notifications/package.json

Update _@aws-amplify/ui_ dep in _@aws-amplify/ui-react-core-notifications_  to current/expected version

fix(ui-react-core-notifications): update ui dep version

---

packages/react-notifications/package.json

fix(ui-react-notifications): add tinycolor2 dep and types

---

packages/react-liveness/src/components/FaceLivenessDetector/service/utils/freshnessColorDisplay.ts

Fixes CodeQL unused variables alerts:
* https://github.com/aws-amplify/amplify-ui/security/code-scanning/149
* https://github.com/aws-amplify/amplify-ui/security/code-scanning/150

chore(react-liveness): Remove unused variables

---

.github/workflows/reusable-e2e.yml

Monitor changes in react-core-notifications to run e2e in ios and android.

ci: monitor changes in react-core-notifications to run e2e in ios and android

---

package.json

Publish latest job failed due to angular package not being built: https://github.com/aws-amplify/amplify-ui/actions/runs/4998257048/jobs/8953779063

fix: Update yarn build command to include angular package

---

docs/src/pages/[platform]/getting-started/introduction/intro.mdx

chore: fix docs link to discussions

---

docs/src/components/AppDirectoryAlert.tsx
docs/src/pages/[platform]/connected-components/account-settings/account-settings.react.mdx
docs/src/pages/[platform]/connected-components/authenticator/DeveloperPreview.tsx
docs/src/pages/[platform]/connected-components/authenticator/index.page.mdx
docs/src/pages/[platform]/connected-components/authenticator/quick-start-install.android.mdx
docs/src/pages/[platform]/connected-components/geo/react.mdx
docs/src/pages/[platform]/connected-components/in-app-messaging/index.page.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.react.mdx
docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
yarn.lock

Docs release pr 2023 05 24

---

examples/next/pages/ui/components/account-settings/change-password/index.page.tsx
packages/e2e/features/ui/components/account-settings/change-password.feature

chore: fix typo succesfully

---

canary/apps/react/cra-ts/package.json
canary/apps/react/cra/package.json

CRA test builds are failing due to https://github.com/facebook/create-react-app/issues/13189
Temporary resolution for previous @babel/core version

fix: temp pin of babel/core for cra canaries

---

canary/apps/react/cra-ts/package.json
canary/apps/react/cra/package.json

This reverts commit b877a541cb88f07c046917981c669a81e1098c65.

Revert "fix: temp pin of babel/core for cra canaries (#3999)"

---

.github/ISSUE_TEMPLATE/2.feature_request.yaml

Changes to feature request template

chore: Update feature request template

---

docs/src/pages/[platform]/getting-started/usage/nextjs/react.mdx

fix: fix AppDirectoryAlert import to fix nextjs getting started page

---

docs/src/pages/[platform]/getting-started/usage/nextjs/react.mdx

fix AppDirectoryAlert import to fix nextjs getting started page …(#4003)

fix: Hot fix for NextJS Getting Started Page

---

README.md

chore: update FileUploader to StorageManager in README

---

docs/src/pages/[platform]/getting-started/internationalization/internationalization.react.mdx

Update link caught by link-checker https://github.com/aws-amplify/amplify-ui/actions/runs/5124356237/jobs/9216447982?pr=3986

fix: update link

---

examples/react-native/README.md
packages/e2e/README.md
packages/e2e/detox/integration/common/authenticator.ts
packages/e2e/detox/integration/common/shared.ts
packages/e2e/features/ui/components/authenticator/reset-password.feature

* Add troubleshooting note to example app Readme
* Add single test that types into input field and checks validation (our other tests replace tests instead of typing, this adds coverage for the usecase that is closer to user behavior without impacting test duration)

chore(e2e): Add RNA e2e test

---

docs/src/pages/[platform]/connected-components/authenticator/quick-start-example.swift.mdx

Added 'state' variable in the Swift Authenticator getting started code snippet

add state variable in swift authenticator code example

---

canary/apps/angular/angularcli/angular.json

style import needs a `node_modules` prefix.
Ran canary locally against `next-release`.

fix(next-release): fix angular canary

---

.changeset/dependabot-doggo.md

chore: add changeset for PR#4011

---

docs/flutter/authenticator/lib/authenticator_config.dart
docs/src/pages/[platform]/connected-components/authenticator/customization/sign-up-fields.flutter.mdx

fix typo in Flutter Authenticator documentation

fix(docs): fix typo in Flutter Authenticator documentation

---

.changeset/lovely-chairs-tell.md
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCameraModule.test.tsx
packages/react-liveness/src/components/FaceLivenessDetector/shared/Hint.tsx

- Updated progress bar to continue showing when face is matched
- Flickering occurred because when the face match state was `MATCHED` we would hide the progress bar

fix(liveness): fix flickering progress bar bug

---

.changeset/bright-dragons-smash.md
.changeset/lovely-chairs-tell.md
.changeset/polite-ants-wonder.md
examples/next/package.json
packages/react-liveness/CHANGELOG.md
packages/react-liveness/package.json
packages/react-liveness/src/version.ts
yarn.lock

- Following our one off liveness release runbook and prepping for the release by combining the releases into a single patch release
- Latest version is 1.0.0 - https://www.npmjs.com/package/@aws-amplify/ui-react-liveness?activeTab=versions
- Only had patch releses up to 1.0.4 so merging all the patch changes to 1.0.1
- Manually ran `yarn changeset version`, and `yarn generateVersions` then combined all patches in the changelog

chore(liveness): prep liveness v1.0.1, manually updated CHANGELOG and version

---

.changeset/big-oranges-hang.md
packages/react-liveness/CHANGELOG.md

- Following our one off liveness release runbook and prepping for the release by combining the releases into a single patch release
- Latest version is 1.0.0 - https://www.npmjs.com/package/@aws-amplify/ui-react-liveness?activeTab=versions
- Only had patch releses up to 1.0.4 so merging all the patch changes to 1.0.1
- Manually ran yarn changeset version, and yarn generateVersions then combined all patches in the changelog

chore: prep liveness v1.0.1, added connection timeout bug fix

---

.changeset/little-radios-do.md
packages/react-liveness/package.json
yarn.lock

- Tested using both `npm pack` and `npm publish` with verdaccio

fix(liveness): add tslib@2.4.1 to react-liveness

---

.changeset/little-radios-do.md
.github/workflows/publish-liveness-test.yml
examples/next/package.json
packages/react-liveness/CHANGELOG.md
packages/react-liveness/package.json
packages/react-liveness/src/version.ts

- This contains the same chagnes as - https://github.com/aws-amplify/amplify-ui/pull/4072
- When pushing this PR to liveness-test it shoudl trigger a publish workflow which publishes `ui-react-liveness` to a tag called `liveness-test`
- Manually updated the version to be `1.0.2-liveness-test`

Test publish workflow

---

.changeset/little-radios-do.md
examples/next/package.json
packages/react-liveness/CHANGELOG.md
packages/react-liveness/package.json
packages/react-liveness/src/version.ts
yarn.lock

Sync main to liveness-release

---

build-system-tests/package-lock.json
build-system-tests/package.json
package.json
yarn.lock

In https://github.com/aws-amplify/amplify-ui/pull/4057, I accidentally installed the package to monorepo...This PR is to fix that.
PoC PR https://github.com/aws-amplify/amplify-ui/pull/4077

chore: move packages to build-system-test/

---

packages/angular/projects/ui-angular/package.json

Adds a peer dependency of `@angular/core` to `>=14.0.0`, which is our intended version support that aligns with Angular LTS. 
Canary test, plus build system test will happen against the tagged release.

deps(angular): add peer deps to `@angular/core`

---

canary/apps/react/cra-ts/package.json

There's a regression from `aria-query@5.2.0`: https://github.com/A11yance/aria-query/issues/502. Until this is resolved, we're pinning this dependency.

chore(canary): pin aria-query deps temporarily

---

yarn.lock

chore: update aws-amplify version in yarnlock

---

.changeset/tidy-gifts-thank.md
packages/react-liveness/src/components/FaceLivenessDetector/shared/MatchIndicator.tsx
packages/react-liveness/src/components/FaceLivenessDetector/shared/__tests__/MatchIndicator.test.tsx

- Updated progress bar to match ios and android by removing the pin

chore(liveness): update progress bar to remove pin

---

.github/scripts/mega-app-build.sh

Accidentally merged https://github.com/aws-amplify/amplify-ui/pull/4091, so follow up on this PR
POC PR https://github.com/aws-amplify/amplify-ui/pull/4092

chore: change mega-app-build platform option

---

.changeset/large-news-grin.md

fix(changeset): remove ui-react and fix typo for PR 4013

---

yarn.lock

Latest `aws-amplify` contains security fix that bumps `fast-xml-parser`.
https://github.com/aws-amplify/amplify-ui/security/dependabot/89
```
$ yarn why fast-xml-parser
=> Found "fast-xml-parser@4.2.4"
- "_project_#@aws-sdk#client-sts" depends on it
- Hoisted from "_project_#@aws-sdk#client-sts#fast-xml-parser"
- Hoisted from "_project_#@aws-amplify#ui-react-liveness#@aws-sdk#client-rekognitionstreaming#@aws-sdk#client-sts#fast-xml-parser"
- Hoisted from "_project_#@aws-amplify#ui-docs#aws-amplify#@aws-amplify#storage#@aws-sdk#client-s3#fast-xml-parser"
info Disk size without dependencies: "160KB"
info Disk size with unique dependencies: "196KB"
info Disk size with transitive dependencies: "196KB"
info Number of shared dependencies: 1
✨  Done in 0.96s.
``` …

deps: bump lockfile

---

docs/src/pages/[platform]/connected-components/liveness/QuickStartReact.tsx

chore: add default error log to liveness component example

---

docs/src/pages/[platform]/guides/auth-protected/auth-protected.react.mdx

The `Amplify` import is missing from the protected routes setup step
Fixes #4130 

docs: add missing code to protected routes setup

---

.changeset/ten-crabs-travel.md
packages/react-geo/package.json

Unpin `maplibre-gl-js-amplify` since it is an internal package and bump to the latest.
fixes #4142 

fix: unpin maplibre-gl-js-amplify

---

docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx

Adds migration section for changing your import paths.
Related: #4157.

docs(angular): add CSS migration section

---

docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx

* Add CSS migration section
* Wrap code in backtick
* Wording
* wording
* Update docs/src/pages/[platform]/getting-started/migration/migration.angular.mdx
---------

docs(angular): add CSS migration section (#4158)

---

docs/package.json

Adds `yarn docs clean` script for our convenience. This will be useful when devs any find issues with cache, especially `.next`.
Ran the script locally.

chore: add `yarn docs clean` script

---

examples/react-native/src/App/App.tsx
examples/react-native/src/ui/components/authenticator/reset-password/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-attributes/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-email/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-phone/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-username/Example.tsx
packages/e2e/README.md

This change adds comments and readme about Detox mock server.

chore(e2e): add notes about Detox mock server

---

docs/src/pages/[platform]/connected-components/liveness/QuickStartReact.jsx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.react.mdx

- Our example for liveness was already typescript-y, added a few more types there
- Added a tab with a plain js example as well

chore: add javascript example to liveness docs

---

docs/src/pages/[platform]/connected-components/liveness/customization/CustomizationCdn.tsx
docs/src/pages/[platform]/connected-components/liveness/customization/customization.cdn.react.mdx
docs/src/pages/[platform]/connected-components/liveness/customization/index.page.mdx
docs/src/pages/[platform]/connected-components/liveness/full-api.react.mdx

- Added instructions on adding/using your own cdn for liveness component

chore: add docs for custom liveness cdn

---

docs/src/pages/[platform]/theming/theming.react.mdx

Updates the links for sass-lang from **https://sass-lang.com** to **http://sass-lang.com** to fix broken links

fix(docs): update broken sass links

---

.changeset/light-cats-eat.md
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts

fix(liveness): liveness package name in user agent

---

packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/index.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__mocks__/testUtils.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/videoRecorder.ts

- Added error handling for case where no chunks are recorded for a full session, the component should throw an error in this case

chore(liveness): add error handling for no chunks being recorded

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml
.github/ISSUE_TEMPLATE/2.feature_request.yaml

Add liveness to github issue templates

Add Liveness component option to 1.bug_report.yaml

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml

- Added extra fields to template which help support liveness component
- Added optional region field
- Added optional field for console error log

chore: update github issue template

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add-with-credentials-provider.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/pages/[platform]/getting-started/installation/dependencies.android.mdx

Update the Amplify Android Liveness and Material versions in the docs.

chore(android): Update Android liveness and material versions

---

package.json
yarn.lock

Bump `changesets` to partially address semver issue https://github.com/changesets/changesets/pull/1176

fix(deps): Bump changesets/cli

---

docs/src/components/home/sections/HeroSection.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerThemeExample.tsx

Remove ts-ignore's in Docs that have already been fixed

chore (docs): remove ts-ignore's that have been fixed

---

docs/src/pages/[platform]/theming/theming.react.mdx

https://sass-lang.com/ is back up.

Revert "fix(docs): update broken sass links"

---

.changeset/heavy-scissors-retire.md
packages/react-native/src/Authenticator/Defaults/ForceNewPassword/__tests__/__snapshots__/ForceNewPassword.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/__snapshots__/SignUp.spec.tsx.snap
packages/react-native/src/primitives/TextField/TextField.tsx
packages/react-native/src/primitives/TextField/__tests__/TextField.spec.tsx
packages/react-native/src/primitives/TextField/__tests__/__snapshots__/TextField.spec.tsx.snap
packages/react-native/src/primitives/TextField/styles.ts
packages/react-native/src/primitives/TextField/types.ts

feat(react-native): adding error styles to text field

---

packages/e2e/cypress/fixtures/FileUploader-uploads-complete.xml
packages/e2e/cypress/integration/common/shared.ts
packages/e2e/features/ui/components/storage/fileuploader/upload-image-to-s3.feature
packages/e2e/features/ui/components/storage/storage-manager/upload-file-to-S3-private-multipart.feature
packages/e2e/features/ui/components/storage/storage-manager/upload-file-to-S3-public-multipart.feature

This change updates the mocks for storage to conform to S3 specification (https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html#API_UploadPart_ResponseElements) - i.e. mock etag header.
The next version of amplify js introduces XML payload validation, which means once it is released, tests will fail.
The issue was surfaced while running tests against custom js client in https://github.com/aws-amplify/amplify-ui/pull/4182/files
Tested change against above PR to be sure, tests pass: https://github.com/aws-amplify/amplify-ui/actions/runs/5482812674/jobs/9988700067

fix(e2e): Update mocks for storage tests

---

packages/react/src/primitives/PasswordField/__tests__/PasswordField.test.tsx

fix: remove unused variables in PasswordField.test.tsx

---

.changeset/tricky-ducks-occur.md
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts

- bug fix for - https://github.com/aws-amplify/amplify-ui/issues/4228

fix(liveness): fix process not defined issues by removing endpoint overrides 

---

packages/vue/src/components/__tests__/alias-control.spec.ts
packages/vue/src/components/__tests__/confirm-reset-password.spec.ts
packages/vue/src/components/__tests__/confirm-sign-in.spec.ts
packages/vue/src/components/__tests__/confirm-sign-up.spec.ts
packages/vue/src/components/__tests__/confirm-verify-user.spec.ts
packages/vue/src/components/__tests__/force-new-password.spec.ts
packages/vue/src/components/__tests__/password-control.spec.ts
packages/vue/src/components/__tests__/reset-password.spec.ts
packages/vue/src/components/__tests__/setup-totp.spec.ts
packages/vue/src/components/__tests__/sign-in.spec.ts
packages/vue/src/components/__tests__/sign-up.spec.ts
packages/vue/src/components/__tests__/verify-user.spec.ts
packages/vue/src/components/authenticator.vue
packages/vue/src/components/confirm-reset-password.vue
packages/vue/src/components/confirm-sign-in.vue
packages/vue/src/components/confirm-sign-up.vue
packages/vue/src/components/confirm-verify-user.vue
packages/vue/src/components/federated-sign-in.vue
packages/vue/src/components/force-new-password.vue
packages/vue/src/components/reset-password.vue
packages/vue/src/components/setup-totp.vue
packages/vue/src/components/sign-in.vue
packages/vue/src/components/sign-up.vue
packages/vue/src/components/verify-user.vue

Cleans up components and spec files touched in this feature branch for the sake of consistency. Barely any source code changes,  other than how we annotate type for `useAuthenticator`.
Existing E2e and unit tests in this feature branch.

refactor(vue): cleanup code

---

.changeset/shaggy-toes-prove.md
packages/react-native/src/Authenticator/Authenticator.tsx
packages/react-native/src/Authenticator/__tests__/Authenticator.spec.tsx
packages/react-native/src/Authenticator/__tests__/__snapshots__/Authenticator.spec.tsx.snap
packages/react-native/src/Authenticator/__tests__/withAuthenticator.spec.tsx

Update RNA signed logic to read directly from `Auth` module
- x ] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)

feature(rna): update is signed in logic to read from Auth

---

.changeset/stupid-kangaroos-chew.md
packages/react-native/src/theme/createTheme.ts
packages/react-native/src/theme/types.ts

fix(react-native): fix the theme components type

---

.changeset/quiet-vans-bow.md
packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx
packages/react/src/components/Authenticator/hooks/useCustomComponents/defaultComponents.tsx

fix(authenticator): force new password header and footer

---

.changeset/pretty-laws-obey.md
.github/workflows/reusable-unit.yml
docs/src/data/ignoredLinks.ts
examples/next/package.json
examples/next/pages/ui/components/liveness/components/LivenessDefault.tsx
examples/next/pages/ui/components/liveness/components/NavBar.tsx
examples/next/pages/ui/components/liveness/with-credential-provider/aws-exports.js
examples/next/pages/ui/components/liveness/with-credential-provider/index.page.tsx
packages/e2e/features/ui/components/liveness/with-credential-provider.feature
packages/react-liveness/src/__tests__/__snapshots__/index.spec.ts.snap
packages/react-liveness/src/components/FaceLivenessDetector/FaceLivenessDetector.tsx
packages/react-liveness/src/components/FaceLivenessDetector/FaceLivenessDetectorCore.tsx
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCheck.test.tsx
packages/react-liveness/src/components/FaceLivenessDetector/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/credentials.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/liveness.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/machine.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/streamProvider.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts
packages/react-liveness/src/index.ts
yarn.lock

- Adding liveness credential provider which was already reviewed and pen tested - https://github.com/aws-amplify/amplify-ui/pull/3790
- This just merges the changes to main for the next mv release

feat(liveness): Liveness cred provider

---

.changeset/stale-dancers-flash.md
docs/src/data/links.tsx
docs/src/pages/[platform]/connected-components/storage/storageimage/examples/DefaultStorageImageExample.tsx
docs/src/pages/[platform]/connected-components/storage/storageimage/examples/StorageImageErrorHandlingExample.tsx
docs/src/pages/[platform]/connected-components/storage/storageimage/examples/index.ts
docs/src/pages/[platform]/connected-components/storage/storageimage/index.page.mdx
docs/src/pages/[platform]/connected-components/storage/storageimage/props.ts
docs/src/pages/[platform]/connected-components/storage/storageimage/react.mdx
docs/tests/__snapshots__/sitemap.test.ts.snap
examples/next/pages/ui/components/storage/storage-image/private-access-level/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/private-access-level/index.page.tsx
examples/next/pages/ui/components/storage/storage-image/protected-access-level/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/protected-access-level/index.page.tsx
examples/next/pages/ui/components/storage/storage-image/public-access-level/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/public-access-level/index.page.tsx
packages/e2e/features/ui/components/storage/storage-image/load-private-image-from-s3.feature
packages/e2e/features/ui/components/storage/storage-image/load-protected-image-from-s3.feature
packages/e2e/features/ui/components/storage/storage-image/load-public-image-from-s3.feature
packages/react-storage/src/components/StorageImage/StorageImage.tsx
packages/react-storage/src/components/StorageImage/types.ts
packages/react/src/hooks/__tests__/useStorageURL.test.ts
packages/react/src/hooks/useStorageURL.ts
packages/react/src/primitives/shared/constants.ts

chore(ui-react-storage): add docs and e2e tests for StorageImage

---

packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts

https://github.com/aws-amplify/amplify-ui/security/code-scanning/155

chore: removed unused variable

---

.changeset/hot-pandas-accept.md
packages/react-native/src/Authenticator/Defaults/ConfirmResetPassword/__tests__/__snapshots__/ConfirmResetPassword.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/ConfirmSignIn/__tests__/__snapshots__/ConfirmSignIn.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/ConfirmSignUp/__tests__/__snapshots__/ConfirmSignUp.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/ConfirmVerifyUser/__tests__/__snapshots__/ConfirmVerifyUser.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/ForceNewPassword/__tests__/__snapshots__/ForceNewPassword.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/ResetPassword/__tests__/__snapshots__/ResetPassword.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/SetupTOTP/__tests__/__snapshots__/SetupTOTP.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/__snapshots__/SignIn.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/__snapshots__/SignUp.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/VerifyUser/__tests__/__snapshots__/VerifyUser.spec.tsx.snap
packages/react-native/src/Authenticator/common/DefaultContent/styles.ts
packages/react-native/src/Authenticator/common/DefaultHeader/__tests__/__snapshots__/DefaultHeader.spec.tsx.snap
packages/react-native/src/Authenticator/common/FederatedProviderButton/__tests__/__snapshots__/FederatedProviderButton.spec.tsx.snap
packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/__snapshots__/FederatedProviderButtons.spec.tsx.snap
packages/react-native/src/primitives/Checkbox/__tests__/__snapshots__/Checkbox.spec.tsx.snap
packages/react-native/src/primitives/Divider/__tests__/__snapshots__/Divider.spec.tsx.snap
packages/react-native/src/primitives/Heading/__tests__/__snapshots__/Heading.spec.tsx.snap
packages/react-native/src/primitives/Heading/styles.ts
packages/react-native/src/primitives/Label/__tests__/__snapshots__/Label.spec.tsx.snap
packages/react-native/src/primitives/Label/styles.ts
packages/react-native/src/primitives/PasswordField/__tests__/__snapshots__/PasswordField.spec.tsx.snap
packages/react-native/src/primitives/PhoneNumberField/__tests__/__snapshots__/PhoneNumberField.spec.tsx.snap
packages/react-native/src/primitives/Radio/__tests__/__snapshots__/Radio.spec.tsx.snap
packages/react-native/src/primitives/RadioGroup/__tests__/__snapshots__/RadioGroup.spec.tsx.snap
packages/react-native/src/primitives/TextField/__tests__/__snapshots__/TextField.spec.tsx.snap
packages/react-native/src/primitives/TextField/styles.ts

Small visual tweaks to make the authenticator look better
| - | - |
| ![Simulator Screenshot - iPhone 11 - 2023-07-21 at 13 02 49](https://github.com/aws-amplify/amplify-ui/assets/321279/3102c46d-dd2a-4540-a12a-71cae996e92b) | ![Simulator Screenshot - iPhone 11 - 2023-07-24 at 08 51 44](https://github.com/aws-amplify/amplify-ui/assets/321279/5540dab6-126e-4f1a-8f36-ffd9cf313b1e) |

fix(react-native): small tweaks to authenticator styling

---

packages/react-core/src/hooks/__tests__/useHasValueUpdated.spec.ts
packages/react-core/src/hooks/useHasValueUpdated.ts

Add internal documentation for `useHasValueUpdated` and swap transposed unit test descriptions
NA
NA

chore(ui-react-core): improve internal documentation of useHasValueUpdated

---

README.md

Mark RN Authenticator ready in README.md

Mark RN Authenticator ready in README.md

---

.changeset/curvy-badgers-swim.md

Add a changeset for https://github.com/aws-amplify/amplify-ui/pull/4297

chore: add missing changeset for #4297

---

canary/e2e/yarn.lock
yarn.lock

Update @cypress/request in lock files to address:
https://github.com/aws-amplify/amplify-ui/security/dependabot/104
https://github.com/aws-amplify/amplify-ui/security/dependabot/103

chore(deps): Update cypress/request

---

docs/src/pages/[platform]/connected-components/authenticator/configuration/signUpAttributes.default.react-native.mdx

Fixes an issue where the [Signup Attributes Expo Snack](https://ui.docs.amplify.aws/react-native/connected-components/authenticator/configuration#sign-up-attributes) doesn't build.
Before:
After:

chore (docs): fix broken expo snack example

---

docs/src/pages/[platform]/connected-components/liveness/full-api.react.mdx

- Following up a previous discussion where we said we would remove references to source code so they do not become stale

chore(docs): remove references to liveness source code

---

.github/workflows/test-internal-prs.yml

- Updates our gh action workflows to run tests on hotfix branch

fix: run tests on hotfix branch

---

.changeset/mighty-papayas-care.md
packages/react-core/src/__tests__/__snapshots__/index.spec.ts.snap
packages/react-core/src/index.ts
packages/react-core/src/types/index.ts
packages/react-core/src/utils/__tests__/createContextUtilities.spec.tsx
packages/react-core/src/utils/__tests__/index.spec.ts
packages/react-core/src/utils/createContextUtilities.tsx
packages/react-core/src/utils/index.ts
packages/react/src/primitives/types/view.ts
packages/ui/src/types/util.ts
packages/ui/src/utils/__tests__/index.test.ts
packages/ui/src/utils/index.ts

- add `createContextUtilities` convenience util and related types
- move `MergeProps` type to react core package
- move `templateJoin` to generic utils in ui package
- add `noop` and `isTypedFunction` generic utils
NA

feat(ui-react-core): add createContextUtilities

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add-with-credentials-provider.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx

Updating released versions of the Android Liveness Library.

Amplify UI Android Liveness 1.1.2 Release

---

docs/src/pages/[platform]/components/button/demo.tsx

Removed ariaLabel from the button code example

Removed ariaLabel from the button code example

---

docs/src/pages/[platform]/connected-components/liveness/prerequisite.android.mdx

Add a note and workaround for Android API 23 (Android v6)

docs: add note on android v6

---

docs/src/pages/[platform]/components/breadcrumbs/index.page.mdx
docs/src/pages/[platform]/components/breadcrumbs/react.mdx

adding breadcrumbs links after launch

---

docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx

Update Storage Manager docs subtitle for consistency with other sections (other sections call out alternatives to the default behavior).

chore(docs): Update storage manager docs subtitle

---

docs/src/pages/[platform]/connected-components/authenticator/customization/customization.full-ui-customization.flutter.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/form-fields.flutter.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/qrcode/form-fields.flutter.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/totp/form-fields.flutter.mdx

Adds UI docs for Flutter Authenticator TOTP

feat(flutter): Authenticator TOTP Customization

---

.changeset/angry-spiders-destroy.md
packages/e2e/features/ui/components/liveness/disable-start-screen.feature
packages/e2e/features/ui/components/liveness/liveness-detector.feature
packages/e2e/features/ui/components/liveness/start-screen.feature
packages/e2e/features/ui/components/liveness/with-credential-provider.feature
packages/react-liveness/src/components/FaceLivenessDetector/displayText.ts

chore(liveness): update start screen text to remove 7 seconds

---

.github/workflows/publish-next-release.yml
.github/workflows/test-internal-prs.yml

This change adds workflows for:
*  running tests on PRs opened against `next-release/main`
* publishing `next-release` tag

chore(ci): Add CICD workflows

---

docs/src/pages/[platform]/components/input/examples/DefaultInputExample.tsx
docs/src/pages/[platform]/components/input/examples/DefaultRequiredInputExample.tsx
docs/src/pages/[platform]/components/input/examples/InputEventHandlersExample.tsx
docs/src/pages/[platform]/components/input/examples/InputSizeExample.tsx
docs/src/pages/[platform]/components/input/examples/InputStatesExample.tsx
docs/src/pages/[platform]/components/input/examples/InputStylePropsExample.tsx
docs/src/pages/[platform]/components/input/examples/InputThemeExample.tsx
docs/src/pages/[platform]/components/input/examples/InputValidationErrorExample.tsx
docs/src/pages/[platform]/components/input/examples/InputVariationExample.tsx
docs/src/pages/[platform]/components/input/examples/RequiredInputExample.tsx
docs/src/pages/[platform]/components/input/react.mdx
docs/src/pages/[platform]/components/label/examples/AccessibilityExample.tsx
docs/src/pages/[platform]/components/label/examples/DefaultLabelExample.tsx

add flex to input examples so they copy correctly

---

.github/dependency-review/config.yml

chore: add BlueOak-1.0.0 to allowed licenses

---

examples/react-native/metro.config.js

Fix `react-hook-form` lookup in RN example app

fix(rn-example): correctly resolve react-hook-form

---

packages/react-auth/jest.config.js
packages/react-auth/package.json
packages/react-core-auth/jest.config.js
packages/react-core-auth/package.json
packages/react-core-auth/src/hooks/index.ts
packages/react-core-auth/src/hooks/useHandleCopy/index.ts
packages/react-core-auth/src/hooks/useHandleCopy/useHandleCopy.ts
packages/react-core-auth/src/hooks/useIsSignedIn/index.ts
packages/react-core-auth/src/hooks/useIsSignedIn/useIsSignedIn.ts
packages/react-core-auth/src/hooks/useQRCodeDataUrl/index.ts
packages/react-core-auth/src/hooks/useQRCodeDataUrl/useQRCodeDataUrl.ts
packages/react-core/jest.config.js
packages/react-core/src/__tests__/__snapshots__/index.spec.ts.snap
packages/react-core/src/hooks/index.ts
packages/react-core/src/hooks/useTimeout.ts
packages/react-core/src/index.ts

Add React util hooks for `A.Next`:
` useIsSignedIn`: listen for `Auth` sign in and sign out `Hub` events
- `useTimeout`: async executes provided `callback` after `delay`
- `useQRCodeDataUrl`: async generates a `qrCodeDataUrl` from an `input` string
- `useHandleCopy`: `handleCopy` sets clipboard value to internal state, clears internal state after specified `reset`
- modify `jest` config files for ui-react-auth, ui-react-core, and ui-react-auth-core packages:
- temporarily lower coverage thresholds
- update coverage patterns to align to other React packages
NA
Manual Testing, some unit tests

feat(ui-react-auth): add util hooks

---

docs/README.md

Quick `docs -> README.md` update to specify the file to set values, so people won't accidentally update an example file

quick readme update

---

canary/apps/angular/angularcli/package.json
canary/apps/react/cra-ts/package.json
canary/apps/react/cra/package.json
canary/apps/react/next/package.json
canary/apps/react/vite/package.json
canary/apps/react/vite3/package.json
canary/apps/vue/vite/package.json
canary/apps/vue/vite3/package.json
canary/apps/vue/vuecli/package.json
docs/package.json
examples/angular/package.json
examples/next/package.json
examples/vue/package.json
guides/react/protected-routes/package.json
packages/angular/projects/ui-angular/package.json
packages/react-core-notifications/package.json
packages/react-core/package.json
packages/react-geo/package.json
packages/react-liveness/package.json
packages/react-native/package.json
packages/react-notifications/package.json
packages/react-storage/package.json
packages/react/package.json
packages/react/src/hooks/useStorageURL.ts
packages/ui/package.json
packages/ui/src/helpers/logger/logger.ts
packages/ui/src/types/authenticator/stateMachine/authMachine.ts
packages/vue/package.json
yarn.lock

Replace JS `console-preview ` deps with `next`

chore(next-release): point js v6 deps at next

---

.github/actions/changed-packages/action.yml
examples/react-native/package.json
package.json

Fix RN e2e testing on `next-release/main`:
- add `react-hook-form` to top level `nohoist`
- add `react-hook-form` dep to RN example app
Tested by forcing RN e2e test runs on all commits. Passing RN e2e tests on previous [commit](https://github.com/aws-amplify/amplify-ui/pull/4473/commits/74d31181807f6deed1490e11ce7fbfd33437da2c):
- [Android](https://github.com/aws-amplify/amplify-ui/actions/runs/6286248977/job/17069660989?pr=4473)
- [iOS](https://github.com/aws-amplify/amplify-ui/actions/runs/6286248977/job/17069660894?pr=4473)

fix(next-release/main): nohoist react-hook-form

---

packages/ui/src/types/displayText.ts
packages/ui/src/types/index.ts

Add utility types for component `DisplayText` properties
NA
Manual testing

chore(displayText): add display text base types

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/authenticator/quick-start-install.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add-with-credentials-provider.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/styles/docs/main.scss
packages/e2e/package.json
yarn.lock

Docs release pr 2023 09 26

---

.changeset/tall-llamas-reflect.md
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/liveness.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/streamProvider.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts

- Fixes issues - https://github.com/aws-amplify/amplify-ui/issues/4228
- Previously used an env variable based endpoint override at launch for testing, this switches it to use a prop instead

chore(liveness): remove env variable endpoint override, replace with prop

---

.github/workflows/test-internal-prs-migration.yml

chore: Add github workflow for running tests on PRs

---

docs/src/pages/[platform]/connected-components/account-settings/change-password/props.ts
docs/src/pages/[platform]/connected-components/account-settings/delete-user/props.ts
docs/src/pages/[platform]/connected-components/account-settings/delete-user/react.mdx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManageri18nExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts
packages/e2e/features/ui/components/account-settings/delete-user.feature
packages/react-storage/src/components/StorageManager/types.ts
packages/react-storage/src/components/StorageManager/ui/FileList/FileControl.tsx
packages/react-storage/src/components/StorageManager/ui/FileList/__tests__/FileList.test.tsx
packages/react-storage/src/components/StorageManager/ui/FileList/types.ts
packages/react-storage/src/components/StorageManager/ui/FileListFooter/FileListFooter.tsx
packages/react-storage/src/components/StorageManager/ui/FileListHeader/FileListHeader.tsx
packages/react-storage/src/components/StorageManager/utils/displayText.ts
packages/react-storage/src/components/StorageManager/utils/index.ts
packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx
packages/react/src/components/AccountSettings/ChangePassword/__tests__/ChangePassword.test.tsx
packages/react/src/components/AccountSettings/ChangePassword/types.ts
packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx
packages/react/src/components/AccountSettings/DeleteUser/__tests__/DeleteUser.test.tsx
packages/react/src/components/AccountSettings/DeleteUser/defaults.tsx
packages/react/src/components/AccountSettings/DeleteUser/types.ts
packages/react/src/components/AccountSettings/utils/displayText.ts

chore: Update display text props

---

examples/next/package.json
packages/react-geo/package.json
packages/react-geo/src/components/LocationSearch/__tests__/LocationSearch.test.tsx
packages/react-geo/src/components/MapView/MapView.tsx
packages/react-geo/src/components/MapView/__tests__/MapView.test.tsx
yarn.lock

- Updates packages to point at console-preview tag since geo changes are not all on next yet
- Just putting it out for review right now, will not work until maplibre amplify package is released

chore(geo): v6 migration for MapView and LocationSearch, updated to point to console-preview amplify package

---

docs/src/components/home/HomeEditor.tsx

chore(docs): fix #4496

---

docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/DefaultStorageManagerExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerComponentOverridesExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerDisplayTextExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerFileTypesExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerHashExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerResumableExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerThemeExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManagerUploadActionsExample.tsx
docs/src/pages/[platform]/connected-components/storage/storagemanager/examples/StorageManageri18nExample.tsx
packages/react-storage/src/components/StorageManager/StorageManager.tsx
packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/__tests__/useUploadFiles.spec.ts
packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts
packages/react-storage/src/components/StorageManager/types.ts
packages/react-storage/src/components/StorageManager/utils/__tests__/uploadFile.test.ts
packages/react-storage/src/components/StorageManager/utils/uploadFile.ts
yarn.lock

Updated unit tests and refactored bits of logic.
`yarn react-storage test`
```
Test Suites: 20 passed, 20 total
Tests:       99 passed, 99 total
Snapshots:   26 passed, 26 total
Time:        8.042 s
Ran all test suites.
✨  Done in 9.27s.
```
In addition, manually tested the example apps.

chore: Fix Storage Manager unit tests

---

.changeset/eleven-books-happen.md
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/index.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts

- Remove distance check during connection

chore(liveness): remove distance check while connecting

---

docs/scripts/util/checkLink.ts
docs/src/data/ignoredLinks.ts

- figma links 301
- updpated to ignore all w3 links for now since they are all randomly timing out

chore: add more ignored links

---

.github/workflows/build-system-test-react-native.yml

- PoC Workflow PR - https://github.com/aws-amplify/amplify-ui/pull/4528
- Passing PoC workflow for build system tests - https://github.com/aws-amplify/amplify-ui/actions/runs/6475031768/job/17581229512?pr=4528

chore: fix rn build system test workflow

---

.github/workflows/test-internal-prs.yml

Reverted changes to Test internal Pr workflow, this branch should use the dedicated workflow `test-internal-prs-migration` 

chore: Revert test internal Pr workflow changes

---

packages/e2e/features/ui/components/authenticator/reset-password.feature
packages/e2e/features/ui/components/authenticator/sign-in-force-new-password.feature
packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature
packages/e2e/features/ui/components/authenticator/sign-in-with-username.feature

chore: redisable brekaing e2e tests for now

---

docs/src/pages/_app.page.tsx

chore: Fix docs e2es

---

packages/ui/src/utils/setUserAgent/constants.ts
packages/ui/src/utils/setUserAgent/index.ts
packages/ui/src/utils/setUserAgent/setUserAgent.ts
packages/ui/src/utils/utils.ts

Add initial `setUserAgent` util and types

chore(setUserAgent): add initial util and types

---

packages/ui/src/machines/authenticator/signUp.ts

chore: fix xstate bug with always transition

---

docs/src/data/ignoredLinks.ts

Ignore some links to unblock migration work

Added more links to ignore

---

examples/next/pages/ui/components/authenticator/sign-up-with-email/index.page.tsx
packages/ui/src/machines/authenticator/actors/signIn.ts

fix: getCurrentUser before resolving

---

packages/ui/src/machines/authenticator/actors/signIn.ts
packages/ui/src/machines/authenticator/defaultServices.ts

- Previously getCurrentAuthenticatedUser returned user information as well as attributes
- Now that they are two separate calls combining them helps return a value similar to what was returned previously

chore: call fetchUserAttributers with getUser

---

packages/ui/src/helpers/authenticator/textUtil.ts
packages/ui/src/machines/authenticator/actors/signIn.ts

- Sign up with totp was working
- Sign in with totp was not, this fixes that

fix: fix totp sign in

---

examples/next/pages/ui/components/geo/use-map-hook/index.page.tsx
examples/next/pages/ui/components/geo/use-map-hook/styles.css

In geo `use-map-hook` example, couldn't see button, updated css to put button on top of map 
before
after

chore: updating geo example to show button

---

yarn.lock

chore: update geo package

---

examples/angular/src/pages/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.component.html
examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue
packages/ui/src/helpers/authenticator/formFields/defaults.ts
packages/ui/src/machines/authenticator/actions.ts
packages/ui/src/machines/authenticator/actors/signIn.ts
packages/ui/src/types/authenticator/user.ts
packages/vue/src/components/confirm-sign-in.vue

fix: various bug fixes found in bug bash

---

yarn.lock

chore: update aws-amplify to fix confirm sign in issue

---

examples/angular/src/pages/ui/components/authenticator/sign-up-with-email/sign-up-with-email.component.ts
examples/vue/src/pages/ui/components/authenticator/sign-up-with-email/index.vue

fix: example apps for vue and angular auto signin

---

packages/ui/src/machines/authenticator/actors/signIn.ts

* Removed superfluous comments
* Fixes signIn getCurrentUserResolved using event for logging without defining it.

chore: Fix signIn actor

---

packages/ui/src/theme/css/component/accordion.scss

| - | - |
| <img width="310" alt="CleanShot 2023-10-25 at 10 17 07@2x" src="https://github.com/aws-amplify/amplify-ui/assets/321279/d1de9335-f104-405e-bb9e-4a3eaebad225"> | <img width="311" alt="CleanShot 2023-10-25 at 10 20 51@2x" src="https://github.com/aws-amplify/amplify-ui/assets/321279/464af66a-7ff0-496c-b7d4-7bbb8bfa3108"> |

fix(accordion): safari bug

---

packages/react-native/jest.setup.js
packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/SignIn.spec.tsx
packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/SignUp.spec.tsx
packages/react-native/src/Authenticator/common/FederatedProviderButton/__tests__/FederatedProviderButton.spec.tsx
packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/FederatedProviderButtons.spec.tsx
packages/react-native/src/primitives/Divider/__tests__/__snapshots__/Divider.spec.tsx.snap
packages/react-native/src/primitives/Icon/__tests__/Icon.spec.tsx
packages/ui/package.json
yarn.lock

fix(react-native): fix broken unit tests, add correct mocks

---

package.json
packages/react-auth/rollup.config.ts
packages/react-core-notifications/rollup.config.ts
packages/react-geo/rollup.config.ts
packages/react-liveness/rollup.config.ts
packages/react-notifications/rollup.config.ts
packages/react-storage/rollup.config.ts
packages/react/rollup.config.ts
packages/ui/rollup.config.ts
yarn.lock

chore(rollup): remove terser plugin

---

packages/react-auth/rollup.config.ts
packages/react-core-notifications/rollup.config.ts
packages/react-geo/rollup.config.ts
packages/react-liveness/rollup.config.ts
packages/react-native/jest.config.ts
packages/react-native/jest.setup.ts
packages/react-native/package.json
packages/react-native/src/Authenticator/Defaults/ConfirmSignUp/__tests__/ConfirmSignUp.spec.tsx
packages/react-native/src/Authenticator/Defaults/SignIn/__tests__/__snapshots__/SignIn.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/SignUp/__tests__/__snapshots__/SignUp.spec.tsx.snap
packages/react-native/src/Authenticator/common/FederatedProviderButton/__tests__/FederatedProviderButton.spec.tsx
packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/__snapshots__/FederatedProviderButtons.spec.tsx.snap
packages/react-native/src/InAppMessaging/components/withInAppMessaging/__tests__/withInAppMessaging.spec.tsx
packages/react-native/src/primitives/Divider/__tests__/__snapshots__/Divider.spec.tsx.snap
packages/react-notifications/rollup.config.ts
packages/react-storage/rollup.config.ts
packages/react/rollup.config.ts
packages/ui/rollup.config.ts

fix: update ui-react-native post RN mv bump

---

.github/workflows/publish-next-release-merge-main.yml

Add workflow to publish custom tag.

chore: Add publish workflow

---

docs/package.json
examples/angular/package.json
examples/next/package.json
examples/react-native/package.json
examples/vue/package.json
packages/angular/projects/ui-angular/package.json
packages/react-auth/package.json
packages/react-core-auth/package.json
packages/react-core-notifications/package.json
packages/react-core/package.json
packages/react-geo/package.json
packages/react-liveness/package.json
packages/react-native-auth/package.json
packages/react-native/package.json
packages/react-notifications/package.json
packages/react-storage/package.json
packages/react/package.json
packages/ui/package.json
packages/ui/src/machines/authenticator/actors/signIn.ts
packages/vue/package.json
yarn.lock

chore: bump amplify to 6.0

---

docs/src/components/home/HomeEditor.tsx

chore(docs): fix live editor blur bug

---

packages/e2e/cypress/integration/common/fileuploader.ts

Fixed failing e2e test in storage-manager 
Ran e2e tests 

fix(e2e): fix storage manager test 

---

docs/package.json
yarn.lock

chore: update docs next version to 13.5.5

---

packages/vue/vite.config.ts

Added import path for `setCustomUserAgent` to vite.config externals which makes custom headers work with Vue

chore(Vue): Add UA path to vite config

---

examples/next/pages/_app.page.tsx

fix: remove next example window updates

---

docs/src/data/ignoredLinks.ts
docs/src/pages/[platform]/getting-started/migration/migration.react.mdx

One typo fix and added two links throwing 403s to ignored list
Link checker passing locally 

chore(docs): fix links in link checker 

---

docs/src/data/ignoredLinks.ts
docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx
docs/src/pages/[platform]/connected-components/authenticator/configuration/totpIssuer.swift.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/customization.full-ui-customization.swift.mdx
yarn.lock

Docs release pr 2023 11 01

---

docs/src/components/InstallScripts.tsx
docs/src/pages/[platform]/getting-started/migration/migration.react.mdx

chore(docs): update liveness install instructions to use aws-amplify 5.x

---

docs/src/pages/[platform]/connected-components/authenticator/configuration/index.page.mdx
docs/src/pages/[platform]/connected-components/authenticator/configuration/totpIssuer.swift.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/customization.full-ui-customization.swift.mdx
yarn.lock

Update component-theme from main

---

docs/src/components/ExpoSnack.tsx

https://expo-snack-fix.d32sljejpnv3v5.amplifyapp.com/

chore(docs): fix expo snack

---

docs/src/components/ExpoSnack.tsx

chore(docs): fix expo snack (#4630)

---

.github/actions/changed-packages/action.yml
.github/workflows/publish-next-release.yml
.github/workflows/reusable-e2e.yml
packages/e2e/features/ui/components/authenticator/sign-in-with-email.feature

chore(ci): turn back on RN e2e ci, remove early publish

---

packages/ui/src/machines/authenticator/defaultServices.ts

chore: fix lodash import

---

packages/ui/src/machines/authenticator/defaultServices.ts

chore: make lodash import a default import

---

.github/workflows/publish-next-release-fix.yml

chore: add next-release-fix publish action

---

packages/react/package.json
yarn.lock

Chore: remove deepmerge

---

.github/workflows/build-system-test-react-native.yml

chore: add react native build tests

---

examples/next/package.json
examples/react-native/src/ui/components/authenticator/reset-password/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-attributes/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-email/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-phone/Example.tsx
examples/react-native/src/ui/components/authenticator/sign-up-with-username/Example.tsx
packages/react-geo/package.json
yarn.lock

chore: update aws-amplify to use new unstable

---

packages/react-native-auth/jest.setup.ts
packages/react-native/jest.setup.ts

fix(rn): fix amplify rn package mocks

---

packages/react-geo/package.json
yarn.lock

fix: udpate maplibre-amplify dependencies

---

package.json
yarn.lock

chore(ui-react/v3): adding patched version of babel/traverse

---

docs/src/components/Layout/PageTabLayout.tsx

fix(docs): fix flicker when changing tabs 

---

.changeset/cool-mangos-dress.md
examples/next/pages/ui/components/storage/storage-image/error/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/error/index.page.tsx
packages/react-storage/src/components/StorageImage/StorageImage.tsx
packages/react-storage/src/components/StorageImage/types.ts

fix(storageimage): handle onStorageGetError properly

---

packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts

fix(storage): sending metadata again

---

examples/next/package.json
examples/react-native/android/app/build.gradle
examples/react-native/android/settings.gradle
examples/react-native/ios/Podfile
examples/react-native/ios/Podfile.lock
package.json
yarn.lock

fix(rn): no hoist rn community namespace

---

packages/react-native/src/Authenticator/common/FederatedProviderButtons/__tests__/FederatedProviderButtons.spec.tsx

chore(react-native): fixing rn unit test

---

packages/react-storage/src/components/StorageManager/hooks/useStorageManager/__tests__/reducer.test.ts
packages/react-storage/src/components/StorageManager/hooks/useStorageManager/reducer.ts

fix(storagemanager): fix duplicate key issue

---

.github/workflows/reusable-unit.yml
packages/vue/package.json

chore(ci): re-enable ci size and esm checks

---

packages/e2e/cypress/fixtures/auto-sign-in.json
packages/e2e/cypress/integration/common/shared.ts
packages/e2e/features/ui/components/authenticator/sign-in-totp-mfa.feature
packages/react-core/src/Authenticator/hooks/useAuthenticatorInitMachine/useAuthenticatorInitMachine.tsx
packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx
packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx
packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx
packages/react/src/components/Authenticator/ForgotPassword/ConfirmResetPassword.tsx
packages/react/src/components/Authenticator/ForgotPassword/ForgotPassword.tsx
packages/react/src/components/Authenticator/SetupTotp/SetupTotp.tsx
packages/react/src/components/Authenticator/VerifyUser/ConfirmVerifyUser.tsx
packages/react/src/components/Authenticator/VerifyUser/VerifyUser.tsx
packages/ui/src/helpers/authenticator/getRoute.ts
packages/ui/src/machines/authenticator/actors/signOut.ts

chore(MV): clean up some migration comments and logs

---

packages/angular/jest.config.js
packages/react-core-notifications/jest.config.js
packages/react-core/jest.config.js
packages/react-geo/jest.config.js
packages/react-liveness/jest.config.js
packages/react-native/jest.config.js
packages/react-notifications/jest.config.js
packages/react-storage/jest.config.js
packages/react/jest.config.js
packages/ui/jest.config.js
packages/vue/jest.config.cjs
yarn.lock

Bump `aws-amplify` to fix `axios` dependabot alert.

chore: update aws-amplify to latest

---

packages/ui/src/machines/authenticator/__tests__/utils.test.ts
packages/ui/src/machines/authenticator/actions.ts
packages/ui/src/machines/authenticator/actors/signUp.ts
packages/ui/src/machines/authenticator/utils.ts
packages/ui/src/types/authenticator/attributes.ts

fix(authenticator): include parsed phone_number in signUp input

---

packages/ui/src/machines/authenticator/__tests__/utils.test.ts
packages/ui/src/machines/authenticator/actions.ts
packages/ui/src/machines/authenticator/actors/signUp.ts
packages/ui/src/machines/authenticator/utils.ts

fix(authenticator): fix username lookup for signUp with phone_number

---

build-system-tests/package.json

Merge main to next release/main

---

docs/src/pages/[platform]/connected-components/account-settings/delete-user/props.ts
docs/src/pages/[platform]/connected-components/authenticator/advanced/index.page.mdx
examples/angular/src/pages/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.component.html
examples/angular/src/pages/ui/components/authenticator/sign-in-with-phone/sign-in-with-phone.component.html
examples/angular/src/pages/ui/components/authenticator/sign-up-with-email-lambda/sign-up-with-email-lambda.component.html
examples/next/pages/ui/components/authenticator/sign-in-sms-mfa/index.page.tsx
examples/next/pages/ui/components/authenticator/sign-in-with-phone/index.page.tsx
examples/next/pages/ui/components/authenticator/sign-up-with-email-lambda/index.page.tsx
examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue
examples/vue/src/pages/ui/components/authenticator/sign-in-with-phone/index.vue
examples/vue/src/pages/ui/components/authenticator/sign-up-with-email-lambda/index.vue
packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts
packages/react-core/src/Authenticator/hooks/useAuthenticator/__mock__/useAuthenticator.ts
packages/react-core/src/Authenticator/hooks/useAuthenticator/__tests__/__snapshots__/useAuthenticator.spec.tsx.snap
packages/react-core/src/Authenticator/hooks/useAuthenticator/__tests__/useAuthenticator.spec.tsx
packages/react/src/components/AccountSettings/ChangePassword/__tests__/ChangePassword.test.tsx
packages/react/src/components/AccountSettings/DeleteUser/__tests__/DeleteUser.test.tsx
packages/react/src/components/AccountSettings/DeleteUser/types.ts
packages/react/src/components/Authenticator/Authenticator.tsx
packages/react/src/components/Authenticator/withAuthenticator.tsx
packages/react/src/hooks/useAuth.ts
packages/ui/src/helpers/authenticator/facade.ts
packages/ui/src/machines/authenticator/actors/__tests__/signIn.test.ts
packages/ui/src/types/authenticator/user.ts
packages/vue/src/components/__tests__/__snapshots__/confirm-sign-in.spec.ts.snap
packages/vue/src/components/__tests__/authenticator.spec.ts
packages/vue/src/components/__tests__/confirm-sign-in.spec.ts
packages/vue/src/components/__tests__/setup-totp.spec.ts

Replace types `AmplifyUser` with `AuthUser` 

chore(mv): replace AmplifyUser with AuthUser

---

.github/workflows/reusable-e2e.yml

chore: disable RN e2e tests

---

.github/workflows/publish-next.yml

Disable guides test until we fix the guide

chore: disable guides test on publish-next

---

.changeset/weak-melons-sell.md
docs/package.json
examples/angular/package.json
examples/next/package.json
examples/react-native/ios/Podfile.lock
examples/react-native/package.json
examples/vue/package.json
guides/react/protected-routes/package.json
packages/react-auth/package.json
packages/react-core-auth/package.json
packages/react-core-notifications/package.json
packages/react-core/package.json
packages/react-geo/package.json
packages/react-liveness/package.json
packages/react-native-auth/package.json
packages/react-native/package.json
packages/react-notifications/package.json
packages/react-storage/package.json
packages/react/package.json
packages/ui/package.json
yarn.lock

Upgrade `aws-amplify` and related deps to 

chore(deps): upgrade aws-amplify deps

---

.github/workflows/publish-next.yml

chore: skip e2e tests on publish next

---

.github/workflows/publish-latest.yml

chore: skip publish to latest workflow

---

.changeset/fuzzy-cars-beg.md
examples/next/pages/ui/components/authenticator/custom-slots/index.page.tsx
packages/react-native/src/Authenticator/Defaults/ForgotPassword/ForgotPassword.tsx
packages/react-native/src/Authenticator/Defaults/ForgotPassword/__tests__/ForgotPassword.spec.tsx
packages/react-native/src/Authenticator/Defaults/ForgotPassword/__tests__/__snapshots__/ForgotPassword.spec.tsx.snap
packages/react-native/src/Authenticator/Defaults/types.ts
packages/react/src/components/Authenticator/Authenticator.tsx
packages/react/src/components/Authenticator/ForgotPassword/ForgotPassword.tsx
packages/react/src/components/Authenticator/Router/Router.tsx
packages/react/src/components/Authenticator/hooks/useCustomComponents/defaultComponents.tsx

fix: rename ResetPassword to ForgotPassword

---

docs/next.config.js
docs/src/components/home/sections/AuthenticationSection.tsx

chore(docs): hide expo snack for now

---

docs/src/pages/[platform]/connected-components/geo/react.mdx

chore: update geo installation

---

.github/workflows/publish-latest.yml

Reverts aws-amplify/amplify-ui#4725

Revert "chore: skip publish to latest workflow"

---

.changeset/red-seas-attack.md
canary/e2e/features/liveness/face-detect.feature
docs/src/pages/[platform]/connected-components/liveness/customization/customization.cdn.react.mdx
packages/react-liveness/package.json
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/index.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/faceDetection.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__mocks__/testUtils.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/blazefaceFaceDetection.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/liveness.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/blazefaceFaceDetection.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts
yarn.lock

Reverts aws-amplify/amplify-ui#4685

Revert "chore(liveness): upgrade blazeface model"

---

.github/workflows/publish-latest.yml

Override build test requirement - publish-latest.yml

---

build-system-tests/package.json
build-system-tests/scripts/mega-app-install.sh

fix: build system tests prep for v6

---

canary/apps/react/next/package.json
canary/apps/react/next/pages/index.js

chore: remove liveness from canaries

---

.github/workflows/publish-latest.yml

Reverts aws-amplify/amplify-ui#4740

Revert "Override build test requirement - publish-latest.yml"

---

docs/src/data/ignoredLinks.ts

Remove `Accordion` links from ignored links for docs link checker
NA
Visited links

chore(docs): remove excluded links Accordion links

---

yarn.lock

Upgrade `wait-on` to bump `axios`

fix(dependabot): upgrade wait-on to bump axios version

---

examples/next/next.config.js
examples/react-native/src/features/InAppMessaging/Demo/utils.ts
packages/react/src/primitives/ButtonGroup/__tests__/ButtonGroup.test.tsx
packages/react/src/primitives/Link/__tests__/Link.test.tsx

Clean up unused imports picked up by CodeQL after merging `next-release/main` to `main`

fix(codeql): remove unused imports

---

docs/src/data/globalnav.ts

fix: docs pricing link

---

.changeset/manually-created-storage.md

chore: add changeset for storagemanager bug #4666

---

.changeset/manually-created.md

chore: add changeset for patching ui

---

.changeset/early-sheep-crash.md
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/forgot-password/forgot-password.component.ts
packages/react-native/src/Authenticator/Defaults/types.ts
packages/react/src/components/Authenticator/ForgotPassword/ForgotPassword.tsx
packages/ui/src/helpers/authenticator/textUtil.ts
packages/vue/src/components/__tests__/__snapshots__/authenticator.spec.ts.snap
packages/vue/src/components/__tests__/__snapshots__/forgot-password.spec.ts.snap
packages/vue/src/components/authenticator.vue
packages/vue/src/components/forgot-password.vue

- fix Forgot Password container component data attribute formats
- fix a couple slot names in vue
- fix a type namespace in react native
NA
Ran unit tests, manually verified DOM for data attribute format

fix(authenticator): forgot password clean up

---

canary/apps/react/next/package.json
canary/apps/react/next/pages/index.js

chore: reenable liveness canary

---

examples/next/pages/ui/components/liveness/components/LivenessDefault.tsx

chore: remove unused import from liveness

---

.changeset/tidy-kids-rush.md
packages/ui/src/machines/authenticator/actors/forgotPassword.ts

Fixes: https://github.com/aws-amplify/amplify-ui/issues/4772

fix: resend code forgot password

---

.changeset/blue-apes-own.md
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCameraModule.test.tsx
packages/react-liveness/src/components/FaceLivenessDetector/shared/Hint.tsx
packages/react-liveness/src/components/FaceLivenessDetector/shared/__tests__/Hint.test.tsx

chore(liveness): update hold still text to show when matched

---

docs/src/pages/_document.page.tsx

chore: allow liveness cdn

---

docs/scripts/util/checkLink.ts
docs/src/data/ignoredLinks.ts
docs/src/pages/[platform]/connected-components/authenticator/prerequisite.web.mdx

chore(e2e): ignore external links in link checker

---

.changeset/nasty-lemons-dress.md
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx

chore: added aria label for video element on liveness

---

docs/src/pages/[platform]/connected-components/liveness/customization/customization.cdn.react.mdx

chore: update liveness custom cdn to include older versions

---

.changeset/moody-feet-fly.md
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/displayText.ts
packages/react-liveness/src/components/FaceLivenessDetector/utils/getDisplayText.ts

chore: add i18n for a11y video text

---

docs/src/pages/[platform]/connected-components/liveness/customization/CustomizationComponents.tsx
docs/src/pages/[platform]/connected-components/liveness/customization/CustomizationComponentsErrorView.tsx
docs/src/pages/[platform]/connected-components/liveness/customization/customization.components.react.mdx
docs/src/pages/_document.page.tsx

chore(docs): add a updated liveness error modal example

---

.changeset/perfect-brooms-reflect.md

update Liveness changelog

---

docs/src/components/InstallScripts.tsx

chore: fix liveness pointing to aws-amplify v5

---

packages/ui/package.json
yarn.lock

Introduces updated version of `glob` which drops `inflight` dependency 

chore: bump style-dictionary

---

docs/src/pages/[platform]/theming/dark-mode/react.mdx

Fix broken tab container for dark mode code examples:
* default dark mode JS code example wasn't showing
* custom dark mode examples were not in tab panels
| --- | --- |
| <img width="1229" alt="Screenshot 2023-12-12 at 12 54 54 PM" src="https://github.com/aws-amplify/amplify-ui/assets/68251134/b109bfd3-4a9a-49a4-a320-134e6a37d29f"> | <img width="1229" alt="Screenshot 2023-12-12 at 12 55 02 PM" src="https://github.com/aws-amplify/amplify-ui/assets/68251134/f0c32a45-1c27-42a5-962d-771dc972bf4e"> |
| <img width="1264" alt="Screenshot 2023-12-12 at 12 44 51 PM" src="https://github.com/aws-amplify/amplify-ui/assets/68251134/c84fba0a-251f-4735-b8fb-d1bce1d7b9ec"> | <img width="1236" alt="Screenshot 2023-12-12 at 12 50 49 PM" …

chore(docs): Fix dark mode code examples

---

.changeset/light-zoos-raise.md
packages/angular/projects/ui-angular/src/lib/services/authenticator.service.ts
packages/react-core/src/Authenticator/context/AuthenticatorProvider.tsx
packages/ui/jest.config.ts
packages/ui/src/helpers/authenticator/__tests__/defaultAuthHubHandler.test.ts
packages/ui/src/helpers/authenticator/defaultAuthHubHandler.ts
packages/ui/src/helpers/authenticator/types.ts
packages/vue/src/composables/useAuth.ts

- fix `defaultAuthHubHandler` unit tests
- remove extraneous async declaration from `defaultAuthHubHandler` and handling in consumers
NA
Ran unit tests

chore(ui): fix defaultAuthHubListener unit tests, remove asynchronous declaration

---

packages/react/jest.config.ts
packages/react/src/components/AccountSettings/DeleteUser/__tests__/DeleteUser.test.tsx

Fix and re-enable DeleteUser unit tests. Adjust coverage thresholds.

chore(tests): Fix DeleteUser tests and adjust thresholds

---

.github/workflows/publish-hotfix.yml
.github/workflows/reusable-e2e-hotfix.yml
.github/workflows/test-internal-prs-hotfix.yml
canary/package.json
canary/script/changePackageVersion.js

chore(e2e): hotfix workflows for v5

---

.github/workflows/publish-hotfix.yml

chore: add publish hotfix workflow so we don't publish over latest

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add-with-credentials-provider.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx

This PR bumps version of liveness component for Android Library.

Update Liveness component version for Android

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add-with-credentials-provider.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx

This reverts commit a62b774dd09e178a95eb80345a0e81d2da83e187 to unblock merging https://github.com/aws-amplify/amplify-ui/pull/4869. Relevant reverted content in this PR committed [here](https://github.com/aws-amplify/amplify-ui/pull/4869/commits/320df3d9db7097c201f685ea9462ae98bde2d446)

Revert "Update Liveness component version for Android (#4873)"

---

packages/angular/__tests__/__snapshots__/exports.ts.snap
packages/angular/__tests__/exports.ts

Adding a public exports test to the angular package 

chore(angular): add public exports test

---

.changeset/neat-shrimps-dream.md
packages/react-liveness/src/components/FaceLivenessDetector/displayText.ts
packages/ui/src/types/displayText.ts

Update Liveness `displayText` type to extend from `DisplayTextTemplate`
- wrap `LivenessDisplayText` in `DisplayTextTemplate` to ensure key/value alignment with other connected components
- improve `DisplayTextTemplate` key/value filtering
- add deprecation warnings for misspelled Liveness `displayText` keys
NA
- `yarn build && yarn lint`

chore(liveness): type Liveness DisplayText with DisplayTextTemplate

---

docs/src/pages/[platform]/getting-started/installation/styles.web.mdx

fixes css layer import paths for UI react. Layers are currently not exported directly:
```json
"exports": {
".": {
"types": "./dist/types/index.d.ts",
"import": "./dist/esm/index.mjs",
"require": "./dist/index.js"
},
"./internal": {
"import": "./dist/esm/internal.mjs",
"require": "./dist/internal.js"
},
"./styles.css": "./dist/styles.css",
"./styles.layer.css": "./dist/styles.layer.css",
"./styles/*": "./dist/styles/*",
"./primitives.json": "./dist/primitives.json"
},
```

fix(docs): update ui-react CSS layer import paths

---

docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.angular.mdx
docs/src/pages/[platform]/getting-started/usage/usage.angular.mdx

Added a note in Usage and Troubleshooting guides that we only support `Default` change detection that link to angular docs 

chore(docs): add notes about angular change detection

---

docs/src/data/frameworks.ts

Remove `amazon-cognito-identity-js` from React Native install script
Fixes https://github.com/aws-amplify/amplify-ui/issues/4946
Verified the update locally

fix(docs): remove extraneous dep from RN install script

---

docs/package.json
yarn.lock

Remove unused `sitemap-urls` dep
NA

chore(docs): remove unused sitemap-urls dep

---

docs/src/pages/[platform]/connected-components/storage/storageimage/props.ts
docs/src/pages/[platform]/connected-components/storage/storageimage/react.mdx
docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts
docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx

Update 'public' -> 'guest' in access level props 

chore(docs): update access level props for storage

---

.changeset/poor-bottles-push.md
packages/vue/package.json

Add `vue@3.x` peer dependency to `@aws-amplify/ui-vue`
`yarn clean && yarn && yarn build`

chore(vue): add vue peerDep

---

.changeset/poor-bottles-push.md
.gitignore
docs/package.json
docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/storage/storageimage/props.ts
docs/src/pages/[platform]/connected-components/storage/storageimage/react.mdx
docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts
docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx
docs/src/pages/[platform]/getting-started/usage/vite/react.mdx
docs/src/pages/[platform]/theming/theming.react-native.mdx
docs/src/styles/docs/layout.scss
examples/vue/package.json
packages/vue/CHANGELOG.md
packages/vue/package.json
packages/vue/src/version.ts
yarn.lock

Docs release pr 2024 01 30

---

.github/workflows/build-system-test.yml

Reduce frequency of build system tests; 4x/hour wasn't adding value 

chore(build-system-tests): change frequency to every 30 min

---

package.json
yarn.lock

Add `socks` resolution
NA
Ran Angular example app locally

fix(dependabot): add socks resolution

---

packages/e2e/.detoxrc.json

Remove unused `detox` "release" apps/configurations
NA
Manually ran Android e2e tests locally

chore(e2e): remove unused detox release app/configuration

---

packages/e2e/features/ui/components/in-app-messaging/demo.feature

Disable in-app e2e tests that directly interact with pinpoint
NA

fix(in-app): disable e2e tests that use pinpoint

---

packages/e2e/features/ui/components/in-app-messaging/demo.feature

This reverts commit 983a3c8883c26de5255dc956490b62d3c9141d92.

Revert "fix(in-app): disable e2e tests that use pinpoint (#5012)"

---

packages/react-liveness/jest.config.ts
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/index.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/machine.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/CustomWebSocketFetchHandler.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__mocks__/testUtils.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/freshnessColorDisplay.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/liveness.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/streamProvider.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/videoRecorder.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/videoRecorder.ts

Clean up some duplicated test utils, unused variables and extraneous/unused types in the liveness middleware. 
No changes in this PR impact functionality of `FaceLivenessDetector`
NA

chore(liveness): cleanup test utils and random cruft

---

packages/e2e/features/ui/components/liveness/disable-start-screen.feature
packages/e2e/features/ui/components/liveness/liveness-detector.feature
packages/e2e/features/ui/components/liveness/with-credential-provider.feature

chore(CI): disable failing liveness e2e tests

---

packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts

- fix unused imports from https://github.com/aws-amplify/amplify-ui/pull/5051
- remove umbrella `eslint-disable` and fix linting issues for the [liveness state machine](https://github.com/aws-amplify/amplify-ui/compare/liveness/fix-unused-import?expand=1#diff-49f4d37e97030928199c54c5f8be21e23f8cb9565e90c1cc0845e6c3ad7a7fe9) and [state machine utilities](https://github.com/aws-amplify/amplify-ui/compare/liveness/fix-unused-import?expand=1#diff-4dc9d74828ef070874870649a51d5a4dd622a7ab2eca61a4d761f36075cffd9d)
NA
`yarn test && yarn lint`

fix(liveness): remove unused import/fix linting errors

---

.changeset/little-monkeys-serve.md

chore: add changeset for pr5068

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.android.mdx

Updated to 1.2.2 version of Android Liveness.

Update Android Liveness Version

---

package.json
yarn.lock

Update follow-redirects resolution `1.15.4` -> `1.15.6` 

fix(dependabot): update follow-redirects resolution

---

.github/workflows/codeql.yml
.github/workflows/test-fork-prs.yml
.github/workflows/test-internal-prs.yml

New codeql gh action is [passing on main](https://github.com/aws-amplify/amplify-ui/actions/runs/8331236754/job/22797662304), this updates gh action version for forked and internal prs:

chore: update codeql ghactions version for internal/fork prs

---

.github/dependabot.yml

This PR creates a dependabot.yml file, so that dependabot can automatically open PR's to update our github action hashes.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions

chore: create dependabot.yml to autoupdate github actions

---

package.json
yarn.lock

Remove `wait-on` top level dependency. While looking in to https://github.com/aws-amplify/amplify-ui/security/dependabot/134 saw that all the usage of `wait-on` was prefixed with `npx`~~, not entirely sure this PR will pass so opening as a draft.~~
NA
Ran CI 

chore(deps): remove wait-on

---

.github/dependabot.yml

chore: update dependabot.yml to update GH actions monthly

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.android.mdx

Updating version references for Amplify UI Android Liveness Component

Amplify UI Android - Liveness 1.2.3 Release

---

.github/actions/set-status/action.yml
.github/workflows/test-fork-prs.yml
.github/workflows/test-internal-prs.yml

This PR updates the official GH actions/github-script to Node 20

chore: update actions/github-script to Node 20

---

.changeset/seven-frogs-complain.md
docs/__tests__/__snapshots__/cssvars-table.test.ts.snap
packages/ui/src/theme/__tests__/__snapshots__/defaultTheme.test.ts.snap
packages/ui/src/theme/__tests__/__snapshots__/overrides.test.ts.snap
packages/ui/src/theme/__tests__/__snapshots__/themeType.test.ts.snap
packages/ui/src/theme/__tests__/themeType.test.ts
packages/ui/src/theme/tokens/components/liveness.ts

fix(Liveness): update camera module background on verifying step to match theme

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.android.mdx

Android Liveness Version Update 1.2.4

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/authenticator/quick-start.mdx
docs/src/pages/[platform]/getting-started/installation/dependencies.mdx

- add callout regarding Expo Go support with `aws-amplify@^6`
- update `expo` install command
- remove extraneous dep from React Native/Expo install commands
- remove extraneous RN/Expo getting started code examples
- fix some terminal commands
resolves https://github.com/aws-amplify/amplify-ui/issues/5137 https://github.com/aws-amplify/amplify-ui/issues/5134

chore(docs): update expo install and usage guidance

---

.changeset/seven-frogs-complain.md

Update changeset for liveness background color patch

---

docs/src/components/FunctionOverridesTable.tsx
docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/authenticator/customization/customization.override-function-calls.react-native.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/customization.override-function-calls.web.mdx

- Shows how to use `handle*` functions with latest `aws-amplify` and with `aws-amplify@5` and below. 
- Updates wording above table for accuracy
The table is the same for all frameworks minus heading
Angular - https://ui.docs.amplify.aws/angular/connected-components/authenticator/customization#override-function-calls
React - https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls
Vue - https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#override-function-calls
React Native - https://ui.docs.amplify.aws/react-native/connected-components/authenticator/customization#override-function-calls

chore(docs): Add table showing override functions in current and prev major versions

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.android.mdx

Android Liveness Version Update 1.2.5

---

README.md

Update readme to reflect that Account Settings went GA, and to add Liveness component

chore: add liveness and account settings to README components

---

docs/storageMock.ts

chore(gen2-storage): clean up a typo

---

package.json
packages/angular/.lintstagedrc.js
packages/react-auth/.lintstagedrc.js
packages/react-core-auth/.lintstagedrc.js
packages/react-core-notifications/.lintstagedrc.js
packages/react-core/.lintstagedrc.js
packages/react-geo/.lintstagedrc.js
packages/react-geo/jest.setup.ts
packages/react-liveness/.lintstagedrc.js
packages/react-liveness/jest.setup.ts
packages/react-native-auth/.lintstagedrc.js
packages/react-native/.lintstagedrc.js
packages/react-notifications/.lintstagedrc.js
packages/react-notifications/jest.setup.ts
packages/react-storage/.lintstagedrc.js
packages/react-storage/jest.setup.ts
packages/react/.lintstagedrc.js
packages/react/jest.setup.ts
packages/ui/.lintstagedrc.js
yarn.lock

Removes type checking from commit hook and the `tsc-files` dep
NA
Ran linting and unit tests

chore(tsc-files): remove type checking on commit

---

examples/next/package.json
package.json
yarn.lock

Replace `aws-amplify@gen2-storage` with `aws-amplify@unstable`
NA
NA

chore(aws-amplify): use aws-amplify unstable tag

---

.gitignore
examples/next/pages/ui/components/storage/storage-image/error/index.page.tsx
examples/next/pages/ui/components/storage/storage-image/with-path/error/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/with-path/error/index.page.tsx
examples/next/pages/ui/components/storage/storage-image/with-path/private-access-level/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/with-path/private-access-level/index.page.tsx
examples/next/pages/ui/components/storage/storage-image/with-path/protected-access-level/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/with-path/protected-access-level/index.page.tsx
examples/next/pages/ui/components/storage/storage-image/with-path/public-access-level/aws-exports.js
examples/next/pages/ui/components/storage/storage-image/with-path/public-access-level/index.page.tsx
packages/e2e/features/ui/components/storage/storage-image/load-image-with-error.feature
packages/e2e/features/ui/components/storage/storage-image/with-path/load-image-with-error.feature
packages/e2e/features/ui/components/storage/storage-image/with-path/load-private-image-from-s3.feature
packages/e2e/features/ui/components/storage/storage-image/with-path/load-protected-image-from-s3.feature
packages/e2e/features/ui/components/storage/storage-image/with-path/load-public-image-from-s3.feature

Adds additional examples and e2e tests for gen2 props with StorageImage

chore(gen2-storage): add StorageImage examples and e2e tests

---

.changeset/dull-days-learn.md
examples/next/package.json
package.json
packages/angular/projects/ui-angular/package.json
packages/react-auth/package.json
packages/react-core-auth/package.json
packages/react-core-notifications/package.json
packages/react-core/package.json
packages/react-geo/package.json
packages/react-liveness/package.json
packages/react-native-auth/package.json
packages/react-native/package.json
packages/react-notifications/package.json
packages/react-storage/package.json
packages/react/package.json
packages/ui/package.json
packages/vue/package.json
yarn.lock

Bump `aws-amplify` to version `6.2.0`
NA
NA

chore(aws-amplify): point amplify to 6.2.0

---

docs/src/pages/[platform]/connected-components/storage/storageimage/react.mdx
docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx

Add 'Deprecated Props' subheadings to sections mentioning gen1 props 

chore(docs): Update storage headings 

---

docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.react.mdx

chore(docs): update liveness to use amplify gen 2 setup

---

docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/overview.react-native.mdx
docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/overview.react.mdx
docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/prereqs.react-native.mdx
docs/src/pages/[platform]/connected-components/in-app-messaging/fragments/prereqs.react.mdx
docs/src/pages/[platform]/connected-components/in-app-messaging/index.page.mdx

Updates links to point to gen2 docs 

chore(docs): update in-app links to point to gen2 docs

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/authenticator/quick-start.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.android.mdx

Bump Android Amplify UI versions

---

docs/src/pages/[platform]/connected-components/geo/react.mdx

chore(docs): update geo links to point to gen2 docs

---

docs/src/data/globalnav.ts
docs/src/pages/_app.page.tsx

- Remove the nav link to Learn
- Delete unused variable

Remove learn from navbar

---

.changeset/moody-ads-protect.md
packages/react/src/index.ts

tets change

---

amplify.yml

Update docs build to use node20
n/a
Successfully deployed on fork and smoke tested https://update-next.d3ndg8mva9vlsy.amplifyapp.com/

chore(docs): update runtime to node20

---

.changeset/flat-planes-sing.md
packages/ui/src/i18n/dictionaries/authenticator/de.ts

Add a few missing translations for German
Fixes https://github.com/aws-amplify/amplify-ui/issues/5245
Ran forgot-password example app with translations

chore(i18n): Add german translations

---

.changeset/angry-ants-grow.md
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/liveness.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/constants.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/getFaceMatchStateInLivenessOval.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts

- Updated Liveness flow to use more config values from the server session Info
- Added values for FaceDistanceThresholdMin, FaceDistanceThreshold, OvalHeightWidthRatio

chore(liveness): add more dynamic configs

---

.github/workflows/publish-liveness-alpha.yml

chore(liveness): update publish-liveness-alpha workflow

---

yarn.lock

Fix https://github.com/aws-amplify/amplify-ui/security/dependabot/143

fix: fix security vulnerability in ip package

---

docs/src/pages/[platform]/components/autocomplete/react.mdx

Minor improvements to docs: corrected some component props names in text.
n/a
Looked up props names in source code.

[docs] react/Autocomplete: Correct props names

---

docs/src/pages/[platform]/components/input/examples/InputVariationExample.tsx

Updated example to make distinction between Default and Quiet clearer.
n/a
n/a

InputVariationExample.tsx: Make variations clearer

---

packages/react-liveness/src/components/FaceLivenessDetector/service/utils/TelemetryReporter/TelemetryReporter.ts

chore: added comment about telemetry usage

---

docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/liveness/quick-start-add.android.mdx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.android.mdx

- [] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)

Amplify UI Android - Liveness 1.2.6 Release

---

amplify.yml
docs/flutter/authenticator/lib/authenticator_config.dart
docs/flutter/authenticator/lib/main.dart
docs/flutter/authenticator/lib/stubs/amplify_auth_cognito_stub.dart
docs/flutter/authenticator/pubspec.lock
docs/flutter/authenticator/pubspec.yaml
docs/src/pages/[platform]/connected-components/authenticator/quick-start.mdx
docs/src/pages/[platform]/getting-started/installation/dependencies.mdx

- Update the Flutter docs and example to use Amplify Flutter v2
- Update the background color of the Flutter authenticator example to match the docs site
- Update the Android device used in the Flutter authenticator example to a more modern device
Current UI
Updated UI
I deployed the changes to the URL below and manually confirmed the docs site and the flutter example built successfully.
https://chore-amplify-flutter-v2.d4urt9m0exbgc.amplifyapp.com/flutter/connected-components/authenticator

chore: update flutter examples to use Amplify Flutter v2

---

docs/src/pages/[platform]/connected-components/liveness/troubleshooting/index.page.mdx

Adds an item to https://ui.docs.amplify.aws/react/connected-components/liveness/troubleshooting

chore(docs): Update liveness troubleshooting guide with connection timeout error

---

package.json
yarn.lock

- Added resolution for `"ws": "^8.17.1"`
- `ws` is a dependency for `@size-limit/preset-big-lib@9.0.0`, but there are no patch versions for this package. At the moment the next version is a major version change for `10` or `11`. Trying out the resolution first and will open up another PR to test updating `@size-limit/preset-big-lib` to latest version

Add resolution for ws

---

packages/react-core/src/hooks/__tests__/useDataState.spec.ts
packages/react-core/src/hooks/index.ts
packages/react-core/src/hooks/useDataState.ts

Add `useDataState` react utility hook
NA
`yarn test`

feat(react-core): add useDataState

---

build-system-tests/scripts/mega-app-copy-files.sh
build-system-tests/templates/template-aws-exports.d.ts

- Updated script to copy over a `aws-exports.d.ts` file
Ran commands locally to verify changes:
- `npm run react-latest-vite-2-ts`
- https://github.com/aws-amplify/amplify-ui/actions/runs/9652710993/job/26623442326
- `npm run vue-latest-vite-latest-ts`
- https://github.com/aws-amplify/amplify-ui/actions/runs/9652710993/job/26623443371

fix(build-system-tests): add awsexports declaration file

---

.github/changeset-presets/bump-react.md
.github/changeset-presets/bump-versions.md
package.json
packages/react-ai/.eslintrc.js
packages/react-ai/.gitignore
packages/react-ai/.lintstagedrc.js
packages/react-ai/LICENSE
packages/react-ai/README.md
packages/react-ai/jest.config.ts
packages/react-ai/jest.setup.ts
packages/react-ai/package.json
packages/react-ai/rollup.config.ts
packages/react-ai/src/components/createAIConversation.ts
packages/react-ai/src/components/index.ts
packages/react-ai/tsconfig.dist.json
packages/react-ai/tsconfig.json

- Initial commit setting up new `react-ai` package

chore: initial commit setting up new ai package

---

packages/e2e/cypress/integration/common/shared.ts
packages/e2e/features/ui/components/liveness/disable-start-screen.feature
packages/e2e/features/ui/components/liveness/no-light.feature

Add feature file and related utils for testing the no light challenge 
N/A

chore(liveness): Add e2e tests for no-light challenge 

---

.changeset/plenty-bears-live.md
packages/react-liveness/package.json
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/liveness.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/CustomWebSocketFetchHandler.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/__tests__/CustomWebsocketFetchHandler.test.ts
yarn.lock

- Upgrade liveness streaming SDK
- Our CustomWebsocketFetchHandler is mostly copied from the sdk, so update it to match the more recent version but keep custom logic https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-websocket/src/websocket-fetch-handler.ts 
N/A
tested locally for successful check and connection/regular/session timeouts 

chore(deps): Update client-rekognitionstreaming sdk and custom fetch handler

---

.changeset/chilled-rice-listen.md
.changeset/plenty-bears-live.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
build-system-tests/scripts/mega-app-copy-files.sh
build-system-tests/templates/components/react/vite/template-tsconfig-vite-latest.json
build-system-tests/templates/template-aws-exports.d.ts
examples/next/package.json
package.json
packages/react-core/src/hooks/__tests__/useDataState.spec.ts
packages/react-core/src/hooks/index.ts
packages/react-core/src/hooks/useDataState.ts
packages/react-liveness/CHANGELOG.md
packages/react-liveness/package.json
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/__tests__/liveness.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/CustomWebSocketFetchHandler.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/__tests__/CustomWebsocketFetchHandler.test.ts
packages/react-liveness/src/version.ts
packages/react/src/context/elements/__tests__/createElementsContext.spec.tsx
packages/react/src/context/elements/createElementsContext.tsx
packages/react/src/context/elements/defaultElements.tsx
packages/react/src/context/elements/index.ts
packages/react/src/context/elements/types.ts
yarn.lock

Merged main branch into feature branch

Feat identity providers/main

---

docs/src/pages/[platform]/connected-components/liveness/customization/customization.system-clock-offset.react.mdx
docs/src/pages/[platform]/connected-components/liveness/troubleshooting/index.page.mdx

- Update to show max clock skew greater than or equal to 5 min
- Update example to use mock server time and add note about getting server time  

chore(docs): Update systemClockOffset example

---

docs/src/pages/[platform]/connected-components/liveness/customization/customization.system-clock-offset.react.mdx
docs/src/pages/[platform]/connected-components/liveness/troubleshooting/index.page.mdx

chore(docs): Update systemClockOffset example (#5367)

---

packages/react-core/elements/package.json
packages/react-core/package.json
packages/react-core/src/elements/ElementsContext.tsx
packages/react-core/src/elements/__tests__/ElementsContext.spec.tsx
packages/react-core/src/elements/defineBaseElement.tsx

Fix _@aws-amplify/ui-react-core/elements_ subpath export, clean up typos
NA

fix(react-core): update elements subpath exports

---

packages/react-ai/src/components/AIConversation/context/elements/definitions.ts
packages/react-ai/src/components/AIConversation/context/elements/index.ts

chore: add base elements definitions

---

.github/workflows/publish-ai.yml
.github/workflows/test-internal-prs.yml

- Copied branch `feature/ai-release` to `feat-ai/main`
- Updated github workflows

chore: update github workflows

---

packages/react-core/src/hooks/__tests__/useDataState.spec.ts
packages/react-core/src/hooks/index.ts
packages/react-core/src/hooks/useDataState.ts

- abstract forced async resolving in to `resolveMaybeAsync`
- add `hasError` to `DataState`
- add/update unit tests
NA
unit tests

chore(react-core): update useDataState async logic and add hasError

---

examples/next/pages/ui/components/storage/storage-browser/composable-playground/index.page.tsx
packages/react-core/src/elements/index.ts
packages/react-core/src/elements/types.ts
packages/react-core/src/index.ts
packages/react-storage/src/components/StorageBrowser/Views/ActionView.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/ActionSelect.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Message.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Navigate.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Paginate.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Refresh.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Search.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Summary.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Title.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/index.ts
packages/react-storage/src/components/StorageBrowser/Views/Controls/types.ts
packages/react-storage/src/components/StorageBrowser/Views/types.ts
packages/react-storage/src/components/StorageBrowser/context/HistoryState.tsx
packages/react-storage/src/components/StorageBrowser/context/PaginateState.tsx
packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
packages/react-storage/src/components/StorageBrowser/types.ts

chore(storage-browser): add composable api types

---

packages/react-ai/src/components/AIConversation/views/Controls/index.ts

Removes `Conversation` export from `Controls` directory

fix: remove circular dependency

---

packages/react-ai/package.json
packages/react-ai/rollup.config.ts
packages/react-ai/src/ai-conversation-styles.css
packages/react-ai/src/ai-conversation-styles.ts
packages/ui/src/theme/css/styles.scss

chore: move ai conversation styles to subpackage

---

packages/react-storage/jest.config.ts

Remove styles directory from jest coverage
NA
`yarn test`

chore(storage-browser): remove styles directory from jest coverage

---

packages/react-core/src/hooks/index.ts
packages/react-core/src/hooks/useDataState.ts
packages/react-core/src/index.ts
packages/react-storage/src/components/StorageBrowser/context/actions/__tests__/createUseActionStateContext.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/actions/constants.ts
packages/react-storage/src/components/StorageBrowser/context/actions/createActionStateContext.tsx

Add `createActionStateContext`, utils and base unit tests
NA

feat(storage-browser): add createActionStateContext

---

.changeset/silver-dolls-report.md
.changeset/tricky-fishes-wave.md
packages/angular/projects/ui-angular/src/lib/components/authenticator/components/verify-user/verify-user.component.html
packages/e2e/cypress/integration/common/shared.ts
packages/e2e/features/ui/components/authenticator/verify-user.feature
packages/react-core/src/hooks/__tests__/useDataState.spec.ts
packages/react-core/src/hooks/index.ts
packages/react-core/src/hooks/useDataState.ts
packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx
packages/react/src/components/Authenticator/FederatedSignIn/FederatedSignInButtons/FederatedSignInButton.tsx
packages/react/src/components/Authenticator/FederatedSignIn/FederatedSignInButtons/__tests__/__snapshots__/FederatedSignInButton.test.tsx.snap
packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx
packages/react/src/components/Authenticator/SignIn/SignIn.tsx
packages/react/src/components/Authenticator/SignUp/SignUp.tsx
packages/react/src/components/Authenticator/VerifyUser/VerifyUser.tsx
packages/react/src/components/Authenticator/VerifyUser/__tests__/VerifyUser.test.tsx
packages/react/src/components/Authenticator/shared/ConfirmSignInFooter.tsx
packages/react/src/components/Authenticator/shared/TwoButtonSubmitFooter.tsx
packages/vue/src/components/__tests__/verify-user.spec.ts
packages/vue/src/components/verify-user.vue

Updates feature branch to have newest version of useDataState.

chore: merge main into feat-use-user-attributes/main

---

packages/react-storage/jest.config.ts
packages/react-storage/src/components/StorageBrowser/context/controls/ActionSelect/ActionSelect.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/ActionSelect/__tests__/ActionSelect.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/ActionSelect/index.ts
packages/react-storage/src/components/StorageBrowser/context/controls/Divider/Divider.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Divider/__tests__/Divider.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Divider/index.ts
packages/react-storage/src/components/StorageBrowser/context/controls/Message/Message.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Message/__tests__/Message.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Message/index.ts
packages/react-storage/src/components/StorageBrowser/context/controls/Navigate/__tests__/Navigate.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Paginate/__tests__/Paginate.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Refresh/Refresh.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Refresh/__tests__/Refresh.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Refresh/index.ts
packages/react-storage/src/components/StorageBrowser/context/controls/Search/Search.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Search/__tests__/Search.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Search/index.ts
packages/react-storage/src/components/StorageBrowser/context/controls/Summary/Summary.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Summary/__tests__/Summary.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Summary/index.ts
packages/react-storage/src/components/StorageBrowser/context/controls/Table/Table.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Table/__tests__/Table.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Table/index.ts
packages/react-storage/src/components/StorageBrowser/context/controls/Title/Title.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Title/__tests__/Title.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Title/index.ts

Feat storage browser/scaffold reducers

---

docs/src/components/FunctionOverridesTable.tsx

- Documentation for service overrides is incorrect for `handleResetPassword` and `handleConfirmResetPassword`
- Compare against values in default services - https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/machines/authenticator/defaultServices.ts#L90

fix(docs): update authenticator services docs for reset password

---

packages/react-core/src/elements/types.ts
packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx

- Update class names for table control
- Remove `divider` from element display name. Missed this when removing divider control

Update table control css to use class base

---

packages/e2e/README.md

Includes link to environments and examples READMEs in the e2e README. This is to expedite the process of setting up e2e environments.

docs: adds link to environments documentation

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/types.ts

Removes the Table composability

chore(storage-browser): update Table composability

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Target.tsx
packages/react-storage/src/components/StorageBrowser/Views/types.ts

Removes composability of Target.
**Output:**
**Only `<Target />` is allowed**

chore(storage-browser) update Target composability

---

docs/src/pages/[platform]/connected-components/liveness/customization/customization.components.react.mdx
docs/src/pages/[platform]/connected-components/liveness/customization/customization.i18n.react.mdx
docs/src/pages/[platform]/connected-components/liveness/customization/customization.theming.react.mdx

Remove the 'live' Liveness components from the docs 
(context: they don't really work and it's confusing that the docs ask for camera access)
N/A
Visual inspection

chore(docs): Remove liveness components from docs

---

docs/src/pages/[platform]/connected-components/authenticator/customization/customization.headers-and-footers.web.mdx

Fix part of the example being cut off on vue customization page 
Fixes https://github.com/aws-amplify/amplify-ui/issues/5493

fix(docs): Fix vue customization example 

---

.changeset/four-apricots-compete.md
.changeset/late-roses-sin.md
docs/src/components/FunctionOverridesTable.tsx
docs/src/pages/[platform]/connected-components/authenticator/customization/customization.headers-and-footers.web.mdx
docs/src/pages/[platform]/connected-components/liveness/customization/customization.components.react.mdx
docs/src/pages/[platform]/connected-components/liveness/customization/customization.i18n.react.mdx
docs/src/pages/[platform]/connected-components/liveness/customization/customization.theming.react.mdx
environments/liveness/liveness-environment/amplify/backend/function/livenessenvironment3477af97/src/yarn.lock
environments/liveness/liveness-environment/amplify/backend/function/livenessenvironmentb20a0fc6/src/yarn.lock
examples/next/package.json
examples/next/pages/ui/components/storage/storage-manager/process-file-access-level/index.page.tsx
packages/e2e/README.md
packages/react-liveness/CHANGELOG.md
packages/react-liveness/package.json
packages/react-liveness/src/version.ts
packages/react-storage/CHANGELOG.md
packages/react-storage/package.json
packages/react-storage/src/components/StorageManager/__tests__/StorageManager.test.tsx
packages/react-storage/src/components/StorageManager/utils/__tests__/getInput.spec.ts
packages/react-storage/src/components/StorageManager/utils/getInput.ts
packages/react-storage/src/version.ts
yarn.lock

Docs release pr 2024 07 30

---

package.json
yarn.lock

* Dependency `aws-amplify` is incremented from version 6.3.2 -> 6.4.3 at the root directory of the repository
* This is a routine process to increment the pinned version of the dependency to ensure it remains up to date
N/A
With the increment of the version of `aws-amplify`, a successful build and tests were confirmed.

chore: update dependency 'aws-amplify' to increase version to 6.4.3

---

.husky/pre-commit
package.json
turbo.json
yarn.lock

Update `turbo` and `husky` deps, remove deprecated API usage
NA
- `yarn && yarn build`
- verify commit blockage to `main`
- verify prevention of commit on lint error

chore(deps): update turbo and husky deps and configuration

---

packages/react-storage/src/components/StorageBrowser/Controller.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/LocationDetailView.tsx

- Update `pageSize` for `handleListLocations` and `handleListLocationItems` call

chore(storage-browser): update pageSize to 1000

---

packages/react-ai/src/components/AIConversation/context/ResponseComponentsContext.tsx
packages/react-ai/src/components/AIConversation/createAIConversation.tsx
packages/react-ai/src/components/AIConversation/createProvider.tsx
packages/react-ai/src/components/AIConversation/types.ts
packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx

- Initial set up for responseComponents, can't test e2e until js makes a tagged release

chore(ai): setup for response ui components

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Table.spec.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/index.ts
packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx

- Update Table control to accept rows and columns as props
- Create `LocationsViewTable` to be used in `LocationsView`

chore(storage-browser): update table control to accept props and add it to LocationsView

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Table.spec.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/index.ts
packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/LocationDetailView.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/__tests__/LocationDetailView.spec.tsx

- Add `LocationDetailViewTable`

chore(storage-browser): set up LocationDetailViewTable

---

examples/next/pages/ui/components/storage/storage-browser/default-auth/custom-elements.tsx
examples/next/pages/ui/components/storage/storage-browser/default-auth/index.page.tsx

Just cleaning up some TS stuff

chore(storage-browser): minor clean up of initial elements

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Navigate.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Paginate.tsx
packages/react-storage/src/styles/storage-browser.css

- Cleanup and consolidate some CSS
- Fix some parent element class names for controls (remove `__container` since they are the parent element)

chore(storage-browser): cleanup css

---

.changeset/healthy-baboons-film.md
docs/src/pages/[platform]/connected-components/storage/storagemanager/props.ts
docs/src/pages/[platform]/connected-components/storage/storagemanager/react.mdx
examples/next/pages/ui/components/storage/storage-manager/use-accelerate-endpoint/amplify_outputs.js
examples/next/pages/ui/components/storage/storage-manager/use-accelerate-endpoint/index.page.tsx
packages/e2e/features/ui/components/storage/storage-manager/upload-file-to-S3-accelerate-endpoint.feature
packages/react-storage/src/components/StorageManager/StorageManager.tsx
packages/react-storage/src/components/StorageManager/hooks/useUploadFiles/useUploadFiles.ts
packages/react-storage/src/components/StorageManager/types.ts
packages/react-storage/src/components/StorageManager/utils/__tests__/getInput.spec.ts
packages/react-storage/src/components/StorageManager/utils/getInput.ts

Adds `useAccelerateEndpoint` to the StorageManager props
#5163 
Added unit test
Added example in Next
Added integ test

feat(storagemanager): add useAccelerateEndpoint

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Title.tsx
packages/react-storage/src/components/StorageBrowser/Views/CreateFolderActionView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/LocationActionView.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx
packages/react-storage/src/components/StorageBrowser/Views/types.ts

- Updates Title control to allow children, so it can be re-used across the other views (maybe a temp change? But this way we aren't duplicating a bunch of other code for making titles)

chore(storage-browser): update Title control usage

---

packages/react-storage/jest.config.ts
packages/react-storage/src/components/StorageBrowser/Views/Controls/Navigate.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Target.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Navigate.spec.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Table.spec.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/index.ts
packages/react-storage/src/components/StorageBrowser/Views/CreateFolderActionView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/CreateFolderControls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/LocationActionView.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/useHandleUpload.ts
packages/react-storage/src/components/StorageBrowser/__tests__/createStorageBrowser.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/actions/actions.tsx
packages/react-storage/src/components/StorageBrowser/context/actions/createFolderAction.ts
packages/react-storage/src/components/StorageBrowser/context/actions/listLocationItemsAction.ts
packages/react-storage/src/components/StorageBrowser/context/controls/ActionSelect/ActionSelect.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/ActionSelect/__tests__/ActionSelect.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Navigate/Navigate.tsx
packages/react-storage/src/components/StorageBrowser/context/controls/Navigate/__tests__/Navigate.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/elements/definitions.ts
packages/react-storage/src/components/StorageBrowser/context/types.ts

Add create folder support, refactor navigation to have deterministic behavior location types

feat(storage-browser): add create folder support

---

examples/next/pages/ui/components/storage/storage-browser/default-auth/custom-elements.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Summary.tsx
packages/react-storage/src/styles/storage-browser.css

Fixes the Term and Detail for Summary to reference the correct elements, adjust styles for Summary and add custom UI example usage in next-example

chore(storage-browser): fix/update Term/Detail usage in Summary, update styles

---

packages/react-storage/jest.config.ts
packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/LocationActionView.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/__tests__/UploadControls.spec.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/useHandleUpload.ts

- Add `UploadControls.tsx` to render controls and table for uploading files

chore(storage-browser): add LocationActionView table for upload

---

packages/react-ai/src/components/AIConversation/utils.ts
packages/react-ai/src/components/AIConversation/views/Controls/FieldControl.tsx

chore: allow base64 conversion to happen in browser

---

package.json
packages/react-storage/src/components/StorageBrowser/context/actions/downloadAction.ts
yarn.lock

- Updated `aws-amplify` with latest tag of `storage-browser`: https://github.com/aws-amplify/amplify-js/actions/runs/10308077551/job/28544368835#step:5:6343
```
Successfully published:
- @aws-amplify/adapter-nextjs@1.2.13-storage-browser.37d5283.0+37d5283
- @aws-amplify/analytics@7.0.43-storage-browser.37d5283.0+37d5283
- @aws-amplify/api@6.0.45-storage-browser.37d5283.0+37d5283
- @aws-amplify/api-graphql@4.1.14-storage-browser.37d5283.0+37d5283
- @aws-amplify/api-rest@4.0.43-storage-browser.37d5283.0+37d5283
- @aws-amplify/auth@6.3.14-storage-browser.37d5283.0+37d5283
- @aws-amplify/core@6.3.10-storage-browser.37d5283.0+37d5283
- @aws-amplify/datastore@5.0.45-storage-browser.37d5283.0+37d5283
```
- Use `contentDisposition: attachment` to directly download files on download button click …

chore(storage-browser): update yarn.lock with latest aws-amplify storage-browser tag and use contentDisposition

---

examples/next-app-router/src/app/theme/page.tsx
packages/ui/src/theme/createTheme/__tests__/createComponentClasses.test.ts

Fixes code scanning issues related to unused variables in Theming v2
https://github.com/aws-amplify/amplify-ui/security/code-scanning

chore: remove unused variables

---

packages/react-storage/jest.config.ts
packages/react-storage/src/components/StorageBrowser/Controller.tsx
packages/react-storage/src/components/StorageBrowser/__tests__/Controller.spec.tsx
yarn.lock

- remove infinite `locations` loading in `Controller`
- add unit tests
- decrease jest coverage threshold for functions by `0.05`
- removal of shouldRenderLocations resulted in less overall function coverage
- refresh _aws-amplify@storage-browser_ version to [latest available](https://www.npmjs.com/package/@aws-amplify/storage/v/6.6.1-storage-browser.7faa74e.0)
NA

fix(storage-browser): address infinite locations loading

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx

[WIP] chore(storage-browser): use renderHeaderItem function to render table header items

---

packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts

chore(liveness): randomize hair check screen oval

---

packages/react-ai/src/hooks/createAIHooks.tsx
packages/react-ai/src/hooks/useAIConversation.tsx
packages/react-ai/src/hooks/useAIGeneration.tsx
packages/react-ai/src/types.ts

- Patch fix for excessive stack depth type comparison, will check with Ivan what the proper solution should be

fix(ai): move away from using v6 client

---

packages/react-core/src/elements/index.ts

Export all `elements` types to fix type reference issues in consumers
**before**
**after**
NA
Verified build output

fix(elements): export all elements types

---

packages/react-ai/package.json

chore: fix ai deps after merge

---

.changeset/orange-pets-smile.md
packages/react-geo/package.json
yarn.lock

Updates `maplibre-gl-js-amplify` to 4.0.1 which pins `@maplibre/maplibre-gl-geocoder` to a working version

chore(deps): Update maplibre-gl-js-amplify package

---

packages/react-ai/src/components/AIConversation/types.ts

chore(ai): remove chain of thought prop

---

.changeset/orange-pets-smile.md
examples/next/package.json
packages/react-geo/CHANGELOG.md
packages/react-geo/package.json
packages/react-geo/src/version.ts
yarn.lock

Docs release pr 2024 08 20

---

packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx
packages/react-storage/src/components/StorageBrowser/context/actions/listLocationsAction.ts

- Adds error `<Message />` to LocationsView

chore(storage-browser): Add error Message to LocationsView

---

.changeset/seven-ears-cheat.md
docs/__tests__/__snapshots__/props-table.test.ts.snap
docs/src/pages/[platform]/components/scrollview/examples/AutoScrollExample.tsx
docs/src/pages/[platform]/components/scrollview/examples/index.ts
docs/src/pages/[platform]/components/scrollview/react.mdx
packages/react/__tests__/__snapshots__/exports.ts.snap
packages/react/jest.config.ts
packages/react/src/primitives/ScrollView/ScrollView.tsx
packages/react/src/primitives/types/scrollView.ts

Added a `autoScroll` prop to the `ScrollView` primitive that can be set to 'smooth', 'instant', or 'auto'. This will be useful for a chat history to always show the latest message. 

feat(scrollview): add autoScroll prop

---

packages/react/__tests__/__snapshots__/exports.ts.snap
packages/react/src/components/FederatedIdentities/controls/__tests__/utils.test.tsx
packages/react/src/components/FederatedIdentities/controls/index.ts
packages/react/src/components/FederatedIdentities/controls/utils.tsx
packages/react/src/components/FederatedIdentities/index.ts

Exposes a utility for customers to pull supported providers from backend with zero-configuration.

feat(react): getProviderConfig utility

---

packages/react/src/components/FederatedIdentities/constants.ts
packages/react/src/components/FederatedIdentities/controls/IdentityControl.tsx
packages/react/src/components/FederatedIdentities/controls/__tests__/IdentityControl.spec.tsx
packages/react/src/components/FederatedIdentities/controls/types.ts
packages/react/src/components/FederatedIdentities/controls/utils.tsx

This PR adds the IdentityControl component, which is a forwardRef of the provider button.

feat(react): IdentityControl component

---

packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx

chore(ai): add aria live region to messages container

---

packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx

Just adds them to the UI, they're not wired up yet. 

chore(storage-browser): add paginate to Locations/LocationDetail views

---

examples/next/pages/ui/components/ai/ai-conversation/amplify/data/resource.ts
examples/next/pages/ui/components/ai/use-ai-generation/amplify/data/resource.ts

fix(ai): fix build

---

packages/react/src/components/FederatedIdentities/context/DisplayTextContext.tsx
packages/react/src/components/FederatedIdentities/context/__tests__/DisplayTextContext.test.tsx
packages/react/src/components/FederatedIdentities/controls/FederatedIdentitiesControl.tsx
packages/react/src/components/FederatedIdentities/controls/__tests__/FederatedIdentitiesContol.spec.tsx
packages/react/src/components/FederatedIdentities/controls/__tests__/IdentityControl.spec.tsx

This PR adds the create function for the main control block (FederatedIdentities). This PR also makes a small fix for the displayText utility.

feat(react): createFederatedIdentities function

---

packages/react-ai/src/types.ts

- Narrowing down the type of the V6 client seems to fix the issue with excessive type depth checking error

fix(ai): fix excessive type depth error

---

examples/next/pages/ui/components/federated-identities/composition/aws-exports.js
examples/next/pages/ui/components/federated-identities/composition/customElements.tsx
examples/next/pages/ui/components/federated-identities/composition/index.page.tsx
examples/next/pages/ui/components/federated-identities/composition/styles.css
examples/next/pages/ui/components/federated-identities/custom-render/aws-exports.js
examples/next/pages/ui/components/federated-identities/custom-render/index.page.tsx
examples/next/pages/ui/components/federated-identities/custom-render/styles.css
examples/next/pages/ui/components/federated-identities/stand-alone/aws-exports.js
examples/next/pages/ui/components/federated-identities/stand-alone/index.page.tsx
examples/next/pages/ui/components/federated-identities/stand-alone/styles.css
examples/next/pages/ui/components/federated-identities/with-redirect-hook/aws-exports.js
examples/next/pages/ui/components/federated-identities/with-redirect-hook/index.page.tsx
examples/next/pages/ui/components/federated-identities/with-redirect-hook/styles.css
packages/e2e/features/ui/components/federated-identities/composition.feature
packages/e2e/features/ui/components/federated-identities/custom-render.feature
packages/e2e/features/ui/components/federated-identities/standalone.feature
packages/react/src/components/FederatedIdentities/index.ts
packages/ui/src/theme/css/component/federatedIdentities.scss
packages/ui/src/theme/css/styles.scss

This PR implements the style classes for the FederatedIdentities component, as well as creating a few example apps to go over the capabilities of the component.

feat(react): FederatedIdentities styling and example apps

---

.github/workflows/build-system-test-react-native.yml
build-system-tests/package.json
build-system-tests/scripts/build-android.sh

- log the output of `npm run android` in the `build-android` workflow to capture any errors that occur in the bundling step
- Remove unnecessary `install-with-retries` at the beginning of the RN build-system-test, because this installs monorepo dependencies 
- Add esbuild-register as a dev dependency (used in `checkReactNativeLog`, previously the dep was coming from the monorepo)  
POC https://github.com/aws-amplify/amplify-ui/pull/5649
- Ran against `@aws-amplify/ui-react-native@2.2.4` and failed as expected with the style-dictionary error https://github.com/aws-amplify/amplify-ui/actions/runs/10515974678/job/29137194085?pr=5649 ([commit](https://github.com/aws-amplify/amplify-ui/pull/5649/commits/eb49a96149f5432e15ff44a3e1072a441811ec2e))
- Ran against …

chore(build-system-test): Update React Native build system test to capture bundling errors

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Message.tsx
packages/react-storage/src/components/StorageBrowser/context/elements/definitions.ts

- Removes low level composability and uses base elements.
- No change to visuals
- Adds dismiss functionality

chore(storage-browser): Refactor MessageControl

---

.github/workflows/build-system-test-react-native.yml

chore(build-system-test): run RN tests on push to main

---

packages/react-ai/src/hooks/useAIGeneration.tsx
packages/react-ai/src/types.ts

chore(ai): rename narrowed down v6 client type

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Cancel.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Download.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Exit.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Primary.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Refresh.tsx
packages/react-storage/src/components/StorageBrowser/context/types.ts

Refactors Download, Refresh, Exit, Primary, and Cancel controls.
Should be no visual changes. Removes low level composability.
**Download**
**Refresh**
**Exit / Primary**
**Cancel:**

[WIP] chore(storage-browser): Refactor controls

---

yarn.lock

- Updates `micromatch` entry to use safe version, it's only used in peer and dev dependencies so safe to just refresh the lock file 
https://github.com/aws-amplify/amplify-ui/security/dependabot/153

chore(deps): Refresh micromatch dependency

---

packages/react-core/src/elements/ControlsContext.tsx
packages/react-core/src/elements/__tests__/ControlsContext.spec.tsx
packages/react-core/src/elements/__tests__/utils.spec.tsx
packages/react-core/src/elements/index.ts
packages/react-core/src/elements/utils.ts

Add `ControlsContext`, utils and unit tests
NA
Manual tests with `StorageBrowser`, unit tests

feat(storage-browser): add Controls context

---

packages/react-storage/package.json

Increase package limit to 15kb

increase package size

---

examples/next/pages/ui/components/storage/storage-browser/default-auth/index.page.tsx
examples/next/pages/ui/components/storage/storage-browser/managed-auth/index.page.tsx
packages/react-storage/src/styles/storage-browser.css

chore(storage-browser): fix title alignment, update example app button

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Loading.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Title.tsx

Refactors Loading and Title to just use base elements.

chore(storage-browser): refactor Title/Loading

---

packages/react-liveness/src/components/FaceLivenessDetector/service/utils/liveness.ts

chore(liveness): remove random x and y values

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Overwrite.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/__tests__/Overwrite.spec.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/index.ts
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/useHandleUpload.ts
packages/react-storage/src/components/StorageBrowser/context/elements/defaults.tsx
packages/react-storage/src/components/StorageBrowser/context/elements/definitions.ts
packages/react-storage/src/styles/storage-browser.css

- Modifies useHandleUpload to also accept `preventOverwrite` boolean
- Adds Overwrite checkbox control that accepts `defaultChecked` and `handleChange` props to control the checkbox
**Existing file uploaded, "Overwrite existing files" not checked**
**Existing file uploaded, "Overwrite existing files" checked**

chore(storage-browser): add preventOverwrite toggle for upload

---

packages/e2e/package.json
yarn.lock

- Merge `main` branch to get latest changes to e2e package

Feat storage browser/merge main

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/Controls/Summary.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx
packages/react-storage/src/styles/storage-browser.css

chore(storage-browser): show task summary totals

---

packages/react-storage/src/components/StorageBrowser/context/actions/__tests__/listLocationsAction.spec.ts
packages/react-storage/src/components/StorageBrowser/context/actions/listLocationsAction.ts

Fix the recursive listLocation pagination logic 

feat(storage-browser): add pagination to locations view

---

packages/react/package.json

I didn't add 'server' to the 'files' in package.json so it wasn't being published and packages couldn't import stuff from the /server namespace. 

fix(rsc): add server to files in package.json

---

docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx

Update troubleshooting guide to show the exact error message from using Amplify components with SSR
https://github.com/aws-amplify/amplify-ui/issues/5653

chore(docs): Update troubleshooting guide to show SSR error

---

packages/react-storage/src/components/StorageBrowser/context/actions/__tests__/listLocationItemsAction.spec.ts
packages/react-storage/src/components/StorageBrowser/context/actions/listLocationItemsAction.ts

Address `listLocationItemsAction` filtered `results` issue for `refresh` and initial load events
NA

fix(storage-browser): add listLocationItemsAction off by one mitigation

---

packages/react-storage/src/components/StorageBrowser/Views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationActionView/UploadControls.tsx

fix(storage-browser): add 'sort' variant to button; remove incorrect class

---

environments/ai/gen2/package.json
environments/ai/package.json
environments/package.json
package.json
yarn.lock

- Setup a gen2 environment on our staging repo
- Added code to pull down and generate the amplify_outputs.json

chore(ai): setup ai gen2 backend

---

packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/hooks/usePaginate.ts

Wrap `usePaginate().handleReset` in ref and provide to initial loading effect in `LocationDetailView`

chore(storage-browser): update usePaginate and reset pagination count on location/prefix update

---

packages/react-storage/src/components/StorageBrowser/Views/LocationsView/LocationsView.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationsView/__tests__/LocationsView.spec.tsx

Update unit test for LocationsView to include tests for error Message

chore(storage-browser): add unit test for error Message in LocationsView

---

packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/Views/LocationDetailView/__tests__/LocationDetailView.spec.tsx

Adds unit tests for rendering an error Message in LocationDetailView

chore(storage-browser): add unit tests for Message in LocationDetailView

---

.changeset/foo-bar.md

chore: add missing changeset

---

.github/workflows/publish-latest.yml

fix(ci): fix build test steps to be jobs instead of steps

---

packages/react-ai/src/components/AIConversation/AIConversation.tsx
packages/react-ai/src/components/AIConversation/createAIConversation.tsx
packages/react-ai/src/components/AIConversation/createProvider.tsx
packages/react-ai/src/components/AIConversation/types.ts
packages/react-ai/src/components/AIConversation/views/Controls/ActionsBarControl.tsx
packages/react-ai/src/components/AIConversation/views/Controls/AttachFileControl.tsx
packages/react-ai/src/components/AIConversation/views/Controls/AvatarControl.tsx
packages/react-ai/src/components/AIConversation/views/Controls/FieldControl.tsx
packages/react-ai/src/components/AIConversation/views/Controls/HeaderControl.tsx
packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx
packages/react-ai/src/components/AIConversation/views/Controls/PromptControl.tsx

chore(ai): fix ai conversation control types

---

packages/react-ai/src/hooks/__tests__/createAIHooks.test.tsx
packages/react-ai/src/hooks/useAIGeneration.tsx

fix(ai): fix return type for useAIGeneration

---

packages/react-storage/package.json

Add bundle size tests for `FileUploader` and `StorageImage`
NA
Ran size tests locally

chore(react-storage): add bundle size tests for FileUploader and StorageImage

---

.changeset/fluffy-fireants-doubt.md
packages/react-ai/src/components/AIConversation/views/Controls/FieldControl.tsx

fix(ai): remove unnecessary use of Buffer

---

.github/workflows/test-fork-prs.yml

fix(workflows): fix fork pr workflow

---

.github/workflows/publish-next.yml

fix(workflow): fix test and publish next

---

.changeset/heavy-bottles-poke.md
examples/next/pages/ui/components/ai/ai-conversation/index.page.tsx
packages/react-ai/src/components/AIConversation/AIConversation.tsx
packages/react-ai/src/components/AIConversation/__tests__/__snapshots__/displayText.test.tsx.snap
packages/react-ai/src/components/AIConversation/__tests__/displayText.test.tsx
packages/react-ai/src/components/AIConversation/context/DisplayTextContext.tsx
packages/react-ai/src/components/AIConversation/context/index.ts
packages/react-ai/src/components/AIConversation/createAIConversation.tsx
packages/react-ai/src/components/AIConversation/createProvider.tsx
packages/react-ai/src/components/AIConversation/displayText.ts
packages/react-ai/src/components/AIConversation/views/Controls/MessagesControl.tsx
packages/react-ai/src/components/AIConversation/views/default/MessageList.tsx

- Adds displayText providers and hooks
- Adds a getMessageTimestamp function to displayText

chore(ai): add timestamp function to displayText

---

environments/ai/gen2/package.json
environments/package.json
examples/next/package.json
package.json
yarn.lock

Remove `@aws-amplify/backend-cli` and related deps, migrate `@aws-amplify/backend` to top level _package.json_ dev deps
NA
Manual tests, CI run of this PR

chore: move amplify backend deps to top level devDeps

---

.changeset/happy-cobras-change.md
packages/react-storage/src/components/FileUploader/index.ts
packages/react-storage/src/components/StorageManager/index.ts
packages/react-storage/src/components/index.ts
packages/react-storage/src/index.ts

Exports storage handle types from the ui-react-storage package 
https://github.com/aws-amplify/amplify-ui/issues/5813

chore(storage): Export FileUploaderHandle and StorageManagerHandle

---

packages/react-ai/package.json
packages/react-notifications/package.json
yarn.lock

Update stale internal dep versions

fix(deps): update stale internal dep versions

---

.changeset/slimy-numbers-beg.md
packages/angular/projects/ui-angular/package.json

Move `@angular/common` and `rxjs` to peerDeps for angular 
- angular v14-18 has `"rxjs": "^6.5.3 || ^7.4.0"` as a peerDep so we match their versioning
- we already have  `@angular/core >= 14.0.0` as a peerDep so making the "common" dep match that 
Installed/built angular mega apps with this version of the ui-angular package 

chore(deps): Update angular peer deps

---

.github/workflows/publish-liveness-dca.yml
packages/react-liveness/jest.config.ts
packages/react-liveness/package.json
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/types/liveness.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/StreamRecorder/StreamRecorder.ts

DCA changes. We want to merge this in a new `liveness-dca-v2` branch but GitHub doesn't allow me to so here we are.

feat: add dca changes

---

.github/workflows/publish-liveness-dca.yml

Seeing the following error:
```
The workflow is not valid. .github/workflows/publish-liveness-dca.yml (Line: 27, Col: 11): Secret LIVENESS_E2E_CODE_ARTIFACT_ARN is required, but not provided while calling
```

Update publish workflow

---

.github/workflows/publish-liveness-dca.yml

Remove e2e tests from dca workflow

---

yarn.lock

fix(ai): fix data-schema dep in yarn.lock

---

packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCameraModule.test.tsx
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts

- **chore(liveness): allow selecting all cameras, allow camera selection … (#5833)**
- **fix(liveness): fix camera select showing up with one camera, fix camera changing weirdness with hair check screen (#5845)**

Merge liveness/alpha into dca v2

---

.changeset/cyan-baboons-applaud.md
packages/react-core-auth/src/hooks/useHandleCopy/useHandleCopy.ts
packages/react-core/src/components/FormCore/useControlledField.ts
packages/react-core/src/hooks/useTimeout.ts
packages/react-storage/src/components/FileUploader/utils/getInput.ts
packages/react/src/primitives/Accordion/AccordionTrigger.tsx
packages/react/src/primitives/Tabs/TabsItem.tsx
packages/ui/src/utils/__tests__/index.test.ts
packages/ui/src/utils/utils.ts

Prefer `isFunction`, remove extraneous `isTypedFunction` util

chore(utils): prefer isFunction

---

.changeset/grumpy-needles-push.md
packages/react-core-auth/package.json
packages/react-core/package.json
packages/react-core/src/hooks/__tests__/useSetUserAgent.test.ts
packages/react-liveness/package.json
packages/react-storage/package.json
packages/react/package.json
packages/ui/package.json
packages/vue/package.json
yarn.lock

Remove _@aws-amplify/core_ devDep from _@aws-amolify/ui-react-core_ to fix multiple singleton installations when pointing _aws-amplify_ at a tagged version.
- refactor a unit test in _@aws-amplify/ui-react-core_ to no longer reference _@aws-amplify/core_
- set all _@aws-amplify/core_ peerDeps to point at `*` to remove potential for version mismatch with _aws-amplify_
NA
`yarn build && yarn test`

fix(deps): remove @aws-amplify/core devDep from react-core

---

.github/workflows/publish-storage-browser.yml
package.json
packages/react-storage/package.json
packages/react-storage/src/components/StorageBrowser/adapters/createAmplifyAuthAdapter.ts
packages/react-storage/src/components/StorageBrowser/adapters/createManagedAuthAdapter.ts
packages/react-storage/src/components/StorageBrowser/adapters/types.ts
packages/react-storage/src/components/StorageBrowser/context/__tests__/useGetCredentialsProvider.spec.ts
packages/react-storage/src/components/StorageBrowser/context/actions/__tests__/listLocationsAction.spec.ts
packages/react-storage/src/components/StorageBrowser/context/actions/listLocationItemsAction.ts
packages/react-storage/src/components/StorageBrowser/context/actions/listLocationsAction.ts
packages/react-storage/src/components/StorageBrowser/context/config.tsx
packages/react-storage/src/components/StorageBrowser/context/types.ts
packages/react-storage/src/components/StorageBrowser/context/useGetCredentialsProvider.ts
packages/react-storage/src/components/StorageBrowser/createProvider.tsx
yarn.lock

Bump _aws-amplify_ tag version

chore(storage-browser): bump amplify tag

---

.github/workflows/issue-comment.yml

Reverts aws-amplify/amplify-ui#5865

Revert "feat(GitHub): Add support for 'discussion' label on issues"

---

.github/workflows/publish-storage-browser.yml

Point feature publish dist-tag to `storage-browser-alpha`

chore(storage-browser): update publish dist-tag

---

build-system-tests/package.json

fix(build-test): Fix failing RN build test

---

packages/react-ai/package.json

chore(ai): add size limits

---

packages/react-storage/src/components/StorageBrowser/controls/__tests__/TitleControl.spec.tsx

Fix Dependency for useResolvedComposable

---

packages/react-storage/src/components/StorageBrowser/controls/__tests__/TitleControl.spec.tsx

Fix mock dependency

---

packages/react-storage/src/components/StorageBrowser/composables/Title.tsx
packages/react-storage/src/components/StorageBrowser/composables/__tests__/Title.spec.tsx
packages/react-storage/src/components/StorageBrowser/controls/TitleControl.tsx
packages/react-storage/src/components/StorageBrowser/controls/__tests__/TitleControl.spec.tsx
packages/react-storage/src/components/StorageBrowser/controls/context.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useTitle.spec.tsx
packages/react-storage/src/components/StorageBrowser/controls/hooks/useTitle.ts

Feat storage browser/refactor title

---

packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useTitle.spec.tsx

Remove unused variable from the test

---

packages/e2e/features/ui/components/storage/storage-browser/navigate-locations.feature
packages/react-storage/src/components/StorageBrowser/ComponentsProvider.tsx
packages/react-storage/src/components/StorageBrowser/actions/handlers/utils.ts
packages/react-storage/src/components/StorageBrowser/tasks/useProcessTasks.ts
packages/react-storage/src/components/StorageBrowser/views/Controls/Table.tsx

Couple small follow ups from https://github.com/aws-amplify/amplify-ui/pull/5941
NA
Manual test, ran unit tests

chore(storage-browser): minor follow ups to browser nav support integration

---

packages/react-storage/src/components/StorageBrowser/controls/TitleControl.tsx
packages/react-storage/src/components/StorageBrowser/controls/__tests__/TitleControl.spec.tsx
packages/react-storage/src/components/StorageBrowser/controls/hooks/useTitle.ts

Address comments

---

packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useTitle.spec.tsx

Remove props from unit test

---

packages/react-ai/src/components/AIConversation/AIConversationProvider.tsx

fix(ai): message renderer not being applied

---

packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/CameraSelector.test.tsx
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCameraModule.test.tsx
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/machine.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts
packages/react-liveness/src/components/FaceLivenessDetector/types/classNames.ts
packages/react-liveness/src/components/FaceLivenessDetector/utils/__tests__/device.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/utils/device.ts
packages/ui/src/theme/css/component/liveness.scss

- **chore(liveness): allow selecting all cameras, allow camera selection … (#5833)**
- **fix(liveness): fix camera select showing up with one camera, fix camera changing weirdness with hair check screen (#5845)**
- **fix(liveness): Only apply transform style on user-facing video (#5953)**
- **fix(liveness): Fix oval render when switching cameras  (#5954)**

Merge liveness/alpha into liveness dca v2

---

packages/react-ai/src/components/AIConversation/AIConversationProvider.tsx

fix(ai): message renderer not being applied (#5979)

---

examples/next/pages/ui/components/storage/storage-browser/default-auth/index.page.tsx
packages/react-storage/src/components/StorageBrowser/components/DataTable.tsx
packages/react-storage/src/components/StorageBrowser/views/Controls/Table.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyFilesControls.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DeleteFilesControls.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DestinationPicker.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/UploadControls.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/Controls.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/LocationsView.tsx
packages/react-storage/src/styles/storage-browser.css

updating styles for copy view

---

packages/react-storage/package.json
packages/react-storage/src/components/StorageBrowser/actions/configs/__tests__/__snapshots__/defaults.spec.ts.snap
packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/listLocationItems.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/listLocationItems.ts

feat: storage browser/list location items handler

---

packages/react-storage/src/components/StorageBrowser/composables/Search.tsx
packages/react-storage/src/components/StorageBrowser/composables/__tests__/Search.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/elements/definitions.ts

- Add onKeyUp event to type definitions
- Add onKeyUp listener to Field
- Update tests

feat: search on enter key press

---

packages/e2e/features/ui/components/storage/storage-browser/drag-and-drop.feature

This PR re-enables an E2E test that was disabled when integrating tables but was fixed in a different PR in parallel

fix(storage-browser): Re-enable folder drag and drop test

---

packages/react-storage/src/components/StorageBrowser/composables/Search.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/__tests__/CopyFilesControls.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/LocationDetailView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/__tests__/LocationDetailView.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/__tests__/LocationsView.spec.tsx

- re-add search props that were lost in merge
- add more tests

fix: missing search in detail view

---

packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/__tests__/useLocationDetailView.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/useLocationDetailView.ts

- Update value for `prefix` to match rest of handleList calls
- Update tests

fix: pass correct prefix to search

---

packages/react-storage/src/components/StorageBrowser/views/__tests__/utils.spec.ts

* Adds additional unit tests to cover view utils

chore(tests): add additional test coverage for view utils

---

packages/react-ai/src/components/AIConversation/views/default/Form.tsx
packages/react-ai/src/components/AIConversation/views/default/PromptList.tsx
packages/react-ai/src/components/AIConversation/views/default/__tests__/PromptList.test.tsx

chore(ai): fixing ai test coverage

---

packages/react-storage/src/components/StorageBrowser/tasks/__tests__/useProcessTasks.spec.ts
packages/react-storage/src/components/StorageBrowser/tasks/types.ts
packages/react-storage/src/components/StorageBrowser/tasks/useProcessTasks.ts
packages/react-storage/src/components/StorageBrowser/tasks/utils.ts

Expose and add additional `useProcessTasks` event callbacks

chore(sto-bro): expose/add additional task callbacks

---

examples/next/pages/ui/components/storage/storage-browser/composable-playground/index.page.tsx
packages/react-storage/src/components/StorageBrowser/ComponentsProvider.tsx
packages/react-storage/src/components/StorageBrowser/composables/defaults.ts
packages/react-storage/src/components/StorageBrowser/composables/index.ts
packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
packages/react-storage/src/components/StorageBrowser/views/context.tsx

Expose `components` API with initial slots
Manually tested in example app

feat(sto-bro): expose components API for existing composables

---

packages/react-storage/src/components/StorageBrowser/ComponentsProvider.tsx
packages/react-storage/src/components/StorageBrowser/composables/LoadingIndicator.tsx
packages/react-storage/src/components/StorageBrowser/composables/Message.tsx
packages/react-storage/src/components/StorageBrowser/composables/__tests__/LoadingIndicator.spec.tsx
packages/react-storage/src/components/StorageBrowser/composables/__tests__/Message.spec.tsx
packages/react-storage/src/components/StorageBrowser/composables/defaults.ts
packages/react-storage/src/components/StorageBrowser/composables/types.ts
packages/react-storage/src/components/StorageBrowser/controls/LoadingIndicatorControl.tsx
packages/react-storage/src/components/StorageBrowser/controls/MessageControl.tsx
packages/react-storage/src/components/StorageBrowser/controls/__tests__/LoadingIndicatorControl.spec.tsx
packages/react-storage/src/components/StorageBrowser/controls/__tests__/MessageControl.spec.tsx
packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useDataTable.spec.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useLoadingIndicator.spec.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/__tests__/useMessage.spec.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/__tests__/compareButtonData.spec.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/__tests__/compareDateData.spec.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/__tests__/compareNumberData.spec.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/__tests__/compareTextData.spec.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/compareButtonData.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/compareDateData.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/compareNumberData.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/compareFunctions/compareTextData.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/useDataTable.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/useLoadingIndicator.ts
packages/react-storage/src/components/StorageBrowser/controls/hooks/useMessage.ts
packages/react-storage/src/components/StorageBrowser/controls/types.ts

Add `LoadingIndicator` and `Message` composables/controls
NA
Manual testing, unit tests

feat(sto-bro): add LoadingIndicator and Message composables/controls

---

packages/react-storage/package.json

Remove unused `lodash` dep from _@aws-amplify/ui-react-storage_

chore(react-storage): remove unused lodash dep

---

.github/workflows/reusable-build-system-test-react-native.yml
build-system-tests/scripts/mega-app-create-app.sh

Temporarily Pin expo version in pipeline

Pin expo version

---

packages/react-storage/src/components/StorageBrowser/composables/SearchField.tsx
packages/react-storage/src/components/StorageBrowser/composables/__tests__/SearchField.spec.tsx
packages/react-storage/src/components/StorageBrowser/composables/defaults.ts
packages/react-storage/src/components/StorageBrowser/composables/types.ts
packages/react-storage/src/components/StorageBrowser/controls/SearchControl.tsx
packages/react-storage/src/components/StorageBrowser/controls/__tests__/SearchControl.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/CopyView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/LocationDetailView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/LocationsView.tsx
packages/react-storage/src/styles/storage-browser.css

Follow up from: https://github.com/aws-amplify/amplify-ui/pull/6063

refactor: remove wrapper elements from search

---

packages/react-ai/src/components/AIConversation/context/ResponseComponentsContext.tsx
packages/react-ai/src/components/AIConversation/context/__tests__/ResponseComponentsContext.spec.tsx
packages/react-ai/src/components/AIConversation/views/default/MessageList.tsx
packages/react-ai/src/hooks/useAIConversation.tsx
packages/react-ai/src/types.ts

chore: cleaning up ai streaming hook

---

.changeset/beige-pugs-drive.md
examples/next/pages/ui/components/ai/ai-conversation/context.page.tsx
packages/react-ai/src/components/AIConversation/AIConversationProvider.tsx
packages/react-ai/src/components/AIConversation/context/AIContextContext.tsx
packages/react-ai/src/components/AIConversation/context/index.ts
packages/react-ai/src/components/AIConversation/types.ts
packages/react-ai/src/components/AIConversation/views/Controls/FormControl.tsx

feat(ai): add aiContext prop to AIConversation

---

packages/react-storage/src/components/StorageBrowser/actions/__tests__/createEnhancedListHandler.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/createEnhancedListHandler.ts
packages/react-storage/src/components/StorageBrowser/composables/SearchField.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/LocationDetailView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/__tests__/LocationDetailView.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/useLocationDetailView.ts
packages/react-storage/src/styles/storage-browser.css

- Warn users when we limit search to 10,000 items in Location Detail
- Updated unit tests

feat: add search results limit message

---

packages/react-core/src/utils/createContextUtilities.tsx
packages/react-storage/src/components/StorageBrowser/components/DropdownMenu.tsx
packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/__tests__/__snapshots__/copyView.spec.ts.snap
packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/copyView.ts
packages/react-storage/src/components/StorageBrowser/displayText/types.ts
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/CopyViewProvider.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/FoldersMessageControl.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/__tests__/CopyViewProvider.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/__tests__/__snapshots__/useFolders.spec.ts.snap
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/types.ts
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/useFolders.ts

Remove conditionally `undefined` value from `props` provided to `FoldersMessageProvider`

fix(sto-bro): fix conditional value provided to FoldersMessageProvider

---

packages/react-storage/src/components/StorageBrowser/composables/ActionExit.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/CopyView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CreateFolderView/CreateFolderView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/DeleteView/DeleteView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/UploadView/UploadView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/LocationDetailView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/LocationsView.tsx
packages/react-storage/src/styles/storage-browser.css

chore: fixing the UI

---

packages/react-storage/package.json

Bumps FileUploader kb restriction
- [] `yarn test` passes and tests are updated/added

chore: fileuploader size limit

---

packages/react-storage/src/components/StorageBrowser/ComponentsProvider.tsx

chore(storage-browser): expose Message slot

---

packages/react-storage/src/components/StorageBrowser/actions/useAction/__tests__/createEnhancedListHandler.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/useAction/createEnhancedListHandler.ts
packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/__tests__/__snapshots__/locationsView.spec.ts.snap
packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/locationsView.ts
packages/react-storage/src/components/StorageBrowser/views/LocationsView/LocationsViewProvider.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/__tests__/LocationsView.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/__tests__/useLocationsView.spec.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/types.ts
packages/react-storage/src/components/StorageBrowser/views/LocationsView/useLocationsView.ts

- Locations view can search up to 10,000 items
- Add search exhausted message
- Update unit tests

feat(storage-browser): integrate new locations handler search in locations view

---

packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/__tests__/useFolders.spec.ts
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/useFolders.ts

- Clear search when user selects a folder 
- Add test

fix(storage-browser): reset search on copy view navigation

---

examples/next/pages/ui/components/storage/storage-browser/managed-auth/index.page.tsx
packages/react-storage/package.json
packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
packages/react-storage/src/components/StorageBrowser/types.ts
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/index.ts
packages/react-storage/src/components/StorageBrowser/views/LocationsView/index.ts
packages/react-storage/src/components/StorageBrowser/views/index.ts

chore(storage-browser): use Amplify UI for default components

---

packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/LocationDetailViewProvider.tsx

- Fix behavior of isNoActionAvailable check on undefined actions

fix(storage-browser): fix isNoActionAvailable

---

examples/next/pages/ui/components/storage/storage-browser/composable-playground/index.page.tsx
examples/next/pages/ui/components/storage/storage-browser/default-auth/index.page.tsx
examples/next/pages/ui/components/storage/storage-browser/managed-auth/index.page.tsx
examples/next/pages/ui/components/storage/storage-browser/managed-auth/routed/[locations]/[location-detail]/index.page.tsx
examples/next/pages/ui/components/storage/storage-browser/managed-auth/routed/[locations]/index.page.tsx
examples/next/pages/ui/components/storage/storage-browser/managed-auth/routed/index.page.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationsView/LocationsView.tsx
packages/react-storage/src/styles/storage-browser.css
packages/ui/src/theme/css/component/StorageBrowser/storageBrowser.scss

Update "progress" text data cell icon classname to include "amplify-" prefix

fix(storage-browser): fix task table progress icon classname

---

packages/react-storage/src/components/StorageBrowser/providers/store/locationItems/context.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/CopyView.tsx
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CreateFolderView/useCreateFolderView.ts
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/LocationDetailView.tsx

This PR contains trivial cleanups

chore(storage-browser): Super minor cleanups

---

packages/e2e/cypress/integration/common/shared.ts
packages/e2e/features/ui/components/storage/storage-browser/search-locations.feature

* Adds tests for search functionality
* Basic search + clear search
* Sub-directory search
* Search without results + clear removes "No files" message

test(react-storage): add e2e testing for storage browser search

---

packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/__tests__/__snapshots__/uploadView.spec.ts.snap
packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/__tests__/scenarios.ts
packages/react-storage/src/components/StorageBrowser/displayText/libraries/en/uploadView.ts

fix(storage-browser): show number of files canceled for upload

---

packages/react-storage/src/components/StorageBrowser/actions/useAction/__tests__/search.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/useAction/createEnhancedListHandler.ts

fix: make search diacritic insensitive

---

examples/next/pages/ui/components/storage/storage-browser/default-auth/routed/StorageBrowser.ts
packages/react-storage/src/__tests__/__snapshots__/exports.spec.ts.snap
packages/react-storage/src/components/StorageBrowser/StorageBrowserAmplify.tsx
packages/react-storage/src/components/StorageBrowser/__tests__/StorageBrowserAmplify.spec.tsx
packages/react-storage/src/components/StorageBrowser/context/elements/__tests__/defaults.spec.tsx
packages/react-storage/src/components/StorageBrowser/createStorageBrowser.tsx
packages/react-storage/src/components/StorageBrowser/index.ts
packages/react-storage/src/components/StorageBrowser/types.ts

Remove `elements` and `actions` from `createStorageBrowser` input

chore(storage-browser): clean up csb input

---

packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/copy.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/createFolder.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/delete.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/download.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/listLocationItems.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/upload.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/__tests__/utils.spec.ts
packages/react-storage/src/components/StorageBrowser/actions/handlers/listLocationItems.ts

This PR improves test coverage of action handlers. Also adds tests for related utils and converts spies into mocks so tests are not inadvertently calling the underlying library implementations.

test(storage-browser) Shore up action handler unit tests

---

.changeset/selfish-parents-rush.md
package.json
packages/angular/projects/ui-angular/package.json
packages/vue/package.json
yarn.lock

Resolve all versions of nanoid to 3.3.8

deps: resolve all versions of nanoid to 3.3.8

---

.changeset/selfish-parents-rush.md
.changeset/sto-bro-progress.md
.changeset/sto-bro-ua.md

chore(changesets): update and add missing

---

packages/react-storage/src/components/StorageBrowser/__tests__/createStorageBrowser.spec.tsx

fix(storage-browser): update user agent unit test

---

docs/package.json
examples/next-app-router/package.json
examples/next/package.json
yarn.lock

Upgrade next deps to point to ^14.2.15
NA
- smoke test UI docs locally
- CI

chore(deps): upgrade next deps to point to ^14.2.15

---

.changeset/old-suits-brush.md

chore(changeset): update react 19 changeset from patch to minor bump

---

.changeset/angry-crabs-jog.md
packages/react/package.json
yarn.lock

Remove radix-ui upgrades due to ESM compat issues

chore(react): remove radix-ui upgrades

---

.github/workflow-samples/tagged-release.yml
.github/workflows/email-mfa.publish.yml
.github/workflows/test-internal-prs.yml

Add internal PR checks to the branch and add an npm tag for merges to the branch.

chore: update github workflows and add publishing tag on merge

---

docs/package.json
examples/next-app-router/package.json
examples/next/package.json
yarn.lock

chore(deps): bump nextjs version

---

docs/src/pages/[platform]/connected-components/authenticator/configuration/hidesignup.web.mdx

Add an example snippet for using the `hideSignUp` option for `withAuthenticator`
NA
NA

chore(docs): update react web Authenticator hideSignUp example

---

.changeset/many-bugs-pay.md

* Add changeset for https://github.com/aws-amplify/amplify-ui/pull/6197, which removed outdated styles for StorageBrowser

chore: add changeset for #6197

---

.github/workflow-samples/tagged-release.yml

chore: enabled tagged release of storage-browser-alpha

---

.changeset/patch-6061.md

Ad changeset for https://github.com/aws-amplify/amplify-ui/pull/6061
NA
NA

chore: add changeset for #6061

---

build-system-tests/package-lock.json
build-system-tests/package.json

Resolves https://github.com/aws-amplify/amplify-ui/security/dependabot/190

chore(deps): add esbuild resolution in build-system-tests/package.json

---

.github/dependency-review/config.yml

The latest version of a dependency `type-fest` includes a dual license that reads as `MIT OR CC0-1.0`, the dependency check interprets this license as `CC0-1.0 AND MIT` and as such this dual license will be added to the allow list. This combination of licenses should be allowed.

chore: update license allowlist

---

.changeset/cuddly-hounds-sort.md
.github/workflows/reusable-build-system-test-react-native.yml
build-system-tests/scripts/mega-app-install.sh
docs/src/components/ReactNativeSafeAreaContextInstallation.tsx
docs/src/data/frameworks.ts
docs/src/pages/[platform]/connected-components/authenticator/quick-start.mdx
docs/src/pages/[platform]/getting-started/installation/dependencies.mdx
packages/react-native/package.json
yarn.lock

The purpose of this pull request is to expand the range of supported peer dependency `react-native-safe-area-context` in `@aws-amplify/ui-react-native` from `^4.2.5` to `*` to allow customers to install a version compatible with their version of `react-native`.
- `react-native` is currently 0.78
- `react-native@0.78` requires `react-native-safe-area-context@^5.2.0`
- `react-native` < 0.74 requires `react-native-safe-area-context@^4`
- `@aws-amplify/ui-react-native` currently has a peer dependency with `react-native-safe-area-context@^4.2.5`
[See `react-native-safe-area-context` supported versions here.](https://appandflow.github.io/react-native-safe-area-context/#supported-react-native-versions)
RN version compatibility callout SS
Build test with changes to align with recommendation in …

chore(react-native): update react-native-safe-area-context peer dep

---

packages/react-storage/src/components/StorageBrowser/views/hooks/useResolveTableData/__tests__/useResolveTableData.spec.ts
packages/react-storage/src/components/StorageBrowser/views/hooks/useResolveTableData/index.ts
packages/react-storage/src/components/StorageBrowser/views/hooks/useResolveTableData/types.ts
packages/react-storage/src/components/StorageBrowser/views/hooks/useResolveTableData/useResolveTableData.ts

Add `useResolveTableData` hook, interfaces and unit tests
NA
- manual testing with `StorageBrowser` action views
- `yarn test`

chore(storage-browser): add useResolveTableData

---

.changeset/curvy-llamas-build.md
docs/__tests__/__snapshots__/cssvars-table.test.ts.snap
docs/src/components/ComponentsMetadata.ts
examples/next/pages/ui/components/ai/ai-conversation/attachments.page.tsx
packages/ui/src/theme/__tests__/__snapshots__/defaultTheme.test.ts.snap
packages/ui/src/theme/__tests__/__snapshots__/overrides.test.ts.snap
packages/ui/src/theme/css/component/AIConversation/aiConversation.scss
packages/ui/src/theme/css/component/textArea.scss
packages/ui/src/theme/css/component/textAreaField.scss
packages/ui/src/theme/tokens/components/aiConversation.ts
packages/ui/src/types/primitives/componentClassName.ts

fix(ai): textarea overflow bug

---

docs/src/pages/[platform]/connected-components/storage/storage-browser/react.mdx

Storage Browser Quickstart Docs

---

docs/package.json
docs/src/pages/[platform]/connected-components/storage/storage-browser/react.mdx
examples/next-app-router/package.json
examples/next/package.json
yarn.lock

Upgrades Next.js to `^14.2.25`

Docs Release PR 2025 03 26 

---

docs/src/pages/[platform]/connected-components/authenticator/advanced/current-route.angular.mdx
docs/src/pages/[platform]/connected-components/authenticator/advanced/current-route.react-native.mdx
docs/src/pages/[platform]/connected-components/authenticator/advanced/current-route.react.mdx
docs/src/pages/[platform]/connected-components/authenticator/advanced/current-route.vue.mdx
docs/src/pages/[platform]/connected-components/authenticator/advanced/index.page.mdx
docs/src/pages/[platform]/connected-components/authenticator/advanced/routes-list.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/customization.headers-and-footers.react-native.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/customization.labels-and-text.web.mdx
docs/src/pages/[platform]/connected-components/authenticator/customization/formfields/form-fields.web.mdx
examples/angular/src/pages/ui/components/authenticator/custom-slots/custom-slots.component.html
examples/angular/src/pages/ui/components/authenticator/custom-slots/custom-slots.component.ts
examples/next/pages/ui/components/authenticator/custom-slots/index.page.tsx
examples/react-native/src/features/Authenticator/OverrideComponents/Example.tsx
examples/react-native/src/features/Authenticator/OverrideComponents/SelectMfaType.tsx
examples/react-native/src/features/Authenticator/OverrideComponents/SetupEmail.tsx
examples/vue/src/pages/ui/components/authenticator/custom-slots/index.vue
packages/react-native/src/Authenticator/Defaults/index.ts
packages/react-native/src/Authenticator/Defaults/types.ts
packages/react-native/src/Authenticator/index.ts
packages/react-native/src/__tests__/__snapshots__/index.spec.ts.snap
packages/react-native/src/index.ts

The purpose of this pull request is to update documentation to support Email MFA feature.
This includes:
- RN component overrides
- i18n / translations
- form field overrides
- header and footer slots on each framework / library

docs(email-mfa): add email mfa documentation updates

---

examples/next-app-router/package.json

Use exact versions for next app router example internal deps to ensure version incrementing

chore(next-app-router-example): use exact version for internal deps

---

examples/next/pages/ui/components/storage/storage-browser/managed-auth/routed/StorageBrowser.ts

Cleanup unused import in next pages router example to clear codeql alert

fix(codeql): remove unused import in next pages router example app

---

packages/react-ai/package.json

Remove unused `jest` related dev deps from `@aws-amplify/ui-react-ai`

deps(react-ai): remove unused dev deps

---

packages/react-core/src/__tests__/__snapshots__/index.spec.ts.snap
packages/react-core/src/hooks/__tests__/useControlledReducer.spec.ts
packages/react-core/src/hooks/index.ts
packages/react-core/src/hooks/useControlledReducer.ts
packages/react-core/src/index.ts

Add `useControlledReducer` and unit tests
NA
- manual tested with controlled props in `StorageBrowser`
- unit tests

feat(react-core): add useControlledReducer

---

.github/workflows/test-internal-prs.yml

Revert "chore: run CI against feature branch PRs"
NA
NA

Revert "chore: run CI against feature branch PRs"

---

packages/test-utils/src/storage-browser/mock-handlers.ts

Fix folder uploads in `StorageBrowser` mock `upload` handler
NA
Manual test

chore(test-utils): fix folder uploads in StorageBrowser test-utils

---

.changeset/lucky-humans-talk.md
package.json
packages/angular/projects/ui-angular/package.json
packages/react-ai/package.json
packages/react-auth/package.json
packages/react-core-auth/package.json
packages/react-core-notifications/package.json
packages/react-core/package.json
packages/react-geo/package.json
packages/react-liveness/package.json
packages/react-native-auth/package.json
packages/react-native/package.json
packages/react-notifications/package.json
packages/react-storage/package.json
packages/react/package.json
packages/ui/package.json
packages/vue/package.json
yarn.lock

- Bump `aws-amplify` package a version below [fix react-native exports condition order](https://github.com/aws-amplify/amplify-js/pull/14353) see [comment](https://github.com/aws-amplify/amplify-ui/pull/6520#discussion_r2054480319)
- Bump `radix-ui` package version [beyond problematic versions](https://github.com/radix-ui/primitives/issues/3485)
| Package  | problematic versions | fixed versions |
| ------------- | ------------- | ------------- |
| @radix-ui/react-dropdown-menu  | 2.1.9  | 2.1.10  |
| @radix-ui/react-slider  | 1.3.1  | 1.3.2 |
| @radix-ui/react-direction  | NA  | NA |
- Tested build locally
- Confirmed build fails with ^ radix _problematic versions_ and is fixed beyond _fixed versions_
By submitting this pull request, I confirm that my contribution is made under the terms …

chore: update aws-amplify version

---

.changeset/nasty-months-teach.md
.github/workflows/publish-hotfix.yml
.github/workflows/publish-latest.yml
docs/package.json
examples/next-app-router/package.json
examples/next/package.json
examples/react-router/package.json
packages/react-storage/CHANGELOG.md
packages/react-storage/package.json
packages/react-storage/src/components/StorageBrowser/tasks/__tests__/useProcessTasks.spec.ts
packages/react-storage/src/components/StorageBrowser/tasks/types.ts
packages/react-storage/src/components/StorageBrowser/tasks/useProcessTasks.ts
packages/react-storage/src/components/StorageBrowser/useAction/__tests__/useHandler.spec.ts
packages/react-storage/src/components/StorageBrowser/useAction/useHandler.ts
packages/react-storage/src/version.ts
packages/test-utils/CHANGELOG.md
packages/test-utils/package.json

Cherry pick the following commits and hot fix release
- https://github.com/aws-amplify/amplify-ui/pull/6525
- https://github.com/aws-amplify/amplify-ui/pull/6527
Squash and merge PR. Merge squashed commit back to main.
…atch handler (#6525)…atch handler (#6525)

fix(storage-browser): move useProcessTasks concurrency option to dispatch handler

---

.changeset/empty-cobras-obey.md
packages/react-storage/package.json
packages/react-storage/src/components/StorageBrowser/useAction/__tests__/createEnhancedListHandler.spec.ts
packages/react-storage/src/components/StorageBrowser/useAction/__tests__/searchItems.spec.ts
packages/react-storage/src/components/StorageBrowser/useAction/createEnhancedListHandler.ts
packages/react-storage/src/components/StorageBrowser/useAction/searchItems.ts
packages/react-storage/src/components/StorageBrowser/useAction/useListFolderItems.ts
packages/react-storage/src/components/StorageBrowser/useAction/useListLocationItems.ts
packages/react-storage/src/components/StorageBrowser/useAction/useListLocations.ts
packages/react-storage/src/components/StorageBrowser/views/LocationActionView/CopyView/useFolders.ts
packages/react-storage/src/components/StorageBrowser/views/LocationDetailView/useLocationDetailView.ts
packages/react-storage/src/components/StorageBrowser/views/LocationsView/useLocationsView.ts

Fix typing of `createEnhancedListHandler` to infer missing options from provided handler
- update type interfaces/cleanup
- remove extraneous casting
- migrate `searchItems` util to own file
- update consumers
NA
- unit tests
- CI

fix(StorageBrowser): update createEnhancedListHandler interfaces

---

.github/workflows/build-system-test-react-native.yml
.github/workflows/reusable-build-system-test-react-native.yml

Reduce the frequency of the [React Native Build System Test Canary](https://github.com/aws-amplify/amplify-ui/actions/workflows/build-system-test-react-native.yml) to every two hours. Minor cleanup of commands for readability and simplicity
NA
POC test run using updated commands: https://github.com/aws-amplify/amplify-ui/actions/runs/14784826637

chore(build-system-tests): reduce frequency of RN tests

---

README.md
packages/angular/README.md
packages/react-ai/README.md
packages/react-core-notifications/README.md
packages/react-core/README.md
packages/react-geo/README.md
packages/react-liveness/README.md
packages/react-native/README.md
packages/react-notifications/README.md
packages/react-storage/README.md
packages/react/README.md
packages/ui/README.md
packages/vue/README.md

Update and align top level and public package READMEs
NA
NA

chore: update top level and package READMEs

---

.changeset/happy-windows-grow.md

chore: Add changeset for table resolver refactor

---

packages/react-liveness/package.json
packages/react-liveness/src/components/FaceLivenessDetector/index.ts
packages/react-liveness/src/index.ts
yarn.lock

- Some constants e.g `FACE_MOVEMENT_CHALLENGE` were exported as type which was causing a TS issue (see the error below) and the fix was to export normally not type export. 
- Update to use the latest version of [rekognitionstreaming 3.828.0](https://www.npmjs.com/package/@aws-sdk/client-rekognitionstreaming/v/3.826.0
) which is required for the upcoming no light feature. 
```
import React from 'react';
import { View, Flex, Loader, Text } from '@aws-amplify/ui-react';
import {
FaceLivenessDetectorCore,
FACE_MOVEMENT_AND_LIGHT_CHALLENGE,
SUPPORTED_CHALLENGES,
} from '@aws-amplify/ui-react-liveness';
import { useLiveness } from './useLiveness';
import { ChallengeSelection } from './ChallengeSelection';
import { SessionIdAlert } from './SessionIdAlert';
import LivenessInlineResults from …
```

fix(ui): update constants exports in liveness package. 

---

docs/src/pages/[platform]/connected-components/liveness/QuickStartReact.jsx
docs/src/pages/[platform]/connected-components/liveness/QuickStartReact.tsx
docs/src/pages/[platform]/connected-components/liveness/quick-start-pull.react.mdx

Update liveness documentation to improve error handling guidance. 
I've validated the changes by introducing them in a sample application. 

chore(liveness): improve documentation for error handling

---

build-system-tests/e2e/package.json
docs/package.json
examples/angular/package.json
examples/next/package.json
examples/vue/package.json
package.json
yarn.lock

Bumping `glob` and `rimraf` versions in dependent packages

chore(react-liveness): bump dep versions

---

.github/workflows/build-and-runtime-test.yml
.github/workflows/build-system-test-react-native.yml
.github/workflows/reusable-e2e.yml
.github/workflows/reusable-setup-cache.yml
.github/workflows/reusable-unit.yml
packages/react-liveness/jest.config.ts
packages/react-liveness/jest.setup.ts
packages/react-liveness/package.json
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx
packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/__tests__/LivenessCameraModule.test.tsx
packages/react-liveness/src/components/FaceLivenessDetector/service/machine/__tests__/machine.test.ts
packages/react-liveness/src/components/FaceLivenessDetector/service/utils/types.ts

This PR fixes GitHub Actions workflow failures caused by deprecated `actions/cache` versions. The workflows were using a specific commit hash (`0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`) that corresponds to an older version of `actions/cache` which is being deprecated by GitHub and will be fully retired by March 1st, 2025.
**Changes made:**
- Updated all instances of `actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9` to `actions/cache@v4`
- Fixed 5 workflow files:
- `.github/workflows/reusable-setup-cache.yml`
- `.github/workflows/reusable-unit.yml`
- `.github/workflows/build-system-test-react-native.yml`
- `.github/workflows/reusable-e2e.yml`
- `.github/workflows/build-and-runtime-test.yml`
This resolves the workflow failure: "This request has been automatically failed because it …

fix: update deprecated actions/cache to v4 in GitHub workflows
